### ISSUE TITLE
no method named `with_graceful_shutdown` found for opaque type `impl Future<Output = Result<(), std::io::Error>>`

### ISSUE THREAD

**Issue by frederikhors** [tokio-rs/axum#1007]
### Version

axum v0.5.4
axum-core v0.2.4
axum-server v0.3.3

### Platform

Windows 10 64

### Description

Sorry to bother you. Thanks for your unbelievable work!

I'm new to Rust and reading your examples I'm trying to create a server with basic TLS and graceful shutdown using this code:

```rust
axum_server::bind_rustls(addr, tls_config)
  .serve(router.into_make_service())
  .with_graceful_shutdown(shutdown_signal())
  .await
  .unwrap();
```

But I'm getting this error:

```
no method named `with_graceful_shutdown` found for opaque type `impl Future<Output = Result<(), std::io::Error>>` in the current scope
method not found in `impl Future<Output = Result<(), std::io::Error>>`rustcE0599
```

Is it my fault somehow?

I'm reading examples:

1. https://github.com/tokio-rs/axum/blob/main/examples/tls-rustls/src/main.rs

1. https://github.com/tokio-rs/axum/blob/main/examples/graceful-shutdown/src/main.rs

**Comment by davidpdrsn** [comment]
`axum::Server` is not the same as `axum_server` so their APIs are different. You probably want https://docs.rs/axum-server/latest/axum_server/struct.Handle.html#method.graceful_shutdown.
