### ISSUE TITLE
Add example for using threads/thread pool

### ISSUE THREAD

**Issue by chmnchiang** [tokio-rs/axum#1017]
### Motivation

Currently, all the examples use default tokio runtime, which spawn number of threads equal to the number of processors. However, all the example only spawn one future for all requests, which make them single thread servers.

### Proposal

Add an example to demonstrate how to use axum with multiple threads.

**Comment by davidpdrsn** [comment]
hyper will use `tokio::spawn` to handle multiple requests concurrently. So no special setup is necessary.

**Comment by chmnchiang** [comment]
Sorry, that was a confusion of mine. Thanks!

**Comment by 1192724521** [comment]
Sorry,I didn't understand.qwq
