### ISSUE TITLE
Common JSON wrapper type for response and request

### ISSUE THREAD

**Issue by gbaranski** [tokio-rs/axum#102]
Currently there is `axum::extract::Json` and `axum::response::Json`, this introduces naming conflicts if handler accepts Json and returns Json.

Actix have `actix_web::web::Json` which can do at the same time.

**Comment by davidpdrsn** [comment]
I've thought this as well. However where do we put `Json`? In `extract`? `response`? In both? Some totally new module? Actix puts it at `actix_web::web::Json` which I'm not a fan of.

It also hurts API discoverability on docs.rs if extractors aren't in `axum::extractor`.

**Comment by gbaranski** [comment]
> I've thought this as well. However where do we put `Json`? In `extract`? `response`? In both (using a re-export)? Some totally new module? Actix puts it at `actix_web::web::Json` which I'm not a fan of.
> 
> It also hurts API discoverability on docs.rs if extractors aren't in `axum::extractor`.

I'd put `Json` and other data formats in a completely new module, while removing them from `extract` and `response` module. I think `format` could be okay for naming the module with structs like `Json`, or `Form`.

**Comment by davidpdrsn** [comment]
`Form` only implements `FromRequest` and doesn't conflict with anything, unlike `Json`. So keeping `Form` in `extract` should be fine.

I guess `format` could work but not sure 🤔

**Comment by davidpdrsn** [comment]
I guess what a "format" is, is up for debate. Just to play devils advocate; HTML, websockets, and server-sent events are also response body formats with specifications. So do they go in `format` as well?

**Comment by gbaranski** [comment]
> I guess what a "format" is, is up for debate. Just to play devils advocate; HTML, websockets, and server-sent events are also response body formats with specifications. So do they go in `format` as well?

I see your point now. Putting them into `format` isn't the best idea, maybe there is some better name that is generic along those types?

**Comment by pepoviola** [comment]
HI @davidpdrsn / @gbaranski, 
   Sorry to chime in here, but I want to just add my two cents. I think moving `Json` and other potencial data formaters are a good direction but I think `serialization` is maybe a better name?  Nevertheless, awesome work @davidpdrsn!! and is awesome to see how things are taking shape pr to pr.

Thanks!

**Comment by jplatte** [comment]
I think re-exports in both extract and response make sense, but then it would still have to be decided where the type is defined. If that place was a private module I don't think the docs would make it clear that both are the same type I think. One option might be just `axum::Json`, wdyt about that @davidpdrsn ?

**Comment by davidpdrsn** [comment]
> One option might be just `axum::Json`

Honestly I think putting it in the root is probably fine. That coupled with re-exports from `axum::response` and `axum::extract` isn't too bad. I would be open to doing that. Should also be possible to do without breaking changes.

The docs just have to make it clear that `Json` works as both a response and extractor.

**Comment by tesaguri** [comment]
> Should also be possible to do without breaking changes.

Technically speaking, re-exporting would be a breaking change as well. A downstream crate can write something like the following now:

```rust
impl<T> MyTrait for axum:extract::Json<T> {}
impl<T> MyTrait for axum:response::Json<T> {}
```

But making `extract::Json` and `response::Json` point to a same item would break this code.

**Comment by sunli829** [comment]
So are we now going to create a new `axum::Json`, or directly implement `IntoResponse` on `axum::extract::Json`?

**Comment by davidpdrsn** [comment]
I say we

- Move `extract::Json` to `axum::Json`
- Copy implement of `IntoResponse` to `axum::Json`, along with any appropriate trait impls like `From` and `Deref`
- Update the docs
- Remove `response::Json`
- Add `pub use crate::Json` to `response` and `extract.

**Comment by sunli829** [comment]
I will do this now. 🙂
