### ISSUE TITLE
WebSocket subprotocols negotiation

### ISSUE THREAD

**Issue by MatteoJoliveau** [tokio-rs/axum#1020]
## Feature Request

Axum has support for specifying the supported WebSocket subprotocols when handling a WS request

```rust
ws.protocols(["cloudevents.cbor", "cloudevents.json"]).on_upgrade(handle_socket);
```

However, there is currently no way for the `handle_socket` function to know which protocol was chosen as the result of the client-server negotiation.

### Proposal

The simplest solution seems to be adding a new field to the [axum::extract::ws::WebSocket](https://docs.rs/axum/latest/axum/extract/ws/struct.WebSocket.html) struct called `protocol: Option<String>` (with a corresponding getter function `WebSocket::protocol -> Option<&str>`).

### Alternatives

I submitted this problem on [Discord](https://discord.com/channels/500028886025895936/870760546109116496/973633756990697542) and this seems to be the simplest solution.

**Comment by MatteoJoliveau** [comment]
I'm preparing a PR to add the field to `WebSocket`

**Comment by coolreader18** [comment]
It would also be nice to be able to access this from the `WebSocketUpgrade`, in order to possibly refuse the connection altogether if the client didn't give any acceptable subprotocols.

**Comment by coolreader18** [comment]
For a breaking change (maybe for 0.7) it'd be cool for it to be more strongly typed, something like a `trait SubProtocol { fn from_str(&str) -> Option<Self>; }`, or `protocols()` being `fn protocols<P>(impl IntoIterator<Item = (&str, P)>) -> Option<P>`.
