### ISSUE TITLE
example stream-to-file contains directory traversal vulnerability

### ISSUE THREAD

**Issue by kosta** [tokio-rs/axum#1037]
### Version

main branch

```
cargo tree | grep axum
example-stream-to-file v0.1.0 (/Users/kosta/code/3rd/axum/examples/stream-to-file)
├── axum v0.5.6 (/Users/kosta/code/3rd/axum/axum)
│   ├── axum-core v0.2.4 (/Users/kosta/code/3rd/axum/axum-core)
```

### Platform

uname -a
Darwin hostname.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### Crates

axum examples

### Description

`async fn save_request_body(Path(file_name): Path<String>,...)` just passes file_name to `stream_to_file` which calls `File::create()` on it.

I know this is just an example, but this is a textbook directory traversal issue. An example should show secure code :)

Example that creates a file in the parent directory:

```sh
curl -X POST --data-binary 'oopsie' http://127.0.0.1:3000/file/..%2Fok
```

The file should be created in a sub-directory (e.g. `uploads`) and it should be ensured that the given file name is contained in that directory, e.g. using [path_absolutize](https://docs.rs/path-absolutize/latest/path_absolutize/trait.Absolutize.html#tymethod.absolutize_virtually) or check all path segments like [ServeDir does](https://docs.rs/tower-http/latest/src/tower_http/services/fs/serve_dir/mod.rs.html#58-67). If you know of a better way, let me know.

**Comment by davidpdrsn** [comment]
Thanks for noticing! https://github.com/tokio-rs/axum/pull/1040 should fix it.

**Comment by kosta** [comment]
Thanks for fixing this so quickly! :)
