### ISSUE TITLE
peekable stream body

### ISSUE THREAD

**Issue by waynr** [tokio-rs/axum#1039]
## Feature Request

When using [BodyStream](https://docs.rs/axum/latest/axum/extract/struct.BodyStream.html) I would like to be able to "peek" at the contents in a way that doesn't consume the stream.

### Motivation

The motivation for this is that I want to deterministically know whether there is data in the request body (that is, any data at all as opposed to None) without buffering the entire body in memory (as I believe would be required with `RawBody`) nor prematurely consuming some of the body's contents before passing the stream on to the intended consumer (in my case I am attempting to stream the body into an S3 api endpoint without buffering the entire thing in memory).

I imagine that one way this could be done is to create a `BodyStream` wrapper with a "peek" method that polls the next chunk of bytes from the inner stream, stores them in a buffer and returns a slice over that buffer's contents, then returns and evacuates the contents of that buffer when this wrapper's poll_next method is called.

Does that make sense? I'll probably try implementing something like this myself, but it seems like generic and useful enough behavior that someone else might want it so I thought I'd mention it here.

### Proposal

Whoops, I already made a hand-wavy proposal above. I don't really know what I'm doing though.

### Alternatives

I don't think size hint is a viable alternative to me since it may return a zero size hint depending on the body type.

For my use case it's not clear if there is an alternative. The problem is that am writing an API against a spec whose conformance tests seem to be written in such a way that the API is expected to safely handle a request with non-zero `ContentLength` and an empty body so I also can't use `ContentLength` as a hint. Yet if I do try to rely on `ContentLength` then when I attempt to stream the body to an S3 API endpoint the content length (required for uploading an object) is considered invalid.

I suppose I could try to properly capture and ignore that error response from the S3 API. I may also submit a PR to the conformance test suite to point out that APIs conforming to the spec shouldn't be expected to deal with mismatches between the presence of a `ContentLength` header and no actual request body...

**Comment by davidpdrsn** [comment]
I think something like this makes sense to support however I don't think it should be built into axum. It would depend on any axum internals so limiting it to axum is unnecessary. I suggest you file an issue on [http-body](https://github.com/hyperium/http-body).

> I imagine that one way this could be done is to create a BodyStream wrapper with a "peek" method that polls the next chunk of bytes from the inner stream, stores them in a buffer and returns a slice over that buffer's contents, then returns and evacuates the contents of that buffer when this wrapper's poll_next method is called.

That sounds like a good way to do it. Its basically how `Iterator::peekable` works :)

I'll close this for now but feel free to ask follow up questions.

**Comment by waynr** [comment]
Hey, thanks for the quick response and the suggestion! I'll re-file this issue with http-body when I get a chance.
