### ISSUE TITLE
Support for CORS preflight requests

### ISSUE THREAD

**Issue by nkconnor** [tokio-rs/axum#106]
### Motivation

Communicating with an `axum` app from the browser is a popular use case and many browsers restrict cross-origin requests by default.

### Background

[MDN CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
[CORS server flowchart](https://www.html5rocks.com/static/images/cors_server_flowchart.png)

### See Also

[CORS PR in `tower-http`](https://github.com/tower-rs/tower-http/pull/112)

Related issue on `OPTIONS` requests #44 
Related issue on SPAs #87

[Warp "wrapping filter"](https://docs.rs/warp/0.3.1/warp/filters/cors/fn.cors.html)
[Tide middleware](https://docs.rs/tide/0.16.0/tide/security/struct.CorsMiddleware.html)
[3rd party crate recommended for `rocket`](https://docs.rs/rocket_cors/0.5.2/rocket_cors/) 

### Proposal

Add ergonomic support and docs for handling CORS preflight requests.

`axum` already provides support for setting headers globally or specifically using middleware, however, I'm not sure of an ergonomic way to handle [preflight requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests). That's an `OPTIONS` request preceding e.g. a `POST` request to the same path.

An app could handle this for example by (pseudocode)

```
let app = route("/user", get(get_user).options(cors_fn));
```

Since routing precedence (I think?) limits the ability to put a path wildcard `OPTIONS` at the root of the application, or some part of the application, the developer is required to chain `options` to every path declaration.

I'm not ready to propose any specific changes or weigh in on alternatives yet as I'm a new user and this an issue I'm encountering.

**Comment by davidpdrsn** [comment]
The intention is that axum will use https://github.com/tower-rs/tower-http/pull/112 when its merged. I don't think building something specifically for axum is necessary. I generally prefer adding things to tower-http is possible since it makes things usable outside of axum.

**Comment by davidpdrsn** [comment]
[tower-http now finally has cors support](https://docs.rs/tower-http/0.1.2/tower_http/cors/index.html) 🥳

**Comment by silvioprog** [comment]
> [tower-http now finally has cors support](https://docs.rs/tower-http/0.1.2/tower_http/cors/index.html) partying_face

Awesome news! 🎉

**Comment by silvioprog** [comment]
> [tower-http now finally has cors support](https://docs.rs/tower-http/0.1.2/tower_http/cors/index.html) partying_face

Wow, awesome news! Congrats dudes! 🎉
