### ISSUE TITLE
Implement MethodFilter as bitflags 

### ISSUE THREAD

**Issue by Kestrer** [tokio-rs/axum#107]
### Motivation

`MethodFilter` is currently somewhat restricted, it only supports singular methods as well as a catch-all variant. It would be nice if it were more flexible.

Note that I do not have a specific use case for this, I just thought it would be neat and feel more natural than an `Any` enum variant. 

### Proposal

Implement the type as bitflags. It will grow to be two instead of one bytes, but that's a minute cost.

### Alternatives

Have a `MethodFilter` trait implemented on Method as well as closures. This would support custom HTTP methods as well as more advanced filters, but I'm not sure how useful that is.

**Comment by davidpdrsn** [comment]
Would this allow making filters "get or head" and "patch or put"? I've thought that would be nice to support with making `MethodFilter` recursive which would require boxing.

**Comment by Kestrer** [comment]
Yes, it would: `on(MethodFilter::PATCH | MethodFilter::PUT, xyz)`.

**Comment by davidpdrsn** [comment]
Sweet! Then I don't see why we wouldn't do it 😊

Added to the 0.2 milestone since I assume it would require a breaking change to implement. If that isn't case let me know. I don't think we should jump through hoops to do it in a non-breaking way.

**Comment by davidpdrsn** [comment]
Would you recommend exporting what [bitflags](https://docs.rs/bitflags/1.2.1/bitflags) generates directly or is it best practice to wrap it so we can more tightly control the API?

**Comment by davidpdrsn** [comment]
Removed `E-help-wanted` because I think we should decide on whether to use bitflags first.

**Comment by jplatte** [comment]
Personally I think it should be fine to expose what bitflags generates directly.
