### ISSUE TITLE
Graceful shutdown with timeout?

### ISSUE THREAD

**Issue by davechallis** [tokio-rs/axum#1070]
I've looked at the example for graceful timeout, but wondering if there's a way to add a timeout to graceful shutdown?

I'm migrating some server code from Actix web where this is configurable (and defaults to 30s), so wondering if that's possible with Axum yet, or whether this feature isn't supported yet.

**Comment by jplatte** [comment]
`axum::Server` is a re-export of `hyper::Server`, so please look for issues about this in [its issues](https://github.com/hyperium/hyper/issues) (or file a new one there).
