### ISSUE TITLE
HTTP/3 & QUIC support

### ISSUE THREAD

**Issue by dhalucario** [tokio-rs/axum#1096]
### Motivation

IETF published HTTP/3 to the RFC as RFC 9114 and it seems to become the new internet standard. Every major browser and a good bunch of major webservers support it already.

Besides that HTTP/3 runs a lot faster based on a benchmark I have seen. Also package loss isn't as devestating as it is on HTTP/2 which is very important for mobile users.

### Proposal

Implement [RFC 9114](https://www.rfc-editor.org/rfc/rfc9114.html).

### Alternatives

None. We could ignore it.

**Comment by dhalucario** [comment]
Related to: https://github.com/hyperium/hyper/issues/1818

**Comment by HigherOrderLogic** [comment]
Related: hyperium/hyper#3925.
