### ISSUE TITLE
Axum Tonic interop

### ISSUE THREAD

**Issue by jvdwrf** [tokio-rs/axum#1100]
## Feature Request
Better interoperability between Axum and Tonic

### Motivation
I would like to integrate Axum and Tonic together. This would give me a lot of the flexibility that Axum has, with the niceties of Grpc and Tonic.

### Proposal
I have attempted to create what nice interoperability would look like in a simple repository: https://github.com/jvdwrf/axum-tonic/blob/main/src/main.rs.
I have very little experience using the whole Tower/Hyper ecosystem, so everything is still very new to me. There are probably a lot of errors here, but if someone could point me in the right direction, I could make this into a usable library.

### Alternatives
The alternative is to go like currently done in the Multiplex example. This definitely works, but immediately you lose all flexibility that Axum gives you.

edit: changed link

**Comment by davidpdrsn** [comment]
What do you mean by "better interop"? Interop between the two is already possible as you've discovered. Our [multiplex example](https://github.com/tokio-rs/axum/blob/main/examples/rest-grpc-multiplex/src/multiplex_service.rs) is what I'd recommend.

**Comment by jvdwrf** [comment]
Well I guess I'd like to be able to add different layers to different Tonic services/servers. 

This is not really an issue with Axum per se, but I hoped that by being able to nest Tonic services directly in an Axum Router, this would be solvable in an easy way.

**Comment by davidpdrsn** [comment]
You can do what tonic does internally https://github.com/hyperium/tonic/blob/master/tonic/src/transport/service/router.rs#L50-L52 (tonic's router is actually implemented with axum). That gives you an `axum::Router` that you can add layers to.

There isn't much we can do from axum, since axum shouldn't depend on tonic. So I'm gonna close the issue but feel free to ask follow up questions.

**Comment by jvdwrf** [comment]
Okay thanks! I'll try to see if I can get this working

**Comment by jvdwrf** [comment]
I ended up creating and releasing a small crate for this, for anyone coming across this for whom it might be useful:
https://crates.io/crates/axum_tonic

There is not a lot that's actually done inside, but I'm quite happy with the API.
