### ISSUE TITLE
extract::Form : Change of behavior between previous axum-extra and new axum-0.5.8

### ISSUE THREAD

**Issue by olivier-fs** [tokio-rs/axum#1105]
Hi! 

[I'm using latest release axum-0.5.8 (not git) with axum-extra-0.34; and building with rust-1.61.0 on Windows 10 Pro]

I just updated to axum-0.5.8, and I noticed a slight but annoying change in behavior between previous axum-extra::extract::Form
and fresh new axum::extract::Form.

* axum-extra::extract::Form uses serde_html_form to deserialize form body

* axum::extract::Form uses serde_urlencoded to deserialize form body

With serde_html_form I could handle forms with multiple values with same name, and serde deserialized thes into Vec<String>
[I could even handle names with [] like you find in tons of legacy PHP forms I have to deal with, thanks to serde having 'rename']

              <form action="/" method="post">
                    <label for="name">
                        Enter your name: <input type="text" name="name">
                    </label>
                    <br/>
                    <label for="email"
                        Enter your email: <input type="text" name="email">
                    </label>
                    <br/>
                    <input name="vals[]"/>
                    <input name="vals[]"/>
                    <input name="vals[]"/>
                    <br/>
                    <input type="checkbox" name="checkboxes[]" value="cb1"/>
                    <input type="checkbox" name="checkboxes[]" value="cb2"/>
                    <input type="checkbox" name="checkboxes[]" value="cb3"/>
                    <br/>
                    <input type="radio" name="radiobuttons[]" value="rb1" checked="true"/>
                    <input type="radio" name="radiobuttons[]" value="rb2"/>
                    <input type="radio" name="radiobuttons[]" value="rb3"/>
                    <br/>
                    <input type="submit" value="Submit !">
             </form>

#[derive(Deserialize, Debug)]
#[allow(dead_code)]
struct Input {
    name: String,
    email: String,

    #[serde(default, rename = "vals[]")]
    vals: Vec<String>,

    #[serde(default, rename = "radiobuttons[}")]
    radiobuttons: Vec<String>,

    #[serde(default, rename = "checkboxes[]")]
    checkboxes: Vec<String>,
}

// Log form data and display it back as text in browser
async fn accept_form(Form(input): Form<Input>) -> String {
    dbg!(&input);
    format!("{input:?}")
}

In tokio main:

    ...

    let app = Router::new()
        .route("/", get(show_form).post(accept_form));

    ...

But with axum::extract::Form using serde_urlencoded, the form deserialization fails with following error message :

     Failed to deserialize query string. Expected something of type `form_test1::Input`. Error: invalid type: string "aa", expected a sequence

It happens 'vals' is the first of problematic fields, with it would fail the same with 'radiobuttons' or 'checkboxes' if they were first.

Removing [] in field names (and the rename directive in serde) changes nothing ; exact same behavior OK with serde_html_form and KO serde_urlencoded.

This is of course by no way a bug in axum, just how serde_urlencoded works, and I can keep using axum-extra for now, but :

  - Is is really necessary to switch serde_html_form => serde_urlencoded ? Is serde_urlencoded doing something better ?

  - Am I doing things wrong here ? This code used to work, but I remember old discussions about this kind of problem, and if I remember well that dealing with multiple values with same name was not even standardized...

Thank you !

[Last but not least, many kudos do David and the axum and tokio teams, I enjoy each hour of rust development with these great tools, and I suffer each time I  have to go back to PHP...]

**Comment by davidpdrsn** [comment]
Not quite sure I follow. Nothing has changed here. axum uses serde_url_encoded and axum-extra uses serde_html_form. axum::extract::Form has existed since 0.1. It's not new.

We might move axum to serde_html_form someday but that hasn't happened yet.

**Comment by olivier-fs** [comment]
Oh I see.

I'm using released crates on my servers, but I also follow changes on the git crate ; and since I saw the move from extract/form.rs to form.rs I decided to give it a try, and see if i could remove dep on axum-extra

I should have checked that it previously worked the same.

Sorry for the noise, The not-so-bad part is : Now there is a reminder on this (non-urgent but quite important) question :

Forms having multiple checkboxes / radiobuttons are quite usual, and - despite the examples directory being really great with tons of goodies - form handling (i.e. the POST part) may deserve a richer example with more controls (checkboxes, radiobuttons, select).

Even if I enjoy it and will always spend as many hours as needed making my axum webapps run fine, it may be a much less nice experience to newcomers (i.e. Oh it doesn't work ... Is it a serde or axum problem ? Do I need more trait here for FromRequest ? etc.)

Thank you, I'll keep using axum-extra Form for now.

**Comment by davidpdrsn** [comment]
> Forms having multiple checkboxes / radiobuttons are quite usual, and - despite the examples directory being really great with tons of goodies - form handling (i.e. the POST part) may deserve a richer example with more controls (checkboxes, radiobuttons, select).

You're absolutely right. serde_url_encoded implements just the standard which doesn't support passing multiple values. Why that's not standard I don't know. But that's why @jplatte made serde_html_form, to at least support what HTML does. Maybe axum will switch to that some day. Dunno 🤷

There is also serde-qs which supports even more stuff.

actix-web and warp also uses serde_url_encoded so they have the same issues.

I'll close this for now but feel free to ask follow up questions.
