### ISSUE TITLE
cargo doc fails without --all-features due to deny(broken_intra_doc_links)

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#112]
## Bug Report

Trying to generate docs while working on axum fails when `cargo doc` isn't run with `--all-features` or with `--features` used to enable the features that the main readme has intradoc links to.

### Version

4e9b38ddf986ce596429ec73d9d77e1bc6738fb9

### Suggested fix

I think a reasonable way to fix this would be removing `deny(broken_intra_doc_links)` from `lib.rs` and adjusting CI to pass `-D broken_intra_doc_links` to rustdoc (not sure whether it has to be passed to `cargo doc` directly, after ` -- `, or rather via `RUSTDOCFLAGS`).

**Comment by davidpdrsn** [comment]
I believe this was fixed by https://github.com/tokio-rs/axum/pull/141

Please re-open if not.
