### ISSUE TITLE
Middleware cannot change the request in a way that impacts routing

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1120]
As part of removing trailing slash redirects (https://github.com/tokio-rs/axum/issues/1118) I've added a `NormalizePath` middleware to tower-http, however that requires changing the path before routing. That means `Router::layer` cannot be used, since those middleware only run after routing.

Instead you have to do something like

```rust
NormalizePath::trim_trailing_slash(
    Router::new().route("/foo", get(handler))
);
```

which isn't very obvious. It also means you cannot use `Router::into_make_service`, since your service is now `NormalizePath<Router>` and not `Router`. Instead you have to use `tower::make::Shared` or something similar.

We should think of a more ergonomic solution to this. Maybe a third `*_layer` method?

**Comment by jplatte** [comment]
Maybe as an easy first step, `NormalizePath` itself could just have an `into_make_service` method? And have its docs call out that it should usually be (very close to) the outermost layer / has to run before routing.

**Comment by davidpdrsn** [comment]
What if axum provided a trait like

```rust
pub trait ServiceExt<R>: Service<R> + Sized {
    fn into_make_service(self) -> IntoMakeService<Self>;

    // fn into_make_service_with_connect_info(self) -> ...
}
```

`Router::into_make_service` should still take precedence since that method exists directly on `Router`. But if you've added a `Layer` around a `Router` you can use `ServiceExt::into_make_service`.

We could technically remove `Router::into_make_service` but I'm not a fan of users having to always import that trait, although I suppose it is more consistent.

**Comment by jplatte** [comment]
Sure, why not. Agree about keeping the inherent method.
