### ISSUE TITLE
Reverse proxied web socket extraction can panic

### ISSUE THREAD

**Issue by dwalker109** [tokio-rs/axum#1132]
### Version

axum v0.5.9
axum-core v0.2.6

### Platform

x86_64 GNU/Linux

### Crates

axum

### Description

With a misconfigured NGINX reverse proxy, extracting the websocket causes a panic.

I used a simple websocket route handler which uses the `WebSocketUpgrade` extractor. This works normally when accessing the Axum server directly. 

Also, when accessed via an NGINX proxy_pass with correct config like this it it works fine:

```
    location /ws/ {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass_request_headers on;
        proxy_http_version 1.1;
        proxy_pass  http://127.0.0.1:8081/ws/;
    }
```

However, if the `proxy_http_version 1.1;` line is omitted trying to establish the connection panics:

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.5.9/src/extract/ws.rs:277:69
```

I don't know enough about websockets to understand why this happened or if it is just one of those things, but perhaps the messaging could be clearer.

I'd be happy to tackle the bug if it was decided this was something to be fixed.

**Comment by davidpdrsn** [comment]
Thanks for noticing! The panic will be fixed in https://github.com/tokio-rs/axum/pull/1135 so it instead returns a rejection. I'm not exactly sure why hyper couldn't upgrade the request. Try opening an issue with [hyper](https://github.com/hyperium/hyper).

**Comment by dwalker109** [comment]
Will do - and thanks for jumping on this so quickly, incredible stuff 💯.
