### ISSUE TITLE
Unexpected crate name confliction when there is a package named `core` in a workspace

### ISSUE THREAD

**Issue by ikey4u** [tokio-rs/axum#1133]
### Version

axum 0.5.10

### Platform

archlinux with kernel 5.18

### Crates

Showed below.

### Description

If there is a package named `core` in a workspace, axum will failed to compile when implement FromRequest trait.  The demo below will make the problem clear.

Let make a directory called `axum-bug`, and the directory structure is
```
→ tree -I target
axum-bug
├── Cargo.lock
├── Cargo.toml
├── conflict
│   ├── Cargo.toml
│   └── src
│       └── main.rs
└── core
    ├── Cargo.toml
    └── src
        └── lib.rs

```
The `-I target` option is used to ignore the `target` directory. Content of each file in above is listed below.

- axum-bug

    - Cargo.toml

             [workspace]
             members = ["core", "conflict"]

    - conflict
        - Cargo.toml

                [package]
                name = "conflict"
                version = "0.1.0"
                edition = "2021"

                [dependencies]
                axum = "0.5.10"
                tokio = { version = "1.0", features = ["full"] }
                core = { path = "../core" }
                http = { version = "0.2.7" }

        - src/main.rs

                use axum::{
                    routing::get,
                    extract::{Form, FromRequest, RequestParts},
                    Router,
                    async_trait,
                };

                struct Auth;

                #[async_trait]
                impl<B> FromRequest<B> for Auth
                where
                    B: Send,
                {
                    type Rejection = http::StatusCode;

                    async fn from_request(req: &mut RequestParts<B>) -> Result<Self, Self::Rejection> {
                        Ok(Self)
                    }
                }

                #[tokio::main]
                async fn main() {
                    // build our application with a single route
                    let app = Router::new().route("/", get(|| async { "Hello, World!" }));

                    // run it with hyper on localhost:3000
                    axum::Server::bind(&"0.0.0.0:3003".parse().unwrap())
                        .serve(app.into_make_service())
                        .await
                        .unwrap();
                }

    - core

        - src/Cargo.toml

                [package]
                name = "core"
                version = "0.1.0"
                edition = "2021"

                [dependencies]

        - src/lib.rs

                #[cfg(test)]
                mod tests {
                    #[test]
                    fn it_works() {
                        let result = 2 + 2;
                        assert_eq!(result, 4);
                    }
                }

If you go to `conflict` crate and built it using `cargo run` you will have errors like

    error[E0433]: failed to resolve: could not find `pin` in `core`
      --> conflict/src/main.rs:18:14
       |
    18 |     async fn from_request(req: &mut RequestParts<B>) -> Result<Self, Self::Rejection> {
       |              ^^^^^^^^^^^^ could not find `pin` in `core`

    error[E0433]: failed to resolve: could not find `future` in `core`
      --> conflict/src/main.rs:18:14
       |
    18 |     async fn from_request(req: &mut RequestParts<B>) -> Result<Self, Self::Rejection> {
       |              ^^^^^^^^^^^^ could not find `future` in `core`

    error[E0433]: failed to resolve: could not find `marker` in `core`
      --> conflict/src/main.rs:18:14
       |
    18 |     async fn from_request(req: &mut RequestParts<B>) -> Result<Self, Self::Rejection> {
       |              ^^^^^^^^^^^^ could not find `marker` in `core`

    error[E0433]: failed to resolve: could not find `option` in `core`
      --> conflict/src/main.rs:18:87
       |
    18 |       async fn from_request(req: &mut RequestParts<B>) -> Result<Self, Self::Rejection> {
       |  _______________________________________________________________________________________^
    19 | |         Ok(Self)
    20 | |     }
       | |_____^ could not find `option` in `core`

but if you change the line `core = { path = "../core" } ` in `conflict/Cargo.toml` to something like
`mycore = { path = "../core", package = "core" }`, or if you remove the `impl FromRequest`, the error disappers.

**Comment by jplatte** [comment]
`core` is the name of the lowest-level builtin crate. You can't expect to be able to just shadow it and have things still work.

This is not a bug, and if it was it would be in async-trait, which defines thr macro that produces these errors.
