### ISSUE TITLE
Should we re-export `debug_handler` from axum itself?

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1143]
I've been thinking that we should consider re-exporting `debug_handler` from axum itself. So its more directly accessible and highlighted more clearly in the docs. Should probably be behind an on-by-default feature so you can avoid the dependency on `syn`.

**Comment by jplatte** [comment]
Sounds good to me, although I'm not sure about the feature being on by default 🤔

**Comment by davidpdrsn** [comment]
Yeah I don't think that's important either actually. The main benefit is showing it in the docs which it does regardless.
