### ISSUE TITLE
Make `TestClient` public

### ISSUE THREAD

**Issue by rouge8** [tokio-rs/axum#1146]
### Motivation

I want to write tests for my axum app. `TestClient` makes that easy to do so.

### Proposal

Make the existing `TestClient` public. 

### Alternatives

Use [axum-test-helper](https://github.com/cloudwalk/axum-test-helper) or vendor the `TestClient` myself.

**Comment by davidpdrsn** [comment]
It's just a thin wrapper around reqwest so I recommend you use that instead.

You can also have a look at the testing example https://github.com/tokio-rs/axum/blob/main/examples/testing/src/main.rs

**Comment by Eric-Arellano** [comment]
Hi, thanks for Axum! I heard about it on Rustacean Station and am really enjoying it.

Thoughts on adding an explicit section to the main page of the docs on testing, and linking to this example? It took some digging through GitHub to find the recommended approach. I'm happy to submit a patch if you'd like.

**Comment by davidpdrsn** [comment]
Sure. Wanna make a PR?
