### ISSUE TITLE
CI doesn't seems to not actually run for MSRV

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#115]
When setting up CI for axum I just copied the setup from Tower thinking that would be fine. However I didn't notice it included an MSRV of 1.40 [which is tested on CI](https://github.com/tokio-rs/axum/blob/main/.github/workflows/CI.yml#L15).

axum requires at least Rust 1.51 due the use of const generics in [`ContentLengthLimit`](https://github.com/tokio-rs/axum/blob/main/src/extract/content_length_limit.rs#L24). So it seems the 1.40 step on CI isn't actually running, since it should be failing 🤔 

We should fix CI so it actually does perform the checks and bump our MSRV to 1.51. If it turns out we use a feature not available on 1.51 I would be fine with requiring an even newer version, but it depends on the exact case.

**Comment by jplatte** [comment]
[Toolchain installation](https://github.com/tokio-rs/axum/blob/7cf8dafdce26276b1969111dbbf034bb98786e30/.github/workflows/CI.yml#L18-L21) sets neither `default` nor `override`, maybe it's just always the [pre-installed Rust toolchain](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#rust-tools) that's being used?

**Comment by jplatte** [comment]
By the way, today I learned about [act](https://github.com/nektos/act#readme), a way to locally run GitHub CI to test this kind of thing. Might be helpful :)
