### ISSUE TITLE
How to use multiple threads

### ISSUE THREAD

**Issue by 1192724521** [tokio-rs/axum#1160]
Complete requests:     200000
Concurrency Level:      5000

|work threads|Time taken for tests|Requests per second|
|:-:|:-:|:-:|
|1|43|4616|
|8|44|4484|
|16|41|4777|

Guys, why does the number of worker threads have no effect on concurrency, I'm confused.

**Comment by davidpdrsn** [comment]
I'm not exactly sure and you give way to little context for us to provide an answer. You gotta help us help you please.

With that said axum doesn't know anything about threads so this is a question for tokio/hyper. Please open an issue with one of those repos.
