### ISSUE TITLE
How to use multiple threads

### ISSUE THREAD

**Issue by 1192724521** [tokio-rs/axum#1162]
```rust
//#[tokio::main(worker_threads = 16)]
//#[tokio::main(worker_threads = 8)]
#[tokio::main(worker_threads = 1)]
async fn main() {
    let app = Router::new().route("/", get(root));
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));

    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn root() -> &'static str {
    tokio::spawn(async move {
        tokio::time::sleep(tokio::time::Duration::from_secs(2)).await;
        "success"
    })
    .await
    .unwrap()
}
```
Complete requests:     100000
Concurrency Level:      10000

|work threads|Time taken for tests|Requests per second|
|:-:|:-:|:-:|
|1|31|3179|
|8|31|3142|
|16|31|3139|

Why does the number of worker threads have no effect on concurrency?
I just can't figure it out. I need a little help.please.Thank you.

I want this result
|work threads|Time taken for tests|Requests per second|
|:-:|:-:|:-:|
|1|31|3179|
|2|15|6000|
|4|10|10000|

**Comment by davidpdrsn** [comment]
[Like I said yesterday](https://github.com/tokio-rs/axum/issues/1160#issuecomment-1183292663), please ask the hyper or tokio. axum doesn't know anything about threads and has no control over this. I recommend you join the [tokio discord](https://discord.gg/tokio) and ask in #hyper.

**Comment by 1192724521** [comment]
Oh, oh, you can delete these two issues.Any trouble

> [就像我昨天说](https://github.com/tokio-rs/axum/issues/1160#issuecomment-1183292663)的，请问hyper或tokio。axum对线程一无所知，也无法控制这一点。我建议你加入[tokio不和谐，](https://discord.gg/tokio)并在#hyper询问。

Oh, oh, you can delete these two issues.Any trouble
