### ISSUE TITLE
Add an example for multiple listen addresses

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#1174]
We should have an example for multiple listen addresses. Most of the code was already written by David, you can copy it from https://github.com/tokio-rs/axum/discussions/1063#discussioncomment-3051746. Somebody just needs to create an example from that and open a PR for it, and I'm always low on time.

There should probably also be a small comment about IPv6 catch-all listeners applying to IPv4 as well in some OS configurations (see https://serverfault.com/q/21657).

**Comment by DesmondWillowbrook** [comment]
I'd like to work on this.
