### ISSUE TITLE
Add an example for a GET-or-HEAD handler that special-cases HEAD

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#1175]
Registering a `GET` route also registers a `HEAD` route that calls the same handler. axum will strip the response body if this handler is called with `HEAD`, but that is potentially much slower than never generating a response body in the first place. We should have an example with a handler that uses `http::Method` as an extractor and checks its value to decide whether to build a response with or without a body.

**Comment by DesmondWillowbrook** [comment]
I'd be happy to tackle this one as well, though I understand if you want to reserve an issue for the upcoming TWiR.

**Comment by jplatte** [comment]
Maybe we wait a few days and if nobody else shows interest you do it?

**Comment by lexcao** [comment]
Hi, @jplatte 
I found this from TWIR.
I am interested in contributing, let me grab this.
Thanks.
