### ISSUE TITLE
"Commonly used middleware" links are broken in middleware module docs

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#1180]
Title says it all.

**Comment by jplatte** [comment]
Go ahead!

**Comment by jplatte** [comment]
@davidpdrsn have you been following the discussion in #1184? There seem to be some reproducibility issues with this bug. Maybe it's worth just doing another small point release with recent back-portable improvements and seeing whether this is fixed when docs.rs does a re-generation of the docs? Or alternatively, I think there's a way for people from the docs.rs team to trigger re-builds of existing docs, if you want I can get in touch with them.

**Comment by davidpdrsn** [comment]
@jplatte Sure! I'll backport some stuff and prep a release PR.

**Comment by davidpdrsn** [comment]
0.5.14 is out. Lets see if that fixes it 🤞

**Comment by davidpdrsn** [comment]
Seems that didn't fix it :(

**Comment by jplatte** [comment]
Right. Have you tried reproducing locally yourself? If it's really not reproducible easily, we might have to have a closer look at how docs.rs actually operates (which Nightly / which compiler flags / ...).

**Comment by davidpdrsn** [comment]
I tried a regular `cargo doc` yesterday and that worked. So yeah I think we need to dig deeper.

**Comment by jplatte** [comment]
Did you try what I posted in #1180?

**Comment by davidpdrsn** [comment]
That works if I build with `RUSTDOCFLAGS='--cfg docsrs' cargo +nightly doc --all-features` so without `--no-deps`.

**Comment by jplatte** [comment]
But what happens with `--no-deps`? That's important, docs.rs doesn't re-create all the dependencies docs when documenting one crate (it uses the rustdoc-map feature instead to be able to generate cross-crate links).

**Comment by davidpdrsn** [comment]
Then it doesn't work and I get these errors in the browser dev console

<img width="752" alt="image" src="https://user-images.githubusercontent.com/718941/180972797-4a02da49-bfbc-4cb2-9872-ae0ebdd2a8e0.png">

**Comment by jplatte** [comment]
Right. I would expect that #1184 changes nothing about that? I think we just have to use http links to `docs.rs` for now. And ideally report a bug about this on [rust-lang/rust](/rust-lang/rust) (I couldn't find an existing one).

**Comment by jplatte** [comment]
Sooo.. I found out what's wrong! It's that the intra-doc links only resolve tower / tower-http actually contain those items, which is determined by the features activated on them. It looks like somehow `docs.rs` ignores dev-dependencies when building docs, which are of course usually not required for docs to build correctly, but here they are. I'll look for existing bug reports about this.
