### ISSUE TITLE
Ship new version of axum and axum-extra

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1202]
We accidentally shipped https://github.com/tokio-rs/axum/pull/1171 in a minor version which included a breaking change in axum but didn't merge a new version of axum-extra so axum-extra broke.

I've yanked axum 0.5.14 so no one can update to it.

I'll ship a new version of axum and axum-extra (that depends on the version of axum) in a week from today.

**Comment by jplatte** [comment]
Actually, we can't just ship both as non-breaking, since people could upgrade to the new version of axum without upgrading axum-extra. We'll have to backport #1171 in a way that doesn't change the number of type parameters, or have it wait until axum 0.6.

**Comment by Xuanwo** [comment]
Any updates on this? We have to work around to make `cargo audit` happy: https://github.com/datafuselabs/databend/issues/6996

**Comment by davidpdrsn** [comment]
Not yet. I've been on vacation. ETA is sometime this week.

**Comment by Xuanwo** [comment]
> Not yet. I've been on vacation. ETA is sometime this week.

Oh, sorry for disturbing your vacation. Have a nice day!

**Comment by davidpdrsn** [comment]
This was fixed in https://github.com/tokio-rs/axum/pull/1233
