### ISSUE TITLE
Make `IntoMakeService::new()` public

### ISSUE THREAD

**Issue by daxpedda** [tokio-rs/axum#1203]
### Motivation

I would like to wrap a user supplied app, like a `Router`, in a global layer. For that purpose I stumbled upon ["Routing to services/middleware and backpressure"](https://docs.rs/axum/0.5.13/axum/middleware/index.html#routing-to-servicesmiddleware-and-backpressure), talking about [`ServiceBuilder`](https://docs.rs/tower/0.4.13/tower/struct.ServiceBuilder.html).

The issue is that to use it for example with `axum-server`, I need to turn it into a service factory, exactly like [`Router::into_make_service()`](https://docs.rs/axum/0.5.13/axum/routing/struct.Router.html#method.into_make_service), which isn't available for `ServiceBuilder`.

### Proposal

~~Add `ServiceBuilder::into_make_service()`, wrapping `ServiceBuilder` in [`IntoMakeService`](https://docs.rs/axum/0.5.13/axum/routing/struct.IntoMakeService.html).~~

I just realized that `ServiceBuilder` doesn't live in `axum`, so we can't actually add methods. So I changed my proposal to make `IntoMakeService::new()` public instead.

### Alternatives

I'm actually not sure at all if this the appropriate solution to begin with, maybe there is a better alternative?

~~I have also tried to roll my own `IntoMakeService`, because `IntoMakeService::new()` is private, which worked as expected and requires very little code.~~

Maybe a trait adding a `into_make_service()` method to appropriate types would be a better solution.

**Comment by davidpdrsn** [comment]
You can use `tower::make::Shared` instead. It's the same. We have the type in axum to not have a public dependency on tower.

**Comment by daxpedda** [comment]
> We have the type in axum to not have a public dependency on tower.

Do you mean "We **don't** have the type in axum"? Or do you mean a different type then `Shared` (I couldn't find `Shared` in axum)?

In any case, it worked like a charm!

**Comment by davidpdrsn** [comment]
`Shared` is in tower but we have `IntoMakeService` in axum to not have tower as part of axum's public API.

**Comment by daxpedda** [comment]
Ah, I see! Thank you for the explanation!

**Comment by ttys3** [comment]
> You can use `tower::make::Shared` instead. It's the same. We have the type in axum to not have a public dependency on tower.

Maybe this could add to the `IntoMakeService` code comment so that new learners will know this ?

**Comment by daxpedda** [comment]
> > You can use `tower::make::Shared` instead. It's the same. We have the type in axum to not have a public dependency on tower.
> 
> Maybe this could add to the `IntoMakeService` code comment so that new learners will know this ?

@davidpdrsn are you against this idea? Was just about to make a PR before I saw your reaction.

**Comment by davidpdrsn** [comment]
I would rather find a solution to https://github.com/tokio-rs/axum/issues/1120 or document how to wrap the whole router and then use `Shared`.

I don't documenting `Shared` at `IntoMakeService` solves much.

**Comment by daxpedda** [comment]
> document how to wrap the whole router and then use `Shared`.

How about adding some text to `Server::serve` about that? Or where else would you suggest? Happy to make the PR.

> I don't documenting `Shared` at `IntoMakeService` solves much.

Why not, considering the scenario that led to the this issue right now, it seems to me that it is quiet appropriate. After all `IntoMakeService` exists specifically to avoid re-exporting `Shared`, so documenting exactly that fits the bill in my opinion.

I agree it's not solving anything and it doesn't replace documentation at more discoverable places.

**Comment by davidpdrsn** [comment]
> How about adding some text to Server::serve about that? Or where else would you suggest? Happy to make the PR.

`Server` is re-exported from hyper so you'd have to make a PR against hyper.

> Why not, considering the scenario that led to the this issue right now, it seems to me that it is quiet appropriate. After all IntoMakeService exists specifically to avoid re-exporting Shared, so documenting exactly that fits the bill in my opinion.

axum has several types like that. Should we also document that `Route` is just a `BoxCloneService` from tower?

I think it's treating the symptom rather than the problem 🤷

**Comment by daxpedda** [comment]
> `Server` is re-exported from hyper so you'd have to make a PR against hyper.

Ah, I made an unfortunate mistake here, I meant `axum_server::Server`. I can't really speak about how `axum` should treat this issue, I don't really have a use-case. To me the whole limitation happens in `axum_server::Server::serve()`.

So I will leave this problem to others and will make a new issue in `axum-server`.

> axum has several types like that. Should we also document that `Route` is just a `BoxCloneService` from tower?

I don't know if that actually helps anybody.

> I think it's treating the symptom rather than the problem shrug

I don't think treating a symptom excludes treating the cause, treating the symptom isn't useless either, we have a real-world example right here. But as with the problem above, I will leave this to people with an actual understanding of the problem and with a stake in it.

**Comment by davidpdrsn** [comment]
I still think the right solution is what wrote here https://github.com/tokio-rs/axum/issues/1203#issuecomment-1199108275
