### ISSUE TITLE
Static server doesn't handle missing file

### ISSUE THREAD

**Issue by nanoqsh** [tokio-rs/axum#1208]
### Version
```
├── axum v0.5.13
│   ├── axum-core v0.2.7
```

### Platform
```
Linux npc 5.18.14-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 23 Jul 2022 11:46:17 +0000 x86_64 GNU/Linux
```

### Description

I tried this code:
```rust
use {
    axum::{http::StatusCode, routing::get_service, Router, Server},
    std::net::SocketAddr,
    tower_http::services::ServeDir,
};

#[tokio::main]
async fn main() {
    let service = ServeDir::new("static");

    let app =
        Router::new().fallback(get_service(service).handle_error(|_| async {
            (StatusCode::INTERNAL_SERVER_ERROR, "Something went wrong..")
        }));

    let addr = SocketAddr::from(([0; 4], 3000));
    Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .expect("serve");
}
```

I expected to see a response "Something went wrong.." with 500 status code when I request a non-existent file.
Instead, I got an empty page with 404 status code:
![image](https://user-images.githubusercontent.com/40631392/181745733-e57018b7-cfc0-4549-8380-e33728b417a8.png)

Although existing files are hosted without any problems.

**Comment by davidpdrsn** [comment]
You're misunderstanding how error handling works. You'll wanna use https://docs.rs/tower-http/latest/tower_http/services/fs/struct.ServeDir.html

See https://docs.rs/axum/latest/axum/error_handling/ for more details about error handling.

**Comment by nanoqsh** [comment]
Thanks, I'll try. It seemed to me that Axum could handle this, because I took the code base from the examples
