### ISSUE TITLE
Path extractor which uses `FromStr`

### ISSUE THREAD

**Issue by casey** [tokio-rs/axum#1224]
I have a type which has a `FromStr` implementation and a `Deserialize` implementation which are different. I'd like to use the `FromStr` implementation with an extractor, so it would be nice if there was an `axum::extract::FromStr` which would allow me to use it in a route handler:

```
async fn foo(axum::extract::FromStr(foo): axum::extract::FromStr<Foo>) -> impl IntoResponse {
  todo!()
}
```

**Comment by davidpdrsn** [comment]
To parse the request body you mean? Yeah I suppose we could provide that in axum-extra.

Not sure about how to handle the errors. I assume the associated `Err` would have to implement `IntoResponse` so we can use that as the rejection 🤔

**Comment by casey** [comment]
> To parse the request body you mean? Yeah I suppose we could provide that in axum-extra.

Actually I was using it to parse a path component:

```
app.route("/foo/:foo", get(foo))
```

> Not sure about how to handle the errors. I assume the associated `Err` would have to implement `IntoResponse` so we can use that as the rejection

Can it map it the same way that errors from `Deserialize` are handled?

> `FromStr` would also conflict if you've imported the trait, so maybe not the best name 🤔

Yah. I was thinking `Parse`, but that's ambiguous. `PathFromStr` would work if it's for path components only.

**Comment by davidpdrsn** [comment]
> Actually I was using it to parse a path component:

Oh then we definitely need a clearer name.  It loving `PathFromStr` but could work.

How would it handle multiple path params? `Deserialize` has all the visitor machinery to deserialize multiple values into seqs and maps.

> Can it map it the same way that errors from Deserialize are handled?

No. For `Path` axum defines the deserializer and thus also the error. But for `FromStr` the user defines the error.

Can you explain more about your use case for this?

**Comment by davidpdrsn** [comment]
Could require tuples for multiple values but that's quite odd if you only have one param:

```rust
PathFromStr<(Foo,)>
PathFromStr<(Foo, Bar, ...)>
```

**Comment by casey** [comment]
> How would it handle multiple path params? Deserialize has all the visitor machinery to deserialize multiple values into seqs and maps.

I think requiring a tuple for even one element wouldn't be that bad.

> Can you explain more about your use case for this?

I have a type, let's call it `Foo`, whose internal representation is just a number. So I use:

```
#[derive(Deserialize, Serialize)]
#[serde(transparent)]
struct Foo(u64);
```

`Foo` also has a `FromStr` implementation that supports parsing a `Foo` from a bunch of other string representations. These different string representations are used in the CLI interface, so that you can pass a Foo in a bunch of user friendly ways.

However, the `Deserialize` impl is used in a bunch of API/RPC calls, where parsing from the user-friendly `FromStr` representations doesn't make sense, and only parsing from numbers should be supported.

`Foo` is also used in an axum route, where we *do* want to parse from the user-friendly variations, because this is a user-facing path, and we want users to be able to type the different representations into the URL bar. So we want to use `FromStr`, and already have a `Deserialize` impl that we can't change.

**Comment by jplatte** [comment]
I think using `FromStr` is the wrong solution for your problem. I'd recommend a different type, possibly a newtype, with a different `Deserialize` implementation.

**Comment by casey** [comment]
That's basically what I'm doing:

```
pub(crate) struct DeserializeFooFromStr(pub(crate) Foo);

impl<'de> Deserialize<'de> for DeserializeFooFromStr {
  fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
  where
    D: Deserializer<'de>,
  {
    Ok(Self(
      FromStr::from_str(&String::deserialize(deserializer)?).map_err(de::Error::custom)?,
    ))
  }
}
```

However, I do think that often times, `FromStr` is what's desired. `FromStr` is the standard trait to use when deserializing from something a user typed in. If a URL is something a user types in, you probably want `FromStr`, so I think axum providing a way to do that is appropriate.

**Comment by davidpdrsn** [comment]
> However, I do think that often times, FromStr is what's desired. FromStr is the standard trait to use when deserializing from something a user typed in.

Well basic types like `u32`, `i32`, etc. are [already parsed using `FromStr`](https://github.com/tokio-rs/axum/blob/main/axum/src/extract/path/de.rs#L34).

For more complex types I think doing what you're doing (or maybe using [`serde_with`](https://docs.rs/serde_with/latest/serde_with/struct.DisplayFromStr.html)) is fine.

So I don't think this is something we need to support.
