### ISSUE TITLE
Server sent events without data are ignored

### ISSUE THREAD

**Issue by Fxxxlei** [tokio-rs/axum#1238]
### Version

0.5.13-0.5.15

### Platform

all

### Description

Server-sent events without a data field are ignored and not dispatched in the browser.
This is documented in the specs (https://html.spec.whatwg.org/multipage/server-sent-events.html#event-stream-interpretation step 2), but I couldn't find that info anywhere else.

Since axum::response::sse::Event doesn't prevent Events without a data field from being sent, I think this behaviour should be documented and/or prevented in axum.

**Comment by davidpdrsn** [comment]
I just tested this and they not totally ignored. If you send `Event::default()` axum sends a `\n` in the body. I guess its just the browser that ignores that event.

I'm honestly not sure what the most correct thing to do is but I guess we could just ignore events if they're empty and not send anything in the body. What do you think?

**Comment by Fxxxlei** [comment]
The specs say the browser must ignore the event, if it doesn't have a data field. It doesn't prohibit sending events that are ignored this way.

Question is if we want to allow sending events we know won't be dispatched in a compliant client.
On the other hand, I have a use cases for non-dispatched events (to check if the client is still connected).

I'd say the current behaviour is as intended but should be documented. I was sending named events without data and was wondering why they were not dispatched in the client.

**Comment by davidpdrsn** [comment]
Sure. I'm fine with just documenting the current behavior. Do you wanna submit a PR?

**Comment by davidpdrsn** [comment]
I've made a PR for this https://github.com/tokio-rs/axum/pull/1242
