### ISSUE TITLE
Make `SpaRouter` support precompressed files

### ISSUE THREAD

**Issue by lcmgh** [tokio-rs/axum#1240]
## Feature Request

With `ServeDir::new(".").precompressed_gzip()` one can serve precompressed files to the client. I am wondering how I can achieve the same with the `SpaRouter`.

See https://github.com/tokio-rs/axum/issues/66#issuecomment-970730249

```rust
let app: _ = Router::new()
    .merge(axum_extra::routing::SpaRouter::new("/dist", "src/static/dist"))
    .route("/api/userinfo", get(userinfo))
    .layer(TraceLayer::new_for_http())
    .layer(AddExtensionLayer::new(groups));
```

### Motivation

How else could I serve precompressed files while also utilizing features of SpaRouter?

### Proposal

Add precompressed methods as done with ServeDir?

**Comment by davidpdrsn** [comment]
If recommend just using `ServeDir` directly.

**Comment by lcmgh** [comment]
For future googlers
```rust
    let app: _ = Router::new()
        // .merge(axum_extra::routing::SpaRouter::new("/dist", "src/static/dist"))
        .fallback(get_service(ServeFile::new("src/static/dist/index.html")).handle_error(handle_error))
        .nest("/dist", get_service(ServeDir::new("src/static/dist").precompressed_br()).handle_error(handle_error))
        .nest("/api/userinfo", get(userinfo))
        .layer(TraceLayer::new_for_http())
        .layer(AddExtensionLayer::new(groups));
```

**Comment by davidpdrsn** [comment]
[`ServeDir` also has its own fallback mechanism](https://docs.rs/tower-http/latest/tower_http/services/fs/struct.ServeDir.html#method.fallback) that you can use instead.
