### ISSUE TITLE
doc: Broken middleware links

### ISSUE THREAD

**Issue by gitmalong** [tokio-rs/axum#1244]
## Bug Report

https://docs.rs/axum/latest/axum/middleware/index.html#commonly-used-middleware

Links below [Commonly used middleware](https://docs.rs/axum/latest/axum/middleware/index.html#commonly-used-middleware) are not working

**Comment by davidpdrsn** [comment]
This has been fixed on main. See https://github.com/tokio-rs/axum/issues/1180
