### ISSUE TITLE
Re-organize changelog to make updating to 0.6 easier

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1247]
For 0.6 I wanna re-organize to changelog by grouping the changes into areas (like routing, extractors, responses, etc) and provide examples for how to migrate from 0.5 to 0.6. This should also explicitly call out subtle routing changes like the ones made in https://github.com/tokio-rs/axum/pull/1086

**Comment by jplatte** [comment]
Maybe we can also highlight that axum recently had its first birthday? 👶🏼

**Comment by davidpdrsn** [comment]
Hehe sure!
