### ISSUE TITLE
Improve `MatchedPath` API

### ISSUE THREAD

**Issue by Altair-Bueno** [tokio-rs/axum#1255]
### Motivation

`as_str` is not a standard trait implementation, which is discouraged by the Rust API Guidelines. This forces library authors to create their own workarounds. (See [`Key`](https://github.com/Altair-Bueno/axum-template/blob/cc89b515789a87a49c7c40748170a6733784db9c/src/key.rs#L42) on `axum-template`)

### Proposal

`MatchedPath` lacks some trait implementations that would be nice to have, as well as access to the internal `Arc<str>` it uses.

- [ ] Implement common conversion traits such as:
	- [ ] `Borrow<str>`
	- [ ] `AsRef<str>`
	- [ ] `From<MatchedPath> for &str`
    - [ ] `From<MatchedPath> for Arc<str>`
- [ ] Allow access to the internal `Arc<str>`
    - [ ] `as_arc`

### Alternatives

- Allow de-structuring `MatchedPath` (constructor is currently `pub (crate)`)
  - de-structuring would allow middleware to replace `MatchedPath` from requests. May interfere with routing?
  - `Arc<str>` is not commonly used and would probably confuse many people

### Additional resources

- `MatchedPath`'s first apperance: https://github.com/tokio-rs/axum/issues/386
- `matched_path.rs` permalink https://github.com/tokio-rs/axum/blob/90a2e04e9ddc167bf57c9201d9f8fb306aaea5d3/axum/src/extract/matched_path.rs#L57
- Rust API guidelines. `CONV_TRAITS`: https://rust-lang.github.io/api-guidelines/interoperability.html#conversions-use-the-standard-traits-from-asref-asmut-c-conv-traits

**Comment by jplatte** [comment]
Can you explain why you have created your own extractor that wraps `MatchedPath`? The file you linked basically just shows *what* you did as a workaround, not what issue you worked around.

**Comment by Altair-Bueno** [comment]
It's mostly a workaround for lifetime issues with `as_str`


`Render`[^1] and `RenderHtml` are designed to take any key (K: `Borrow<str>`), making it work with `String`, `&str`, `Cow`... you name it. It's generic over any string kind to be more flexible, which is useful if your route must always use the same template, no matter the route it's hooked up to.

```rs
use axum_template::Engine;
use minijinja::Environment;

async fn handler(engine: Engine<Environment<'static>>) -> impl IntoResponse {
	// Static key (&'static str)
    Render("foo", engine, ())
}
```

The thing is, because `MatchedPath` does not implement any of those traits, a transformation is required.

```text
error[E0277]: the trait bound `MatchedPath: Borrow<str>` is not satisfied
 --> src/main.rs:5:96
  |
5 |   async fn handler(path: MatchedPath, engine: Engine<Environment<'static>>) -> impl IntoResponse {
  |  ________________________________________________________________________________________________-
6 | |     Render(path, engine, ())
7 | | }
  | | ^
  | | |
  | |_the trait `Borrow<str>` is not implemented for `MatchedPath`
  |   required by a bound introduced by this call
  |
  = help: the trait `IntoResponse` is implemented for `Render<K, E, S>`
  = note: required because of the requirements on the impl of `IntoResponse` for `Render<MatchedPath, Engine<Environment<'_>>, ()>`

For more information about this error, try `rustc --explain E0277`.
```

Also, because `as_str` shares the same lifetime as `MatchedPath`, it would outlive the current scope

```text
error[E0515]: cannot return value referencing local variable `path`
 --> src/main.rs:6:5
  |
6 |     Render(path.as_str(), engine, ())
  |     ^^^^^^^-------------^^^^^^^^^^^^^
  |     |      |
  |     |      `path` is borrowed here
  |     returns a value referencing data owned by the current function

For more information about this error, try `rustc --explain E0515`.
```


### Additional resources

- [^1]: https://github.com/Altair-Bueno/axum-template/blob/cc89b515789a87a49c7c40748170a6733784db9c/src/render.rs#L34

**Comment by davidpdrsn** [comment]
I'm fine with implementing `AsRef`. Not sure implementing `Borrow` is right - don't have a great intuition for the differences but `AsRef` is more commonly used I think.

I don't we should expose constructors or access to the inner `Arc<str>`.

**Comment by jplatte** [comment]
Yeah, the right trait, if any, for your use case is `AsRef`. I guess we could implement it for `MatchedPath`, but I'm not sure we should.

Another way you could solve this is to remove the `K` parameter from your types, and instead have a constructor to put this on:

```rust
pub struct Render<E, S> {
    key: String,
    engine: E,
    data: S
}

impl<E, S> Render
where
    E: TemplateEngine,
    S: Serialize,
{
    pub fn new(key: &str /* or impl AsRef<str> */, engine: E, data: S) -> Self {
        Self {
            key: key/* .as_ref() */.to_owned(),
            engine,
            data
        }
    }
}

// now `Render::new(matched_path.as_str(), engine, data)` can be used
```

**Comment by Altair-Bueno** [comment]
> I'm fine with implementing AsRef. Not sure implementing Borrow is right - don't have a great intuition for the differences but AsRef is more commonly used I think.

I think the biggest difference is explained [on `AsRef` docs](https://doc.rust-lang.org/std/convert/trait.AsRef.html), but I agree it's not intuitive

> [Borrow](https://doc.rust-lang.org/std/borrow/trait.Borrow.html) also requires that [Hash](https://doc.rust-lang.org/std/hash/trait.Hash.html), [Eq](https://doc.rust-lang.org/std/cmp/trait.Eq.html) and [Ord](https://doc.rust-lang.org/std/cmp/trait.Ord.html) for a borrowed value are equivalent to those of the owned value

---

> the right trait, if any, for your use case is AsRef

Yea i think you are right, it's even more generic than `Borrow`

> but I'm not sure we should.

Could you elaborate on your concerns? `AsRef`, `AsRefMut`, `From`... are pretty common on Rust libraries

> Another way you could solve this is to remove the K parameter from your types, and instead have a constructor to put this on:

My fist implementation used String internally, but I replaced it with generics to be more flexible. In the end, it's the same thing, but `to_owned` lives on `Key` (which hopefully I can remove after closing this issue)

**Comment by jplatte** [comment]
I'm just not sure treating `MatchedPath` as "a kind of string" is right. But if David is fine with it, I don't want to be blocking it.

**Comment by davidpdrsn** [comment]
> I'm just not sure treating MatchedPath as "a kind of string" is right

Hm yeah that might be right 🤔

**Comment by Altair-Bueno** [comment]
> I'm just not sure treating MatchedPath as "a kind of string" is right.

Hmm interesting. This raises the question: Is `Arc<str>` a kind of string? It's a pointer to a string slice yet implements `AsRef<str>`.

**Comment by davidpdrsn** [comment]
I'd say yes `Arc<str>` is as much a string as `&str` is. That is also just a pointer to a string.

**Comment by Altair-Bueno** [comment]
From my understanding there are two options:

- Allow unwrapping to a more featured string type (`Arc<str>`)
  - Making the constructor public is off the table
  - `From<MatchedPath> for Arc<str>` lgtm
  - Paired with a function (`as_arc`?) to make the api consistent
  - Arc<str> doesn't impl `DerefMut`
- Making `MatchedPath` truthful string type, not just implementing `AsRef`
  - I think we all agree that anything could be an string if you try hard enought (String is just a Vec)
  - Requires more work trait impl
  - Consistent with [`BodyStream`](https://docs.rs/axum/latest/axum/extract/struct.BodyStream.html), which also has no public constructor yet behaves like what it wraps

**Comment by davidpdrsn** [comment]
I still think what jplatte suggested [here](https://github.com/tokio-rs/axum/issues/1255#issuecomment-1213031336) looks reasonable and wont require any changes to axum.

**Comment by Altair-Bueno** [comment]
> I still think what jplatte suggested https://github.com/tokio-rs/axum/issues/1255#issuecomment-1213031336 looks reasonable and wont require any changes to axum.

Currently is what `Key` does internally, but requires one extra allocation. I wish to access that internal `Arc` to avoid it, or at least access it on some standard way (`AsRef` as discussed before, or any other standard trait)

**Comment by davidpdrsn** [comment]
A single allocation isn't much to worry about.

I think I'll close this for now. I don't think implementing `AsRef<str>` for `MatchedPath` since I don't consider it a kind of string.
