### ISSUE TITLE
Should `FromRequest` have an associated `Output` type?

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#127]
### Motivation

`FromRequest` is currently requires `from_request` to return `Result<Self, _>`.
This means when you implement it for something like `extract::Extension` you
must return an `extract::Extension` value. That requires users to pattern match
to pull out the inner value. That can get a bit tedious, especially when using
nested extractors like `ContentLengthLimit`.

### Proposal

If we added an associated type `Output` to `FromRequest` it would allow
extractors to return values other than `Self` and you wouldn't need to pattern
match:

```rust
#[async_trait]
pub trait FromRequest<B> {
    type Output;
    type Rejection: IntoResponse;

    async fn from_request(req: &mut RequestParts<B>) -> Result<Self::Output, Self::Rejection>;
}

pub struct Extension<T>(PhantomData<T>);

#[async_trait]
impl<T, B> FromRequest<B> for Extension<T> {
    type Output = T;
    type Rejection = /* ... */;

    async fn from_request(req: &mut RequestParts<B>) -> Result<Self::Output, Self::Rejection> {
        // ...
    }
}

async fn handler(value: Extension<SomeValue>) {
    // `value` is now `SomeValue`
    // no need for matching with `Extension(value): Extension<SomeValue>`
}
```

Would be a breaking change so something to consider for 0.2

### Alternatives

Keep the current API as it works just fine :shrug:

**Comment by jplatte** [comment]
```rust
async fn handler(value: Extension<SomeValue>) {
    // `value` is now `SomeValue`
}
```

Maybe I'm being very stupid, but I think you fooled yourself somewhere along designing this API because that comment is clearly false.

**Comment by davidpdrsn** [comment]
oh yeah wait I see... never mind then 😅
