### ISSUE TITLE
Fix documentation for tower-http middleware

### ISSUE THREAD

**Issue by va-an** [tokio-rs/axum#1295]
### Motivation
Hello!
I noticed that we have broken links for [this section on docs.rs](https://docs.rs/axum/latest/axum/middleware/index.html#commonly-used-middleware)  
For local `cargo doc --open` the same.

### Proposal

Look like someting not working properly [in Cargo.toml](https://github.com/tokio-rs/axum/blob/f1769e513475189251710b0021e72ac0514abf3c/axum/Cargo.toml#L29):

```toml

# Required for intra-doc links to resolve correctly
__private_docs = ["tower/full", "tower-http/full"]
```

But I can't figure it out on my own how to solve it for now.
I will be glad fix this with some help.

### Alternatives

We can use links to `tower-http` docs instead on inner link as an option.

**Comment by davidpdrsn** [comment]
It works but the fix isn't released yet. If you build axum locally with `cargo docs --all-features --open` you'll see the links are working again.
