### ISSUE TITLE
Add helper methods to run easily run extractors

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1297]
In axum 0.5 you could call `request_parts.extract::<T>()` which is a bit nicer than `T::from_request(request_parts)` but https://github.com/tokio-rs/axum/pull/1272 removed the `RequestParts` type and thus also this method.

For 0.6 we should think about adding back something similar.

Haven't thought much about it but perhaps something like

```rust
pub trait RequestExt {
    async fn extract<T>(self) -> Result<(Self, T), T::Rejection>
    where
        T: FromRequest,
    {
        ...
    }
}

pub trait PartsExt {
    async fn extract<T>(&mut self) -> Result<T, T::Rejection>
    where
        T: FromRequestParts,
    {
        ...
    }
}
```

Should also think about how to pass state and whether we need separate methods for when the state is and isn't `()`.

**Comment by jplatte** [comment]
We should also have `extract_parts` in `RequestExt`, so users don't need to do `into_parts` + `from_parts` themselves. Although calling that multiple times consecutively might be slower than doing one `into_parts` + `from_parts` and using `.extract` on the `Parts`.
