### ISSUE TITLE
Validate extension types of handlers

### ISSUE THREAD

**Issue by julianbuettner** [tokio-rs/axum#1303]
### Motivation

```rust
fn handler(Extension(state): Extension<Arc<i32>>) {}
```

When trying to extract a extension of a `State` that ist not `.layer()`d on to the `app`,
a HTTP 500 is returned when querying the handler.

```bash
$ curl http://localhost:3000/
Missing request extension: Extension of type `alloc::sync::Arc<i32>` was not found. Perhaps you forgot to add it? See `axum::Extension`.
```

To validate whether or not all endpoints have valid extension types, every single endpoint has to be queried at runtime.

This feels frustrating and avoidable.  
I assume many projects don't build their paths dynamically, but define the entire application at compile time.  
In these cases it feels like it could be validated at compile time (maybe with macros? other ways?) to fit the
"*If it compiles, it works*" philosophy.  
I understand that this is probably not an easy implementable solution.  

However, validating extension types of endpoints when *starting*, is a simpler logic and would be nice to have available.

### Proposal

Add a method to `axum::Router` which allows for validating handler extensions.
```rust
let state = State::new();
let app = Router::new()
    .route("/", service.get(handler))
    .layer(Extension(state))
    .validate_handler_extension_types()?;
```

Alternatively `app` could require to have the layer mounted before adding routes
requiring this extension type.

```rust
let state = State::new();
let app = Router::new()
     .layer(Extension(state))
    .route("/", service.get(handler));   // panic or Err(x) if layer would not have been mounted
```

### Alternatives

- Doing nothing
- Documenting a way to figure out if all endpoints are using extractable extensions.

**Comment by davidpdrsn** [comment]
This will be fixed in the next major version via the new `State` extractor.

See https://github.com/tokio-rs/axum/pull/1155

We don't have an ETA for when 0.6 will be shipped.
