### ISSUE TITLE
`nest` claims that it panics if the nested router has a fallback

### ISSUE THREAD

**Issue by lilyball** [tokio-rs/axum#1319]
https://github.com/tokio-rs/axum/blob/426b9f91e8c465d8128c2d163d978dd205dcb8fb/axum/src/docs/routing/nest.md?plain=1#L149-L150

This isn't true anymore, and this claim comes immediately after documentation recommending adding a fallback to the nested router.

**Comment by davidpdrsn** [comment]
That's just an oversight. Thanks for noticing!
