### ISSUE TITLE
Doc request: `State(state): State<AppState>` should be the last parameter

### ISSUE THREAD

**Issue by freedit-dev** [tokio-rs/axum#1323]
## Bug Report

if `ValidatedForm(input): ValidatedForm<FormPost>` is not the last one, the compiler keeps complaining that `FromRequestPart` trait is not implemented, which is very misleading.

```rust
pub(crate) async fn edit_post_post(
    State(db): State<Db>,
    ValidatedForm(input): ValidatedForm<FormPost>,
    cookie: Option<TypedHeader<Cookie>>,
    Path((iid, old_pid)): Path<(u64, u64)>,
) -> Result<impl IntoResponse, AppError> {
```

Just change the it to the last parameter, it works.

```rust
pub(crate) async fn edit_post_post(
    State(db): State<Db>,
    cookie: Option<TypedHeader<Cookie>>,
    Path((iid, old_pid)): Path<(u64, u64)>,
    ValidatedForm(input): ValidatedForm<FormPost>,
) -> Result<impl IntoResponse, AppError> {
```

And `Extension` didn't complain it. I think there should be some docs to mention that.

### Version

axum v0.6.0-rc.1

**Comment by davidpdrsn** [comment]
This is documented here https://docs.rs/axum/0.6.0-rc.1/axum/extract/index.html#the-order-of-extractors
