### ISSUE TITLE
Nesting/merging routers that use state could be more ergonomic

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1326]
If you wanna nest routers that use state you currently have to pass the state to each router:

```rust
let state = AppState {};
let api = Router::with_state(state.clone());
let app = Router::with_state(state).nest("/api", api);
```

This is a little inconvenient but its also a source of confusion.

Which state will requests to `/api/*` use? `api`'s state or `app`'s state? Of course in this example it doesn't matter such since we clone the state. But in general its still confusing.

With the current implementation it'll use `api`'s state but it would be great if this wasn't even a question, i.e. the state was only set once.

For 0.6.0 I think we should explore some alternative APIs. @jplatte suggested this which I quite like

```rust
impl<S> Router<S> {
    fn new() -> Self; // this is in the generic impl now

    // need to supply state to turn router into a service
    fn into_service(state: S) -> RouterService<S>;
}

let app = Router::new()
    // nest is updated to take a Router with the same state param
    .nest("/api", Router::new().route("/", get(handler))
    // nest_service is added for arbitrary services, consistent with route and stuff
    .nest_service(
        "/foo",
        // this router uses different state, so it's nested with nest_service
        Router::new()
            .route("/", get(other_handler))
            .into_service(other_state),
    )
    .into_make_service(main_state);
```

All this applies to `Router::merge` as well.

**Comment by Altair-Bueno** [comment]
It's similar to my original proposal, but instead of manually adding `Layer`s, the service is built using a `Router` method. My original `State<Fallback<Router<S>>>` would be equivalent to `RouterService` but without the `Fallback` component

The fallback was meant to transform a `Service<RequestParts, Response = R, Error = RouterError>` into `Service<RequestParts, Response = R, Error = Infalible>` by applying some `Fn`

By allowing the Router to return `RouterError`, we ensure that Fallbacks can be captured on parent routers. We just need to provide a `From<Infalible> for RouterError` impl in order to nest routers

```rs
pub enum RouterError {
	NotFound,
}

let nested = Router::new().route("/foo", get(foo))
// nested.with_state(()) creates a
// `Service<RequestParts<()>, Response = R, Error = RouterError>`

let nested_with_fallback = Fallback::new(|x|"Some message").layer(router)
// nested_with_fallback.with_state(()) creates a 
// `Service<RequestParts<()>, Response = R, Error = Infalible>`

let parent = Router::new()
	// /baz/foo/err will be caught and transformed into a response
	.nest("/baz", nested_with_fallback)
	// /bazz/foo/err will not be caught. A parent `Fallback` layer should handle it
	.nest("/bazz", nested)
```

`Fallback` would pretty much be a type alias to `HandleErrorLayer` 

Maybe we could provide the best of both worlds: Ease of use and flexibility

```rs
impl<S> Router<S> {
	// Creates a service with sensible defaults, ideal for getting started
    fn into_service(state: S) -> State<Fallback<Router<S>>>;
}
// A more powerful API can be unlocked by using `tower::Layer` manually
let service = ServiceBuilder::new()
	.layer(StateLayer::new(my_state))
	.layer(Fallback::from(|_| (StatusCode::IM_A_TEAPOD, "Custom fallback"))
    .service(Router::new().route("/foo", get(foo)));
```

**Comment by davidpdrsn** [comment]
Like I said in the other issue, I don't think we're gonna make this big a change.

**Comment by jplatte** [comment]
> All this applies to `Router::merge` as well.

It can't as easily, actually. I had missed this when you originally wrote it, but thinking about it: That will disallow merging routers with different state, as with the suggested API you always turn the `Router` into a service / `MakeService` type, which then can't be used with `merge`.

I have an idea for a slightly different design without this problem that I'll try to implement now though.
