### ISSUE TITLE
Cars layer must be after route

### ISSUE THREAD

**Issue by alilee** [tokio-rs/axum#1330]
Hiya - I was bitten by the requirement that the ```CorsLayer``` needs to be after the routes (I was getting a 405 on the OPTIONS pre-flight request). I eventually found the answer in a comment in discord.

I think I would have found it sooner if it was a comment in ```example/cors``` in the repo. Would you like a PR for such a comment? Is there a better place for this to be called out in the documentation? 

Thanks!

**Comment by alilee** [comment]
Another thought: it would be great if Debug pretty-printed the routes!

**Comment by davidpdrsn** [comment]
It is documented on [`Router::layer`](https://docs.rs/axum/0.6.0-rc.1/axum/struct.Router.html#method.layer).

I'm not sure that adding comments about that to every example is necessary.

> Another thought: it would be great if Debug pretty-printed the routes!

That's a big topic but it's not something we are planning to support. You can do `dbg!(router)` though.

**Comment by alilee** [comment]
I wrote a [stackoverflow](https://stackoverflow.com/questions/73498537/axum-router-rejecting-cors-options-preflight-with-405-even-with-corslayer/) for this.
