### ISSUE TITLE
Remove cookie does not add domain and path

### ISSUE THREAD

**Issue by alextes** [tokio-rs/axum#1331]
### Version

```
axum v0.5.15
axum-core v0.2.7
axum-extra v0.3.7
```
### Platform

Darwin 21.5.0 (macOS)

### Crates

`axum-extra`

### Description

There may be some deep edge case I don't know about but here's what appears broken.
From [RFC6265: HTTP State Management Mechanism](https://www.rfc-editor.org/rfc/rfc6265#section-3.1).
> Finally, to remove a cookie, the server returns a Set-Cookie header
   with an expiration date in the past.  The server will be successful
   in removing the cookie only if the Path and the Domain attribute in
   the Set-Cookie header match the values used when the cookie was
   created.

Yet, when removing a cookie, `axum-extra` does not set domain or path, failing to remove the cookie.

_here I wrote up an example and figured out what was going wrong, funny how that happens half the time 😄 , I'll reply myself and close, might help someone else._

<details>
<summary>Code</summary>

```rust
use axum::{routing::get, Router};
use axum_extra::extract::{
    cookie::{Cookie, SameSite},
    CookieJar,
};

#[tokio::main]
async fn main() {
    let app = Router::new()
        .route(
            "/add",
            get(|jar: CookieJar| async {
                jar.add(
                    Cookie::build("COOKIE_KEY", "value")
                        .http_only(true)
                        .same_site(SameSite::Lax)
                        .path("/")
                        .finish(),
                )
            }),
        )
        .route(
            "/remove",
            get(|jar: CookieJar| async {
                let mut cookie = Cookie::named("COOKIE_KEY");
                cookie.set_domain("oyfy2.tunnelto.dev");
                jar.remove(cookie)
            }),
        );

    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}
```

</details>

**Comment by alextes** [comment]
Indeed axum does not set domain and path when calling remove, but that is to be expected as browsers won't add the domain and path to the cookie when sending. This means, if you set a cookie with a domain, you need to re-add the domain yourself.

To make things more confusing, you won't notice this if you don't set a domain on the cookie explicitly. A domain would still be added, but when no domain is added explicitly the browser will set the cookie for the exact domain only, but if you explicitly set the exact domain, the browser will instead set the cookie for the exact domain, _and all subdomains_ (some historic, way back, did you say Netscape? stuff), now when you call remove to expire the cookie the domain will mismatch and the cookie will stay.

Side note: why don't the `set_*` methods on `Cookie` return `Self`?

Thanks for a great lib 😊 !

**Comment by davidpdrsn** [comment]
`Cookie` is a re-export of [`cookie::Cookie`](https://docs.rs/cookie/latest/cookie/struct.Cookie.html) so I don't think this is something we can address in axum-extra.
