### ISSUE TITLE
Add support for `either::Either` as an responder and/or extractor

### ISSUE THREAD

**Issue by aleksanderkrauze** [tokio-rs/axum#1344]
## Feature Request

Add implementations for `IntoResponse` and/or `FromRequestParts` for `either::Either`. `Either<L, R>` should implement `IntoResponse` when both `L` and `R` implement it and forward to present variant. It should implement `FromRequestParts` when both `L` and `R` implement it. In this case `L` would be default extractor and `R` would be a fallback.

I would be happy to provide a PR for this if it were to be accepted.

### Motivation

This would allow for more generic code. It would also be similar to what [actix-web does](https://docs.rs/actix-web/4.1.0/actix_web/enum.Either.html).

### Proposal

Just add two simple implementations. `either::Either` could be additionally re-exported.

### Alternatives

First alternative is not to do that. Another is to not use `either::Either` but rather some small local type like actix-web is doing. This would be nicer for users than doing it themselves, but will miss out on all helper functions provided by `either::Either`. Third option is to put this behind a feature gate so that users that don't need this will not have to pay a cost of downloading and compiling either crate.

**Comment by davidpdrsn** [comment]
We already have this in axum-extra https://docs.rs/axum-extra/0.4.0-rc.1/axum_extra/either/index.html

**Comment by aleksanderkrauze** [comment]
Thank you. I didn't know it existed.
