### ISSUE TITLE
impl IntoRequest for () can be confusing

### ISSUE THREAD

**Issue by casey** [tokio-rs/axum#1348]
I was trying to write a router handler and wrote something like this:

```rust
fn foo(query: Query<Foo>) -> impl IntoResponse {
  format!("Hello, {}!", foo.bar);
}
```

It compiled, but the route didn't return anything. It took a bit of head scratching to figure out that `IntoResponse` is implemented for `()`, and that I had an extra `;` that was making the function return `()`.

I can definitely see the argument for implementing `IntoResponse` for `()`, easily writing handlers that do things, but don't return anything but OK, but wanted to open an issue with the confusion I had. If my mistake is common, it might be worth removing the implementation.

**Comment by jplatte** [comment]
I can see where you're coming from, but I think it would be pretty annoying to have to write `http::StatusCode::OK` instead for when you don't want to do anything (e.g. after a POST or PUT was processed).

The documentation already doesn't use `-> impl IntoResponse` a lot these days because things are generally a little clearer with specific return types. Your issue would have been obvious without it.

**Comment by davidpdrsn** [comment]
I agree with jplatte. I still think its right for `()` to implement `IntoResponse`.

**Comment by 44100hertz** [comment]
https://youtu.be/c_5Jy_AVDaM?t=2576 Looks like a significant headache over this issue

Maybe IntoResponse for Option<T> is a logical fix? For Some, you just unwrap the Some, and for None, treat it as null was treated.

Also pardon my asking, but what's the reason for IntoResponse and not Into<Respone>?

**Comment by davidpdrsn** [comment]
I think a better solution is https://github.com/tokio-rs/axum/pull/1801

**Comment by davidpdrsn** [comment]
> Also pardon my asking, but what's the reason for IntoResponse and not Into<Respone>?

axum has impls like `impl Into<Response> for String { ... }` which doesn't work because neither `Response` or `String` are local to axum. So we need our own trait.
