### ISSUE TITLE
User Group

### ISSUE THREAD

**Issue by iodapson** [tokio-rs/axum#1349]
Please create a new room on Matrix Element for current and interested Axum users

**Comment by davidpdrsn** [comment]
We have a [discord channel](https://discord.gg/tokio) which the rest of tokio also uses.

I don't use Matrix and I'm not interested in joining another chat platform. So if you want this to exist you'll have to create it yourself I'm afraid.

**Comment by iodapson** [comment]
Thank you for your response, and sorry for my late response as I did not
know what to say. I have created an Axum room now. Since I am new to Axum
in general, I will focus mainly on the Rust-on-nails framework. I have had
some practice with it, and may be able to entertain questions about it on
Matrix.
For those who might be interested, the room link is at:
https://matrix.to/#/#tokio-rs/axum:matrix.org
