### ISSUE TITLE
Remove `take_*` methods from RequestParts for Version, Method, and Uri

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#135]
`Version`, `Method`, and `Uri` are all cheap to clone so having `take_*` methods for them on [`RequestParts`](https://docs.rs/axum/0.1.2/axum/extract/struct.RequestParts.html) probably isn't necessary. Could just have methods like

```rust
fn method(&self) -> Method {}
fn method_mut(&mut self) -> &mut Method {}
// same for version and uri...
```

That would also remove the `Option`s making extractors that use those types easier to write. It might also remove the need for some the types in https://docs.rs/axum/0.1.2/axum/extract/rejection/index.html, namely things like [`MethodAlreadyExtracted`](https://docs.rs/axum/0.1.2/axum/extract/rejection/struct.MethodAlreadyExtracted.html).

For `HeaderMap`, `Extensions`, and body we still `take_*` methods as those aren't cheap to clone, or cannot be cloned at all.

I think we should do this for 0.2.

**Comment by sunli829** [comment]
I totally agree that a function like `take_method` has no advantage other than causing trouble. 🙂
