### ISSUE TITLE
Returning `(HeaderMap, T)` removes headers from `T`'s `IntoResponse` implementation

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#136]
I would expect the responses from these two routes to be identical:

```rust
route(
    "/one",
    get(|| async { (HeaderMap::new(), "Hello, World!") }),
)
.route(
    "/two",
    get(|| async { "Hello, World!" }),
);
```

But since `impl<T: IntoResponse> IntoResponse for (HeaderMap, T)` [replaces all the headers](https://docs.rs/axum/0.1.2/src/axum/response.rs.html#161) we loose the `content-type` header set by `impl IntoResponse for &'static str`.

`(HeaderMap, T)` should instead merge the headers into the response.

**Comment by sunli829** [comment]
I will fix it.

**Comment by davidpdrsn** [comment]
[`impl<T> IntoResponse for (StatusCode, HeaderMap, T)`](https://docs.rs/axum/0.1.2/src/axum/response.rs.html#166-176) seems to have the same issue as well.
