### ISSUE TITLE
Type error using serde flatten in Query extractor

### ISSUE THREAD

**Issue by tmpfs** [tokio-rs/axum#1366]
## Bug Report

Unexpected error using `#[serde(flatten)]` with `Query` extractor. 

### Version

```
│   ├── axum v0.5.15
│   │   ├── axum-core v0.2.7
│   ├── axum-macros v0.2.3 (proc-macro)
│   ├── axum-server v0.4.2
├── axum-server v0.4.2 (*)
```

### Platform

Darwin sky.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

### Description

I am using the `Query` extractor and want to use `flatten` so I can share common parts of a query string between handlers.

The type I am using in the `Query` extractor looks like this:

```rust
#[derive(Default, Debug, Deserialize)]
#[serde(default)]
pub struct ListPackagesQuery {
    #[serde(flatten)]
    page: Pager,
}

#[derive(Debug, Deserialize)]
#[serde(default)]
pub struct Pager {
    pub offset: i64,
    pub limit: i64,
}
```

However when I pass `?limit=12` I see this unexpected error:

```
Failed to deserialize query string: invalid type: string "12", expected i64
```

If I remove the flatten then deserialization works as expected:

```rust
#[derive(Default, Debug, Deserialize)]
#[serde(default)]
pub struct ListPackagesQuery {
    limit: i64,
}
```

Is this a known limitation? I couldn't find anything searching the issues.

**Comment by jplatte** [comment]
See #1359.
