### ISSUE TITLE
Confusion around sharing `State` using `with_state` and `Arc`

### ISSUE THREAD

**Issue by mlodato517** [tokio-rs/axum#1374]
### Version

0.6.0-rc.2

### Description

I was reading [the docs on the state extractor](https://docs.rs/axum/0.6.0-rc.2/axum/extract/struct.State.html#with-router) and noticed it said:
> Note: the application state *must* derive `Clone` (or be wrapped in e.g. `Arc`)

That seemed consistent with [the docs on sharing state](https://docs.rs/axum/0.6.0-rc.2/axum/index.html#using-the-state-extractor) which did:
```rust
let shared_state = Arc::new(AppState { /* ... */ });

let app = Router::with_state(shared_state)
    .route("/", get(handler));
```

This confused me, however, because it looks like `Router::with_state` uses [`Router::with_state_arc` after wrapping the passed argument in an `Arc`](https://github.com/tokio-rs/axum/blob/7476dd08cb3dbb897245b174d3de8e55bd7003a2/axum/src/routing/mod.rs#L134). So I couldn't tell if:

1. we're supposed to `Arc` the state ourselves and then it's wrapped to become `Arc<Arc<S>>` in the `Router`
2. the docs are mismatched and we should mention that "regular state" need not implement `Clone` and can be passed to `with_state` where it'll be `Arc`'ed for cloning cheaply but if you already have `Arc<S>` then you can use `with_state_arc` to avoid the `Arc<Arc<S>>` (and then, if necessary, maybe some docs for what should be done for handler-local state)

Happy to update the various docs if need be but I wasn't sure if any updating was needed :sweat_smile: And I guess if the docs are correct I'm not sure if it'd be valuable to put some sort of, "No, we _really_ mean it - you want to `Arc` first" to attempt to avoid the confusion I had :balance_scale:

**Comment by mlodato517** [comment]
I guess I should also mention that the reason I was investigating this was because I defined my router as:
```rust
let state = Arc::new(AppState { /* ... */ });
let router = Router::with_state_arc(state);
```
and then defined a handler like:
```rust
pub(crate) async fn foo(state: State<AppState>) -> &'static str { /* ... */ }
```
and got compilation errors. If I use `with_state` instead (to get `Router<Arc<AppState>>`) then things compile okay. I do also use `nest` so this could be related to https://github.com/tokio-rs/axum/issues/1313 but I can't tell.

**Comment by jplatte** [comment]
Yeah, writing good docs for this will a bit hard. You can in fact use a state type that is `!Clone`, but then you won't be able to extract it as `State<AppState>`... You will however be able to extract `State<SubState>` if there's an `impl FromRef<AppState> for SubState>`.

I'm wondering whether we should just go back to not wrapping the state in an `Arc` internally, and requiring it to be `Clone` 🥲

**Comment by mlodato517** [comment]
Ahhh interesting. Follow up question semi-orthogonal to how we should address this - if my state implements `Clone` and I use `with_state` (and it gets wrapped in an `Arc` as it does now) then when I extract it, does each handler get its own copy of the state or are they getting reference counted clones?

**Comment by jplatte** [comment]
Yeah, it doesn't even seem unrealistic to me to let people extract `&State`. But haven't thought a lot about it / tried it out. Not sure when I'll have time for that. I'm sure David will leave a comment with his thoughts in the meantime though ^^

**Comment by arniu** [comment]
See the  discussion https://github.com/tokio-rs/axum/discussions/1343

**Comment by davidpdrsn** [comment]
> Yeah, it doesn't even seem unrealistic to me to let people extract `&State`. But haven't thought a lot about it / tried it out. Not sure when I'll have time for that. I'm sure David will leave a comment with his thoughts in the meantime though ^^

Thats not possible, at least not without changing the trait. Doing

```rust
#[async_trait]
impl<S> FromRequestParts<S> for State<&S>
where
    S: Send + Sync,
{
    type Rejection = Infallible;

    async fn from_request_parts(
        _parts: &mut Parts,
        state: &S,
    ) -> Result<Self, Self::Rejection> {
        Ok(State(state))
    }
}
```

Results in:

```
error: lifetime may not live long enough
   --> axum/src/extract/state.rs:220:40
    |
211 |   impl<S> FromRequestParts<S> for State<&S>
    |   ---- lifetime `'impl0` defined here
...
217 |       async fn from_request_parts(
    |                ------------------ lifetime `'life1` defined here
...
220 |       ) -> Result<Self, Self::Rejection> {
    |  ________________________________________^
221 | |         Ok(State(state))
222 | |     }
    | |_____^ associated function was supposed to return data with lifetime `'impl0` but it is returning data with lifetime `'life1`
    |
    = help: consider adding the following bound: `'life1: 'impl0`
```

I think the trait would have to be

```rust
#[async_trait]
pub trait FromRequestParts<'state, S>: Sized {
    type Rejection: IntoResponse;

    async fn from_request_parts(parts: &mut Parts, state: &'state S) -> Result<Self, Self::Rejection>;
}
```

But even then I'm not sure it would actually be possible. I would like to avoid having lifetimes a core trait like `FromRequestParts` (unless really necessary( because it can be a bit jarring to beginners.

---

> I was reading [the docs on the state extractor](https://docs.rs/axum/0.6.0-rc.2/axum/extract/struct.State.html#with-router) and noticed it said:
> > Note: the application state *must* derive `Clone` (or be wrapped in e.g. `Arc`)

Ah yes that part in the docs is misleading. I filed https://github.com/tokio-rs/axum/pull/1388 which should make things more clear.

**Comment by jplatte** [comment]
> I think the trait would have to be

Yeah I think like that it would work. But agree that it's not a clear win, and I guess it would also be rather confusing if state can be extracted as a reference, but everything else can't.

**Comment by ColemanDunn** [comment]
I noticed the fix that closed this issue out is outdated now and I came across similar confusion in the current docs today, so I opened a [discussion on it](https://github.com/tokio-rs/axum/discussions/3252). Any help/feedback is greatly appreciated. Thanks!
