### ISSUE TITLE
Wrong query string should yield 400, not 422

### ISSUE THREAD

**Issue by jblachly** [tokio-rs/axum#1378]
### Version

axum v0.5.0-rc.2

### Platform

Darwin mbp16.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

### Description

The Query extractor, if unable to serialize results, yields 422 Unprocessable entity.

However, I expect it should return 400, Bad Request.

422 is appropriate when the body is well-formed, but semantically incorrect, and 422 is commonly returned from other frameworks for JSON deserialization errors.

However, I have never seen a bad query string yield 422; typically a bad query string would yield 400 ("The client should not repeat this request without modification.")

Ultimately my suggestion is to keep current behavior for Body extractors such as Json, but return 400 for failed Query extractor.

**references:**

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

**Some prior discussion on 422**
https://github.com/tokio-rs/axum/issues/865

**Comment by jplatte** [comment]
Please add more detail to your issue, only posting a title with no explanation / description is disrespectful of the maintainer's time.

**Comment by jblachly** [comment]
> Please add more detail to your issue, only posting a title with no explanation / description is disrespectful of the maintainer's time.

Sorry, I had hit "cmd+enter" when filling out the template! It's filled out now -- i raced against time to get it filled out before you commented, but you were too quick

**Comment by davidpdrsn** [comment]
422 still seems correct to me. Why is JSON different?

**Comment by jblachly** [comment]
> 422 still seems correct to me. Why is JSON different?

Great question. A reading of the specs reveals this difference in semantics:

422 deals with the the request body in particular and informs us that the "server understands the _content type_ of the request entity, and )the syntax of the request entity is correct,_ " (emphasis mine)

while 400 indicates that "the server cannot or will not process the request due to something that is perceived to be a client error (for example, **malformed request syntax**" (emphasis mine)

**Comment by davidpdrsn** [comment]
Ah yes I see that. I agree, that seems correct to use 400 instead of 422. I've filed https://github.com/tokio-rs/axum/pull/1387
