### ISSUE TITLE
example with sqlx and postgres use removed code "Router::with_state"

### ISSUE THREAD

**Issue by mortifia** [tokio-rs/axum#1412]
### Version

axum = "0.5.16"

### Platform

Windows 11 insider

### Description

`Router::with_state` are removed of axum 

starting with axum I saw in the examples the possibility of integrating an sql client

but all the integration uses code removed from the axum library

I finally found in a pull request that said it was deleted but no solution

I finally figured out how to do it `Router::new().` ... `.layer(Extension(xxxxxxx))`

**Comment by davidpdrsn** [comment]
Like mentioned [in the readme](https://github.com/tokio-rs/axum#breaking-changes) the `main` branch has breaking changes. Look at the `0.5.x` branch or use `0.6.0-rc.x`
