### ISSUE TITLE
Support miniserde

### ISSUE THREAD

**Issue by bit-void** [tokio-rs/axum#1419]
Miniserde is json only and faster to compile, is it possible to support this?

https://github.com/dtolnay/miniserde

**Comment by davidpdrsn** [comment]
You can disable the `json` feature to not depend on serde-json and then write your own extractors that use miniserde.

It's not possible to remove the dependency on serde. Not sure how feasible that would be but I'll look into it.

**Comment by davidpdrsn** [comment]
Yeah I think thats right, or it would require feature gating a large portion of API. Not sure its worth it.

**Comment by davidpdrsn** [comment]
> Basically [this example](https://github.com/tokio-rs/axum/tree/main/examples/customize-extractor-error) but replace the parts with `miniserde`?

Yes you can write your own extractors that uses miniserde but you'd still depend on serde through axum.

**Comment by bit-void** [comment]
Got it, thank you for the responses, feel free to close if if you're not interested. I do think alternative serialization frameworks being available & easy to swap in without a serde dependency is interesting but understood if it's not on the roadmap for now. Thank you!

**Comment by davidpdrsn** [comment]
I'll close this for now. I don't think making serde entirely optional is feasible.
