### ISSUE TITLE
Static files service

### ISSUE THREAD

**Issue by sunli829** [tokio-rs/axum#142]
### Motivation

`axum` does not currently support static files, similar to [`file`](https://docs.rs/warp/0.3.1/warp/filters/fs/fn.file.html) in `warp`, so should we add it?

### Proposal

I think it should be implemented as a [Service](https://docs.rs/tower/0.4.8/tower/trait.Service.html) and add support for [pre-compressed static files](https://github.com/tokio-rs/axum/issues/66).

This service can be used like this:

```rust
let app = route("/files", fs("/static-files").index_file("index.html").show_files_listing(true));
```

If you think this feature is useful, I can implement it. 🙂

**Comment by davidpdrsn** [comment]
tower-http has services for single files and directories already https://docs.rs/tower-http/0.1.1/tower_http/services/fs/index.html. They are usable with axum, there is an example in the examples folder 😊 

I haven't had time to look into yet https://github.com/tokio-rs/axum/issues/66. Ideally that would be possible using off the shelf tools but not sure. 

In general my goal is that services that don't require hyper should live in tower-http. That makes things more reusable outside of axum. Then axum can focus on routing, extractors, and responses.

**Comment by sunli829** [comment]
Ah, `tower-http` looks pretty good!  thank you for telling me.

**Comment by sunli829** [comment]
I will close this issue because it seems that `tower-http` has already provided a lot of features that axum has not yet provided.
