### ISSUE TITLE
Axum_extra reexporting key-expansion feature

### ISSUE THREAD

**Issue by barvirm** [tokio-rs/axum#1424]
## Feature Request
Hello dear, developers.
I'm currently migrating the server from Rocket to Axum and I stumbled on one problem with PrivateCookies.
I have to use the same key, but I'm currently missing function `Key::derive_from(...)` which is locked behind `key-expansion` feature in cookie crate.

### Proposal
Reexport this feature in axum_extra same as private and signed cookies.

**Comment by davidpdrsn** [comment]
Sure! You wanna make a PR?

**Comment by barvirm** [comment]
PR: https://github.com/tokio-rs/axum/pull/1425

**Comment by davidpdrsn** [comment]
Fixed in https://github.com/tokio-rs/axum/pull/1425
