### ISSUE TITLE
Expose WebSocket Message as enum, not struct

### ISSUE THREAD

**Issue by thedodd** [tokio-rs/axum#143]
## Feature Request
Expose the WebSocket `Message` type as an enum (which the underlying tungstenite crate already does).

### Motivation
This will make interop with tungstenite from a client perspective much easier.

A direct use case which we have in Trunk: https://github.com/thedodd/trunk/pull/220

### Proposal
As mentioned already, the underlying tungstenite crate already exposes this type. If Axum could just re-use that same type directly, that would be outstanding!

### Alternatives
Keep things the way they are.

**Comment by davidpdrsn** [comment]
That'll be done by https://github.com/tokio-rs/axum/pull/116
