### ISSUE TITLE
Allow flat parameter structure in derive(FromRequest)

### ISSUE THREAD

**Issue by RReverser** [tokio-rs/axum#1446]
### Motivation

Today, even with `derive(Deserialize)`, extractor helpers and `derive(FromRequest{Parts})`, you need to put path, query params and body all in separate structures like:

```rust
#[derive(Debug, Deserialize, FromRequestParts)]
#[from_request(via(Path))]
struct PostActionPathParams {
    group: String,
    action: String,
}

#[derive(Debug, Deserialize, FromRequestParts)]
#[from_request(via(Query))]
struct PostActionQueryParams {
    client_id: Option<u32>,
    client_transaction_id: Option<u32>,
}

#[derive(Debug, Deserialize, FromRequest)]
#[from_request(via(Json))]
struct PostActionBody {
    parameters: String,
    payload: String,
}

#[axum::debug_handler]
async fn post_action(
    PostActionPathParams { group, action }: PostActionPathParams,
    PostActionQueryParams {
        client_id,
        client_transaction_id,
    }: PostActionQueryParams,
    PostActionBody {
        parameters,
        payload,
    }: PostActionBody,
) -> &'static str {
    "Hello, World!"
}
```

However, a lot of the time I don't really care where the parameters are coming from (I just need to match the spec) and just want to have access to all of them in the body of the function - hence the destructuring above.

### Proposal

Allow flattening `derive(FromRequest)` that collects fields from various parts of the request. Here's what it could look like:

```rust
#[derive(Debug, Deserialize, FromRequest)]
#[from_request(body(Json))]
struct PostActionParams {
    #[from_request(in(Path))]
    group: String,
    #[from_request(in(Path))]
    action: String,
    #[from_request(in(Query))]
    client_id: Option<u32>,
    #[from_request(in(Query))]
    client_transaction_id: Option<u32>,
    #[from_request(in(body))]
    parameters: String,
    #[from_request(in(body))]
    payload: String,
}

#[axum::debug_handler]
async fn post_action(
    PostActionParams {
        group,
        action,
        client_id,
        client_transaction_id,
        parameters,
        payload,
    }: PostActionParams,
) -> &'static str {
    "Hello, World!"
}
```

### Alternatives

Keep everything separate.

**Comment by davidpdrsn** [comment]
That's an interesting idea! My initial impression is that this isn't worth the additional complexity. derive(FromRequest) is already complicated enough as is.

**Comment by RReverser** [comment]
FWIW this was inspired by trying to implement a server by an OpenAPI spec, where OpenAPI also doesn't specially distinguish between where parameters are from, and just has a flat list of `parameters` with `in: path`, `in: query` and so on as attributes. My only addition here is the body in the same struct.

**Comment by RReverser** [comment]
> My initial impression is that this isn't worth the additional complexity. derive(FromRequest) is already complicated enough as is.

Another alternative to syntax that would keep `FromRequest` relatively simple could be emitting all the properties with prefixes to serde, and let it handle the rest via renames instead, like:

```rust
#[derive(Debug, Deserialize, FromRequest)]
#[from_request(flatten, body(Json))]
struct PostActionParams {
    #[serde(rename = "path.group")]
    group: String,
    #[serde(rename = "path.action")]
    action: String,
    #[serde(rename = "query.client_id")]
    client_id: Option<u32>,
    #[serde(rename = "query.client_transaction_id")]
    client_transaction_id: Option<u32>,
    #[serde(rename = "body.parameters")]
    parameters: String,
    #[serde(rename = "body.payload")]
    payload: String,
}
```

**Comment by jplatte** [comment]
I think this is definitely worthwhile for some things (in [Ruma](https://github.com/ruma/ruma) we have a macro like this that also has metadata about endpoints and allows the same request / response types to be used on servers as well as clients), but I agree with David that the `FromRequest(Parts)` derive macros are already complicated enough as-is.

Both the ideas in this thread are complex enough to warrant being their own crate / project IMHO. I've written [a blog series](https://blog.turbo.fish/proc-macro-basics/) on proc-macros that you could go through if you want to work on this and haven't written proc-macro code before 😉

**Comment by RReverser** [comment]
> Both the ideas in this thread are complex enough to warrant being their own crate / project IMHO.

Hm, do you mean implementation-wise or ...? At least the second one, I think, actually needs very little of proc-macro code - most of work would be in a custom internal `Deserializer` implementation, and then `impl FromRequest` simply forwards to it.

**Comment by davidpdrsn** [comment]
I don't understand how that would work. We don't have a request deserializer (it would also need to async I guess).

**Comment by RReverser** [comment]
> I don't understand how that would work. We don't have a request deserializer (it would also need to async I guess).

Would be similar to PathDeserializer that already exists, but feeding headers, path params, query params etc. To Serde one by one via MapAccess interface.

**Comment by davidpdrsn** [comment]
How do you handle the body then?

**Comment by RReverser** [comment]
> And is that really simpler than just writing separate extractors?

If you mean writing out attributes, then perhaps not, but the goal here is to be able to split out logic API - where every function is just accepting bunch of params and doesn't know or care about HTTP details.

This approach seems like the simplest in terms of avoiding duplication or manual merging from different extractors into one final struct, but perhaps I'm missing something even simpler?

**Comment by davidpdrsn** [comment]
Think I'll close this for now. I think `#[derive(FromRequest)]` is complicated enough as it is and I'm not convinced this is worth the additional complexity.

**Comment by RReverser** [comment]
Fair enough. I think I'll play with the idea a bit more outside this crate then.
