### ISSUE TITLE
`handle_error` increases compiles a lot

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#145]
It seems adding `handle_error` to a router will increase compile times quite significantly.

Here is an example:

```rust
use axum::{service::ServiceExt, prelude::*, http::StatusCode};
use std::convert::Infallible;
use std::net::SocketAddr;
use std::time::Duration;
use tower::{BoxError, ServiceBuilder};
use tower_http::trace::TraceLayer;

#[tokio::main]
async fn main() {
    let app = route("/", get(handler))
        .nest(
            "/api",
            route("/pay/get_pay_params", post(handler))
                .nest(
                    "/user",
                    route("/create", post(handler))
                        .route("/login", post(handler))
                        .route("/info", get(handler))
                        .route("/update_password", get(handler)),
                )
                .nest(
                    "/product",
                    route("/list", get(handler)).route("/detail", get(handler)),
                ),
        )
        .layer(
            ServiceBuilder::new()
                .timeout(Duration::from_secs(10))
                .layer(TraceLayer::new_for_http())
                .into_inner(),
        )
        .handle_error(|error: BoxError| {
            if error.is::<tower::timeout::error::Elapsed>() {
                Ok::<_, Infallible>((
                    StatusCode::REQUEST_TIMEOUT,
                    "request took too long".to_string(),
                ))
            } else {
                Ok::<_, Infallible>((
                    StatusCode::INTERNAL_SERVER_ERROR,
                    format!("Unhandled internal error: {}", error),
                ))
            }
        });

    let addr: SocketAddr = "127.0.0.1".parse::<SocketAddr>().unwrap();
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn handler() -> &'static str {
    "index"
}
```

With the `handle_error` it compiles in 5s and in 0.3s without, on my machine in debug mode. Whether this is a rustc issue or something we can improve directly via axum I don't know. Something to investigate for sure.

**Comment by jplatte** [comment]
On my machine the difference is even worse. Around 10s for `cargo check` with `handle_error`, around 0.5s without it (this is with 1.54). Now trying with nightly and then some debug options...

**Comment by jplatte** [comment]
Ran with `RUSTFLAGS='-Ztime-passes'`, these are the clearly deviating entries:

```
# before
time:   0.265; rss:  139MB ->  219MB (  +79MB)	item_bodies_checking
time:   0.268; rss:  121MB ->  219MB (  +97MB)	type_check_crate
time:   0.334; rss:   45MB ->  102MB (  +57MB)	total

# after
time:   9.815; rss:  129MB ->  747MB ( +618MB)	type_check_crate
time:   9.814; rss:  133MB ->  747MB ( +615MB)	item_bodies_checking
time:   9.919; rss:   45MB ->  105MB (  +60MB)	total
```

**Comment by lnicola** [comment]
Yeah, in `self-profile` the time goes into `analysis` and `typeck`.

**Comment by ZhangHanDong** [comment]
On my machine (macos m1), using handle_error took 10s (1/3) longer than without handle_error.

**Comment by ZhangHanDong** [comment]
Use this to print a compile time report ： `cargo +nightly build -Z timings ` .

![Screen Shot 2021-08-10 at 22 40 15](https://user-images.githubusercontent.com/27893/128887173-ebc9d463-2617-4d9a-b49c-05dfe4168d6c.png)

![Screen Shot 2021-08-10 at 22 31 38](https://user-images.githubusercontent.com/27893/128887197-d8de2a12-9b80-4d2b-8dac-0bbeba6e8327.png)

![Screen Shot 2021-08-10 at 22 31 46](https://user-images.githubusercontent.com/27893/128887216-cd3d1170-84f9-4032-b22b-0751adab6773.png)

![Screen Shot 2021-08-10 at 22 31 56](https://user-images.githubusercontent.com/27893/128887231-6315b62e-68bf-42eb-ac82-7ea70a90c328.png)

**Comment by lnicola** [comment]
That's not going to help. [`self-profile`](https://github.com/rust-lang/measureme/) should, but it doesn't seem to.

Usage:

 - `RUSTFLAGS="-Zself-profile -Zself-profile-events=default,args" cargo +nightly check`
 - `crox feiyuan_web-33490.mm_profdata`
 - open Chrome and load the resulting `profile.json` in the performance inspector

**Comment by davidpdrsn** [comment]
I just file https://github.com/rust-lang/rust/issues/87924

**Comment by davidpdrsn** [comment]
I just merged https://github.com/tokio-rs/axum/pull/184 which should help compile times a bit. Let me know if someone tries it!

**Comment by vaniusrb** [comment]
I got a very small improvement. Before your change, my project cargo check took ~60 seconds. With your commit takes 44.83s.
Add a `.boxed()` after last `.route()` still beeing the better workaround, where takes 9.09s.

If I add more routes rustc stays running until reaches OOM.

(I cloned axum git repo to my disk and changed in the cargo.toml to read it, to discard any cargo cache)

**Comment by davidpdrsn** [comment]
@vaniusrb Can you share a reproduction?

**Comment by vaniusrb** [comment]
@davidpdrsn Here: https://github.com/vaniusrb/axum-slow-compile
Note: this is basically the "todo" example with more routes.

**Comment by davidpdrsn** [comment]
Thanks! If you use https://github.com/tokio-rs/axum/pull/198 and remove the `check_infallible` call it compiles in under 1 second for me. So https://github.com/tokio-rs/axum/pull/198 seems to be working!

Just have to look into `check_infallible`. Could probably just remove it 🤷 Not sure its very useful as you can check the return type of `handle_error`.

**Comment by davidpdrsn** [comment]
I was able to find a fix for `check_infallible` b70e8cc485c35. The example @vaniusrb posted now compiles in less than 1 sec on my machine. Thanks for posting it!

Even with 100 routes (without boxing) `cargo check` takes 1.5 seconds 🎊

**Comment by vaniusrb** [comment]
@davidpdrsn Confirmed! Thank you very much. You are awesome.

**Comment by davidpdrsn** [comment]
If someone still has compile time issues with using `main` please post [here](https://github.com/tokio-rs/axum/issues/200).
