### ISSUE TITLE
Allow literal `:` in routes

### ISSUE THREAD

**Issue by DavidSouther** [tokio-rs/axum#1452]
## Feature Request

Allow a way to register routes (and route fragments) that include a literal `:`

### Motivation

[REST](https://cloud.google.com/apis/design/custom_methods) (GCP) [Api](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#performing-an-action) (Azure) [Guidelines](https://spec.openapis.org/oas/v3.1.0#paths-object)† (OpenAPI) suggest mechanisms to define custom verbs using `POST /collection/{id}:verb`. In axum, this is ambiguous as `/collection/12:archive` for the route `/collection/:id:verb` matches `get(Path(id): Path<String>)` as `"12:archive"`. That is, the `:verb` gets ignored, and the entire fragment gets assigned to the first parameter match.

† Ok it's not technically in there, but it's not forbidden, as far as I can tell

### Proposal

Switch (or provide the option) to use `{curly-delimited}` path templates. This conveniently aligns with the [OpenAPI path templating spec](https://spec.openapis.org/oas/v3.1.0#path-templating).

### Alternatives

Recognize Additional :foo after the first :path in a route fragment as literal. That is, for a route section between two "/", only the first :portion is recognized.

**Comment by DavidSouther** [comment]
Looks like this might be a better issue for matchit

**Comment by davidpdrsn** [comment]
Yep. There isn't anything axum can do about this so I'll close since we already have a matchit issue.
