### ISSUE TITLE
dump / convert Request<Body> to raw http string

### ISSUE THREAD

**Issue by erlangparasu** [tokio-rs/axum#1457]
### Motivation

want to debug the raw http request string (headers, path, body, method)

### Proposal

 

ability to create raw string like:
```
HTTP/1.1 200 OK
content-type: text/plain; charset=utf-8
content-length: 475
date: Sun, 09 Oct 2022 11:10:07 GMT
```

**Comment by davidpdrsn** [comment]
I think is something for the [http](https://crates.io/crates/http) crate to support. Wanna file an issue there instead?
