### ISSUE TITLE
Investigate removing `Sync` bounds on `S`

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1463]
See https://github.com/tokio-rs/axum/pull/1460#discussion_r990827652

**Comment by davidpdrsn** [comment]
I did a quick test but don't believe its possible since `from_request` takes `&S` and returns a future containing that reference (because of `#[async_trait]`). So then for that future to be `Send` `S` must be `Sync`.

**Comment by davidpdrsn** [comment]
cc @jplatte

**Comment by jplatte** [comment]
Interesting, before https://github.com/tokio-rs/axum/commit/e7f1c88cd4691f829f26b8376cd0ba2812acd843 we didn't have it. But back then we also didn't have the `&S` parameter. I guess it should be fine in the general case, and once async fn in traits are a thing this is all going to be revamped anyways.

**Comment by davidpdrsn** [comment]
I think thats because we used `&mut RequestParts<S, B>` and `&mut S` is `Send` even if `S: !Sync` (https://doc.rust-lang.org/stable/std/marker/trait.Send.html#impl-Send-for-%26mut%20T)
