### ISSUE TITLE
Implement IntoResponse for all ToString

### ISSUE THREAD

**Issue by HurricanKai** [tokio-rs/axum#1468]
### Motivation
I think It's reasonable to allow handlers to return any value implementing `ToString`, this implicitly allows all values implementing `std::fmt::Display`, given a default implementation exists.

### Proposal
This just improves ergonomics slightly in some cases.
Only drawback I can see is that it's slightly confusing to think about ownership with an `Into*` build on top of a `To*`, but this doesn't really affect the user.
I'd be happy to PR this.

### Alternatives
It's easy enough for users to use .to_string() before returning

**Comment by jplatte** [comment]
Blanket implementation can lead to much worse error messages, which is the reason we removed the blanket implementation of `IntoResponse` for `T: IntoResponseParts` which we had briefly. Also, more importantly, this would make it impossible to have your own `IntoResponse` impl for an error type¹ that also implements `Display`.

¹ or any type at all, but this seems like an important real-world case
