### ISSUE TITLE
axum-core 0.2.8 doesn't have a changelog mentioning new DefaultBodyLimit

### ISSUE THREAD

**Issue by dhedey** [tokio-rs/axum#1470]
## Overview

There is a new version of axum-core (0.2.8) on [crates.io](https://crates.io/crates/axum-core), which introduces quite a large change (a default request body size - see [DefaultBodyLimit](https://docs.rs/axum-core/0.2.8/axum_core/extract/struct.DefaultBodyLimit.html)) - but this isn't captured [in the axum-core changelog](https://github.com/tokio-rs/axum/blob/main/axum-core/CHANGELOG.md).

After an overlooked lock-file update on our end, we've been starting to get new errors on our servers due to this new limit, and searching for Axum `LengthLimitError` didn't really seem to help.

So I just wanted to raise this issue to (A) flag the missing change-log entry, and also to (B) help future googlers.

The full error, when using the `Json` extractor on a payload larger than 2MB was:
```
BytesRejection(FailedToBufferBody(LengthLimitError(LengthLimitError(Error { inner: LengthLimitError }))))
```

**Comment by davidpdrsn** [comment]
Look at the `0.5.x` branch's changelog, its there https://github.com/tokio-rs/axum/blob/0.5.x/axum-core/CHANGELOG.md. I've copied the changes to the main branch as well.

**Comment by dhedey** [comment]
Ahh, fantastic! Thanks @davidpdrsn 👌
