### ISSUE TITLE
Axum hangs in a Docker container

### ISSUE THREAD

**Issue by MorganR** [tokio-rs/axum#1485]
### Version

axum: 0.5.16
axum-core: 0.2.8
tokio: 1.21.2

### Platform

Using Docker in multiple environments:

* Via WSL2
* Via Google Cloud Build and Cloud Run

Docker base images I've tried:

* alpine:latest
* debian:bullseye-slim
* rust:bullseye

### Description

I've been trying to get a simple hello world Axum server running in Docker ([repo](https://github.com/MorganR/hello-world-server-rust-axum)). It runs fine locally with `cargo run`, but when I try to build it and run it from Docker, then it seems to hang somewhere in this group of lines:

```rust
axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
```

I know it at least gets there because it prints `listening on 127.0.0.1:8080`, but I can never connect to the server. I was worried it could just be because I'm using WSL 2, and that was somehow causing an issue, so I built the image with Google Cloud Build and tried running it with Cloud Run, but Cloud Run also reports that the image failed to listen on the expected port (the expected port matches one in the logs).

I'm not too sure what could be going on here. The code sample is about as simple as it gets. Let me know if you're able to reproduce it.

**Comment by davidpdrsn** [comment]
I don't personally use Docker much so I can't offer help. I also doubt its axum specific. I recommend asking on [Discord](https://discord.gg/tokio).

**Comment by yanns** [comment]
You need to listen on `0.0.0.0` instead of `127.0.0.1` (https://github.com/MorganR/hello-world-server-rust-axum/blob/main/src/main.rs#L20)
See docker documentation about network.

**Comment by MorganR** [comment]
🤦 thank you I knew I must be missing something obvious
