### ISSUE TITLE
Expose UrlParams

### ISSUE THREAD

**Issue by cemoktra** [tokio-rs/axum#1512]
### Motivation

For better error handling, we wrote a path extractor wrapper around yours in order to provide detailed errors.

### Proposal

In order to test this without creating a full router, we would need to build a request with `UrlParams` extension which currently is not possible. Therefore it might a good to expose this or at least add a way to create a dummy request with url params

**Comment by davidpdrsn** [comment]
I don't think `UrlParams` should be public. I'd recommend writing a test that creates a router and sends it a request with a non-uft8 path param.

**Comment by cemoktra** [comment]
Well we either need this exposed or a way to influence the response bodies

**Comment by davidpdrsn** [comment]
Can you be more specific? I don't understand what you mean.

You can customize rejection responses like this https://github.com/tokio-rs/axum/tree/main/examples/customize-extractor-error

**Comment by cemoktra** [comment]
Ah i did not know this

**Comment by cemoktra** [comment]
But the axum-extras is not released yet with ẀithRejection` no?  Cause in docs.rs i cannot find it

**Comment by davidpdrsn** [comment]
It's in 0.4.0-rc.1 https://docs.rs/axum-extra/0.4.0-rc.1/axum_extra/extract/struct.WithRejection.html
