### ISSUE TITLE
Can't turn a `Router` that wants to inherit state into a service

### ISSUE THREAD

**Issue by gd87429** [tokio-rs/axum#1516]
Updating from `0.6.0-rc.2` to `0.6.0-rc.3`:

I have a bunch of mods & sub-mods that look like this:

```rust
pub fn get_routes(shared_state: Arc<ServerState>) -> Router<Arc<ServerState>> {
	Router::with_state(shared_state.clone())
		.nest("/sdfg", get_sdfg_routes(shared_state))
}
```

However when trying to remove passing in clones of state and using `inherit_state()`, everything compiles fine but during startup I get: `Can't turn a 'Router' that wants to inherit state into a service`

Which makes me wonder:

1. https://docs.rs/axum/0.6.0-rc.3/axum/handler/trait.Handler.html#method.into_service says that handlers that need state should use `with_state`. Doesn't that defeat the purpose of not passing in state? How do I turn it into something like this and pass in state once at the very top `merge`:

	```rust
	pub fn get_routes() -> Router {
		Router::inherit_state()
			.nest("/sdfg", get_sdfg_routes())
	}
	```

2. Can't it throw an error during compilation instead?

**Comment by davidpdrsn** [comment]
You should only set the state once, at the top level router:

```rust
use axum::Router;

#[tokio::main]
async fn main() {
    let app = Router::with_state(AppState {}).nest("/api", api_router());
}

#[derive(Clone)]
struct AppState {}

fn api_router() -> Router<AppState> {
    // don't pass state here
    Router::inherit_state()
}
```

> Can't it throw an error during compilation instead?

It can but that complicates the types quite a lot. We considered it and currently don't think its worth the additional complexity.

**Comment by gd87429** [comment]
Thank you for the quick response. I seem to be doing the same, but continue having the exact same error. Is something like this supposed to work?

```rust
use axum::Router;
use std::sync::Arc;

#[derive(Clone)]
struct AppState {}
let state = Arc::new(AppState {});

#[tokio::main]
async fn main() {
    let app = Router::with_state(state).merge(routes());
}

fn routes() -> Router<Arc<AppState>> {
    Router::inherit_state().route("/v1", v1_routes());
}

fn v1_routes() -> Router<Arc<AppState>> {
    Router::inherit_state().route("/get", get());
}
```

**Comment by jplatte** [comment]
The code you posted doesn't even compile because of the extra semicolons and I'm pretty sure you can't pass a `Router` to `.route` as the second argument. Only `.nest` and `.merge` do state inheritance, `.route` isn't meant to be used with an inner `Router` at all (it doesn't really make sense).

**Comment by gd87429** [comment]
@jplatte Thanks for taking a look. I accidentally used `route` instead of `nest` while typing that example. Adjusted it above.

This is mostly my original setup, except instead of `inherit_state()` I used `with_state(...)` before. Is there any way to make it work now with the adjusted code above?

**Comment by davidpdrsn** [comment]
Hm yeah that does appear to be a bug.

**Comment by davidpdrsn** [comment]
A workaround is to provide the state using `with_state`:

```rust
use std::sync::Arc;

#[derive(Clone)]
struct AppState;

let inner_router = Router::<Arc<AppState>>::with_state(Arc::new(AppState));
Router::<Arc<AppState>>::inherit_state().nest("/v1", inner_router);
```

**Comment by jplatte** [comment]
Oh, we currently never store inner routers without first turning them into services, but we'll have to do that for this. So not an easy fix unfortunately. We should also make sure that `Router::with_state().nest(Router::inherit_state().nest(Router::inherit_state()))` works..

**Comment by gd87429** [comment]
Thanks all :pray:
