### ISSUE TITLE
axum 0.6: `FromRef` for tuples

### ISSUE THREAD

**Issue by MidasLamb** [tokio-rs/axum#1519]
## Feature Request
Impl `FromRef` for Tuples where each of the elements implements `FromRef`

I'm certainly willing to implement this but I first wanted to start some conversation around it

### Motivation
The `FromRef` derive macro makes it easier to unit tests extractors etc, because you can give it the part of the state that it needs without all the other state.
However, if the thing you want to test uses multiple elements from the original state, you have to either define a "substate", but this becomes annoying when your extractors requirements start to overlap, so you have multiple "substates" that have the same element.

Currently I've solved this conundrum by having this:
```rust
impl<T, U> FromRef<AppState> for (T, U) 
    where T: FromRef<AppState>,
          U: FromRef<AppState>,
{
    fn from_ref(input: &AppState) -> Self {
        (FromRef::from_ref(input), FromRef::from_ref(input))
    }
}
```
which allows me to require arbitrary substates per item that needs it.

I think it would be nice that this would be available by default & provided by `axum`.

### Proposal
Add a blanket `FromRef` implementation for tuples if each of the elements implement `FromRef` from the same `State`, for tuples up to 32(?) elements.

### Alternatives

Leave it up to the user to do this is if required.

**Comment by jplatte** [comment]
Existing tuple impls go up to 16 items so I think we should do the same here. Otherwise I think this is a very good idea, so I think you should post a PR :)

**Comment by jplatte** [comment]
Note that you can also use multiple `State` extractors though.

**Comment by davidpdrsn** [comment]
Good idea! A PR would be much appreciated.

**Comment by MidasLamb** [comment]
> Note that you can also use multiple `State` extractors though.

@jplatte , you mean that it should be generic over `State`? I had to restrict it because to implement a foreign trait, one of the parameter types must be local. So for the implementation here that would certainly be the case.
Or do you mean something else?

**Comment by jplatte** [comment]
I just mean that instead of `(a, b): State<(SubstateA, SubstateB)>`, you can use `a: State<SubstateA>, b: State<SubstateB>` in your own code. But that doesn't mean we shouldn't have this impl.

**Comment by davidpdrsn** [comment]
Yes thats not possible and I also don't see why you'd need it for what jplatte suggested.

**Comment by MidasLamb** [comment]
I was playing around in my codebase with it and based on jplatte's comment I wrote something along the lines of:
```rust
#[axum::async_trait]
impl<S> axum::extract::FromRequestParts<S> for ExtractingThing
where
    SubStateA: FromRef<S>,
    SubStateB: FromRef<S>,
    : FromRef<S>,
    S: 'static + Send + Sync + Clone,
{
}
```
where I first had:
```rust
#[axum::async_trait]
impl<S> axum::extract::FromRequestParts<S> for ExtractingThing
where
    (SubStateA, SubStateB): FromRef<S>,
    : FromRef<S>,
    S: 'static + Send + Sync + Clone,
{
}
```
However with the first one, you cannot use a tuple `(SubStateA, SubStateB)` as a substitute for the proper `AppState` which has `#[derive(FromRef)]`. Even though I think it looked/felt a bit better in the actual body of the function.

**Comment by davidpdrsn** [comment]
Maybe you can describe what your use case actually is? [Feels a bit xy problem](https://xyproblem.info).

**Comment by MidasLamb** [comment]
The main issue I'm trying resolve is that I have a some implementations of e.g. extractors that only require a subset of the full app's State. So when I write tests for that extractor I don't want to be concerned with all the "non-dependencies" in the State, so I want an ergonomic way of allowing both the full app's State and only the subset the extractor etc. is concerned about.
Having to specify a new struct for all the specific combinations that might arise seems a bit off to me, hence I turned to the tuple as a sort of "anonymous" State struct, if that makes sens?

**Comment by davidpdrsn** [comment]
I don't think tuples can solve that. I think you need to define a new struct and do

```rust
#[axum::async_trait]
impl<S> axum::extract::FromRequestParts<S> for ExtractingThing
where
    SubStateA: FromRef<S>,
    SubStateB: FromRef<S>,
    S: 'static + Send + Sync + Clone,
{
}
```

**Comment by MidasLamb** [comment]
After playing around a bit more, It seems that it's indeed the clearest, because otherwise you have to ensure that when passing it in the tests with the tuples, you have to match the order constantly, which also doesn't feel like the nicest DX. 

I've tried implementing the initial suggestion, but the implementation collides with the one present for the bound `T: Clone`, because of the auto-implementation of `Clone` if all T in a tuple `impl Clone`. So I don't know if my suggestion can be done.

**Comment by jplatte** [comment]
Right, extracting `State<(CloneableA, ClonableB)>` would be ambiguous if that impl existed. I think we should just close this then, but I'll wait for David's opinion.

**Comment by davidpdrsn** [comment]
Right that makes sense. Oh well. At least we have the derive macro to handle most of the boilerplate.
