### ISSUE TITLE
[documentation] broadcast TLS support

### ISSUE THREAD

**Issue by efx** [tokio-rs/axum#1542]
## Feature Request

I would love a line or two broadcasting Axum's TLS support.

### Motivation

When I evaluate frameworks I look for parity with incumbent implementations.
When reading through the crates I did read a mention of support.
Some might think that means axum does not support TLS.

### Proposal

A line on the support.
> Axum supports TLS (thanks to rustls friend!)

### Alternatives

Say nothing for now.
Documentation is a maturing concern. 
Or simply point out the example introduced in 
https://github.com/tokio-rs/axum/pull/57

**Comment by davidpdrsn** [comment]
axum doesn't support TLS but requires other library to handle that. I'm fine with linking to the example from the docs however. Do you wanna make a PR?

**Comment by davidpdrsn** [comment]
I actually think I'll just leave it as is. Not quite sure where to put it and in my experience its more common to use a reverse proxy for TLS anyways.
