### ISSUE TITLE
Explore `Router::merge_service` for merging routers with different states

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1547]
I'm wondering if something like this would be possible

```rust
impl<S, B> Router<S, B> {
    fn merge_service(self, service: RouterService<B>) -> Self {
        ...
    }
}
```

seems like that'd be useful for merging routers that have different states. Not sure its actually possible though.

**Comment by jplatte** [comment]
I think `RouterService::<B>::merge(self, RouterService<B>)` could work. Let me try implementing that..

**Comment by jplatte** [comment]
Okay so it's possible but if we want to keep the current simplifications that happen when going from `Router` to `RouterService`, it would not allow merging two `RouterService`s that both have the same route with `MethodRouter`s with different supported methods inside. This works for `Router`s, so I'm not sure what the best way forward is.

**Comment by davidpdrsn** [comment]
> it would not allow merging two RouterServices that both have the same route with MethodRouters with different supported methods inside. This works for Routers, so I'm not sure what the best way forward is.

Ah yeah that true 🤔
