### ISSUE TITLE
extract::Json is giving incorrect values

### ISSUE THREAD

**Issue by colin99d** [tokio-rs/axum#1565]
### Version

├── axum v0.6.0-rc.5
│   ├── axum-core v0.3.0-rc.3

### Platform

Darwin MacBook-Pro-2.lan 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

### Description

The Json Extract seems to be returning incorrect values.
<img width="1212" alt="Screenshot 2022-11-22 at 8 59 41 PM" src="https://user-images.githubusercontent.com/72827203/203409726-338d8211-1445-41dd-aa26-2f6c8a151a07.png">
The top of my function looks like this:

```
pub async fn register(
    State(pool): State<MySqlPool>,
    Json(user): Json<UserCreate>,
) -> JsonResponse<Message> {
    println!("User: {:?}", user);
    println!("Email: {}", user.email);
    let customer = match user.insert(&pool).await {
        Err(err) => return sql_error_response(err),
        Ok(cust) => cust,
    };
```

The UserCreate schema looks like this:

```
#[derive(Deserialize, Debug)]
pub struct UserCreate {
    pub email: String,
    pub password: String,
    pub source: Option<String>,
    pub campaign_source: Option<String>,
    pub referred_by: Option<String>,
    pub promo_code: Option<String>,
}
```

There is only one method implemented for UserCreate, insert, and this just inserts the item into my database. When I hit the endpoint the with my request shown above I would expect the email colin@test.com to print. However, gives the email for the only existing user I have "testemail@test.com". I using HTTPIE instead of Hopscotch to hit the endpoint with: 
`http POST http://127.0.0.1:8000/register password=password email=colin@test.com` 

But I got the same output:
<img width="860" alt="Screenshot 2022-11-22 at 9 05 37 PM" src="https://user-images.githubusercontent.com/72827203/203410736-14ca5877-f761-4992-9882-3cfc7a34ebf2.png">

As you can see, the email and password both do not match the request. And I am just printing the extact, so im not sure how the database is interfering with it.

**Comment by davidpdrsn** [comment]
That looks weird but like someone said in Discord, can't say much without a minimal reproduction script.

**Comment by colin99d** [comment]
```
use axum::{extract::Json, routing::post, Router};
use serde::Deserialize;
use std::net::SocketAddr;

#[tokio::main]
async fn main() {
    let app = Router::new().route("/register", post(register));

    let addr = SocketAddr::from(([0, 0, 0, 0], 8000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

pub async fn register(Json(user): Json<UserCreate>) -> &'static str {
    println!("Email: {}", user.email);
    "Testing"
}

#[derive(Deserialize)]
pub struct UserCreate {
    pub email: String,
    pub password: String,
    pub source: Option<String>,
    pub campaign_source: Option<String>,
    pub referred_by: Option<String>,
    pub promo_code: Option<String>,
}
```

**Comment by colin99d** [comment]
<img width="1239" alt="Screenshot 2022-11-22 at 9 39 12 PM" src="https://user-images.githubusercontent.com/72827203/203416620-b2d1e974-8d5e-4805-bc4e-92d0bcbd04f1.png">
Hitting it with this, getting below:
<img width="481" alt="Screenshot 2022-11-22 at 9 39 27 PM" src="https://user-images.githubusercontent.com/72827203/203416673-1ea1eafc-1051-4c18-91dc-da91e21e73a9.png">

**Comment by colin99d** [comment]
Made MVP a little smaller: 

use axum::{extract::Json, routing::post, Router};
use serde::Deserialize;
use std::net::SocketAddr;

#[tokio::main]
async fn main() {
    let app = Router::new().route("/register", post(register));

    let addr = SocketAddr::from(([0, 0, 0, 0], 8000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

pub async fn register(user: Json<UserCreate>) {
    println!("Email: {}", user.email);
}

#[derive(Deserialize)]
pub struct UserCreate {
    pub email: String,
    pub password: String,
}

**Comment by davidpdrsn** [comment]
Works fine for me:

```rust
$ curl -i localhost:8000/register -d '{"email":"bob@example.com","password":"foobar"}' -H "Content-Type: application/json"
```

And the serve prints

```
Email: bob@example.com
```

**Comment by colin99d** [comment]
Weird. My MVP stayed broken until I sent it this. And now im hitting my normal server with this and its back to being broken.

**Comment by davidpdrsn** [comment]
I'm gonna close this for now. Theres gotta be something wrong with your setup. I'm quite confident axum is doing the right thing. Please do post when you figure it out though, I'm curious to know what it was.

**Comment by colin99d** [comment]
Sounds good! I figured there is no way its you guys, but its baffling me as to what im doing wrong.
