### ISSUE TITLE
No method named into_make_service found for struct Router<S>

### ISSUE THREAD

**Issue by mjanssen** [tokio-rs/axum#1592]
### Platform 
22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

### Description

Axum states are conflicting during compile time in version `0.6.1` (worked as expected in `0.6.0-rc.2`).

Code to reproduce error:
```rust
#[derive(Clone)]
struct AppState {}

fn index_routes(routes: Router<AppState>) -> Router<AppState> {
    routes.route("/", get(|_: State<AppState>| async {}))
}

#[tokio::main]
async fn main() -> () {
    let state = AppState {};
    let mut routes = Router::new()
        .route(
            "/",
            get(|State(db): State<AppState>| async {
                // use state
            }),
        )
        .with_state(state);

    routes = index_routes(routes);

    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        // no method named `into_make_service` found for struct `Router<AppState>` in the current scope
        .serve(routes.into_make_service())
        .await;
}
```

Previously I was able to easily overwrite the mutable router and make sure that the state was available for all children routes. Now the method `into_make_service` is no longer available on the `Router<S>` type.

**Comment by jplatte** [comment]
You must call `.with_state` after registering all routes that need the given state. Please have a closer look at its documentation, which was updated in 0.6.1. The final type has to be `Router<(), _>` so you can call `.into_make_service()`.

**Comment by mjanssen** [comment]
Hi @jplatte, thanks for your reply. Changing the code to implement state after initialising all routes, the final `routes` variable keeps the type `Router<AppState>`. Also since the routes in the method `index_routes` expect the AppState to be set, I am also unable to change return types for this method.

```rust
#[tokio::main]
async fn main() -> () {
    let state = AppState {};
    let mut routes = Router::new();

    routes = index_routes(routes);
    routes = routes.with_state(state);

    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(routes.into_make_service())
        .await;
}
```

**Comment by mjanssen** [comment]
The following code snippet seems to work, but not sure if this is the intended approach 👀 

```rust
let state = AppState {};
let mut routes = Router::new();

routes = index_routes(routes);
let router = routes.with_state(state);

axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
    .serve(router.into_make_service())
    .await;
```

**Comment by jplatte** [comment]
Yes, that is the intended approach. `with_state` "erases" the state type, you must not assign the result to a variable of type `Router<NotUnitType, _>` if you want to follow up with `into_make_service`.

**Comment by mjanssen** [comment]
@jplatte Gotcha, makes sense. Thanks for the explanation!
