### ISSUE TITLE
route_with_tsr doesn't redirect to actual path, but only uses the route

### ISSUE THREAD

**Issue by syphar** [tokio-rs/axum#1605]
### Version
- axum 0.6.1 
- axum-extra 0.4.1

### Platform

Darwin mondo-0984 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Crates
axum-extra

### Description

with axum 0.5 we have the following routes: 
```rust
Router::new()
    .route("/about/:subpage", get_internal(super::sitemap::about_handler))
```

for which axum would correctly 
- serve the page when for example calling `/about/download` 
- serve a redirect to the page above when called via `/about/download/` 

Now with axum 0.6 we would: 
```rust
Router::new()
    .route_with_tsr("/about/:subpage", get_internal(super::sitemap::about_handler))
```

for which axum would now
- serve the correct subpage when requesting `/about/download`
- but when called via `/about/download/`, I'm getting a redirect to `/about/:subpage`, so not the actual redirect target I need. 

From the source it looks like the router just uses the route-name as redirect target, not the actual path from the request.

**Comment by davidpdrsn** [comment]
The fix for this was released in axum-extra 0.4.2 🎉
