### ISSUE TITLE
"/*path" does not match "/" anymore with axum 0.6 ...

### ISSUE THREAD

**Issue by nicolaspernoud** [tokio-rs/axum#1607]
### Version

v0.6.1

### Platform

Linux 5.19.0-26-generic #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Description

Creating a router with : 
```rust
 let mut router = Router::new()
            .route(
                "/*path", ....
```
Used to match an empty path ("/"), but with axum 0.6 it does not work anymore...

**Comment by davidpdrsn** [comment]
Wildcards not matching just a slash is an intentional change. From the [changelog](https://github.com/tokio-rs/axum/blob/main/axum/CHANGELOG.md):

> The request /foo/ no longer matches /foo/*rest. If you want to match /foo/ you have to add a route specifically for that (https://github.com/tokio-rs/axum/pull/1086)

You have to add routes for both `/` and `/*path` or just use `Router::fallback` to catch everything.

**Comment by nicolaspernoud** [comment]
Ok, thanks for the quick answer, fallback does work well !
