### ISSUE TITLE
Make TestHelpers public

### ISSUE THREAD

**Issue by lcmgh** [tokio-rs/axum#1630]
Hi! I would like to reuse the TestHelpers in my tests as seen here: https://github.com/tokio-rs/axum/blob/b1f7ee938dcaaee23e86d572adb3c5f1ccf29575/axum/src/test_helpers/test_client.rs

Would it be an option to make them public and accessible via feature flags?

**Comment by davidpdrsn** [comment]
I'm sorry but no I don't think those should be public. axum is not intended to be a client library. Making those things public would make it harder to change which would make axum harder to maintain. I'd recommend you just copy the code into your own project.
