### ISSUE TITLE
Support zero-hit TLS certificate changes by watching for certificates

### ISSUE THREAD

**Issue by ZhiHanZ** [tokio-rs/axum#164]
## Feature Request
Want some way to rotate on TLS certificate files similar to https://github.com/cloudflare/certinel

### Motivation
Desired certificate should rotate periodically, and after certificate updates, we need to restart server to load newly configured certificates, could we provide a way similar to https://github.com/cloudflare/certinel, which watches certificate resources and update server certificates dynamically without restart?

**Comment by davidpdrsn** [comment]
This is be possible to implement without changes to axum. I don't know how exactly but maybe try asking in #hyper in the tokio discord.

Axum doesn't know anything TLS and requires you to use some crate that is compatible with hyper. It doesn't bundle an HTTP server.
