### ISSUE TITLE
Allow creating a response body from `Arc<Vec<u8>>`

### ISSUE THREAD

**Issue by tamasd** [tokio-rs/axum#1648]
### Motivation

I have a small webservice, that has some assets (css, js) embedded with rust-embed. I would like to support lazy compression of these assets. The way I figured out it could work is to use an `Extension<Arc<Mutex<HashMap<String, Arc<Vec<u8>>>>>>`. This way I could simply get the item from the HashMap without copying (similary how I did it before the compression with `Cow<'static, &[u8]>`).

Without compression:
```rust
        match Assets::get(path.as_str()) {
            Some(content) => {
                let body = boxed(Full::from(content.data));
                let mime = mime_guess::from_path(path).first_or_octet_stream();
                let mut resp = Response::builder()
                    .header(header::CONTENT_TYPE, mime.as_ref())
                    .body(body)
                    .unwrap();

                long_cache_headers(&mut resp);

                resp
            }
            None => Errors::NotFound { path }.into_response(),
        }
```

With compression:
```rust
            let mut asset_cache = asset_cache.lock_owned().await; // HashMap<String, Arc<Vec<u8>>>
            boxed(Full::from(match asset_cache.entry(path.to_owned()) {
                Entry::Occupied(e) => e.get().clone(),
                Entry::Vacant(e) => {
                    let content = get_file(path)?;

                    let mut enc = GzEncoder::new(Vec::new(), Compression::best());
                    enc.write_all(&content)?;

                    e.insert(enc.finish()?).clone()
                }
            }))
```
This is not working, because the body cannot be created from `Arc<Vec<u8>>`.

The error message I get is: 
```
the trait `From<Arc<Vec<u8>>>` is not implemented for `axum::body::Full<_>`
```

### Alternatives

I took out the `Arc<>` and clone the full `Vec<u8>>` for every response.

**Comment by davidpdrsn** [comment]
Use [`Bytes`](https://docs.rs/bytes/1.3.0/bytes/struct.Bytes.html) instead of `Arc<Vec<u8>>` and it should work. `Bytes` is also reference counted. You can make a `Full` with `Full::new(bytes)`.

**Comment by tamasd** [comment]
It works, thanks for the advice.
