### ISSUE TITLE
Unable to upload large files

### ISSUE THREAD

**Issue by asg0451** [tokio-rs/axum#1652]
- [X] I have looked for existing issues (including closed) about this

### Version

 

```
example-stream-to-file v0.1.0 (/home/xxx/build/axum/examples/stream-to-file)
├── axum v0.6.1 (/home/xxx/build/axum/axum)
│   ├── axum-core v0.3.0 (/home/xxx/build/axum/axum-core)
```

### Platform

`Linux xxxx 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Description

I am unable to use Axum to upload large files. Minimal reproduction is just the `stream-to-file` example. It returns 500 - "Error parsing `multipart/form-data` request". On my actual project, with more logging installed, this (same) error is expanded to:

```
2022-12-18T04:24:39.083290Z  WARN request{method=POST uri=/upload version=HTTP/1.1}: site::error: Error: Error parsing `multipart/form-data` request

Caused by:
    failed to read stream: failed to read stream: length limit exceeded
```

.. if that helps

a suitably large file can be generated with `yes | head -c10000000 > some-large.file`

here is what curl says:

```
 $ curl -v -XPOST -F file=@some-large.file localhost:3000
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> POST / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 10000207
> Content-Type: multipart/form-data; boundary=------------------------f8d005641369edee
> Expect: 100-continue
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-type: text/plain; charset=utf-8
< content-length: 43
< date: Sun, 18 Dec 2022 04:28:31 GMT
* HTTP error before end of send, stop sending
<
* Closing connection 0
Error parsing `multipart/form-data` request
```

What is the recommend way to support uploads of large files with axum? I see no reason why this shouldn't work as-is but :shrug:

**Comment by zmlgit** [comment]
`let router=Router::new()
.layer(DefaultBodyLimit::max(1024 * 1024 * 100))
...`

**Comment by davidpdrsn** [comment]
It's because you're hitting the default body limit. See https://docs.rs/axum/latest/axum/extract/struct.DefaultBodyLimit.html for how to tweak it or disable it.

**Comment by asg0451** [comment]
:+1: thanks guys
