### ISSUE TITLE
`extract::Path` cannot be made optional by wrapping in `Option`

### ISSUE THREAD

**Issue by sukhmel** [tokio-rs/axum#1662]
- [x] I have looked for existing issues (including closed) about this

### Version

```shell
$ cargo tree | grep axum
├── axum v0.5.17
│   ├── axum-core v0.2.9
│   │   │       ├── axum v0.6.1
│   │   │       │   ├── axum-core v0.3.0
│   ├── axum v0.5.17 (*)
```

### Platform

```shell
$ uname -a
Darwin VladislavSukhmel-MBP 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64
```

### Description

I tried to use `extract::Path` with `Option` as suggested by [documentation](https://docs.rs/axum/latest/axum/extract/index.html#optional-extractors):

> If you wish to make an extractor optional you can wrap it in Option

but the resulting route rejects calls with a missing path parameter returning status 404 and behaves the same as one without an `Option`  wrapper

I tried this code:
```rust
let listener = TcpListener::bind("0.0.0.0:0").expect("Unable to bind ephemeral socket address");
let router = axum::Router::new()
    .route(
        "/test/:id",
        axum::routing::get(move |_: Option<Path<String>>| async move { StatusCode::OK }),
    );                           // ^^^^^^ this has no effect and may be removed without affecting behaviour
let server = axum::Server::from_tcp(listener)
    .expect("Unable to start Axum web server instance")
    .serve(router.into_make_service());
println!("{}", server.local_addr());
server.await
```

then I called it with cURL:
```shell
$ curl http://localhost:62025/test -w '%{response_code}\n'
```

I expected to see this happen:
```shell
# id is not present but the handler is still called
$ curl http://localhost:62025/test -w '%{response_code}\n'
200

# id is present, that's as usual
$ curl http://localhost:62025/test/id -w '%{response_code}\n'
200
```

Instead, this happened:
```shell
# id is not present, the handler is not called, early rejection?
$ curl http://localhost:62025/test -w '%{response_code}\n'
404

# id is present, that's as usual
$ curl http://localhost:62025/test/id -w '%{response_code}\n'
200
```

As a side note, this approach of wrapping `Path` into an `Option` is advised by at least some [redditors](https://www.reddit.com/r/learnrust/comments/yk0wib/comment/iuspfte/), not sure if they have tested it or also got this from the documentation.

**Comment by jplatte** [comment]
This is intended behavior. A route with the path `/test/:id` matches `/test/` or `/test/foo`, but not `/test`, regardless of which extractors you use. You can still benefit from `Option<Path<_>>`, but you have to register two routes:

```rust
async fn my_handler(path_param: Option<Path<String>>) -> StatusCode {
    StatusCode::OK
}

let router = axum::Router::new()
    .route("/test", my_handler)
    .route("/test/:id", my_handler);
```

**Comment by sukhmel** [comment]
@jplatte well, I did so, but could you specify this as an exception in the documentation? This does not seem to be stated anywhere
