### ISSUE TITLE
Unable to retrieve JSON via GET request

### ISSUE THREAD

**Issue by Time0o** [tokio-rs/axum#1667]
- [x] I have looked for existing issues (including closed) about this

### Version

`axum v0.6.1`
`axum-core v0.3.0`

### Platform

`Ubuntu 22.04.1 LTS (x86_64)`

### Description

I have written this minimal example:

```rust
use std::net::SocketAddr;

#[tokio::main]
async fn main() {
	let app = axum::Router::new()
		.route("/", axum::routing::get(get_root))
		.route("/users", axum::routing::get(get_users));

	let addr = SocketAddr::from(([127, 0, 0, 1], 3000));

	axum::Server::bind(&addr)
		.serve(app.into_make_service())
		.await
		.unwrap()
}


async fn get_root() -> impl axum::response::IntoResponse {
	"Nothing here yet"
}


async fn get_users() -> impl axum::response::IntoResponse {
	let user = User {
		name: String::from("User 1")
	};

	(axum::http::StatusCode::OK, axum::Json(user));
}


#[derive(serde::Serialize)]
struct User {
	name: String
}
```

I can compile this just fine with `rustc 1.66.0` and after starting the server, `curl localhost:3000` returns `Nothing here yet` as expected. However, `curl -i -H "Accept: application/json" localhost:3000/users` simply returns:

```
HTTP/1.1 200 OK
content-length: 0
date: Sat, 31 Dec 2022 15:49:10 GMT
```

Am I doing something fundamentally wrong or is the current release of axum broken?

**Comment by jplatte** [comment]
The issue is simply that your `get_users` handler returns nothing (`()` implements `IntoResponse`). Remove the semicolon at the end of the function body and it will work ad expected.
