### ISSUE TITLE
HTTP/WebSocket/SSE clients

### ISSUE THREAD

**Issue by silvioprog** [tokio-rs/axum#168]
## Feature Request

Add/develop an Axum client project to the tokio-rs. 

### Motivation

To provide client structs/methods as easy to use as Axum-server does.

### Proposal

Not all already existing clients provide support for the features that Axum does (e.g. WebSocket, SSE features), so an Axum client could make it easy to consume those features in the client-side.

### Alternatives

There are Rust clients, but not all provide an easy interface/API as Axum server does.

**Comment by davidpdrsn** [comment]
I think your best bet is probably to post in `#ecosystem` in the Tokio discord. I don't know of any specific plans to develop an HTTP client though. I personally wish reqwest was based on Tower so we could apply tower middleware. When I need an HTTP client I normally go straight to `hyper::Client`.

**Comment by davidpdrsn** [comment]
Think I'll close this for now as its not related to axum. Let me know if you have more questions.
