### ISSUE TITLE
Support for HTTP QUERY method

### ISSUE THREAD

**Issue by 0xflotus** [tokio-rs/axum#1691]
- [x] I have looked for existing issues (including closed) about this

### Motivation

Please consider to support the [HTTP QUERY](https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html) method.

### Alternatives

The in the linked draft above mentioned GET and POST workarounds.

**Comment by davidpdrsn** [comment]
That would require the http supporting it first for its [`Method`](https://docs.rs/http/0.2.8/http/method/struct.Method.html) type.

Until then you can use [`any`](https://docs.rs/axum/0.6.2/axum/routing/method_routing/fn.any.html) and check the method via `Method::as_str`.
