### ISSUE TITLE
docs.rs page for axum 0.6.3 isn't there

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1718]
Not sure what happened but the docs.rs page for axum 0.6.3 isn't there. Doesn't seem like it failed though 🤔

I'll look into it later so this just a note to those who might be wondering.

**Comment by syphar** [comment]
this is odd... I also remember seeing the build in the queue. 

First I thought about a caching issue, but even in uncached pages I don't see the version. 

There _are_ some error situations where the build currently doesn't even log an error, for example invalid metadata. 

Looking at sentry, I see this error ( among others): 
```
the package `axum` depends on `axum-macros`, with features: `__private` but `axum-macros` does not have these features.
```

**Comment by syphar** [comment]
( among other messages, this might be an intermediate one).

**Comment by syphar** [comment]
If needed I can give you more context later today, now I have to jump.

**Comment by davidpdrsn** [comment]
> Looking at sentry, I see this error ( among others):

Yeah thats probably it. I was hoping that since it only depends on that feature as a `dev-dependency` it would be fine. But maybe not. I'll get some new versions published soon.

**Comment by davidpdrsn** [comment]
[0.6.4 is on docs.rs now 🥳 ](https://docs.rs/axum/0.6.4/axum/)
