### ISSUE TITLE
Cookie Support

### ISSUE THREAD

**Issue by theduke** [tokio-rs/axum#172]
## Feature Request

It would be nice to have support for cookie handling.

### Proposal

Add:
*  a typed helper for adding cookies to a response
* `extract::Cookies` for getting request cookies as a map
* Add `extract::Cookie`for getting a single cookie.
  That's a little bit awkward to do without const generics supporting `&str`.
  One option would be 
  ```rust 
    struct extract::Cookie<T: CookieName>;
    trait CookieName {
      const NAME: &'static str;
    }
  ```

**Comment by theduke** [comment]
`reqwest` uses [cookie-rs](https://github.com/SergioBenitez/cookie-rs), which should provide most of what's needed.

This should probably be an optional feature for users that don't want to pull in that extra dependency.

**Comment by davidpdrsn** [comment]
We already provide an integration with [headers](https://docs.rs/headers/0.3.4/headers/index.html) which provides typed headers. It has a [`Cookie`](https://docs.rs/headers/0.3.4/headers/struct.Cookie.html) header that can be extracted using `TypedHeader` like so:

```rust
use axum::extract::TypedHeader;
use headers::Cookie;

async fn handler(TypedHeader(cookie): TypedHeader<Cookie>) {
    let value = cookie.get("key");
}
```

Do you think this fits your use-case?

In general I'm trying to be conservative with which crates axum provides specific integrations for. I'd rather provide good tools that users can use to build exactly what fits their app. Specifically I'm talking about `FromRequest`. While I haven't looked into cookie-rs I don't think it would be difficult to build an extractor for it by implementing `FromRequest` for some type you have.

**Comment by jplatte** [comment]
I think cookie-rs provides a decent bit more functionality than just cookie header parsing / formatting, notably around encrypted cookies. I don't personally have a use case for it, but that might warrant some sort of an integration (which could likely just be its own crate, though).

**Comment by davidpdrsn** [comment]
Adding an example for it, like we do for tokio-postgres, would be fine.

**Comment by theduke** [comment]
The `headers` crate is indeed fine for extracting request cookies.

Sadly it doesn't allow constructing a cookie header, but I guess we'll need some other helper crate for that.

**Comment by davidpdrsn** [comment]
> Sadly it doesn't allow constructing a cookie header, but I guess we'll need some other helper crate for that.

Sounds like that would make a good contribution to `headers`. If someone is up for implementing it :)

**Comment by NOVA-ME** [comment]
and I want  to ask how to set cookie

**Comment by davidpdrsn** [comment]
@NOVA-ME You can include a Set-Cookie header in a response like so https://github.com/tokio-rs/axum/blob/main/examples/sessions/src/main.rs. There are more examples of how to return headers here https://docs.rs/axum/0.2.3/axum/#building-responses

How you build the header value itself is up to you.

**Comment by Dominux** [comment]
> You can include a Set-Cookie header in a response like so https://github.com/tokio-rs/axum/blob/main/examples/sessions/src/main.rs

Hi, the link doesn't work anymore

And [the headers crate](https://github.com/hyperium/headers/blob/master/src/common/set_cookie.rs#L55) used in axum has `SetCookie`, but I can't build the struct to use it since it has it's field private. What should I do? Contructing headers like "set-cookie: ..." seems to be too low level

**Comment by davidpdrsn** [comment]
Please open a new “question” instead of pinging everyone on this old PR.
