### ISSUE TITLE
Add Query Parameter functionality to TypedPath

### ISSUE THREAD

**Issue by erlandsona** [tokio-rs/axum#1740]
- [x] I have looked for existing issues (including closed) about this

### Motivation

There are a number of frameworks that include the concept of "typed" or "checked" URL generation for use in templating systems returning Html specifically in like links `<a href={route_for_path}` or form tags.

See prior art:
In Rust:
https://rocket.rs/v0.5-rc/guide/upgrading/#more-typed-uris
In Haskell (servant)
https://docs.servant.dev/en/stable/cookbook/generic/Generic.html#links
As an example
```hs
-- Type Directed API derivation (client, server, links, swagger, et al)
data Site_ r = Site_
  { _index :: r :- Get '[HTML] Html
  , _smile :: r :- "smile" :> Get '[HTML] Html
  , _wow   :: r :- "wow" :> Capture "stuff" Int :> Get '[HTML] Html
  , static :: r :- Raw
  }
  deriving Generic

smile :: Html
smile =
  btn
    -- Typesafe Routing via Servant Links!
    ! hxGet (_wow route 1) -- _wow :: Site_ -> Int -> String basically.
    ! hxSwap "outerHTML"
    $ "Click me :)"
```

### Proposal

As I posted on Discord there's a few directions I think this could go in Axum:
Context / Problem description:
```rust
    // Old Way w/ Format string can go stale super easily.
    let formated = format!(r#"/colleagues/social.html?locked={}"#, (!opts.show_locked).to_string());
```
Hacked together approach leveraging TypedPath
```rust
    // Newer-ish way is less susceptable to the pathname being changed because it's compile checked here.
    let url = SocialHtmlPath.to_string();
    let params = serde_urlencoded::to_string(Params {
        locked: Some(!opts.show_locked),
    })
    .unwrap();
    let url_and_params = url + "?" + &params;
```

But _IDEALLY_ I'm thinking of being able to use a helper function like what I've defined for my codebase.
```rust
// Look mah, sorta type-safe link generation!
fn path_and_params<P: TypedPath, Q: Serialize>(p: P, q: Q) -> String {
    p.to_string()
        + &serde_urlencoded::to_string(q)
            .map(|q| "?".to_string() + &q)
            .unwrap_or("".to_string())
}
// And later in the rsx! template
<button
    hx-get={
        // Look Mah! Type Safe links!
        path_and_params(SocialHtmlPath, Params { locked: Some(!opts.show_locked) }) //=> /colleagues/social.html?locked=true
    }
```

I think _PREFERABLY_ this logic would be either implemented as an integration with the `#[typed_path]` macro EG:
```rust
#[derive(TypedPath)]
#[typed_path("/colleagues_simple")]
pub struct SimplePath { 
    #[typed_param] // Or something like this?
    locked: Option<bool> // and maybe these instances could come from extractors::Query or something?
};
```

Or maybe that `path_and_params` function could just be another method implemented in terms of the TypedPath trait EG:
```rust
SocialHtmlPath.with_query_params(Params {locked: Some(!opts.show_locked) }).to_string()
```

**Comment by jplatte** [comment]
Sounds like a neat idea. I would propose:

```rust
pub trait TypedPathExt: TypedPath {
    fn to_uri_with_query_string(&self, q: &str) -> Uri {
        let mut uri_parts = self.to_uri().into_parts();
        let path_and_query = uri_parts.path_and_query.as_mut().unwrap();
        *path_and_query = format!("{}?{q}", path_and_query.path()).parse().unwrap();
        Uri::from_parts(uri_parts).unwrap()
    }

    fn to_uri_with_query_params<P>(&self, q: P) -> Result<Uri, impl std::error::Error>
    where
        P: Serialize,
    {
        serde_html_form::to_string(q).map(|query_string| {
            self.to_uri_with_query_string(&query_string)
        })
    }
}

impl<T: TypedPath> TypedPathExt for T {}
```

**Comment by erlandsona** [comment]
Love that you're doing this off of a more correct underlying Uri type.

riffing... as I understand it the `TypedPath` isn't ever going to include the domain, right?
Also if this is going to be used to _construct_ Uri's that we know ahead of time are going to be present, can we leverage NonEmpty types to guarantee construction?

Psuedo-coding off what @jplatte wrote something like:

```rust
pub trait TypedPathExt: TypedPath {
    // some cargo feature gate?
    fn with_params<P: Serialize>(&self, q: NonEmpty<P>) -> Uri
    {
        serde_html_form::to_string(q).map(|query_string| {
            self.to_string() + "?".to_string() + &query_string
        }).parse::<Uri>().unwrap() // Safe because of both TypedPath & having a NonEmpty<P>
    }
}

impl<T: TypedPath> TypedPathExt for T {}
```

Also just proposing alternative names here given that the context (Uri) is known and the function is being called on something of TypedPath, the name can be elided a bit for brevity?

Again just riffing.

**Comment by davidpdrsn** [comment]
What is `NonEmpty`? I'd expect serde_url_encoded to handle empty things.

**Comment by erlandsona** [comment]
NonEmpty is a category of types that are guaranteed to have data. And they enable you to forgo Option or Result because the existence of the type guarantees that it's filled with stuff.

Rust apparently has a crate for NonEmpty types too which is nice!

https://docs.rs/nonempty/latest/nonempty/

**Comment by davidpdrsn** [comment]
Seems like you're over complicating things. If you pass something that serializes to nothing then `serde_urlencoded::to_string` just returns an empty string. Demo https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=782121684e32519dcde8b84070a41d55

URLs with a trailing `?` isn't invalid afaik so I don't think we even need to check for that, at least on the case that uses `serde_urlencoded`.

**Comment by erlandsona** [comment]
> URLs with a trailing ? isn't invalid afaik

This is so much yes. In which case I totally agree NonEmpty is unnecessary 🙌

That said, prolly still don't need the unwrap calls right? Or we can leverage unwrap_or_default so we're not panicking right?

**Comment by erlandsona** [comment]
> Seems like you're over complicating things. If you pass something that serializes to nothing then `serde_urlencoded::to_string` just returns an empty string. Demo https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=782121684e32519dcde8b84070a41d55

Wait, so I tinkered with the Demo example you gave and now I don't think I was over complicating things.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=782121684e32519dcde8b84070a41d55
^ That should be caught by the compiler but instead it panics.

IMO Encoder's shouldn't return Result's. I usually reserve fail-ability for Decoders.

**Comment by davidpdrsn** [comment]
Did you post the right link? https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=782121684e32519dcde8b84070a41d55 doesn't panic.

**Comment by erlandsona** [comment]
Ah the link didn't update... but I posted the issue on the PR.

**Comment by davidpdrsn** [comment]
Thats a broader issue with serde. There is no way for an encoder to know upfront whether it supports a given input, without just trying to serialize it. Its hard to solve in general because you can implement `Serialize` for whatever you want, however you want.

**Comment by erlandsona** [comment]
I just looked up the serde docs on the Serialize and you're correct. https://serde.rs/impl-serialize.html returns a result to this isn't serde_urlencoded's fault but serde itself.

It makes me sad because that's just philosophically incorrect. EG: Decoder's go from a broader type to a more specific type in a potentially lossy way so it makes sense for a Decoder to return a Result where decoding from string to int for example includes the possibility of failure. But going the other way around is perfectly safe to encode an int -> str without the need for any failure mode.

Interesting that serde is basically saying everything is a function from `whatever -> Result<T, Err>` and you pick Serialize / Deserialize based on what you want the method name to be.

Or I'm probably misunderstanding this somehow :thinking: I really hope so :disappointed:

**Comment by davidpdrsn** [comment]
I think its a very practical choice and not something that, empirically, has caused me much trouble 😅 I understand your point though.

Do you know of another serialization library that works like that? I can imagine its hard in terms of types/generics to do statically.

**Comment by erlandsona** [comment]
Elm/JSON, Haskell's Aeson, every serialization lib I've learned until serde is like that? It's not hard or anything to do with types. In Rust it'd just be a requirement of the trait just like in Haskell it's how the typeclass for ToJSON is defined?

**Comment by erlandsona** [comment]
Of course a change to the serde interface NOW would be massive for the ecosystem, granted I think ultimately it'd mean a LOT less use of unwraps and panics 🤷

**Comment by davidpdrsn** [comment]
The difference is that serde is an intermediate between any data type and any data format. Sure if your library only supports JSON the it is easy. But serde supports arbitrary formats. I recommend https://www.youtube.com/watch?v=BI_bHCGRgMY for a general introduction to how serde works.

**Comment by erlandsona** [comment]
Ah yes! Thanks for the link! It's now at the top of my watchlist! Thanks.
