### ISSUE TITLE
Update 'Routing' Documentation to HIghlight 'nest' and it's use case and link

### ISSUE THREAD

**Issue by scott-ling** [tokio-rs/axum#177]
## Feature Request
Update 'Routing' Documentation to HIghlight 'nest' and it's use case and link

### Motivation
Simply put, `nest` works very similar to the routing in other WEB/API frameworks, due to this most new users of Axum look to `routing' in the existing documents and get frustrated when trying to use it.  

Ironically, the most common user errors are non-existent if they start with `nest` routes. 

ps. fo reference most people coming to Axum currently seem to be experienced with Actix.

### Proposal
Just add a note at top of the Routing documentation stating explicitly that if a user has experience in a framework with routing like Actix they should look at `nest routing`  first and provide a link to that area of the documentation.   <-- this is likely the simplest solution.

I know the first place I and from my chats, others look for API endpoint routing is the routing section of the documentation :)

### Alternatives
Not an Alternative, but an addition: Add in documentation an example of how to do an Actix route in Axum (nest), and or other WEB/API.  -> this would likely be the first place people look before looking at online docs.  We all love to look at examples after all.

**Comment by davidpdrsn** [comment]
I believe this was addressed by https://github.com/tokio-rs/axum/pull/175. IMO this highlights `nest` well enough.
