### ISSUE TITLE
Allow Header from 405 response is lost through service layers unless the route is `.nest`ed

### ISSUE THREAD

**Issue by taylor1791** [tokio-rs/axum#1770]
### Versions

axum 0.6.7
axum-core 0.3.2
axum-macros v0.3.4

### Prior Art
- [X] I have looked for existing issues (including closed) about this
Issues: #1525 #731 
PRs: #1526 #733 

### Platform

Linux hostname 5.15.94 # 1-NixOS SMP Tue Feb 14 18:18:05 UTC 2023 x86_64 GNU/Linux

### Description

While flattening some of my `.nest`ed routers, the router stopped responding with the Allow header on 405 responses. I simplified my code down to the following failing test.

```rust
#[crate::test]
async fn fail_1() {
    async fn hello() -> &'static str {
        "Hello World"
    }

    let middleware = tower::ServiceBuilder::new();
    let app = Router::<(), Body>::new().route("/hello", get(hello)).layer(middleware);
    let client = TestClient::new(app);

    let res = client.patch("/hello").send().await;
    assert_eq!(res.status(), StatusCode::METHOD_NOT_ALLOWED);
    assert_eq!(res.headers()[ALLOW], "GET,HEAD");
}
```

The interesting thing is that the following tests both pass!
```rust
#[crate::test]
async fn pass_1() {
    async fn hello() -> &'static str {
        "Hello World"
    }

    let app = Router::<(), Body>::new().route("/hello", get(hello));
    let client = TestClient::new(app);

    let res = client.patch("/hello").send().await;
    assert_eq!(res.status(), StatusCode::METHOD_NOT_ALLOWED);
    assert_eq!(res.headers()[ALLOW], "GET,HEAD");
}

#[crate::test]
async fn pass_2() {
    async fn hello() -> &'static str {
        "Hello World"
    }

    let middleware = tower::ServiceBuilder::new();
    let hello = Router::<(), Body>::new().route("/hello", get(hello));
    let app = Router::<(), Body>::new().nest("/", hello).layer(middleware);

    let client = TestClient::new(app);

    let res = client.patch("/hello").send().await;
    assert_eq!(res.status(), StatusCode::METHOD_NOT_ALLOWED);
    assert_eq!(res.headers()[ALLOW], "GET,HEAD");
}
```

I expected all of the previous tests to pass since, based on my read of the [middleware](https://docs.rs/axum/latest/axum/middleware/index.html) docs, they should all be functionally identical. This behavior is either a subtle difference that was lost on my density or a bug.

**Comment by davidpdrsn** [comment]
Huh that is very weird. Seems that simply adding a middleware that does nothing break its. Thats certainly a bug.
