### ISSUE TITLE
Use tuples as `Router` state

### ISSUE THREAD

**Issue by Altair-Bueno** [tokio-rs/axum#1793]
- [X] I have looked for existing issues (including closed) about this

### Motivation

Currently users define the application state as a custom type (normally a struct) that is later used for multiple `FromRef` implementations. While this trait can be manually implemented, there is an option to derive said trait with a prod macro. This contrasts with axum's claim of having a "macro free API" (technically still true, but the derive macro is frankly the best option for creating sharing state, at the time of writing)

### Proposal

Add blanked `FromRef` implementations for tuple types, allowing users to use a tuple. This would have the following advantages:

- True macro free API
- Minimal diffs between state changes
- Less boilerplate to get started with state sharing

```rs
// Example implementations. Not the actual code
impl<T> FromRef<(T,)> for T
where
    T: Clone,
{
    fn from_ref(input: &(T,)) -> Self {
        input.0.clone()
    }
}

impl<T, A> FromRef<(T, A)> for T
where
    T: Clone,
{
    fn from_ref(input: &(T, A)) -> Self {
        input.0.clone()
    }
}

impl<T, A> FromRef<(A, T)> for T
where
    T: Clone,
{
    fn from_ref(input: &(A, T)) -> Self {
        input.1.clone()
    }
}
// Every other combination ...
```

```rs
// Sample usage
let router = Router::new()
	// ...
	.with_state((
		state1, 
		state2, 
		state3, 
		state4,
		// ...
	));
```

### Known limitations

This isn't possible at the moment in stable Rust (to my knowledge), as the compiler yields a `conflicting implementations of trait E0119` error.

On nightly, this can be archived with unstable feature `negative_impls`. [Link to nightly playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9489df07e47b7ee5dc7adff783bfbe21).

I don't know if there is any other way to declare that two generic types are different, this is one is the easiest I know of.

### Related issues 

- Related to https://github.com/tokio-rs/axum/issues/1519
  - OP's idea is to extract tuples from State as substates
  - This issue differs on motivation and behaviour
- [Tracking issue for `negative_impls`](https://github.com/rust-lang/rust/issues/68318)

**Comment by davidpdrsn** [comment]
I don't think we should introduce features that require nightly stuff. So unless there is a way to do this on stable I don't think we should do this.

> This contrasts with axum's claim of having a "macro free API"

While true, the "macro free API" mainly refers to the route builder. I'm okay with the `FromRef` and `FromRequest` derives.

**Comment by Altair-Bueno** [comment]
> I don't think we should introduce features that require nightly stuff

Agreed. Got any clue on how to do this on stable? If not we could leave this as blocked until the feature gets stabilised or someone shares another way of doing this. 

The other day I found this thought it was weird that tuples couldn't be used as macro-states. Specially when tuples are fairly common on axum

**Comment by davidpdrsn** [comment]
> Got any clue on how to do this on stable?

Nope 😕 

> If not we could leave this as blocked until the feature gets stabilised or someone shares another way of doing this.

Yeah that's fine. We have a couple of such issues already. I do it would be cool if we could make it work.

**Comment by davidpdrsn** [comment]
I'll close this for now since its not actionable.
