### ISSUE TITLE
Hide functions generated by debug_handler from docs

### ISSUE THREAD

**Issue by A-Walrus** [tokio-rs/axum#1824]
- [x] I have looked for existing issues (including closed) about this

### Motivation
When using rustdoc on an Axum project, which uses `#[axum::debug_handler]`, the doc output is very cluttered by functions generated by the macro:
![image](https://user-images.githubusercontent.com/58790821/223385774-023b37f2-6685-45a1-bfd4-4590ada7c702.png)

### Proposal
Hide these generated functions from the docs with `#[doc(hidden)]` annotation.
### Alternatives
Maintain status quo and continue showing generated functions in docs.

**Comment by jplatte** [comment]
Seems like a good idea 👍🏼
