### ISSUE TITLE
Remove `axum::prelude`

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#185]
### Motivation

I added `axum::prelude` mainly to make documentation examples shorter and have less imports. But preludes have fallen out of style over the last few years for a few reasons:

- Glob imports make things harder to understand. Scanning a list of imports and seeing everything that gets pulled in is nice. Can't do that when using glob imports which preludes require.
- Auto import in rust-analyzer has gotten pretty reliable even for methods on traits.
- They're doing a dis-service to new users since it makes things harder to find in the docs.

### Proposal

Remove the prelude and update all the docs and examples. Shouldn't be hard but will most likely be tedious work.

### Alternatives

None that come to mind.

**Comment by ZFLloyd** [comment]
I've started working on it, I'll probably finish after work and make the PR this evening 👍

**Comment by davidpdrsn** [comment]
Thanks!

**Comment by mrgzi** [comment]
I think preludes are very important, especially when working with frameworks. Additionally, they don't prevent developers from using regular imports.

**Comment by jplatte** [comment]
- axum is not a framework
- as the current maintainer, I'm not interested in (re-)adding a prelude module
- this issue was closed 3y ago
