### ISSUE TITLE
Support relative redirect or reading its ancestor path from inside a nested `Router` or `handler`

### ISSUE THREAD

**Issue by dulguun0225** [tokio-rs/axum#1858]
### Discussed in https://github.com/tokio-rs/axum/discussions/1854

<div type='discussions-op-text'>

<sup>Originally posted by **dulguun0225** March 15, 2023</sup>
I wanna redirect to one of my own paths without hardcoding what my ancestor path is.

```Rust
use std::net::SocketAddr;

use axum::{response::Redirect, routing::get, Router};

fn users_router() -> Router {
    Router::new()
        .route("/", get(|| async { "users index" })) 
        .route("/fallback", get(|| async { "users fallback"}))
        // make it redirect without hardcoding /users part.
        .fallback(|| async { Redirect::to("/users/fallback") })
}

#[tokio::main]
async fn main() {
    let app = Router::new().nest("/users", users_router());
    
    axum::Server::bind(&SocketAddr::from(([127, 0, 0, 1], 5000)))
        .serve(app.into_make_service())
        .await
        .unwrap()
}
```

Maybe I could pass ancestor path to the `users_router` function. But it could get tedious when things are nested deeply.</div>

**Comment by dulguun0225** [comment]
Maybe a path extractor would do? How one would implement it?

**Comment by davidpdrsn** [comment]
I guess nesting a router could set some extension, which handlers can then extract. Similar to how `MatchedPath` works.

**Comment by ttys3** [comment]
this is important when impl a otel tracing middleware.

https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/http/#http-server-semantic-conventions

now we can not get route name in nested route.

related issue: https://github.com/davidB/axum-tracing-opentelemetry/pull/54#issuecomment-1493376105
