### ISSUE TITLE
Remove tower from axum's public API

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#186]
### Motivation

There are currently a few places where things from tower appears in axum's public API. Since tower's versioning is a bit more loose, than say tower-service, I think it makes sense to remove.

### Proposal

Remove tower from axum's public API most likely by vendoring the parts.

I think have an exhaustive list but these come to mind:

- `RoutingDsl::into_make_service` returns `tower::make::Shared`
- `tower::BoxError` is still used in some bounds. Can just be vendored since its just a type alias.

There are probably other places I'm forgetting.

**Comment by ZizhengTai** [comment]
Sorry for probably a noob question, but what does "vendoring" mean in this context?

**Comment by davidpdrsn** [comment]
Copying code from a dependency into axum so we can control the API, or in this case to avoid breaking changes propagating into axum. For example `tower::make::Shared` is very simple so copying it into axum wouldn't be too bad.

**Comment by pepoviola** [comment]
Hi @davidpdrsn, this sounds like a fun issue to work and contribute is nobody start to work on it yet.
Thx!

**Comment by davidpdrsn** [comment]
@pepoviola go for it!

For `tower::BoxError` that should just become `pub type BoxError = Box<dyn std::error::Error + Send + Sync>` in `lib.rs`. For `tower::make::Shared` I think we should just vendor it, rename it to `MakeRouteService` and make the constructor private.

I'm not sure if there are other tower things in axum's public API. Would be neat if there was a tool that could figure that out 🤔

**Comment by pepoviola** [comment]
Great! thanks @davidpdrsn! I will also look if there is some tool we can use for scan the public api.

**Comment by davidpdrsn** [comment]
@pepoviola Not sure if you started working on this yet but I'm gonna look into it today. Would like to get 0.2 out next week.

**Comment by pepoviola** [comment]
Hi @davidpdrsn, I didn't make time to make any progress. I saw your pr and looks awesome 🚀🙌
Thanks!
