### ISSUE TITLE
Make it more ergonomic to return headers from handlers

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#187]
### Motivation

Currently returning headers + a response from a handler looks like this:

```rust
async fn handler() -> impl IntoResponse {
    let mut headers = HeaderMap::new();
    headers.insert(CONTENT_TYPE, "my-fancy-content".parse().unwrap());
    (headers, "Hello, World!")
}
```

While that isn't too bad I've been wondering if we could make something nicer.

### Proposal

I'm wondering if this could work

```rust
async fn handler() -> impl IntoResponse {
    (
        [(CONTENT_TYPE, "my-fancy-content")],
        "Hello, World!",
    )
}
```

So a `([(K, V); const N: usize], impl IntoResponse)` where `K` can be converted into a `HeaderName` and `V` into a `HeaderValue`.

**Comment by jplatte** [comment]
I think just using an array would not make it clear enough that this is for headers. Why not add a macro like `maplit::hashmap` for `HeaderMap` (preferably to the http crate)?

**Comment by scott-ling** [comment]
I agree with  @jplatte that the suggestion is actually more cryptic for new users or people doing code reviews than how it is right now.  

Some synaptic sugar via named types/helpers would be better for clarity of use and readability.  (or a macro <- but, I know axum is avoiding these ideally, something I like )

**Comment by davidpdrsn** [comment]
We could add a `Headers` wrapper that works for any `IntoIterator`:

```rust
async fn handler() -> impl IntoResponse {
    (
        Headers([(CONTENT_TYPE, "my-fancy-content")]),
        "Hello, World!",
    )
}
```

Then you can return a map or an array depending on whats appropriate.
