### ISSUE TITLE
Add `Redirect` response

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#188]
### Motivation

The oauth example contains [a little `Redirect` utility](https://github.com/tokio-rs/axum/blob/main/examples/oauth.rs#L198-L210). I think that is quite useful and so we should move it to axum proper.

### Proposal

I think an API similar to tower-http's [`Redirect`](https://docs.rs/tower-http/0.1.1/tower_http/services/redirect/struct.Redirect.html) leaf service would be good. So something like

```rust
Redirect::temporary(uri)
Redirect::permanent(uri)
Redirect::with_status_code(uri, status)
```

**Comment by heliumbrain** [comment]
I'm gonna give this a shot. Can hopefully fix it today

**Comment by davidpdrsn** [comment]
@heliumbrain I've already started working on something.
