### ISSUE TITLE
OptionalPath extractor

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#1884]
- [x] I have looked for existing issues (including closed) about this

### Motivation

We've been getting many people asking about an easy way of extracting a path segment value only if a placeholder exists at the route the handler was called from.

### Proposal

Add an extractor `struct OptionalPath<T>(Option<T>);` that succeeds with `None` if there are no placeholders for the given route, and if there are placeholders, attempts to deserialize the arguments to `T` and return `Some(T)` on success, rejecting the request on failure.

### Alternatives

🤷🏼

**Comment by simbleau** [comment]
```
            .route("/", get(handler)
            .route("/:path", get(handler))
```

```rs
pub(crate) async fn handler(
    path: Option<Path<String>>,
) -> impl IntoResponse
{
..
}
```

**Comment by jplatte** [comment]
Yes, that works most of the time, but it doesn't reject the request for `/:path` requests with invalid UTF-8. Or maybe it does for the wrong reason. Anyways if using `u32` instead of `String` in your example, a non-integer value for `:path` will still call the handler.

@davidpdrsn wdyt about this idea?

**Comment by davidpdrsn** [comment]
I'm wondering if we can change `PathRejection` so you can tell if a param was missing, without needing a new extractor. An `OptionalPath` might still be worth it but in that case we could put it in axum-extra as a simple wrapper around `Path` + `PathRejection::MissingParam` (or smth)

**Comment by jplatte** [comment]
Yeah, the idea was to put it in axum-extra, and implement it in terms of `Path`. I didn't realize that isn't yet possible 😄

**Comment by davidpdrsn** [comment]
Then I think it's a good idea!

I don't specifically remember if its possible today but looking at `PathRejection` seems like we're missing a variant for it:

```rust
pub enum PathRejection {
    FailedToDeserializePathParams(FailedToDeserializePathParams),
    MissingPathParams(MissingPathParams),
}
```

`MissingPathParams` is for the internal extension missing and responds with `Internal Server Error` so that's a different thing. Though the name is a bit confusing in this context.

**Comment by davidpdrsn** [comment]
Looking at `PathRejection` a bit more closely it seems we might be able to use `WrongNumberOfParameters` from the `axum::extract::path::ErrorKind` that you get from [`FailedToDeserializePathParams::into_kind`](https://docs.rs/axum/latest/axum/extract/path/struct.FailedToDeserializePathParams.html#method.into_kind).
