### ISSUE TITLE
Unwrapping extractor's payload using generics

### ISSUE THREAD

**Issue by Altair-Bueno** [tokio-rs/axum#1903]
- [x] I have looked for existing issues (including closed) about this

### Motivation

Working on [axum-garde](https://github.com/Altair-Bueno/axum-garde), we were facing the issue that there is no common trait on all extractors to unwrap the inner payload using generics

### Proposal

Include [`IntoInner`](https://github.com/Altair-Bueno/axum-garde/blob/f5abf1834d5a6460709e963ba2db2825c1fee8a8/src/wrapper.rs) on `axum_core`, and implement the trait on all extractors where it makes sense. 

### Alternatives

Current workaround is to create and implement the trait on our own crate, but this makes `axum-garde` incompatible with third party crates. Having this trait on `axum_core` would unlock compatibility with other crates, such as `axum-yaml` or `axum-msgpack`

**Comment by davidpdrsn** [comment]
Would the only benefits of having such a trait in axum-core be that third party crates don't need it to depend no axum-grade? Are there any other benefits? If so I'm not sure it's a great idea. It would still burden third party library developers

**Comment by davidpdrsn** [comment]
It's hard to judge the usefulness without more context. Can you show what APIs that trait enables and what the alternative is? Is it just so the user doesn't have to pattern match themselves (`.foo(|Json(inner)| inner)`)?

Would the only benefit of having such a trait in axum-core be that third party crates don't need it to depend no axum-garde (or axum-garde depend on the third party lib)? Are there any other benefits? If so I'm not sure it's a great idea.

How would you ensure that extractors implement `IntoInner`? Doing `trait FromRequest: IntoInner` isn't good because then you're required to implement `IntoInner` even if you don't use axum-garde and for private extractors that you just use inside your app.

There might also be some extractors that doesn't have an inner value, such as `Multipart`. I guess `IntoInner` would just return `self` in that case but that's just tedious boilerplate.

So while I'm open to the idea, my initial impression is that it isn't worth the additional burden on third party developers and potentially users.

**Comment by Altair-Bueno** [comment]
> Can you show what APIs that trait enables and what the alternative is? 

It would enable more advanced extractor composition. Currently, the only kind of composition we can have is like what we built with `WithRejection`, as we cannot access the inner values on the extractor.

With this trait, the following could be archived:

```rs
// Imaginary module that provides functional extractors
use axum_functional::{Map, Filter};
// Another crate that leverages `IntoInner`
use axum_garde::WithValidation;
// Any crate could provide more extractors

async handler(
	// We leverage the type to perform multiple operations over the payload
	WithValidation(user): WithValidation<Map<Filter<Json<User>, IsPremiumUser>,Capitalize>>, TransFormUser>>,
) -> impl IntoResponse {}
// ...
```

Without `IntoInner`, we can `Deref` and `DerefMut` to obtain references to the wrapped value, but would result on the following:

```rs
use axum_functional::{Map, Filter};
use axum_garde::WithValidation;


// `valid` has type `Valid<Map<Filter<Json<Users>>>`. Defeats the purpose of 
// `Valid` and the typestate pattern, the reason why the constructor isn't public
async handler(
	WithValidation(valid): WithValidation<Map<Filter<Json<User>, IsPremiumUser>, Capitalize>>, TransFormUser>>,
) -> impl IntoResponse {}
// ...
```

Also, some extractors don't implement `DerefMut`. Form, for example, being one of them

> How would you ensure that extractors implement IntoInner? 

I don't think this is something that we should enforce, but rather a recommendation. If the idea of "unwrapping an inner value" makes sense on the extractor, it should implement `IntoInner`. Some extractors that exhibit this behaviour would be `Json`, `Form` and `Query`.

**Comment by davidpdrsn** [comment]
> ```rust
> async handler(
> 	// We leverage the type to perform multiple operations over the payload
> 	WithValidation(user): WithValidation<Map<Filter<Json<User>, IsPremiumUser>,Capitalize>>, TransFormUser>>,
> ) -> impl IntoResponse {}
> ```

I'm sorry, but that's nuts 😅 if you want to enable such APIs you'll have to roll your own traits.

I'm still not convinced we should add this.

@jplatte what do you think?

**Comment by Altair-Bueno** [comment]
> I'm sorry, but that's nuts 😅 if you want to enable such APIs you'll have to roll your own traits.

Type aliases would make it better, but agreed it's not the best looking API 😆. Specially that example, which is overkill. Something like this would be more realistic, and something i would actually use as and end user

```rs
async handler(
  // Extract the authentication claims from an specific header, and login the user with 
  // it's contents
  Login(user_data): Login<TypedHeader<Authorization>>,
  // Obtaining the contents of the base64 encoded header
  Base64Decode(header_content): Base64Decode<TypedHeader<X_My_Header>>,
  // Data validation, as discussed before
  WithValidation(valid_yaml): WithValidation<Yaml<User>>,
) -> impl IntoResponse {}
```

**Comment by jplatte** [comment]
> @jplatte what do you think?

I think it doesn't make sense for axum-core to define traits that none of the first-party crates use. This trait should continue to be defined by the project that needs it.

**Comment by Altair-Bueno** [comment]
I understand the reasoning why `IntoInner` shouldn't be included on `axum-core`, but what about `axum-extra`? That would allow crates to opt in if they want to (optional dependency and feature).

**Comment by davidpdrsn** [comment]
Then they might as well depend on your crate 🤷

**Comment by Altair-Bueno** [comment]
But that would leave APIs like the one described [here](https://github.com/tokio-rs/axum/issues/1903#issuecomment-1493040880) out of the table, something i would like to give a try too. `axum-garde` is meant to provide an extractor to validate payloads, not to build an ecosystem around a trait. An alternative would be creating another crate (something like `axum-traits`) but that would be overkill imho.

**Comment by davidpdrsn** [comment]
We won't be adding it to axum-extra. If you wanna make your own crate or not, that is up to you.

**Comment by Altair-Bueno** [comment]
Totally understandable. As always, thanks for your time :)
