### ISSUE TITLE
Decide whether extractors in axum should implement DerefMut

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#1907]
As pointed out in another issue recently, we are inconsistent about whether (generic) newtype extractors implement `DerefMut` or not. Some examples of newtype extractors that do are `Path` and `State`, some examples of newtype extractors that don't are `Form` and `Query`.

**Comment by davidpdrsn** [comment]
I don't see why not. None of those extractors have methods of their own so should be fine. Think it's just an oversight that they don't currently.
