### ISSUE TITLE
`RoutingDsl::or` causes HTTP/2 requests to hang

### ISSUE THREAD

**Issue by programatik29** [tokio-rs/axum#191]
### Version

#108 and after.

### Platform

`Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux`

### Crates

`dev-dependencies` in `Cargo.toml`

### Description

When running tls example any request to non-matching route cause hanging when using `http2` protocol.

I ran tls example using `cargo run --example tls_rustls`.

Then I ran `curl -k https://localhost:3000/asdasd` in a separate tab. That did not return as expected.

After last command, I ran `curl -k --http1.1 https://localhost:3000/asdasd`. That returned nothing(404 status code) as expected.

**Comment by davidpdrsn** [comment]
This can be reproduced without axum using just hyper:

```rust
use http::{Request, Response};
use hyper::Body;
use std::convert::Infallible;

#[tokio::main]
async fn main() {
    let svc = tower::service_fn(|req: Request<Body>| async move {
        let mut res = Response::new(Body::empty());
        let body = req.into_body();
        res.extensions_mut().insert(body);
        Ok::<_, Infallible>(res)
    });

    hyper::Server::bind(&"127.0.0.1:3000".parse().unwrap())
        .serve(tower::make::Shared::new(svc))
        .await
        .unwrap();
}
```

`curl -v localhost:3000 --http2-prior-knowledge` fails but `curl -v localhost:3000` works.

**Comment by davidpdrsn** [comment]
I've filed https://github.com/hyperium/hyper/issues/2621
