### ISSUE TITLE
Undocumented breaking change to bounds on `Router::layer` parameter

### ISSUE THREAD

**Issue by nsunderland1** [tokio-rs/axum#1917]
### Version

0.6.12

### Platform

Amazon Linux 2

### Crates

`axum`

### Description

In `axum-0.5`, `Router::layer`'s parameter did not have a `Clone + Send + 'static` bound: https://docs.rs/axum/0.5.17/axum/routing/struct.Router.html#method.layer

```rust
L: Layer<Route<B>>,
```

In `axum-0.6`, there is now a tighter bound: https://docs.rs/axum/0.6.0/axum/struct.Router.html#method.layer

```rust
L: Layer<Route<B>> + Clone + Send + 'static,
```

This is the PR that made the change: https://github.com/tokio-rs/axum/pull/1368

This is a breaking change, as some types that were previously accepted by `layer` are now rejected. It's not a huge deal, in our codebase I was able to fix this by implementing `Clone` for our `Layer` type. But I don't see any explicit documentation of this breaking change in the changelog for `0.6`.

**Comment by davidpdrsn** [comment]
You're welcome to submit a PR that updates the changelog.
