### ISSUE TITLE
Consider adding tuple support to OptionalPath

### ISSUE THREAD

**Issue by fwgreen** [tokio-rs/axum#1936]
I'm getting this error when try to use **OptionalPath** with multiple params:

```Rust
OptionalPath((thing_one, thing_two)): OptionalPath<(String, String)>

//...
mismatched types
expected enum `std::option::Option<(std::string::String, std::string::String)>`
found tuple `(_, _)`
```

**Comment by jplatte** [comment]
Tuples are already supported, you just can't use a tuple pattern against an `Option<(T1, T2)>` like the compiler says. Instead you have to write `OptionalPath(opt): OptionalPath<(T1, T2)>` in the function signature and then match `opt`, e.g.

```rust
match opt {
    Some((param1, param2)) => {}
    None => {}
}
```

**Comment by fwgreen** [comment]
Thank you!
