### ISSUE TITLE
Can `axum::serve` handle both http 1 and 2?

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1953]
`axum::Server` was a re-export of `hyper::Server` which is going away for hyper 1.0. Therefore axum is getting `axum::serve(tcp_listener, service)` in 0.7 for simple use cases.

It currently only supports http 1. We should investigate if we can also support http 2. Might require https://github.com/hyperium/hyper-util/pull/11

**Comment by rakshith-ravi** [comment]
Looks like that got merged. Is this something we can do now? Can I help in any way?

**Comment by davidpdrsn** [comment]
Great! I'm curious if we can just replace the implementation of `axum::serve` to instead be a small wrapper around something in hyper-util. That was always the intention. Would be much appreciated if you'd give that a shot!

**Comment by rakshith-ravi** [comment]
No rustbot? Lol okay. Force of habit I guess
