### ISSUE TITLE
any way to use debug_handler macro while using re-exported axum?

### ISSUE THREAD

**Issue by horacimacias** [tokio-rs/axum#1960]
- [x] I have looked for existing issues (including closed) about this

### Motivation

I'm trying to use debug_handler and I am already using axum, reexported from another crate I'm using.

### Proposal

Provide a means to use `debug_handler` while at the same time using reexported axum.
Similar to how `serde` does it with the `crate` attribute: https://serde.rs/container-attrs.html#crate

### Alternatives

manually `cargo add axum` use `debug_handler` and remember to remove the "direct" axum dependency once done as otherwise I'm importing axum twice.

**Comment by davidpdrsn** [comment]
> manually cargo add axum use debug_handler and remember to remove the "direct" axum dependency once done as otherwise I'm importing axum twice.

I think that is fine. I don't think its worth adding additional stuff to support this.
