### ISSUE TITLE
`req.headers()` does not contain the `sec-websocket-key` header.

### ISSUE THREAD

**Issue by GavBog** [tokio-rs/axum#1971]
- [✔️] I have looked for existing issues (including closed) about this

### Version
axum v0.6.17
axum-core v0.3.4

### Platform
MacOS

### Description
I got all the headers from the websocket request using `req: Request<Body>` and `req.headers()`... This code works great except I noticed that the `sec-websocket-key` header was missing. If there is another way to get this header please let me know! This is my first time using axum. Thanks!

**Comment by GavBog** [comment]
https://github.com/tokio-rs/axum/blob/ce7739e76dd10b45492b6f1a73a41c9b7e59009f/axum/src/extract/ws.rs#L382

**Comment by GavBog** [comment]
I'm no where near qualified to work on this repository and I am sure that the code was structured this way for a reason but this seems to fix it.

https://github.com/GavBog/axum/commit/bdcade2793a4bb468cd3ca75cd2a1f94eb8e9214

**Comment by davidpdrsn** [comment]
Oh yeah that shouldn't remove the header

**Comment by davidpdrsn** [comment]
Fix published in 0.6.18.
