### ISSUE TITLE
Implement IntoResponse<Vec<T>> where T: IntoResponse

### ISSUE THREAD

**Issue by clarkmcc** [tokio-rs/axum#1989]
- [x] I have looked for existing issues (including closed) about this

## Feature Request
I have a `T` that implements `IntoResponse` but I can't seem to return a `Vec<T>`.

### Motivation
Make axum easier to work with

### Proposal
Is it possible for Axum to auto-implement `impl<T: IntoResponse> IntoResponse for Vec<T>`?

### Alternatives
```
Ok(Json(json!(vec)))
```

**Comment by clarkmcc** [comment]
I'm realizing that this doesn't work for everything. It works for JSON because JSON can represent multiple serializable Ts as a single T in the form of an array of Ts, but maybe that doesn't apply across the board.

**Comment by davidpdrsn** [comment]
That's not possible. How should the list be turned into a response? As json, yaml, xml, protobuf? There isn't an obvious answer so you therefore you need to use `Json`, if you want JSON.

**Comment by jplatte** [comment]
> ### Alternatives
> ```
> Ok(Json(json!(vec)))
> ```

This is more complicated and less efficient than necessary. You can write `Ok(Json(vec))` instead.
