### ISSUE TITLE
Can not run the hello-world example

### ISSUE THREAD

**Issue by liebkne** [tokio-rs/axum#1991]
- [x] I have looked for existing issues (including closed) about this

### Version

```
├── axum v0.6.18
│   ├── axum-core v0.3.4
```

### Platform

`Darwin macOS.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64 i386 Darwin`

### Crates

```
[dependencies]
axum = { version = "0.6.18", features = ["tokio"] }
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread"] }
```

### Description

Running the hello-world example inside the repo is fine. But when I copy the hello world example to a `cargo new hello-world` with the above dependencies it fails with the following error:

```
error[E0425]: cannot find function `serve` in crate `axum`
  --> src/main.rs:19:11
   |
19 |     axum::serve(listener, app).await.unwrap();
   |           ^^^^^ not found in `axum`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `hello-world` due to previous error
```

I tried this code:

```
cargo new hello-world
cd hello-world
cargo add tokio --features macros --features rt-multi-thread
cargo add axum --features tokio
```

Then paste the hello-world example inside this repo into `src/main.rs` and run `cargo run`.

**Comment by davidpdrsn** [comment]
![image](https://github.com/tokio-rs/axum/assets/718941/80445904-dad1-4831-ae72-8ce06c430672)

**Comment by merlindru** [comment]
axum::serve is for the 0.7 docs!

For 0.6, check out this example:

https://docs.rs/axum/0.6.18/axum/index.html#example

```rust
#[tokio::main]
async fn main() {
    // build our application with a single route
    let app = Router::new().route("/", get(|| async { "Hello, World!" }));

    // run it with hyper on localhost:3000
    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}
```

**Comment by tsal** [comment]
Nice. Way to ensure no one wants to use this framework by being a dick @davidpdrsn -- I will never recommend anyone use or contribute to anything you or Embark touches as a result of your lack of empathy for developers running into a breaking change that was - _at best_ - poorly documented, and at worst, obfuscated behind excuses of "you should know" or "read the source code" or utterly pointless image-posting-tantrums like in this case.

You want people to use your framework, then you need to actually pay attention to the user's needs at a VERY minimal level, and you couldn't even do the bare minimum here.

**Comment by jplatte** [comment]
@tsal I understand that you're not happy, but lashing out like that does nobody a favor.

Being an open source maintainer is often thankless work and getting many of the same questions or feature requests over and over can be very tiring. That's no excuse for being an ass, but actually I have never seen David use such a negative tone as you just did.

If you want to let somebody know they could have been more friendly, follow that same standard and do it in a friendly manner. If you want to vent, do so to your friends.

**Comment by tsal** [comment]
> @tsal I understand that you're not happy, but lashing out like that does nobody a favor.
> 
> Being an open source maintainer is often thankless work and getting many of the same questions or feature requests over and over can be very tiring. That's no excuse for being an ass, but actually I have never seen David use such a negative tone as you just did.
> 
> If you want to let somebody know they could have been more friendly, follow that same standard and do it in a friendly manner. If you want to vent, do so to your friends. 

I get the frustration, but the image was clearly meant to insult the intelligence of someone asking for help with a change that was poorly documented. I wasn't the target of said image but it was insulting to see it used in this manner by someone who is a representative of this project. 

My tone is returning the insult the image intended. 

Or put another way: you may say my comment is off topic or too harsh, but nothing I said was untrue. That image is clearly meant to hurt someone.

**Comment by tsal** [comment]
Deleting my follow up reply only makes it worse.  Now it's even clearer you don't want a positive community here.
