### ISSUE TITLE
Having compile time issues? Post here!

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#200]
Crates should not be slow to compile due to axum. If you're having compile issues please post a reproduction script here so we can fix it!

Note that compiles have been improved for the upcoming 0.2 release. If you're having issues try depending directly on `main`.

## Known issues

These are the currently known compile time issues:

- A lot of chained `.route(...)` calls that ends in `.boxed()` can be slow to compile. We believe this is a rustc bug and don't have a fix for it in axum. See https://github.com/tokio-rs/axum/issues/200#issuecomment-942066491 for a possible workaround.
- Calling `Handler::layer` multiple times to add several middleware. See https://github.com/tokio-rs/axum/issues/200#issuecomment-928892100. Note that using `tower::ServiceBuilder` fixes the issue and is the recommended way to add multiple middleware.
- https://github.com/tokio-rs/axum/issues/399

**Comment by sindreij** [comment]
I get really slow compile times when using `boxed()`. The compile-time is dependent on the number of routes, the more the worse the compile-time is.

In my real production-app, the compile time goes from 3 seconds to around a minute when using boxed.

I have a small reproduction here, where the effect is a bit less, but it still takes 10 seconds to compile (and 0.5 seconds without boxed).

https://github.com/sindreij/boxed-slow-axum

**Comment by paulzhang5511** [comment]
Every time i change the code, the compilation is very slow.

![image](https://user-images.githubusercontent.com/53463972/130207517-c568e90c-3203-4020-af4f-77ad04b5d39c.png)

Example:

https://github.com/paulzhang5511/axum-compile-slow

**Comment by sindreij** [comment]
@davidpdrsn My bad, it's still slow. I have updated my original post.

**Comment by sindreij** [comment]
I also get a similar slowness when using nest also when the router is not boxed.

**Comment by davidpdrsn** [comment]
Compile times improve when we remove the trait bounds from the methods like `route` and `nest`. I'm gonna make a PR that does that later today.

However we cannot remove the bounds from `boxed` because they're necessary for boxing. So sadly nothing we can do there. Its a rustc bug apparently. I think we should investigate making a minimal reproduction script and filing an issue for rust.

**Comment by sindreij** [comment]
Okay, thanks. Until it's fixed, I work around it by defining all the routes in one place.

And btw, thanks for a great framework, it's really nice to use.

**Comment by davidpdrsn** [comment]
@paulzhang5511 I just merged https://github.com/tokio-rs/axum/pull/220 which should help with your issue, if you remove `.boxed()` which is still problematic as mentioned above. Honestly not sure thats something we can fix in axum 😕

**Comment by ufoscout** [comment]
FYI, another workaround is also to declare all routes as `.boxed()`.

E.g., this takes years to compile:
```rust
    let app = Router::new()
        .route("/a", get(get_a))
        .route("/a", get(get_a))
        .route("/a", get(get_a))
        .route("/a", get(get_a))
        .route("/a", get(get_a))
        .route("/a", get(get_a))
        .route("/a", get(get_a))
        .route("/a", get(get_a))
        .route("/a", get(get_a))
        .route("/a", get(get_a))
        .route("/a", get(get_a))
        .route("/a", get(get_a)).boxed();
```

and this is extremely fast:
```rust
    let app = Router::new()
        .route("/a", get(get_a)).boxed()
        .route("/a", get(get_a)).boxed()
        .route("/a", get(get_a)).boxed()
        .route("/a", get(get_a)).boxed()
        .route("/a", get(get_a)).boxed()
        .route("/a", get(get_a)).boxed()
        .route("/a", get(get_a)).boxed()
        .route("/a", get(get_a)).boxed()
        .route("/a", get(get_a)).boxed()
        .route("/a", get(get_a)).boxed()
        .route("/a", get(get_a)).boxed()
        .route("/a", get(get_a)).boxed();
```

BTW, I am not sure whether it has any runtime performance hit.

**Comment by davidpdrsn** [comment]
> BTW, I am not sure whether it has any runtime performance hit.

It will have some perf impact but exactly how big I don't know. That'd require benchmarking which I haven't done.

**Comment by nicrgren** [comment]
After a great experience testing axum out by converting some of my warp based projects I ran into this problem with boxed(), and its a real blocker for me.

The problem is that boxed() is required for testing - since I need to be able to specify a type in order to get a Router against which I can run my tests.

Sorry if I'm missing something obvious here :)

**Comment by Z4RX** [comment]
@nicrgren you can add boxed() for every route. It s a bit annoying, but it remove compiler issue. And I don't feel that it's critically affect performance

**Comment by davidpdrsn** [comment]
@nicrgren yes this is unfortunate. Here is a workaround:

```rust
use axum::{
    handler::{get, post},
    routing::BoxRoute,
    Json, Router,
};
use tower_http::trace::TraceLayer;

#[tokio::main]
async fn main() {
    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], 3000));
    let listener = std::net::TcpListener::bind(addr).unwrap();
    run(listener).await;
}

async fn run(listener: std::net::TcpListener) {
    let app = Router::new()
        .route("/", get(|| async { "Hello, World!" }))
        .route(
            "/json",
            post(|payload: Json<serde_json::Value>| async move {
                Json(serde_json::json!({ "data": payload.0 }))
            }),
        )
        // We can still add middleware
        .layer(TraceLayer::new_for_http());

    let addr = listener.local_addr().unwrap();
    tracing::debug!("listening on {}", addr);

    axum::Server::from_tcp(listener)
        .unwrap()
        .serve(app.into_make_service())
        .await
        .unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::Body;
    use axum::http::{self, Request, StatusCode};
    use serde_json::{json, Value};
    use std::net::{SocketAddr, TcpListener};

    // You can also spawn a server and talk to it like any other HTTP server:
    #[tokio::test]
    async fn a_test() {
        let listener = TcpListener::bind("0.0.0.0:0".parse::<SocketAddr>().unwrap()).unwrap();
        let addr = listener.local_addr().unwrap();

        tokio::spawn(run(listener));

        let client = hyper::Client::new();

        let response = client
            .request(
                Request::builder()
                    .uri(format!("http://{}", addr))
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        let body = hyper::body::to_bytes(response.into_body()).await.unwrap();
        assert_eq!(&body[..], b"Hello, World!");
    }
}
```

**Comment by nicrgren** [comment]
@Z4RX Yeah, that's also a good solution. I'll try it out. Thanks for helping out!

@davidpdrsn thanks so much! I'll try it out

**Comment by sunli829** [comment]
This code compiles very slowly. When the memory usage of `rustc` reaches 20G, I stop compiling.

```rust
    async fn handler() -> &'static str {
        "hello"
    }

    let service = axum::handler::get(
        handler
            .layer(axum::AddExtensionLayer::new(1))
            .layer(axum::AddExtensionLayer::new((1, 1)))
            .layer(axum::AddExtensionLayer::new((1, 1, 1)))
            .layer(axum::AddExtensionLayer::new((1, 1, 1, 1)))
            .layer(axum::AddExtensionLayer::new((1, 1, 1, 1, 1)))
            .layer(axum::AddExtensionLayer::new((1, 1, 1, 1, 1, 1)))
            .layer(axum::AddExtensionLayer::new((1, 1, 1, 1, 1, 1, 1)))
            .layer(axum::AddExtensionLayer::new((1, 1, 1, 1, 1, 1, 1, 1))),
    );
```

**Comment by davidpdrsn** [comment]
@sunli829 good catch! Thats is worth investigating.

It works and compiles instantly using `tower::ServiceBuilder` (which I personally prefer for adding multiple middleware anyway):

```rust
Router::new().route(
    "/",
    get(handler.layer(
        ServiceBuilder::new()
            .layer(AddExtensionLayer::new(1))
            .layer(AddExtensionLayer::new((1, 1)))
            .layer(AddExtensionLayer::new((1, 1, 1)))
            .layer(AddExtensionLayer::new((1, 1, 1, 1)))
            .layer(AddExtensionLayer::new((1, 1, 1, 1, 1)))
            .layer(AddExtensionLayer::new((1, 1, 1, 1, 1, 1)))
            .layer(AddExtensionLayer::new((1, 1, 1, 1, 1, 1, 1)))
            .layer(AddExtensionLayer::new((1, 1, 1, 1, 1, 1, 1, 1)))
            .into_inner(),
    )),
);
```

This compiles in 0.2 seconds on my machine.

Would still be worth investing what you posted though.

**Comment by sunli829** [comment]
> This compiles in 0.2 seconds on my machine.
> 
> Would still be worth investing what you posted though.

Thank you for your answer. I realized that my `rustc` version is `rustc 1.56.0-nightly`. When I switched to `rustc 1.54.0`, the memory leak disappeared and the compilation was completed quickly. 😁

**Comment by davidpdrsn** [comment]
I'll close this now since 0.3 is out and fixed all issues mentioned here. If someone still has compile time issues I'd *very* interested to hear about it.
