### ISSUE TITLE
Allow multiple TypedPaths to be defined on single struct

### ISSUE THREAD

**Issue by maxwell8888** [tokio-rs/axum#2007]
- [y] I have looked for existing issues (including closed) about this

## Feature Request
As far as I can tell, the below is not allowed since I get `thread 'main' panicked at 'Overlapping method route.` when I run my application with something similar.
```rust
#[derive(TypedPath, Deserialize)]
#[typed_path(
    "/foos/:foo_name",
    "/foos/:foo_name/delete",
    "/foos/:foo_name/create",
    "/foos/:foo_name/update"
)]
struct Foo {
    foo_name: String,
}
```

### Motivation

In my application, many paths deseralize to the same type. It makes the application unintuitive and verbose to have to redefine the same type multiple times with different names.

### Proposal

I have no idea how feasible this is as a feature.

### Alternatives

Define new structs for every path:
```rust
#[derive(TypedPath, Deserialize)]
#[typed_path("/foos/:foo_name")]
struct Foo {
    foo_name: String,
}

#[derive(TypedPath, Deserialize)]
#[typed_path("/foos/:foo_name/delete")]
struct DeleteFoo {
    foo_name: String,
}

#[derive(TypedPath, Deserialize)]
#[typed_path("/foos/:foo_name/create")]
struct CreateFoo {
    foo_name: String,
}
#[derive(TypedPath, Deserialize)]
#[typed_path("/foos/:foo_name/update")]
struct UpdateFoo {  
    foo_name: String,
}
```

**Comment by davidpdrsn** [comment]
Yeah I don't think is much better than what we have now. Technically `TypedPath` is a regular trait that you can implement yourself. That's generally not recommended but is possible. Maybe you could try that?

**Comment by maxwell8888** [comment]
Ok, thanks for the feedback. Probably worth closing in that case.

Just to make sure my use case is clear, I would like to be able to define methods on the structs which I can then resuse in different handlers.
In the below for example, methods which return the `Uri` for other paths which I can use in handlers to create the links in a web application, and I obviously want to avoid having to implement the exact same methods on duplicate structs.
```rust
#[derive(TypedPath, Deserialize)]
#[typed_path("/foos/:foo_name")]
struct Foo {
    foo_name: String,
}
impl Foo {
    fn bar_uri(&self, bar_name: String) -> Uri {
        let bar = Bar {
            foo_name: self.foo_name.clone(),
            bar_name,
        };
        bar.to_uri()
    }
}

#[derive(TypedPath, Deserialize)]
#[typed_path("/foos/:foo_name/update")]
struct UpdateFoo {
    foo_name: String,
}
impl UpdateFoo {
    fn bar_uri(&self, bar_name: String) -> Uri {
        let bar = Bar {
            foo_name: self.foo_name.clone(),
            bar_name,
        };
        bar.to_uri()
    }
}

#[derive(TypedPath, Deserialize)]
#[typed_path("/foos/:foo_name/bars/:bar_name")]
struct Bar {
    foo_name: String,
    bar_name: String,
}
impl Bar {
    fn foo_uri(&self) -> Uri {
        let foo = Foo {
            foo_name: self.foo_name.clone(),
        };
        foo.to_uri()
    }
}
```
