### ISSUE TITLE
`()` should not implement `IntoResponse`

### ISSUE THREAD

**Issue by dullbananas** [tokio-rs/axum#2026]
The implementation of `IntoResponse` for `()` makes it easy to accidentally make a function return an empty response by putting a semicolon after the return value if the return type is `impl IntoResponse`.

I made this mistake here: https://codeberg.org/dullbananas/font-generator/commit/4a664035a58e1f2c85fb91989b4f7058a1e3e776 and fixed it here: https://codeberg.org/dullbananas/font-generator/commit/5f0d59ba7f361ffb56376f94694381b013b11d3b

It took a while to notice that I broke this part of my app. Once I noticed it, it was very hard to figure out the cause of the problem.

**Comment by avdb13** [comment]
You make a very good point there. Are you using `clippy` and did it by any chance throw any warnings?

**Comment by jplatte** [comment]
Clippy doesn't warn in this situation.

**Comment by dullbananas** [comment]
I made the mistake when trying to fix this: https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return

**Comment by ttys3** [comment]
I think this is a good suggestion.

**Comment by TmLev** [comment]
To make it even more safe, you can use concrete return type instead of `impl IntoResponse`

**Comment by ttys3** [comment]
> To make it even more safe, you can use concrete return type instead of `impl IntoResponse`

But you need that if you need return diff tyoes

**Comment by TmLev** [comment]
It won't help with different return types in different control flow branches. `-> impl Trait` is just a shortcut for one concrete type.

**Comment by davidpdrsn** [comment]
We generally don't recommend `impl IntoResponse` (https://docs.rs/axum/latest/axum/response/index.html#regarding-impl-intoresponse) and all built in responses have `#[must_use]` which warns against it.

I personally like `impl IntoResponse for ()` so I think we should keep that.
