### ISSUE TITLE
Remove `unwrap`s from examples, where feasible

### ISSUE THREAD

**Issue by erlangparasu** [tokio-rs/axum#2039]
### Motivation
For production ready sample

**Comment by davidpdrsn** [comment]
Which examples?

**Comment by erlangparasu** [comment]
@davidpdrsn All examples :)

**Comment by Ptrskay3** [comment]
Well, I'm not sure I agree.

The examples generally are to show you how does a particular feature works, and not supposed to teach you Rust basics about error handling or other miscellaneous topics. Making all the examples production ready and robust would take the focus away from the actual feature it tries to present. 

If you're looking for a more advanced code sample, take a look at [realworld-axum-sqlx](https://github.com/launchbadge/realworld-axum-sqlx) for example.

**Comment by Altair-Bueno** [comment]
> The examples generally are to show you how does a particular feature works, and not supposed to teach you Rust basics about error handling or other miscellaneous topics. Making all the examples production ready and robust would take the focus away from the actual feature it supposed to present.

Unfortunately, people are used to just copy/paste and carry on with their lives. [We already make sure the right status codes are being used for this exact reason](https://github.com/tokio-rs/axum/pull/1276#discussion_r949514713), so I would consider this request sensible. Also, a more rusty (but basic) error handling can be archived with `Box<dyn Error>` and the question mark operator. At least the compiler would be able to check silly panics in case of copy/paste.

Thankfully there are "only" 271 instances of unwrap/expect around the examples dir. rustdoc examples should be changed too, which im afraid I don't have a regex around to count them. I would consider this to be a low priority, good first issue to leave open and let someone pick up.

<details><summary>Grep command for examples dir</summary>
<p>

```sh
$ grep -rnw 'examples' -e '\(unwrap\|expect\)(' | wc -l
271
```

</p>
</details>

**Comment by davidpdrsn** [comment]
The goal of the examples is not to showcase production ready setups. Like people have mentioned that's would make the examples much less focused on what they're actually trying to show.

With that said, there are probably some unwraps that could be removed. Happy to take PRs that cleans that up!

**Comment by davidpdrsn** [comment]
I have removed some unnecessary unwraps from example-stream-to-file and example-reverse-proxy. There are still some left in example-oauth that would be nice to clean up. So if someone wants to submit a PR that'd be much appreciated.

The remaining examples are fine so I'll close this for now.

@erlangparasu if there are any specific examples you want clarity on please open a new issue and be specific about what you'd like to see clarified.

**Comment by erlangparasu** [comment]
Thanks!

**Comment by rsdlt** [comment]
> 

I'll be happy to clean the `unwraps` in the `example-oauth` file. Cheers.
