### ISSUE TITLE
Consider adding TryFrom<&Uri> for Query

### ISSUE THREAD

**Issue by CosmicHorrorDev** [tokio-rs/axum#2048]
- [x] I have looked for existing issues (including closed) about this

## Feature Request

Consider adding `impl TryFrom<&Uri> for axum::extract::Query`

### Motivation

I was porting a project from `rocket` and `axum` and accidentally regressed some endpoints from differences in query parsing. It would have been nice to have a simple way to test the query parsing in isolation, but the simplest solution I could come up with was to just copy the internals of `Query`'s `FromRequestParts`

### Proposal

Move the logic from `Query`'s `FromRequestParts` implementation into `TryFrom<&Uri> for Query` and call `Query::try_from(&parts.uri)` in `from_request_parts()`

Only drawback I can think of is that this adds some slight noise to the API

### Alternatives

None that seem compelling

**Comment by davidpdrsn** [comment]
Sure! That sounds like a fine addition to me.

**Comment by davidpdrsn** [comment]
Fixed in https://github.com/tokio-rs/axum/pull/2058
