### ISSUE TITLE
Retrieve list missing fields from JsonRejection

### ISSUE THREAD

**Issue by hongquan** [tokio-rs/axum#2060]
- [x] I have looked for existing issues (including closed) about this

### Motivation

I'm building a RESTful API server with axum and need to show validation error detail about which fields are missing. Howver, using `axum::Json` extractor, I cannot have this information.

The purpose is to show on frontend, under each form field which user forgot to input data.

### Proposal

No.

### Alternatives

No.

**Comment by davidpdrsn** [comment]
You need to access the inner serde_json::Error and get whatever you need from it. More details here https://docs.rs/axum/latest/axum/extract/index.html#accessing-inner-errors

**Comment by davidpdrsn** [comment]
I remembered that Json also uses https://github.com/dtolnay/path-to-error. You can downcast the error to that which should give you more details.

**Comment by hongquan** [comment]
Thanks!
