### ISSUE TITLE
Provide IncomingStream::new

### ISSUE THREAD

**Issue by tetsuyainfra** [tokio-rs/axum#2064]
- [x] I have looked for existing issues (including closed) about this

### Motivation
To use http and non-http at same tcp port.

Currently in the main branch, the axum::serve function passes a TcpListener to accept TCP/IP connections.
By porting this function, we can create an application where http and non-http share the same port.

However, the IncomingStream structure cannot be instantiated from outside the axum library.

### Proposal
Create IncomingStream::new function. 
https://github.com/tetsuyainfra/axum/commit/85e16c3c621d23efd78300399cf620a89e591635

### Alternatives
I could think of no other approach.

**Comment by davidpdrsn** [comment]
I’d like to keep that API as minimal as possible so I’d recommend you use hyper or hyper-util directly instead.
