### ISSUE TITLE
Route conflict although they define different segments

### ISSUE THREAD

**Issue by hongquan** [tokio-rs/axum#2079]
- [x] I have looked for existing issues (including closed) about this

## Bug Report

I tried to add routes as:

```rust
Router::new()
.route("/blog/:year/:month/:id_and_slug", get(views::old_urls::redirect_old_post_view))
.route("/blog/:cat_slug", get(views::old_urls::redirect_old_category_view))
```
but axum panics:

```
thread 'main' panicked at 'Invalid route "/blog/:cat_slug": insertion failed due to conflict with previously registered route: /blog/:year/:month/:id_and_slug', src/front/routes.rs:16:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
### Version

├── axum v0.6.18
│   ├── axum-core v0.3.4
│   ├── axum-macros v0.3.7 (proc-macro)
├── axum-extra v0.7.4
│   ├── axum v0.6.18 (*)
│   ├── axum-core v0.3.4 (*)
│   ├── axum-macros v0.3.7 (proc-macro) (*)
├── axum-login v0.5.0
│   ├── axum v0.6.18 (*)
│   ├── axum-sessions v0.5.0
│   │   ├── axum v0.6.18 (*)
│   │   ├── axum-extra v0.7.4 (*)
├── axum-sessions v0.5.0 (*)
├── axum_garde v0.11.2
│   ├── axum v0.6.18 (*)
│   ├── axum-extra v0.7.4 (*)
│   ├── axum v0.6.18 (*)

### Platform

Linux DeskMini 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jplatte** [comment]
Known issue in the routing library used by axum: https://github.com/ibraheemdev/matchit/issues/13

**Comment by davidpdrsn** [comment]
Yep it’s a matchit bug. Nothing axum can do unfortunately.

**Comment by hongquan** [comment]
How about replacing matchit with this lib https://github.com/viz-rs/path-tree?
Matchit's author seems not willing to fix this bug.
