### ISSUE TITLE
Add JsonRPC support or good example

### ISSUE THREAD

**Issue by dayvejones** [tokio-rs/axum#2087]
I think it would be a very useful feature to add a JSON-RPC support. JSON-RPC defines several data structures and the rules around their processing.

https://www.jsonrpc.org/specification

If the Axum can make it easier to work with this, then it will be great. Maybe it's possible to add special extractors/responses or something else. Even just adding adding a 'best practice' example to the /examples/  rep folder would be great 😊

### Alternatives

https://github.com/paritytech/jsonrpsee/tree/master/examples/examples

thanks!

**Comment by davidpdrsn** [comment]
JSON RPC support can be added via an external crate. It doesn't need to be built-in. I did a quick search and found https://crates.io/crates/axum-jrpc. Maybe that works for you?
