### ISSUE TITLE
Streaming/Chunked Response Performance

### ISSUE THREAD

**Issue by Clueliss** [tokio-rs/axum#2107]
- [x] I have looked for existing issues (including closed) about this

### Version
```
$ cargo tree | grep axum
├── axum v0.6.18
│   ├── axum-core v0.3.4
│   ├── axum-macros v0.3.7 (proc-macro)
```

### Platform
```
$ uname -a
Linux lpf-main 6.3.12-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul  6 04:05:18 UTC 2023 x86_64 GNU/Linux
```

### Description
Hello there,
we are trying to figure out chunked HTTP responses and have observed performance issues when the server is
loaded with just a few clients (< ~12) which each sends some number of requests. This issue seems to disappear once the server is properly loaded with more clients.

We have two routes: one regular and one streaming. Both routes to basically the same thing; the streaming route is basically just indented for cases where responses get very large. The following code is a sketch of how the routes roughly look like.
```rust
async fn regular_route(query: String) -> Response {
    let (tx, rx) = tokio::sync::oneshot::channel();

    rayon::spawn(move || {
        let mut buf = Vec::with_capacity(16 * 4096);
        // some potentially expensive work here (not async)
        // is in different thread to not block the executor
        tx.send(buf);
    });
    
    let res = rx.recv().await.unwrap();
    res.into_response()
}

async fn streaming_route(query: String) -> Response {
    let (tx, rx) = tokio::sync::mpsc::channel();

    rayon::spawn(move || {
        // some potentially expensive work here, including serialization
        let mut buf = Vec::with_capacity(16 * 4096);
        loop {
            // potentially expensive work here
            // then write chunk of calculated data into buf

            if buf.len() >= 16 * 4096 {
                tx.send(std::mem::replace(&mut buf, Vec::with_capacity(16 * 4096)));
            }
        }

        tx.send(buf);
    });
    
    StreamBody::new(tokio_stream::wrappers::UnboundedReceiverStream::new(rx))
}
```

While the performance of the regular route is very good the streaming route is roughly 8 times slower on the same requests.
As of right now we have no idea why it behaves this way. We would have expected a slight performance decrease but certainly not that much. Especially because an otherwise equivalent server in C++ (using restinio) does not have this large performance gap between streaming and regular routes. (Note: axum outperforms restinio basically everywhere except this one special case: few clients + streaming route)

If you have any insights for us that would be greatly appreciated.
Have a nice day.

**Comment by davidpdrsn** [comment]
Can you reproduce that using hyper directly, without axum?

**Comment by Clueliss** [comment]
> Can you reproduce that using hyper directly, without axum?

Good point, will try that

**Comment by jplatte** [comment]
Closing in favor of the hyper issue then.
