### ISSUE TITLE
A axum::routing:: post better documentation!

### ISSUE THREAD

**Issue by ruizdiazever** [tokio-rs/axum#2111]
Dear Colleagues,

I hope you are all having a productive day. I am writing to you to emphasize the importance of proper documentation in our daily work. We are all aware that our workload is considerable and that we face new challenges every day. However, taking the time to clearly and completely document our tasks and projects has a significant impact on our efficiency and the quality of our work.

**Comment by jplatte** [comment]
This is not a useful issue, you are *implying* that the existing documentation is somehow not clear or complete, yet you don't provide *any* details.
