### ISSUE TITLE
Support derive FromRef for wrapper structures

### ISSUE THREAD

**Issue by belovaf** [tokio-rs/axum#2114]
## Feature Request
Support derive FromRef for wrapper structures like this: `StateWrapper(Arc<AppState>) `. 

### Motivation
Now we have to implement `FromRef` for each `AppState` field manually. This is inconvinient.

### Proposal
Extend macro logic to support this common case.

**Comment by davidpdrsn** [comment]
Does https://docs.rs/axum/latest/axum/extract/derive.FromRef.html not work you?

**Comment by belovaf** [comment]
When I have a simple structure as a state all is great:
```
#[derive(Clone, FromRef)]
pub struct AppState {
    pub db_pool: PgPool,
    pub http_client: HttpClient,
}
```

But I noticed that a state is cloned many times during request processing. For large structures it feels very natural to wrap them with `Arc`:
```
#[derive(Clone, Deref)]
pub struct AppState(pub Arc<InternalState>);

pub struct InternalState {
    pub db_pool: PgPool,
    pub http_client: HttpClient,
}
```

But now I have to manually implement FromRef trait for each substate:
```
impl FromRef<AppState> for PgPool {
    fn from_ref(input: &AppState) -> Self {
        input.db_pool.clone()
    }
}

impl FromRef<AppState> for HttpClient {
    fn from_ref(input: &AppState) -> Self {
        input.http_client.clone()
    }
}
```

**Comment by davidpdrsn** [comment]
I see. I think it’s fine having to write that yourself. I don’t think I want to make the macro more complicated.

You can write your own declarative macro easily to take care of the boilerplate.

**Comment by davidpdrsn** [comment]
Proc macros also don’t know the fields of other structs. So it wouldn’t know the fields on InternalState

**Comment by belovaf** [comment]
Ok, thank you for your response.

Can this case be more convinient with additional "adapter" trait? `FromDeref` or something.

Am I doing right? I haven't see wrapped with `Arc` immutable state in examples.

I also tried Box::leak for state to make it static. Do you see any drowbacks of this?

**Comment by davidpdrsn** [comment]
> Can this case be more convinient with additional "adapter" trait? `FromDeref` or something.

I don’t think needing a second derive is worth writing the few lines of code yourself.

> Am I doing right? I haven't see wrapped with `Arc` immutable state in examples.

Yeah wrapping the state in an Arc is fine.

> I also tried Box::leak for state to make it static. Do you see any drowbacks of this?

Not besides making it harder to test.

**Comment by belovaf** [comment]
Can you elaborate why is it harder to test?
I mean not static global variable, but `with_state` with static lifetime reference.

Can you look at this example, is it ok?
It looks awkward, but with this approach it is possible to never clone a state and nested states.

```
struct AppState {
    db_pool: PgPool,
    http_client: HttpClient,
}

impl <'a> FromRef<&'a AppState> for &'a PgPool {
    fn from_ref(input: &&'a AppState) -> Self {
         // not cloning here!
        &input.db_pool
    }
}

impl <'a> FromRef<&'a AppState> for &'a HttpClient {
    fn from_ref(input: &&'a AppState) -> Self {
         // not cloning here!
        &input.http_client
    }
}

#[tokio::main]
async fn main() {
    // init db, http client, etc...

    let state: &'static AppState = Box::leak(Box::new(AppState {
        db_pool,
        http_client,
    }));
    
    let app = Router::new()
        .route("/", get(handler))
        .with_state(state);

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}

async fn health_check_handler(
    State(db_pool): State<&PgPool>,
    State(http_client): State<&HttpClient>,
) -> impl IntoResponse {
    StatusCode::OK
}

```

**Comment by davidpdrsn** [comment]
That’s fine. Thought you meant to make it a global.

I wouldn’t worry about cloning the state honestly. Any amount of network traffic is orders of magnitude slower.

**Comment by belovaf** [comment]
Thank you very much for so fast responses and the great framework!
