### ISSUE TITLE
examples of middleware using hyper, but hyper has no re-export in axum

### ISSUE THREAD

**Issue by sassman** [tokio-rs/axum#2120]
- [x] I have looked for existing issues (including closed) about this

There was a conversation in #205 going on to remove hyper from axum's public API. 
I guess The issue I'm going to describe is a left over / corner case.

### Version

```raw
❯ cargo tree | grep axum
├── axum v0.6.18
│   ├── axum-core v0.3.4
├── axum v0.6.18 (*)
├── axum-extra v0.6.0
│   ├── axum v0.6.18 (*)
│   ├── axum v0.6.18 (*)
├── axum-macros v0.3.7 (proc-macro)
├── axum v0.6.18 (*)
```

### Platform

Darwin XM7NDJ005Y 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

### Description

There are cases where you want to consume the body in a middleware.
E.g. There is this example:

https://github.com/tokio-rs/axum/blob/5567d665d7c5f0ed09e1d5c588c18c28751f23e1/examples/consume-body-in-extractor-or-middleware/src/main.rs#L54

So the Problem that I have is, that I cannot turn a body into their bytes without having hyper as direct dependency.

There are 2 possibilities that would reduce my pain:

- have a method `.to_bytes()` on the Body directly, where the details of using hyper to do so are hidden away [that would be my preference]
- re-export maybe only the method `hyper::body::to_bytes` from axum, so that I don't need to define the hyper dependency myself for that use case

**Comment by davidpdrsn** [comment]
Just add a dependency on hyper yourself.

I don’t think adding more re-exports is worth it. It’s all gonna change for hyper and http-body 1.0 anyways.
