### ISSUE TITLE
More principled error handling in the examples

### ISSUE THREAD

**Issue by lnicola** [tokio-rs/axum#217]
### Motivation

Error handling is an important part of an application, and it's not always obvious what approach to use.

### Proposal

I think it's desirable to:

- return internal errors (can't connect to the database etc.) as 500 errors
- (arguably) not panic on configuration errors (a misconfigured route shouldn't bring down the whole app)
- make sure that every error is logged
- show how to mix custom error types with rejections
  - consider a session extractor using a database backing store: how should it handle database errors? They come as `Error`s, but need to be turned into a `Rejection`
  - maybe not always, but it's sometimes useful to return different `Body` types (`Empty` vs. `Full` vs. `Body` vs. `BoxBody`)
- probably others too, I'm not sure right now

### Alternatives

- do nothing: the examples are here to teach how to get started with `axum`, not how to structure a larger application
- have a single, complex example with a larger app that does everything right, and happily panic in the other ones

**Comment by davidpdrsn** [comment]
I think we should follow the points you mention, without going overboard.

**Comment by davidpdrsn** [comment]
Its been a while and https://github.com/tokio-rs/axum/blob/main/examples/error-handling-and-dependency-injection/src/main.rs have been able to clear up most questions we have gotten regarding error handling. I don't remember getting specific questions that the points here addresses. So I think we should just leave things as they are.
