### ISSUE TITLE
Why is the `Typed Headers` feature flag not in the official release?

### ISSUE THREAD

**Issue by vallezw** [tokio-rs/axum#2181]
This is the [lib.rs](https://github.com/tokio-rs/axum/blob/main/axum-extra/src/lib.rs) on GitHub
This is the [lib.rs](https://docs.rs/axum-extra/0.7.7/src/axum_extra/lib.rs.html#1-118) in which was released.

My question is when it will be officially released, since your [jwt example](https://github.com/tokio-rs/axum/blob/main/examples/jwt/Cargo.toml) is dependent on it?

**Comment by davidpdrsn** [comment]
Remember to always check the examples for the version you're using https://github.com/tokio-rs/axum/blob/axum-v0.6.20/examples/jwt/Cargo.toml

As noted in the readme the `main` branch has breaking changes.

**Comment by vallezw** [comment]
Ahh alright thanks @davidpdrsn
