### ISSUE TITLE
Router::into_make_service doesn't compile unless with_state is called last

### ISSUE THREAD

**Issue by selfhoster1312** [tokio-rs/axum#2182]
It took me quite a bit of hair pulling to figure this out. When calling `with_state` before `route` or `nest` the compilation fails with:

```
error[E0599]: no method named `into_make_service` found for struct `Router<Foo, _>` in the current scope
  --> src/main.rs:17:20
   |
17 |         .serve(app.into_make_service())
   |                    ^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `route_service`
```

The error message is not informative.

Doesn't work:

```
    let app = Router::new()
        .with_state(shared_state)
        .route("/", get(handler));
```

Works:

```
    let app = Router::new()
        .route("/", get(handler))
        .with_state(shared_state);
```

I don't think this is documented yet. I don't know if this should be fixed somehow.

Minimum reproduction case:

```
use axum::extract::State;

#[tokio::main]
async fn main() {
    let shared_state: u8 = 1;
    let app = axum::Router::new()
        .with_state(shared_state)
        .route("/", axum::routing::get(handler));

    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn handler(
    State(_state): State<u8>,
) {}
```

**Comment by davidpdrsn** [comment]
Not sure I'd call this a bug. It's more a consequence of how the implementation works. The router doesn't store the state itself directly. Instead when you call `with_state` it provides the state to all handlers and boxes them as `Box<dyn Service>`. Therefore the routes must be added first.

I don't think we need to change this but its worth documenting for sure. You're welcome to make a PR.
