### ISSUE TITLE
Cannot use wrapped JSON Extractor for responses based on derive_from_request example

### ISSUE THREAD

**Issue by lennart** [tokio-rs/axum#2186]
The code in the [custom-extractor-error example](https://github.com/tokio-rs/axum/blob/52a90390195e884bcc12ff5bd9fd805cac806447/examples/customize-extractor-error/src/derive_from_request.rs#L21) for deriving `FromRequest` for a custom wrapper Json extractor does not compile as soon as one removes the semicolon in the handler (i.e. actually returning the response that is created from `Json(dbg!(value))`):

```rust
pub async fn handler(Json(value): Json<Value>) -> impl IntoResponse {
    Json(dbg!(value))
}
```

```
error[E0277]: the trait bound `derive_from_request::Json<serde_json::Value>: IntoResponse` is not satisfied
  --> examples/customize-extractor-error/src/derive_from_request.rs:20:69
   |
20 |   pub async fn handler(Json(value): Json<Value>) -> impl IntoResponse {
   |  _____________________________________________________________________^
21 | |     Json(dbg!(value))
22 | | }
   | |_^ the trait `IntoResponse` is not implemented for `derive_from_request::Json<serde_json::Value>`
   |
   = help: the following other types implement trait `IntoResponse`:
             &'static [u8; N]
             &'static [u8]
             &'static str
             ()
             (R,)
             (Response<()>, R)
             (Response<()>, T1, R)
             (Response<()>, T1, T2, R)
           and 133 others

error[E0277]: the trait bound `derive_from_request::Json<serde_json::Value>: IntoResponse` is not satisfied
  --> examples/customize-extractor-error/src/derive_from_request.rs:20:51
   |
20 | pub async fn handler(Json(value): Json<Value>) -> impl IntoResponse {
   |                                                   ^^^^^^^^^^^^^^^^^ the trait `IntoResponse` is not implemented for `derive_from_request::Json<serde_json::Value>`
   |
   = help: the following other types implement trait `IntoResponse`:
             &'static [u8; N]
             &'static [u8]
             &'static str
             ()
             (R,)
             (Response<()>, R)
             (Response<()>, T1, R)
             (Response<()>, T1, T2, R)
           and 133 others

For more information about this error, try `rustc --explain E0277`.
```

Is this intentional? It seems the wrapped extractor does not implement `IntoResponse` and can therefore not be used in the same way as `axum::Json`. Should one still use `axum::Json` in this case for the responses in handlers and only the wrapped one as an extractor?

**Comment by jplatte** [comment]
I think the right fix here would be to implement `IntoResponse` for the custom `Json` type in the example, like this or similar:

```rust
impl<T: Serialize> IntoResponse for Json<T> {
    fn into_response(self) -> Response {
        let Self(value) = self;
        axum::Json(value).into_response()
    }
}
```

**Comment by lennart** [comment]
@jplatte yes, that works, thank you! I didn't start to write my own implementation for the trait as I thought it was supposed to be derived as well via `derive(FromRequest)`.

Is there a reason why the demo handler in the uses `Json` at all to wrap the call to `dbg!`? It seems `dbg!` is currently only used for its side-effects (i.e. printing to the console) as the handler does not return any content via http.

**Comment by jplatte** [comment]
I really don't know. I think a custom `Json` type example should show an `IntoResponse` impl as well though, so it's a proper replacement for `axum::Json`.

**Comment by davidpdrsn** [comment]
Yeah I think it's fine to add an `IntoResponse` impl to the example. @lennart do you wanna add a PR for that?

**Comment by lennart** [comment]
@davidpdrsn I added a PR https://github.com/tokio-rs/axum/pull/2191 with a small comment and the mentioned impl from @jplatte 

I did not modify the impl, it _just works_. Is there anything else necessary?
