### ISSUE TITLE
Update Hyper Dependency To Address Slow Shutdown Times

### ISSUE THREAD

**Issue by bonedaddy** [tokio-rs/axum#2215]
Previously https://github.com/tokio-rs/axum/issues/991 detailed an issue with very long service shutdown times, ultimately due to a bug in `hyper`. A fix was recently introduced into hyper (https://github.com/hyperium/hyper/commit/f4b513009d81083081d1c60c1981847bbb17dd5d) , however it is only available in a release candidate with breaking changes. I have submitted an issue on the hyper repository requesting a backport to a non breaking change release https://github.com/hyperium/hyper/issues/3306

**Comment by davidpdrsn** [comment]
Nothing that axum can du about this. We can’t update to a breaking release yet, though the main branch is moving towards that.

**Comment by davidpdrsn** [comment]
Forgot to say that we also have an example that shows to run the recurrent version of axum with hyper 1.0 https://github.com/tokio-rs/axum/blob/axum-v0.6.20/examples/hyper-1-0/src/main.rs

**Comment by bonedaddy** [comment]
> Nothing that axum can do about this. We can’t update to a breaking release yet, though the main branch is moving towards that.

Ah yes apologies for any confusion, only intended to indicate  the fix for the original issue is available to be integrated when suitable as it was hard to tell through existing git issues whether there was a permanent fix.

> Forgot to say that we also have an example that shows to run the recurrent version of axum with hyper 1. https://github.com/tokio-rs/axum/blob/axum-v0.6.20/examples/hyper-1-0/src/main.rs

tyvm!
