### ISSUE TITLE
Overlapping routes with captures having different names panics

### ISSUE THREAD

**Issue by DMaxter** [tokio-rs/axum#2218]
- [X] I have looked for existing issues (including closed) about this

### Version

```
axum v0.6.20
├── axum-core v0.3.4
```

### Platform

Linux zirconium 6.4.12-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:37:46 +0000 x86_64 GNU/Linux

### Description

Cannot have 2 routes with different parameters and different methods, as I receive an error stating there is a conflict

I tried this code:

```rust
use axum::{
    routing::{post, put},
    Router, Server,
};

#[tokio::main]
async fn main() {
    Server::bind(&"0.0.0.0:8000".parse().unwrap())
        .serve(
            Router::new()
                .route("/:name", post(|| async {}))
                .route("/:id/:name", put(|| async {}))
                .into_make_service(),
        )
        .await
        .unwrap();
}
```
I expected to see no error, however, I got this: `Invalid route "/:id/:name": insertion failed due to conflict with previously registered route: /:name`

This is just a reproducer as in a real service, I use  `Path(id): Path<i64>` and `Path(name): Path<String>`, however, it still gives me the same error. Is this some kind of bug?

I looked at the MethodRouter and the issue that motivated its implementation, however MethodRouter doesn't seem to be the correct approach here, but correct me if I am misunderstood

**Comment by davidpdrsn** [comment]
This is because of https://github.com/ibraheemdev/matchit/issues/13. See that issue for a workaround.

Since it's a bug in one of axum's dependencies there isn't anything we can do about it. Though its hopefully going to be fixed in the next major version of axum (which will include the next major of matchit)

**Comment by DMaxter** [comment]
There is no workaround mentioned in that issue

**Comment by davidpdrsn** [comment]
Yes there is. 

> but only if they have a common prefix

**Comment by DMaxter** [comment]
Oh, missed that part, thanks a lot

**Comment by DMaxter** [comment]
https://github.com/ibraheemdev/matchit/issues/13 seems to have been fixed but I still get an error with overlapping routes

```Rust
use axum::{
    Router,
    routing::{post, put},
    serve,
};
use tokio::net::TcpListener;

#[tokio::main]
async fn main() {
    serve(
        TcpListener::bind("0.0.0.0:8080").await.unwrap(),
        Router::new()
            .route("/{name}", post(|| async {}))
            .route("/{id}", put(|| async {}))
            .into_make_service(),
    )
    .await
    .unwrap();
}
```

I get this time `Invalid route "/{id}": Insertion failed due to conflict with previously registered route: /{name}`, they are different routes, is there something we can do here?

**Comment by DMaxter** [comment]
https://github.com/ibraheemdev/matchit/issues/13 seems to have been fixed but I still get an error with overlapping routes

```Rust
use axum::{
    Router,
    routing::{post, put},
    serve,
};
use tokio::net::TcpListener;

#[tokio::main]
async fn main() {
    serve(
        TcpListener::bind("0.0.0.0:8080").await.unwrap(),
        Router::new()
            .route("/{name}", post(|| async {}))
            .route("/{id}", put(|| async {}))
            .into_make_service(),
    )
    .await
    .unwrap();
}
```

I get this time `Invalid route "/{id}": Insertion failed due to conflict with previously registered route: /{name}`, they are different routes, is there something we can do here?

**Comment by DMaxter** [comment]
I know, but they still are different, one is post one is put

**Comment by mladedav** [comment]
That's a different issue from the original and the matchit fix you linked.

Feel free to open a new issue, I'll try to look if we can make it work easily, but you'll have to use the same capture name in the meantime.

**Comment by eythaann** [comment]
@DMaxter did u created an issue? I'm having this exact same issue having different param name on `get` and `put` methods.

**Comment by DMaxter** [comment]
No, I haven't revisited the code that was triggering this issue, so I don't even know if I need a fix anymore
