### ISSUE TITLE
Is there a plan to update to `http-body 1.0-rcX`?

### ISSUE THREAD

**Issue by kkocdko** [tokio-rs/axum#2248]
- [x] I have looked for existing issues (including closed) about this

## Feature Request

https://github.com/tokio-rs/axum/blob/8854e660e9ab07404e5bb8e30b92311d3848de05/axum/Cargo.toml#L39-L55

But I can't see an issue about this, is there something blocks we to update to `http-body 1.0-rcX`?

### Motivation

Reducing dependencies.

**Comment by davidpdrsn** [comment]
Yes. See https://github.com/tokio-rs/axum/pull/1882. The primary blocker is updating tower-http.
