### ISSUE TITLE
Make extractors with Infallible rejection type more convenient

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#2249]
- [x] I have looked for existing issues (including closed) about this

### Motivation

Some extractors such as `CookieJar` use an `Infallible` rejection type. Currently, one has to use `.unwrap()` / `.expect("infallible")` / `.unwrap_or_else(|i| match i {})` after the actual extraction function call to get rid of it.

### Proposal

- Add `RequestPartsExt::extract_infallible` (and `extract_infallible_with_state` `RequestExt::extract_parts_infallible`, ...) for 0.7.x
- Consider renaming current `extract` methods on the extension traits to `try_extract` and removing the `_infallible` suffix for 0.8.x

### Alternatives

- Provide our own `ResultExt` with our own variant of [`Result::into_ok`](https://doc.rust-lang.org/std/result/enum.Result.html#method.into_ok).

### Open questions

Are body extractors ever infallible / does it make sense to provide `RequestExt::extract_infallible`?

**Comment by mladedav** [comment]
> Are body extractors ever infallible / does it make sense to provide RequestExt::extract_infallible?

`Body` itself is infallible as it pretty much just provides the underlying stream. Anything that actually collects the bytes would be fallible though. I don't think it makes much sense to add `extract_infallible` for that case though.

But it does make sense to me for request parts.

**Comment by ItsEthra** [comment]
I think this can be closed now since in the 1.82 you can just match the result with infallible https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html#omitting-empty-types-in-pattern-matching.

**Comment by jplatte** [comment]
Right. `let Ok(ex) = request.extract::<Extractor>();` seems like a very nice solution 👍🏼
