### ISSUE TITLE
ServeDir/ServeFile can fail to send the entire asset under concurrent load

### ISSUE THREAD

**Issue by tomjakubowski** [tokio-rs/axum#2256]
- [x] I have looked for existing issues (including closed) about this

### Version

Our application is using axum 0.6.19. I can also reproduce this from main with the `static-file-server` example

### Platform

Darwin secrethostname 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64

### Description

Our application serves some large static assets. We noticed some flakiness in Playwright tests which were connected to the assets not loading correctly. The red flag symptom is that the server's responses are incomplete and the actual length of the body does not match the Content-length header in the response.

It's easy to reproduce this with the built-in `static-file-server` example and using the handy [Apache Bench](tool) to launch the concurrent clients.

1. Write a big file to the example's asset folder. I'm using a 50,000,000 byte file of all zeroes.
2. `cargo run -p example-static-file-server --release` (also can reproduce in debug builds)
3. Run `ab -n 100 -c 15 'http://127.0.0.1:3001/assets/bigfile.txt'` to send 100 requests 15 at a time
4. Observe in the output that the Document Length (an average, I think? Or it might be the size of the most recently read response) does not equal 50000000, and also that of 100 requests 99 failed due to improper length.

```
Document Length:        14680064 bytes
...
Complete requests:      100
Failed requests:        99
   (Connect: 0, Receive: 0, Length: 99, Exceptions: 0)
```

Important note: sometimes (I would estimate ~25-50% of the time), the test will actually pass and all 100 requests will succeed. If that happens, run it again a few more times.

**Comment by tomjakubowski** [comment]
Attached is the full apache bench output

[ablog.txt](https://github.com/tokio-rs/axum/files/12835980/ablog.txt)

**Comment by jplatte** [comment]
Would be worth trying if this can be reproduced with just `tower-http`, no `axum`. [Here](https://github.com/jplatte/caniuse.rs/blob/1d56560caf33e474df142730a60aa844bd21dc94/xtask/src/main.rs#L54)'s some real-world use of `ServeDir` w/o axum, if you need it.

If it's reproducible w/o axum, we should transfer the issue.

**Comment by davidpdrsn** [comment]
@tomjakubowski I'll close this for now. I doubt it's a problem in axum and more likely in tower-http. Lets us know if you're able to reproduce it.
