### ISSUE TITLE
Number out of range error

### ISSUE THREAD

**Issue by sganis** [tokio-rs/axum#2258]
- [x] I have looked for existing issues (including closed) about this

## Bug Report
Number out of range error

### Version
0.6.18

### Platform
Windows 10

### Description
I want to compute the fibonacci number using the iterative algorithm. 
This function works fine in a command line test with n=100:
```rust
fn fib_iterative(n: u32) -> u128 {
    let mut a = 0;
    let mut b = 1;
    let mut c;
    for _ in 0..n {
        c = a + b;
        a = b;
        b = c;
    }
    a
}
```
However, it produces a "number out of range" error if it is used in an Axum handler:
```rust
pub async fn fibi(Path(n): Path<u32>) 
    -> Result<impl IntoResponse, (StatusCode, Json<serde_json::Value>)> {
    Ok(Json(json!({"n": n, "fibonacci": fib_iterative(n)})))
}
```
Terminal:
```cmd
curl http://localhost:8000/fibi/100
```
Error:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` 
on an `Err` value: Error("number out of range", line: 0, column: 0)'
```
### Note 
It works up to n=93, it breaks if n is larger.

**Comment by davidpdrsn** [comment]
Can you serialize it into a serde_json::Value without involving axum?

**Comment by sganis** [comment]
you are right, the error happens in ```json!({"n": 100, "fibonacci": fib_iterative(100)})```, it is a serde_json issue.
