### ISSUE TITLE
Oudated Examples

### ISSUE THREAD

**Issue by mahmudsudo** [tokio-rs/axum#2261]
the example folder contains examples of the axum usage that are deprecated or outdated with respect with the current axum version

**Comment by davidpdrsn** [comment]
[See this big warning in the readme](https://github.com/tokio-rs/axum#-the-main-branch-has-unpublished-breaking-changes-).

Remember to look at the examples for [the git tag you're using](https://github.com/tokio-rs/axum/tree/axum-v0.6.20/examples).
