### ISSUE TITLE
I decided to use rust write a small forum, here are some question I want to ask.

### ISSUE THREAD

**Issue by NOVA-ME** [tokio-rs/axum#227]
1. Is there a global interceptor for axum for verify token. I see the doc find [this](https://docs.rs/axum/0.1.3/axum/#routing-to-any-service),but I'm not good at rust,I'm not sure is this can make a global interceptor.
2. I think I can impl the [FromRequest](https://docs.rs/axum/0.1.3/axum/extract/trait.FromRequest.html), and get the user info, is that right.
3. I can't find any more examples about axum work with sqlx,jsonwebtoken,redis...
4. I have saw the [Error_Handler](https://github.com/tokio-rs/axum/blob/main/examples/error-handling-and-dependency-injection/src/main.rs#L94),I think here can use thiserror redirect.
5. If i want to add something into header,and return json,how can I do? 
6. I have been use actix-web for a few times. I think the attritube router is very nice. Is axum will support it? 
example
```rust
#[get("/login")]
async fn login(login_user: web::Form<LoginUser>, state: AppState) -> AppResult<HttpResponse> {
  ...
}
```

**Comment by davidpdrsn** [comment]
> 1. Is there a global interceptor for axum for verify token. I see the doc find [this](https://docs.rs/axum/0.1.3/axum/#routing-to-any-service),but I'm not good at rust,I'm not sure is this can make a global interceptor.

The recommended approach is to write an extractor that verifies the request and use `extractor_middleware` to apply it to multiple routes. Like shown [here](https://docs.rs/axum/0.1.3/axum/extract/fn.extractor_middleware.html). You can also use [`RequireAuthorization` from tower-http](https://docs.rs/tower-http/0.1.1/tower_http/auth/require_authorization/index.html).

> 2. I think I can impl the [FromRequest](https://docs.rs/axum/0.1.3/axum/extract/trait.FromRequest.html), and get the user info, is that right.

Yes that is right.

> 3. I can't find any more examples about axum work with sqlx,jsonwebtoken,redis...

There aren't examples for doing those specific things but you should be able to piece together parts of the existing examples https://github.com/tokio-rs/axum/tree/main/examples.

> 4. I have saw the [Error_Handler](https://github.com/tokio-rs/axum/blob/main/examples/error-handling-and-dependency-injection/src/main.rs#L94),I think here can use thiserror redirect.

Yes. `thiserror` will work just fine.

> 5. If i want to add something into header,and return json,how can I do? 

Yeah you can do this:

```rust
async fn header_with_json() -> impl IntoResponse {
    let mut headers = HeaderMap::new();
    headers.insert(
        HeaderName::from_static("x-foo"),
        HeaderValue::from_static("bar"),
    );
    (headers, Json(serde_json::json!({ "key": "value" })))
}
```

> 6. I have been use actix-web for a few times. I think the attritube router is very nice. Is axum will support it?

I'm sorry but no - we have no plans of adding macros to axum. If its something you really want I'd recommend creating a separate crate that does it.

**Comment by NOVA-ME** [comment]
Thank you, so useful to me
