### ISSUE TITLE
Inconsistent handling of empty query param value in axum_extra::extract::Query vs axum::extract::Query

### ISSUE THREAD

**Issue by Patrick-Lehner-Woven-by-Toyota** [tokio-rs/axum#2275]
- [x] I have looked for existing issues (including closed) about this

Thank you very much for your great work on axum, everyone! We have found it really useful for building web APIs 👏 

### Version

```
> cargo tree | grep axum

├── axum v0.6.20
│   ├── axum-core v0.3.4
├── axum-extra v0.7.7
│   ├── axum v0.6.20 (*)
│   ├── axum-core v0.3.4 (*)
├── axum-tracing-opentelemetry v0.11.0
│   ├── axum v0.6.20 (*)
│       ├── axum v0.6.20 (*)
```

### Platform

Apple MacBook Pro with M1 Max
`Darwin <hostname> 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64`

### Crates

Probably `axum` and `axum-extra`?

### Description

Using the query extractors on `Optional<String>` query parameters, [`axum::extract::Query`](https://docs.rs/axum/0.6.20/axum/extract/struct.Query.html) and [`axum_extra::extract::Query`](https://docs.rs/axum-extra/0.7.7/axum_extra/extract/struct.Query.html) behave inconsistently when the parameter has an empty value vs. when the parameter is absent.

* `axum::extract::Query`: absent parameter -> `None`, parameter with empty value -> `Some("")`
* `axum_extra::extract::Query`: both cases result in `None` (I would expect parameter with empty value to still produce `Some("")`)

The documentation pages of both extractors link to the [query-params-with-empty-strings](https://github.com/tokio-rs/axum/blob/main/examples/query-params-with-empty-strings/src/main.rs) example, which demonstrates the distinction between the two cases.
However, they both link to the _same_ example, and [the example only uses `axum::extract::Query`](https://github.com/tokio-rs/axum/blob/8854e660e9ab07404e5bb8e30b92311d3848de05/examples/query-params-with-empty-strings/src/main.rs#L7), _not_ `axum_extra::extract::Query`.

It seems that neither extractor has (unit) test cases covering the "parameter with empty value" case, though.
See [`axum::extract::Query` tests](https://github.com/tokio-rs/axum/blob/axum-v0.6.20/axum/src/extract/query.rs#L98) and [`axum_extra::extract::Query` tests](https://github.com/tokio-rs/axum/blob/axum-extra-v0.7.7/axum-extra/src/extract/query.rs#L118).

It would be great to at least update the docs to reflect this difference.
If this isn't intentional, it would additionally be great if this could be fixed, and test cases confirming the behavior could be added 🙏

**Comment by davidpdrsn** [comment]
@jplatte do you know if this intended or a bug?

**Comment by jplatte** [comment]
Probably a bug. But this should be an issue on `serde_html_form`, sincea axum doesn't contain any of the actual deserialization code. Please reopen there.
