### ISSUE TITLE
Add special handling of `Extension` and `Clone` for `debug_handler`

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#2294]
To help with cases like https://github.com/tokio-rs/axum/issues/2293

Basically generate `T: Clone` for `Extension<T>` arguments.

We already do something similar for argument ordering so should be possible to extend that.

**Comment by loganbnielsen** [comment]
Macros operate on the syntax tree and therefore don't generally have knowledge as to whether a trait is implemented for a type. I'm not sure if it's possible to make a check for this using similar techniques from `debug_handler.rs`. AFAIK, we could only identify whether it's `Extension` and the `T` but not whether the `T` implements `Clone` (without doing something infeasible like registering all types that implement clone haha)

**Comment by jplatte** [comment]
@loganbnielsen If you look at the existing checks in `debug_handler.rs`, we already have checks like "inner type of `Json` implements `Serialize` in return type position. It works by generating a function like `fn assert_serialize<T: Serialize>() {}` and calling it as `assert_serialize::<InnerType>();`.

**Comment by loganbnielsen** [comment]
I can publish a PR for this today

**Comment by jplatte** [comment]
Go ahead! This issue is `help wanted` so PRs are welcome :)

I'll also assign the issue to you so it's easy to see that it has somebody working on it.

**Comment by loganbnielsen** [comment]
PR request [here](https://github.com/tokio-rs/axum/pull/2301).
