### ISSUE TITLE
[FR] missing request in `IntoResponse`, we need process response base on request header `accept`.

### ISSUE THREAD

**Issue by arkxfly** [tokio-rs/axum#2295]
- [x] I have looked for existing issues (including closed) about this

## Feature Request

I found that axum missing request in `IntoResponse`,  we need process reponse base on header `accept`.

### Motivation

I need to serialize different body base on request header `accept`.  eg: JSON, XML. 
but now, I can't get `request` in `IntoResponse::into_response()`

**Comment by davidpdrsn** [comment]
This is intentional. It makes calling into_response way easier, which is useful for things like https://docs.rs/axum/0.6.20/axum/response/index.html#returning-different-response-types. That use case is more important I think.

You’ll have to pass in the necessary data some other way.
