### ISSUE TITLE
Remove or change `impl FromRequest* for Option<impl FromRequest*>`?

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#2298]
The possibility of using `Option<Extractor>` as an extractor has lead to a bunch of confusion because people have expected or wanted it to have different semantics for specific inner extractors. We should consider removing or altering the two implementations.

One option: We could have separate traits `OptionalFromRequest` and `OptionalFromRequestParts` and implement them only for a handful of types where it actually makes sense to discard the error. We could also implement different behavior, such as making `Option<Path<_>>` equivalent to the current `OptionalPath` from axum-extra. If you feel like this is worth exploring, I can open an issue.

This idea originally came up in https://github.com/tokio-rs/axum/discussions/2281#discussioncomment-7434310.

**Comment by jplatte** [comment]
@davidpdrsn How positive are you about the proposal from the second paragraph of the issue description? I could make a PR with that today or tomorrow.

**Comment by davidpdrsn** [comment]
I think that sounds like a good path!
