### ISSUE TITLE
Add an OpenTelemetry exemple 

### ISSUE THREAD

**Issue by aimericsr** [tokio-rs/axum#2300]
- [x] I have looked for existing issues (including closed) about this

### Motivation

I have realise a demo project just for learning purpose in axum and tried to collect traces and send them in the OTLP format to a compatible backend. However I found that there was a lot of different OpenTelemetry related crates and I found difficult to come with something that work the way I want (but I'm still new to rust and OpenTelemetry).

### Proposal

That's why is think it would be a good idea to add a project for this in the examples directory of this repo to help people getting started faster. I can propose a pr if you think it's worth it. The project should be able to create a trace for each incoming HTTP request with Otel naming convention and send them to a backend(over HTTP or grpc).

**Comment by davidpdrsn** [comment]
I think that’s out of scope for the examples in this repo because there are so many different ways of doing it that are more about opentelemetry than axum.

You’re welcome to add an example project to ECOSYSTEM.md
