### ISSUE TITLE
Update rest-grpc-multiplex example to hyper 1.0

### ISSUE THREAD

**Issue by FlyinPancake** [tokio-rs/axum#2325]
- [ x] I have looked for existing issues (including closed) about this

### Motivation
Hyper recently moved to 1.0 and the `hyper::Server` struct is no longer available.

### Proposal
Migrate the code in `examples/rest-grpc-multiplex`

### Alternatives
One can look into `examples/hyper-1-0` and figure it out, but it is not as easy.

**Comment by davidpdrsn** [comment]
The examples that don’t depend on external dependencies are updated as part of https://github.com/tokio-rs/axum/pull/1882

we can’t update the tonic example until tonic also supports hyper 1.0. So that’ll have to wait.
