### ISSUE TITLE
Use `impl Into<Cookie>`

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#2347]
We updated to the latest version of `cookie` in https://github.com/tokio-rs/axum/pull/2343 and they've changed a bunch of methods to use `impl Into<Cookie>`. [Their changelog has the details](https://github.com/SergioBenitez/cookie-rs/blob/master/CHANGELOG.md).

We should make similar changes in axum-extra. At least [`CookieJar::add`](https://docs.rs/axum-extra/latest/axum_extra/extract/cookie/struct.CookieJar.html#method.add) but probably also others.

**Comment by jplatte** [comment]
Related, we should mention the upgrade in the changelog. I only thought about that after pressing merge on #2343.
