### ISSUE TITLE
Update remaining examples to axum 0.7

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#2356]
This tracks the examples that haven't yet been updated to axum 0.7:

- [ ] [rest-grpc-multiplex](https://github.com/tokio-rs/axum/blob/main/examples/rest-grpc-multiplex/src/main.rs) - Blocked. Requires tonic supporting http 1.0 (https://github.com/hyperium/tonic/issues/1579)
- [x] [tls-graceful-shutdown](https://github.com/tokio-rs/axum/blob/main/examples/tls-graceful-shutdown/src/main.rs) - If we're using axum_server then its blocked but maybe it can be done using hyper directly. Not sure.
- [x] [tls-rustls](https://github.com/tokio-rs/axum/blob/main/examples/tls-rustls/src/main.rs) - Blocked. Requires updating axum_server.
- [x] [reqwest-response](https://github.com/tokio-rs/axum/blob/main/examples/reqwest-response/src/main.rs)
- [x] [http-proxy](https://github.com/tokio-rs/axum/blob/main/examples/http-proxy/src/main.rs) - Good to go, no blockers.
- [x] [reverse-proxy](https://github.com/tokio-rs/axum/blob/main/examples/reverse-proxy/src/main.rs) - No blockers. Can use [hyper-util's legacy client](https://docs.rs/hyper-util/latest/hyper_util/client/legacy/struct.Client.html).
- [x] [low-level-rustls](https://github.com/tokio-rs/axum/blob/main/examples/low-level-rustls/src/main.rs) - Fairly certain this one is good to go.
- [x] [low-level-openssl](https://github.com/tokio-rs/axum/blob/main/examples/low-level-openssl/src/main.rs) - Fairly certain this one is good to go.
- [x] [listen-multiple-addrs](https://github.com/tokio-rs/axum/blob/main/examples/listen-multiple-addrs/src/main.rs) - Good to go, no blockers (claimed by @davidpdrsn)
- [x] [testing](https://github.com/tokio-rs/axum/blob/main/examples/testing/src/main.rs) - No blockers. Can use [hyper-util's legacy client](https://docs.rs/hyper-util/latest/hyper_util/client/legacy/struct.Client.html) (claimed by @davidpdrsn)
- [x] [unix-domain-socket](https://github.com/tokio-rs/axum/blob/main/examples/unix-domain-socket/src/main.rs) - No blockers. Should be very similar to [serve-with-hyper](https://github.com/tokio-rs/axum/blob/main/examples/serve-with-hyper/src/main.rs) (claimed by @davidpdrsn)

**Comment by rsdlt** [comment]
Hi David, I'll have some time the next couple of weeks and would like to help with this one, if possible. 

Cheers

**Comment by davidpdrsn** [comment]
Go ahead! Just post here which example you’re working on so others know.

**Comment by takkuumi** [comment]
I'll fix [rest-grpc-multiplex](https://github.com/tokio-rs/axum/blob/main/examples/rest-grpc-multiplex/src/main.rs) example until tonic support http 1.0.

**Comment by davidpdrsn** [comment]
@takkuumi what do you mean? The example can't be updated yet.

**Comment by takkuumi** [comment]
> @takkuumi what do you mean? The example can't be updated yet.

Not this mean, I’d wrote this example and I think that i can help on it.

**Comment by davidpdrsn** [comment]
I'm pretty sure the example can't be updated yet because tonic uses http 0.2 and axum now requires http 1.0. You can't convert requests/responses from 0.2 to 1.0 because extensions are totally opaque. Having to put a bunch of conversion code in an example isn't appropriate either.

I think people using axum with tonic will have to wait until tonic has been updated.

**Comment by sam-kirby** [comment]
It looks like the `tls-graceful-shutdown` example is missing from this list.

**Comment by rsdlt** [comment]
> Go ahead! Just post here which example you’re working on so others know.

Thanks. Working on [http-proxy](https://github.com/tokio-rs/axum/blob/main/examples/http-proxy/src/main.rs) first. 

Will update here. Cheers.

**Comment by erebe** [comment]
Made a PR https://github.com/tokio-rs/axum/pull/2375 to update [low-level-rustls](https://github.com/tokio-rs/axum/blob/main/examples/low-level-rustls/src/main.rs)

**Comment by erebe** [comment]
Made a PR https://github.com/tokio-rs/axum/pull/2384 to update [tls-graceful-shutdown](https://github.com/tokio-rs/axum/blob/main/examples/tls-graceful-shutdown/src/main.rs)

**Comment by hanusek** [comment]
https://github.com/tokio-rs/axum/blob/axum-v0.7.2/examples/tls-rustls/src/main.rs#L30 ?

**Comment by insightfulbit** [comment]
Not sure this is the best place to report as I see `testing` is already updated.

I run with the following when running the example testing
```sh
$cargo test -p example-testing
   Compiling hyper-util v0.1.1
error[E0599]: no method named `with_retries` found for struct `TcpKeepalive` in the current scope
   --> .cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-util-0.1.1/src/client/legacy/connect/http.rs:130:12
    |
130 |         ka.with_retries(retries)
    |            ^^^^^^^^^^^^ help: there is a method with a similar name: `with_time`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `hyper-util` (lib) due to previous error
```

**Comment by jplatte** [comment]
Sounds like hyper-util has one of its dependency specifications wrong. `cargo update` should work around it.

**Comment by gerardcl** [comment]
@davidpdrsn I just realised I did update the only commit in the PR #2430 after you merged so the changes on the comments
here https://github.com/gerardcl/axum/commit/93799cf24d56e9140ca2850b69716d59865002e0#diff-60c9dfa63b6f41b8064cb70bbde4726a91cc3895257ef8b6c39c73c46b223b8eR65 and here https://github.com/gerardcl/axum/commit/93799cf24d56e9140ca2850b69716d59865002e0#diff-60c9dfa63b6f41b8064cb70bbde4726a91cc3895257ef8b6c39c73c46b223b8eR75 , did not get in. Let me know if you want me to fix it somehow. Thanks!

**Comment by davidpdrsn** [comment]
The code looks okay to me https://github.com/tokio-rs/axum/blob/main/examples/reqwest-response/src/main.rs#L67. Am I missing something?

**Comment by davidpdrsn** [comment]
Ah I see. You're free to submit a PR to clean that up :)

**Comment by davidpdrsn** [comment]
I think I'll close this issue now for now. All examples except [rest-grpc-multiplex](https://github.com/tokio-rs/axum/blob/main/examples/rest-grpc-multiplex/src/main.rs) has been updated and that is blocked by tonic being updated. Nothing really we can do about that here. Follow https://github.com/hyperium/tonic/issues/1579 for more updates.

Thanks to everyone who helped porting examples ❤️
