### ISSUE TITLE
A route producing the Unit type `()` should generate a HTTP 204 response

### ISSUE THREAD

**Issue by jbethune** [tokio-rs/axum#2363]
- [x] I have looked for existing issues (including closed) about this

## Feature Request

This is not something super important, but I want to describe a potential semantic improvement on how axum uses HTTP.

Axum currently returns HTTP status 200 for a route that returns the unit type:

```
async fn my_route() -> () { // explicit return type for clarity
    println!("I am not returning anything");
}
```
But a [HTTP 204 status code](https://www.rfc-editor.org/rfc/rfc9110.html#status.204) (=no content) would be more precise, because the unit type is essentially an empty value.

### Motivation

This is mostly useful for routes that get called via ajax. By being more explicit, API breakage can be detected more easily and ajax handling logic may branch on the status code.

Somewhat related: `Option<T>` return types could also benefit from a 200/204 distinction.

### Proposal

My understanding is that this part has to be changed:

https://github.com/tokio-rs/axum/blob/2e963cea9d35cd6b2583670146d25842db1f3618/axum-core/src/response/into_response.rs#L125-L129

This could be as simple as creating the response like above, but before returning, update the status code to 204.

### Alternatives

Just leave things as they are. Which would still be fine.

**Comment by davidpdrsn** [comment]
I suspect that might be difficult because of how we implement `IntoResponse` for tuples but worth a shot! I agree it makes sense.

**Comment by davidpdrsn** [comment]
Gonna close this. See https://github.com/tokio-rs/axum/pull/2393#issuecomment-1871626798 for why.
