### ISSUE TITLE
A request to give an order to the examples

### ISSUE THREAD

**Issue by Benbellah-Owino** [tokio-rs/axum#2383]
- [ ] I have looked for existing issues (including closed) about this

## Feature Request
Please can you number or give a roadmap of your examples, I'm interested in Axum and I'm using your examples to learn but I don't know where to start or which path to follow

**Comment by davidpdrsn** [comment]
The examples are not really meant to be tutorial that you can follow. They're meant to show you how to do a specific thing with axum. So for example if you aren't using sqlx then you can just ignore that example.

If you're looking for tutorials I recommend having a look at [ECOSYSTEM.md](https://github.com/tokio-rs/axum/blob/main/ECOSYSTEM.md)
