### ISSUE TITLE
`h2` crate still pulled in after disabling "http2" feature

### ISSUE THREAD

**Issue by w-flo** [tokio-rs/axum#2386]
- [X] I have looked for existing issues (including closed) about this

### Version

```
├── axum v0.7.1
│   ├── axum-core v0.4.0
├── axum-extra v0.9.0
│   ├── axum v0.7.1 (*)
│   ├── axum-core v0.4.0 (*)
```

### Platform

Linux [..] 6.2.0-36-generic #37-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  4 10:14:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Description

The issue title says it all: After disabling the "http2" feature in axum, the `h2` crate is still getting built in in the cargo build process if the "tokio" feature is enabled. I use these (and no hyper dep):
```
axum = { version = "0.7", default-features = false, features = ["http1", "tokio"] }
axum-extra = { version = "0.9", features = ["cookie"] }
```

### Suspected cause

The reason for this unexpected behavior appears to be that hyper's "http2" feature is still enabled through the optional `hyper-util` dependency with the "server-auto" feature enabled, which is enabled in `axum` when enabling the "tokio" feature.

**Comment by jplatte** [comment]
Can confirm the suspected cause. I think this should likely be considered a bug in `hyper-util` (though unfortunately fixing it will be a breaking change).

**Comment by davidpdrsn** [comment]
Moving issue to hyper-util (https://github.com/hyperium/hyper/issues/3493) since we can't do anything about it from axum's side.

**Comment by w-flo** [comment]
If I understand https://github.com/hyperium/hyper-util/pull/80 correctly, `hyper-util` now supports enabling just the `server` feature with `http1`, which would still make the auto builder available without http2 support.

So if I got that right, `axum` could now drop the `server-auto` feature in `hyper-util`. I think the `http1` and `http2` features in `axum` would then need to enable `hyper-util?/http1` and `hyper-util?/http2`, respectively.

**Comment by davidpdrsn** [comment]
Yes it should be possible to fix now!
