### ISSUE TITLE
Difficulty serving HTTP/2 

### ISSUE THREAD

**Issue by casey** [tokio-rs/axum#2409]
I'm trying to my axum server serving HTTP/2, but I'm having difficulties.

When I do `curl localhost`, I get HTTP/1.1
When I do `curl --http2 localhost`, I also get HTTP/1.1
When I do `curl --http2-prior-knowledge localhost`, I get HTTP/2
When I deploy to a server with HTTPS, and do `curl $URL`, I also get HTTP/1.1.
When I visit the server URL with Chrome, the protocol used is HTTP/1.1.

So it looks like the server can serve HTTP/2, but is failing to upgrade, or failing to select HTTP/2 as part of the TLS negotiation.

I added the `http2` feature to axum and hyper. One potentially complicating factor is that I'm using [rustls-acme](https://github.com/FlorianUekermann/rustls-acme), to use let's encrypt certificates. I'm not sure if that could be the culpret.

Is there anything else I need to do, in terms of code or feature flags, to enable HTTP/2 support?

Some info:

```
$ cargo tree | grep axum
├── axum v0.6.20
│   ├── axum-core v0.3.4
├── axum-server v0.5.1
│   ├── axum-server v0.5.1 (*)
```

We're on axum 0.6.20 at the moment, but can't upgrade due to some conflicting dependencies.

```
$ uname -a
Darwin durandal 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64
```

**Comment by jplatte** [comment]
This is not axum's fault, hyper takes care of HTTP protocol specifics like upgrades. IIRC hyper just doesnt support upgrades *at all*, at least the version that axum 0.6 depends on. Maybe hyper 1.0 (used by axum 0.7) does, you can check if its changelog mentions anything w.r.t. protocol upgrades.

**Comment by casey** [comment]
> This is not axum's fault, hyper takes care of HTTP protocol specifics like upgrades. 

Ah, gotcha. I think then I'm not sure how to configure hyper in that case. I'm doing everything via `axum` and `axum_server`, and don't use hyper directly at all, so I don't know how I would configure hyper, or debug what's going wrong without going through axum.

Should I open an issue on the hyper repo? I'm not sure what I would ask, since I'm not using it directly.

> IRC hyper just doesnt support upgrades at all, at least the version that axum 0.6 depends on. Maybe hyper 1.0 (used by axum 0.7) does, you can check if its changelog mentions anything w.r.t. protocol upgrades.

I think the thing that isn't working here isn't upgrades. It's ALPN protocol negotiating during TLS. I think this is the standard way to establish HTTP/2 connections, so I'd be surprised if hyper didn't support it. In TLS w/ALPN, the client sends a list of acceptable protocols, and the server selects one. When I curl an axum server HTTPS endpoint, I see the client offering HTTP/2 and HTTP/1, and the server not explicitly accepting one of them, which causes the client to default to HTTP/1.

**Comment by casey** [comment]
Got it, thanks for the explanation!
