### ISSUE TITLE
Make it easier to do graceful shutdown with axum 0.7

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#2419]
Most of the work is done (https://github.com/tokio-rs/axum/pull/2398) but currently blocked by PRs for hyper and hyper-util.

**Comment by davidpdrsn** [comment]
No that is unrelated. Please open a separate discussion about it.

**Comment by wangziling** [comment]
Hi David. Leave it alone. My apologize, I forgot to use `.with_state()`. 😞

**Comment by davidpdrsn** [comment]
https://github.com/tokio-rs/axum/pull/2398 has been shipped in axum 0.7.3 🎉
