### ISSUE TITLE
Json() into_response doesn't set `Content-Type` charset

### ISSUE THREAD

**Issue by 0xpr03** [tokio-rs/axum#2441]
- [X] I have looked for existing issues (including closed) about this

### Version

axum v0.7.2
axum-core v0.4.1
axum-macros v0.4.0 (proc-macro)
axum-extra v0.9.0

### Platform

64bit Win10

### Description

The Json() response implementation doesn't set the Content-Type charset header. Thus frameworks like flutter [read them back as latin1](https://pub.dev/documentation/http/latest/http/Response/body.html). The obvious workaround is to override the header manually everywhere.

I tried this code:

```rust
async foo() -> Response {
    Json("€").into_response()
}
```

I expected to see this happen: `Content-type: application/json; charset=utf-8`

Instead, this happened: `content-type: application/json`

I'm not sure if anything but utf8 is expected for `DeserializeOwned` for Json responses. I would definitely say it's a saner default because Rust uses utf8 for String and Json is also mostly expected to be utf8? Maybe Web-browsers are simply peeking to get the charset right, not sure about that.

**Comment by davidpdrsn** [comment]
That’s not necessary actually. The spec (https://datatracker.ietf.org/doc/html/rfc8259#section-8.1) requires that JSON is always encoded as utf-8 so it’s redundant to include that in the chatset.

**Comment by 0xpr03** [comment]
Thanks for pointing out the relevant RFC section, I'll open an issue for dart.http.
