### ISSUE TITLE
Improve the documentation in debugging_handler_type_errors.md regarding what implements Handler

### ISSUE THREAD

**Issue by hydrogen602** [tokio-rs/axum#2450]
- [x] I have looked for existing issues (including closed) about this

## Feature Request

In the documentation about what functions implement the `Handler` trait, the docs only say that `FromRequest` is required. But looking at the source code, every argument is also given a trait bound of `Send`. So my feature request is to update the documentation to say that arguments of functions need to implement both `FromRequest + Send`. 

https://github.com/tokio-rs/axum/blob/3fda093806d43d64dd70cda0274cd3d73d29b6c7/axum/src/docs/debugging_handler_type_errors.md?plain=1#L7

### Motivation

The motivation for this is to reduce confusion in cases where handler are closures created in generic functions where the argument is generic, like `Json<T>`. In this case, a constraint of `T: FromRequest<...>` is not enough to ensure that any closures with `Json<T>` as an argument actually implement `Handler`

### Proposal

Replace
```
 - Take no more than 16 arguments that all implement [`FromRequest`]. 
```
with
```
 - Take no more than 16 arguments that all implement [`FromRequest`] and [`Send`]. 
```

For people that don't need this piece of information, this small add-on doesn't clutter the documentation, and for those that do, this could save a lot of confusion since `#[debug_handler]` can't be applied on closures and so the developer is left guessing why `Handler` is not implemented.

**Comment by davidpdrsn** [comment]
It seems to be out of date in more ways. Only the last can implement FromRequest. The rest must only implement FromRequestParts.

**Comment by hydrogen602** [comment]
Sure

**Comment by hydrogen602** [comment]
I've submitted a PR #2451
