### ISSUE TITLE
RouterIntoService not Clone?

### ISSUE THREAD

**Issue by bryanburgers** [tokio-rs/axum#2455]
- [x] I have looked for existing issues (including closed) about this

### Version

* axum 0.7

### Description

I'm trying to turn a Router into a Service so I can use it in `root_router.nest_service(...)`.

* Router has a [`.into_service()`](https://docs.rs/axum/latest/axum/routing/struct.Router.html#method.into_service) method
* [`Router::nest_service`](https://docs.rs/axum/latest/axum/routing/struct.Router.html#method.nest_service) requires the service to implement `Clone`
* [Router](https://docs.rs/axum/latest/axum/struct.Router.html) does implement `Clone`.
* [RouterIntoService](https://docs.rs/axum/latest/axum/routing/struct.RouterIntoService.html) does *not* implement `Clone`. 

All of that together means that, while I can write code that does

```rust
let sub_router = submod::create_router();

let router = Router::new()
  .nest("/sub", sub_router);
```

I can not write code that does

```rust
let sub_router_service = submod::create_router().into_service();

let router = Router::new()
  .nest_service("/sub", sub_router_service);
```

This seems like it *might* be an oversight? It looks to me like [RouterIntoService](https://docs.rs/axum/latest/axum/routing/struct.RouterIntoService.html) should trivially implement `Clone`? (It only has a Router in it.)

---

Why do I want to use `.nest_service` instead of `.nest` in the first place? It's because I have a layer on my subrouter, and when I use `.nest` that layer doesn't get called for non-matching routes.

**Comment by davidpdrsn** [comment]
Sure, implementing `Clone` for `RouterIntoService` seems fine but I'm confused as to why you can't just use `Router::nest`.
