### ISSUE TITLE
Add `serve_uds` to axum-extra

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#2474]
`axum::serve` intentionally only supports `TcpListener` because it greatly simplifies the API. However that means serving over a unix domain socket requires [a lot of boilerplate](https://github.com/tokio-rs/axum/blob/main/examples/unix-domain-socket/src/main.rs).

We should add a dedicated `serve_uds` function to axum-extra that makes that easier. I should be possible to more or less copy `axum::serve` and use Tokio's `UnixListener` instead.

**Comment by vi** [comment]
Will it also make serving connections over arbitrary `AsyncRead`+`AsyncWrite` pairs easier?

**Comment by davidpdrsn** [comment]
No. hyper 0.14's server used to that but it [leads to nasty trait bounds](https://docs.rs/hyper/0.14.28/hyper/server/struct.Builder.html#method.serve) which I really want to avoid.

**Comment by fundon** [comment]
A trait for a listener already exists: https://docs.rs/tokio-util/latest/tokio_util/net/trait.Listener.html

**Comment by davidpdrsn** [comment]
Oh neat! That might be worth trying to use.

**Comment by jplatte** [comment]
So I guess #2479 will work for UDS and we don't actually want to add a separate `serve_uds`?

**Comment by davidpdrsn** [comment]
Yes!

**Comment by Turbo87** [comment]
@jplatte with https://github.com/tokio-rs/axum/pull/2941 merged, is this issue still relevant?

**Comment by jplatte** [comment]
No, that PR should have closed this issue.
