### ISSUE TITLE
docs: `IntoResponse` focuses too much on Custom `Body` impls

### ISSUE THREAD

**Issue by dbofmmbt** [tokio-rs/axum#249]
Hey, I went to take a look in the `IntoResponse` documentation, as it is the way shown in the `examples` to use custom error types with Axum, but its content may pass the impression that it should rarely be used, which is often not the case when error handling is concerned:

https://github.com/tokio-rs/axum/blob/02e61dfdd6f05cd87f2edc9475b47974a50ce9f7/src/response/mod.rs#L30-L36

It may be just my impression, though. What do you think about it?

**Comment by davidpdrsn** [comment]
Oh yeah that's true. This should be re-worded

> A manual implementation should only be necessary if you have a custom response body type.

Error types is another common reason to implement this trait.

**Comment by davidpdrsn** [comment]
I'm gonna fix this for 0.2.1
