### ISSUE TITLE
Built-in TLS Support 🎯

### ISSUE THREAD

**Issue by NiiightmareXD** [tokio-rs/axum#2494]
- [X] I have looked for existing issues (including closed) about this

## Feature Request
I think it would be better if Axum had built-in TLS support right now we can use [low-level-rustls](https://github.com/tokio-rs/axum/tree/main/examples/low-level-rustls) but it's unnecessarily hard I think it would be better if we had something like in (Actix)[https://actix.rs/docs/http2] which has bind_openssl function and doesn't need any other crates other than OpenSSL and Actix itself.

I can attempt to implement it myself if you believe it would be beneficial.

### Motivation
Pretty much every web server uses TLS.

### Proposal
The implementation should be easy it has been already done in (axum-server)[https://github.com/programatik29/axum-server] but it would be better if we didn't need to add another crate to project just to get TLS.

### Alternatives
using [axum-server](https://github.com/programatik29/axum-server), [low-level-openssl](https://github.com/tokio-rs/axum/tree/main/examples/low-level-openssl), [low-level-rustls](https://github.com/tokio-rs/axum/tree/main/examples/low-level-rustls) and [tls-rustls](https://github.com/tokio-rs/axum/tree/main/examples/tls-rustls).

**Comment by davidpdrsn** [comment]
axum intentionally doesn’t have that built-in and I think I want it to stay that way.

In the future axum::serve will be generic over the listener and IO which will make it easier to plug-in a TLS acceptor. See https://github.com/tokio-rs/axum/pull/2479

**Comment by NiiightmareXD** [comment]
> axum intentionally doesn’t have that built-in and I think I want it to stay that way.
> 
> In the future axum::serve will be generic over the listener and IO which will make it easier to plug-in a TLS acceptor. See [#2479](https://github.com/tokio-rs/axum/pull/2479)

Hey, now that the PR you mentioned has merged, is there any example of how to do it without the `axum-server` crate?

**Comment by mladedav** [comment]
Without having seen the internals of the crate, you could try something like [this](https://github.com/tmccombs/tls-listener/blob/main/examples%2Faxum.rs).

If you're willing to create an example out of it (either by pulling in the crate or by implementing something like that in the example, if it would be easy enough), feel free to send a PR.

**Comment by NiiightmareXD** [comment]
> Without having seen the internals of the crate, you could try something like [this](https://github.com/tmccombs/tls-listener/blob/main/examples%2Faxum.rs).
> 
> If you're willing to create an example out of it (either by pulling in the crate or by implementing something like that in the example, if it would be easy enough), feel free to send a PR.

Is something like this good for Rustls?

```rs
struct RustlsListener {
    tcp_listener: tokio::net::TcpListener,
    tls_acceptor: tokio_rustls::TlsAcceptor,
}

impl Listener for RustlsListener {
    type Io = tokio_rustls::server::TlsStream<tokio::net::TcpStream>;

    type Addr = std::net::SocketAddr;

    #[allow(clippy::cognitive_complexity)]
    async fn accept(&mut self) -> (Self::Io, Self::Addr) {
        loop {
            let (tcp_stream, addr) = match self.tcp_listener.accept().await {
                Ok(tup) => tup,
                Err(e) => {
                    handle_accept_error(e).await;
                    continue;
                }
            };

            let tls_stream = match self.tls_acceptor.accept(tcp_stream).await {
                Ok(stream) => stream,
                Err(_) => {
                    continue;
                }
            };

            tracing::debug!("Accepted connection from {}", addr);
            return (tls_stream, addr);
        }
    }

    fn local_addr(&self) -> io::Result<Self::Addr> {
        self.tcp_listener.local_addr()
    }
}

async fn handle_accept_error(e: io::Error) {
    if is_connection_error(&e) {
        return;
    }

    // [From `hyper::Server` in 0.14](https://github.com/hyperium/hyper/blob/v0.14.27/src/server/tcp.rs#L186)
    //
    // > A possible scenario is that the process has hit the max open files
    // > allowed, and so trying to accept a new connection will fail with
    // > `EMFILE`. In some cases, it's preferable to just wait for some time, if
    // > the application will likely close some files (or connections), and try
    // > to accept the connection again. If this option is `true`, the error
    // > will be logged at the `error` level, since it is still a big deal,
    // > and then the listener will sleep for 1 second.
    //
    // hyper allowed customizing this but axum does not.
    tracing::error!("accept error: {e}");
    tokio::time::sleep(Duration::from_secs(1)).await;
}

fn is_connection_error(e: &io::Error) -> bool {
    matches!(
        e.kind(),
        io::ErrorKind::ConnectionRefused
            | io::ErrorKind::ConnectionAborted
            | io::ErrorKind::ConnectionReset
    )
}
```

I copied both the `handle_accept_error` and `is_connection_error` functions from the axum implementation for normal `TcpStream`.

maybe they should be publiced

**Comment by NiiightmareXD** [comment]
I can create a pull request to update the examples for low_level_tls_x if that sounds good.

**Comment by mladedav** [comment]
`accept` is not called concurrently, so what you wrote will block accepting new connections until the preceding TLS handshake is finished. Which potentially opens you up to DoS by a single misbehaving client which is something that's not appropriate for a TLS example I think.

Any specific reason you decided not to use the linked library?

**Comment by NiiightmareXD** [comment]
Oh, I forgot about that,
Thanks for bringing up the `tls-listener` crate, though I'm concerned that its "batching" mechanism, although it does prevent the DoS vulnerabilities, could have performance overhead compared to the `low-level-rustls`  implementation.

My primary goal for opening this issue is to find a simpler, built-in abstraction that achieves the same outcome as the  `low-level-rustls` example. I feel that a web framework should handle TLS integration seamlessly without requiring extra libraries.

For now, the `low-level-rustls` example implementation seems like the most suitable path forward.

**Comment by mladedav** [comment]
You can also create a wrapper for the `Io` to first finish the handshake and then actually drive the stream. That would be closer to what the current low level example does.

I don't see anything wrong with using 3rd party crates to avoid handling TLS details though. This is kind of a bring your own implementation thing and I believe it's reasonable to expect guidance on how to integrate TLS with axum, but I don't think we should make the choice of whether users should use rustls/OpenSSL/native-tls or maintain all of these. But beyond that, I don't think that anything has changed since the first response in that TLS should not be built in.

You might also want to look at #3253, the second alternative listed there is what I tried to describe earlier.

**Comment by NiiightmareXD** [comment]
Completely agree, the two phase listener proposal would simplify things a lot and with great customization.
