### ISSUE TITLE
Broken link in axum::extract

### ISSUE THREAD

**Issue by qrilka** [tokio-rs/axum#2496]
- [x] I have looked for existing issues (including closed) about this

## Bug Report

The current (0.7.3) rustdocs of axum include a dead link https://github.com/tokio-rs/axum/blob/5b6204168a676497d2f4188af603546d9ebfe20a/axum/src/docs/extract.md#L15

### Version

```
$ cargo tree | grep axum
│   ├── axum v0.7.3
│   │   ├── axum-core v0.4.2
│   ├── axum-extra v0.9.0
│   │   ├── axum v0.7.3 (*)
│   │   ├── axum-core v0.4.2 (*)
├── axum v0.7.3 (*)
│   │       ├── axum v0.6.20
│   │       │   ├── axum-core v0.3.4
│   ├── axum v0.7.3 (*)
```

### Description

I tried to check what does "Request body extractors" in `axum::extract` mean but the link doesn't go anywhere

**Comment by davidpdrsn** [comment]
Thanks for noticing! We can just removed that link from the table of contents. The section was removed a while ago and folded into "The order of extractors".

Would you wanna submit a PR for that?

**Comment by qrilka** [comment]
Here you go
