### ISSUE TITLE
Add Scheme extractor

### ISSUE THREAD

**Issue by bengsparks** [tokio-rs/axum#2504]
- [x] I have looked for existing issues (including closed) about this

## Feature Request

I'd like an easy way to see the scheme / protocol section of the request, which can be found in various headers and the URI itself.

### Motivation
Similar to #826, extracting of the scheme of a URI is desirable.

### Proposal

```rust
use axum::extract::Scheme;

async fn foo(Scheme(scheme): Scheme) -> ...
```

### Alternatives
Manually extracting the scheme via the parts of a URI / analyzing various headers, which is a tedious process.

If this is something that should be part of `axum`, I can submit a Pull Request with the implementation I already have (adapted from the existing extractor for hosts), and follow it up with some tests.

**Comment by davidpdrsn** [comment]
Sure! If that’s possible it would be nice to have.
