### ISSUE TITLE
Allow enumerating routes on service

### ISSUE THREAD

**Issue by casey** [tokio-rs/axum#2515]
I would like to automatically generate an page with a list of all routes for my website, so that I can present it as a sort of index page, to help visitors find their way around.

To do that, it would be nice, after creating a `Router` it was possible to enumerate all the routes of the `Router`. For my purposes, it wouldn't be necessary to know anything about the arguments that the routes take, just the paths.

**Comment by davidpdrsn** [comment]
We intentionally don’t support this because it’s the kind of feature that grows and eventually becomes openapi schema generation. So you’ll have to track which routes you add yourself.

**Comment by davidpdrsn** [comment]
I don’t have much confidence in that actually working. I still recommend you build something yourself.
