### ISSUE TITLE
Document deriving `FromRequestParts` limited to specific state types

### ISSUE THREAD

**Issue by Kinrany** [tokio-rs/axum#2550]
- [x] I have looked for existing issues (including closed) about this

## Feature Request

edit(jplatte): Apparently it is possible to explicitly set a state type for a derived `FromRequest` / `FromRequestParts` via `#[from_request(state(Type))]`. This is not documented.

Previous issue description:

### Motivation

`FromRequest` and `FromRequestParts` are two great derive macros that follow the general pattern of trait `X` being derivable for type `T` when all the fields of `T` are already `X`.

For completeness, one would expect this to also work in the case of `FromRequestParts<S>` where `S` is a concrete type: if all the fields of `T` are `FromRequestParts<S>`, it's reasonable to expect to be able to derive `FromRequestParts<S>` for `T` itself.

### Proposal

Change the derive macro for `FromRequestParts` (and possibly `FromRequest`) to also work for types that can only implement the trait for a certain state type.

It is likely the easiest to initially support a single state type only, with an intentionally long attribute that specifies the type:

```rust
impl FromRequestParts<Foo> for Bar {...}

#[derive(FromRequestParts)]
#[axum(from_parts_single_state = Foo)]
struct Baz {
   bar: Bar,
}
```

### Alternatives

Without the macro support, the only alternative is to implement the traits manually for types that rely on state.

**Comment by mladedav** [comment]
Is this what you mean or am I misunderstanding somehow?

```
use axum::async_trait;
use axum::http::request::Parts;
use axum::extract::FromRequestParts;

struct Foo;
struct Bar;

#[async_trait]
impl FromRequestParts<Foo> for Bar {
    type Rejection = ();

    async fn from_request_parts(_parts: &mut Parts, _state: &Foo) -> Result<Self, Self::Rejection> {
        todo!()
    }
}

#[derive(FromRequestParts)]
#[from_request(state(Foo))]
struct Baz {
   bar: Bar,
}

fn main() {}
```

**Comment by jplatte** [comment]
It is not mentioned in the documentation though.

**Comment by jplatte** [comment]
Docs were unnoticed in #2581.

**Comment by Kinrany** [comment]
Thank you!
