### ISSUE TITLE
help: systemfd + listenfd + tokio::spawn + axum. first connection returns only when second comes

### ISSUE THREAD

**Issue by jonirrings** [tokio-rs/axum#2552]
- [X] I have looked for existing issues (including closed) about this

### Version
0.7.4

### Platform
Linux p 6.6.0-14-generic 14-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 30 10:27:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Crates
```toml
axum = "0.7.4"
tokio = { version = "1", features = ["full"] }
listenfd = "1.0.1"
```

###  Minimum Reproducible Example
Rust Code
```rust
use std::io;
use axum::{
    routing::get,
    Router,
};
use tokio::net::TcpListener;
use listenfd::ListenFd;

#[tokio::main]
async fn main()-> io::Result<()> {
    let mut listenfd = ListenFd::from_env();
    let listener = match listenfd.take_tcp_listener(0).unwrap() {
        Some(listener) => TcpListener::from_std(listener).unwrap(),
        None => TcpListener::bind("127.0.0.1:3000").await.unwrap(),
    };
    let handle = tokio::spawn(async move {
        let app = Router::new().route("/", get(|| async { "Hello, World!" }));
        let b = listener.local_addr().unwrap();
        println!("listening on :{}...",b);
        axum::serve(listener, app)
            .await
    });
    handle.await.unwrap()
}
```
Script 1
```bash
cargo run
```
Script 2
```
systemfd --no-pid -s http::4000 -- cargo watch -x run
```

### Description
I've setup an axum server, and when it comes to `auto-reload`, something goes wrong.

when start a server by script 1, `curl http://localhost:3000 -v` will return immediately.

when start a server by scritp 2, `curl http://localhost:4000 -v` will stuck at `Connected to localhost (127.0.0.1) port 4000`, and create another terminal tab to `curl http://localhost:4000 -v` again, the first connection returns and the second one stuck.

the problem may be misuse of `tokio::spawn`, but I can't figure why and how to fix it.
😅

**Comment by arthurdandrea** [comment]
The problem is that you are providing a blocking socket to [`TcpListener::from_std`](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.from_std). As suggested in the docs, you can fix that as follows:

```rust
let listener = match listenfd.take_tcp_listener(0).unwrap() {
    Some(listener) => {
        listener.set_nonblocking(true).unwrap();
        TcpListener::from_std(listener).unwrap()
    },
    None => TcpListener::bind("127.0.0.1:3000").await.unwrap(),
};
```

**Comment by jonirrings** [comment]
@arthurdandrea thank you very much. It works.🫡

**Comment by jplatte** [comment]
PR to update the example in the same manner: #2558
