### ISSUE TITLE
release axum v0.6.21

### ISSUE THREAD

**Issue by jonassmedegaard** [tokio-rs/axum#2559]
It seems axum v0.6.21 was meant to be released in September, but instead a new branch was created.

@davidpdrsn

**Comment by jplatte** [comment]
Can you be a bit more specific? What makes you think that a version 0.6.21 was meant to be released?

**Comment by jonassmedegaard** [comment]
Oh! Looks like my local fork of this git repo includes a branch "axum-0.6.21" which does not exist (any longer?) on Github.

What make me think that a release was intented was git commit bb8e02b - but since that has since been yanked (or my system is somehow hallucinating), I guess such release was not intended after all.

**Comment by jonassmedegaard** [comment]
Ah, the explanation is dropped PR #2228

**Comment by jonassmedegaard** [comment]
...and the reason I am looking at old stuff is that I maintain axum (re)distribution for Debian, where we limit the amount of available branches of each crate, and are not yet ready to switch to v.0.7.
