### ISSUE TITLE
Make it harder to forget percent-encoding when issuing redirects

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#260]
### Motivation

Failing to do percent encoding was one of the ways https://turbo.fish broke when ported from Rocket to axum.

### Proposal

I'm not certain. Doing percent-encoding automatically might create new issues such as doubly-encoded URL parts. To be a nice API, it would also probably have to be a breaking change.

### Alternatives

Improve the `http` crate so that it allows construction of an `http::Uri` given non-percent-encoded parts, which doesn't seem to be possible currently.

### Prior Art

Rocket has a notion of [type-safe route URI generation](https://docs.rs/rocket/0.5.0-rc.1/rocket/macro.uri.html) that uses the [`UriDisplay` trait](https://docs.rs/rocket/0.5.0-rc.1/rocket/http/uri/fmt/trait.UriDisplay.html) to catch many common ways in which URI generation can go wrong.

**Comment by davidpdrsn** [comment]
I agree that addressing this directly in `http::Url` is ideal. Seems there already is a (mostly empty) issue about it https://github.com/hyperium/http/issues/384.

So I'll close this for now. If the conclusion in `http` is to not address this then we can always reconsider if axum (or another crate) should provide something for it.
