### ISSUE TITLE
I wanna say Thank You for the Axum Team

### ISSUE THREAD

**Issue by MacJayLee** [tokio-rs/axum#2609]
Axum is the best WebFramework I've ever used.
It's helpful for my job and improve the performance of current backend program.
I enjoy programing with Rust because of your contributions. 
Thank you anyway

**Comment by dayvejones** [comment]
i'm too! thanks!

**Comment by FemLolStudio** [comment]
Same! This is the first thing what I used after learning basic Rust, and I love both! It's good to know my API is very stable, safe and it's ready for big trafic too! :D

**Comment by davidpdrsn** [comment]
Thank you ❤️ happy to hear 😊

**Comment by millefalcon** [comment]
I'd like to +1 on this too <3. Learning rust by using axum has been pleasant so far, and it makes me want to learn rust more. Awesome all around. Thank you!!

**Comment by mrgzi** [comment]
People say rust is overkill for the backend, but after using axum, I found i like rust on the backend even more than golang!

**Comment by ElhamAryanpur** [comment]
Axum sparked my enjoyment for Rust in backend again. Thank you Axum team for your incredible tireless work on this project 🔥

**Comment by redactedontop** [comment]
Axum is the best framework for building APIs.
I use it for all software I can use it on.

Consider this a love letter.
Thanks,
Alex <3-

**Comment by yawn** [comment]
Axum is really an aspirational showcase for the power of Rust. For me personally it's a benchmark that demonstrates how expressive and powerful (and performant of course) APIs in Rust can be. Thanks for building it!

**Comment by jilvin** [comment]
Thank you for the beautiful work!❤️

**Comment by canmi21** [comment]
Thank you Axum, best forever!

**Comment by byblakeorriver** [comment]
I have used Axum at work for several years now and it is the bees knees! If any of my servers are acting up, it's definitely not because of Axum! Easy to use, easy to teach, and it just works!

**Comment by mishaldotrs** [comment]
another axum lover thanking the tokio team who built this!
