### ISSUE TITLE
FastAPI-like multiple applications

### ISSUE THREAD

**Issue by Tomperez98** [tokio-rs/axum#2619]
- [X] I have looked for existing issues (including closed) about this

### Motivation

FastAPI support [sub-applications](https://fastapi.tiangolo.com/advanced/sub-applications/) should Axum support something similar to this?

**Comment by dayvejones** [comment]
https://docs.rs/axum/latest/axum/routing/struct.Router.html#method.merge

**Comment by jplatte** [comment]
Actually sounds like they want `nest`, not `merge`. Either way, this is already supported.
