### ISSUE TITLE
I really don't know how to solve this problem

### ISSUE THREAD

**Issue by NOVA-ME** [tokio-rs/axum#262]
![image](https://user-images.githubusercontent.com/18442141/130632300-a41d0c2b-32fd-4790-9071-90112f71bcf0.png)
![image](https://user-images.githubusercontent.com/18442141/130632320-7acbbc27-2d8b-4c16-a27f-ff289a91147b.png)
![image](https://user-images.githubusercontent.com/18442141/130632400-507a2d79-f227-4be7-a150-bacececcb13f.png)
![image](https://user-images.githubusercontent.com/18442141/130632436-53395334-5dc0-4d73-9027-fda87b62130f.png)
only the ```get_captcha``` method can't add to router, ervery thing else is fine.
And I want to ask there have the axum telegram group or other place, that I can ask for some question

**Comment by davidpdrsn** [comment]
Try to isolate which part of the function makes it not work

- Replace the body of the function with `todo!()`.
- If that works then try and remove each of the lines until you find which line might be causing it. Note that handlers must return futures that are `Send`, but that doesn't seem to be an issue here.
- If it doesn't work then try changing the return type to simply `()` or `(StatusCode, HeaderMap, Vec<u8>)`. Maybe `AppResult`'s error type doesn't implement `IntoResponse`?
