### ISSUE TITLE
example was outdated,would encapsulation some general function into axum

### ISSUE THREAD

**Issue by joebnb** [tokio-rs/axum#2626]
https://github.com/tokio-rs/axum/blob/b03f6c1184723bdc079215222fc168ef96847dea/examples/customize-extractor-error/src/derive_from_request.rs#L26C1-L28C23

![image](https://github.com/tokio-rs/axum/assets/1646883/544a9cec-3264-4c49-99c5-7fe3c95012d1)

**Comment by HaoYang670** [comment]
The link posted is not the code you show in the picture.

**Comment by jplatte** [comment]
This sounds like you're looking for help, please use the Q&A discussion section ([new discussion](https://github.com/tokio-rs/axum/discussions/new?category=q-a)) and explain what you want to achieve, what you tried and how it failed.
