### ISSUE TITLE
Update serde_html_form to 0.2.4 in axum extra

### ISSUE THREAD

**Issue by LMH01** [tokio-rs/axum#2637]
- [X] I have looked for existing issues (including closed) about this

### Motivation

I'm currently writing an api endpoint where I require that `Option<Vec<T>>` can properly be parsed in a queries. Currently there is an issue that it can not be correctly parsed.
The fix is already implemented in `serde_html_form 0.2.4`: https://github.com/jplatte/serde_html_form/issues/11

### Proposal

We should update the version of `serde_html_form` to `2.4.0`.

### Alternatives

-

**Comment by jplatte** [comment]
This is not necessary: https://github.com/tokio-rs/axum/pull/2638#issuecomment-1987227198
