### ISSUE TITLE
Update `matchit` to 0.8

### ISSUE THREAD

**Issue by mladedav** [tokio-rs/axum#2641]
- [x] I have looked for existing issues (including closed) about this

### Proposal

`matchit` version 0.8 was just [released](https://github.com/ibraheemdev/matchit/releases/tag/v0.8.0).

It includes changes to the syntax so now instead of `/path/:arg/*wildcard` it uses `/path/{arg}/{*wildcard}`. There are some other changes such as that now `/path` and `/path/` are distinct.

All tests, examples, and documentation must be updated, otherwise the change is trivial.

This is a breaking change.

**Comment by jplatte** [comment]
Do you want to work on this? It would be very appreciated :)

**Comment by mladedav** [comment]
Yeah, sure.

Can you please add the breaking change (and possibly other) labels and add this to the 0.8 milestone?

**Comment by mladedav** [comment]
Sorry for not reacting before. Yes, I think it would be good to throw an error when the old syntax is used with a clear error saying how to upgrade.

I'm not sure providing a method for not checking against this carries it's weight as it's just path segments starting with a colon or an asterisk which  I think (not sure though) cannot be done by escaping in 0.7 either. But maybe it'll just be one bool and one if somewhere so it'll be easy to support, I'm just not sure right now.

As for the time, yeah, I do hope to get around to this this week to finish it. I don't think I need any clarifications but I'll ask if I hit anything.
