### ISSUE TITLE
Failed to parse flatten query

### ISSUE THREAD

**Issue by baskerbyte** [tokio-rs/axum#2698]
- [X] I have looked for existing issues (including closed) about this

### Version

axum v0.7.4

### Platform

Linux gentoo 6.1.69-gentoo-dist #1 SMP PREEMPT_DYNAMIC Thu Jan 18 08:26:20 -04 2024 x86_64 AMD Ryzen 5 1600 Six-Core Processor AuthenticAMD GNU/Linux

### Crates

axum query

### Description

For some reason, when deserializing a query for a struct that has a flatten attribute field, the deserialization does not occur as expected

```rust
#[derive(Serialize, Deserialize, Validate)]
pub struct FilterProducts {
    #[garde(custom(validate_price))]
    pub max_price: Option<Decimal>,
    #[garde(custom(validate_price))]
    pub min_price: Option<Decimal>,
    #[garde(skip)]
    pub min_stars: Option<StarRating>,
    #[garde(range(min = 1, max = 100))]
    pub product_type: Option<i32>,
    #[garde(skip)]
    pub start_time: Option<time::Time>,
    #[garde(skip)]
    pub day_of_week: Option<WeekDay>,
    #[garde(dive)]
    #[serde(flatten)]
    pub pagination: Pagination,
    #[garde(dive)]
    #[serde(flatten)]
    pub location: Option<Location>
}

#[derive(Serialize, Deserialize, Validate)]
pub struct Pagination {
    #[garde(range(min = 1, max = 100))]
    pub page: i16,
    #[garde(range(min = 5, max = 100))]
    pub per_page: i16
}

#[derive(Serialize, Deserialize, Validate)]
pub struct Location {
    #[garde(range(min = -90.0000000, max= 90.0000000))]
    pub latitude: f64,
    #[garde(range(min = -180.0000000, max= 180.0000000))]
    pub longitude: f64,
}
```

My query param:

```rust
WithValidation(query): WithValidation<Query<FilterProducts>>,
```

When I run test (same error happens when I try to access from browser)

```rust
let query = FilterProducts {
    max_price: None,
    min_price: None,
    min_stars: None,
    product_type: None,
    start_time: None,
    day_of_week: None,
    pagination: Pagination {
        page: 1,
        per_page: 10,
     },
    location: None,
};

let res = server.get("/api/v1/products")
        .add_query_params(query)
        .await;

println!("{}", res.text())
``` 

or

```
http://localhost:5443/api/v1/products?page=1&per_page=10
```

The error:
```
Failed to deserialize query string: invalid type: string "1", expected i16
```

Maybe the error isn't with axum, or maybe I'm doing something wrong, I hope anyone can help me

**Comment by jplatte** [comment]
This is https://github.com/serde-rs/serde/issues/1183.

**Comment by manortec** [comment]
A workaround to this using serde_with works welll.Something like this :



use serde::Deserialize;
use serde_with::{serde_as, DisplayFromStr};

#[serde_as]
#[derive(Debug,Deserialize)]
pub struct Page {
    #[serde_as(as = "DisplayFromStr")]
    pub page_num:i32,
    #[serde_as(as = "DisplayFromStr")]
    pub page_size:i32,
    #[serde_as(as = "DisplayFromStr")]
    pub some_bool_type:bool,
}
