### ISSUE TITLE
axum:rejections does not seem to work for TypedHeader

### ISSUE THREAD

**Issue by rbtcollins** [tokio-rs/axum#2737]
- [ X] I have looked for existing issues (including closed) about this

## Bug Report

logging axum:rejections does not seem to work for TypedHeader

### Version
 0.6.13 and 0.7.5

### Platform

Linux

### Description

axum:rejections does not seem to work for TypedHeader

**Comment by mladedav** [comment]
Just to be clear, you're talking just about logging the rejections, right?

**Comment by rbtcollins** [comment]
yep, exactly

**Comment by jplatte** [comment]
Fixed in #2738 IIUC. I think it's not yet released, but we don't usually keep issues open until fixes have been released so I'll close (and remind David about releasing next week).
