### ISSUE TITLE
Is the `reqwest-response` example outdated?

### ISSUE THREAD

**Issue by frederikhors** [tokio-rs/axum#2767]
Is the example here outdated now that `http1` porting is done, right?

https://github.com/tokio-rs/axum/blob/main/examples/reqwest-response/src/main.rs

**Comment by jplatte** [comment]
Hm, it's already upgraded to reqwest 0.12, but it looks more complicated than necessary. I'm not sure actually. If you find a way to cut down on conversion boilerplate (might be simple, or not), a PR would be appreciated.

**Comment by frederikhors** [comment]
I'll PR as soon I understand how. We're trying to find a way here: https://users.rust-lang.org/t/a-proxy-with-axum-0-7-and-reqwest-0-12-based-on-http-1/112489/2.

**Comment by frederikhors** [comment]
I found two ways:

1. This is one way, from https://users.rust-lang.org/t/a-proxy-with-axum-0-7-and-reqwest-0-12-based-on-http-1/112489/5:

    ```rust
    use http_body_util::BodyExt;

    let http_client = reqwest::Client::new();

    let (headers, body) = req.into_parts();

    let req = reqwest::Request::try_from(axum::extract::Request::from_parts(
        headers,
        body.collect().await.unwrap().to_bytes(),
    ))
    .unwrap();

    let res = http_client.execute(req).await.unwrap();
    ```

1. This is another way, from https://stackoverflow.com/a/78577792:

    ```rust
    use sync_wrapper::SyncStream;

    let http_client = reqwest::Client::new();

    let req = req.map(|body| reqwest::Body::wrap_stream(SyncStream::new(body.into_data_stream())));

    let req = reqwest::Request::try_from(req).unwrap();

    let res = http_client.execute(req).await.unwrap();
    ```

I think I'll go with SyncStream.

**Comment by jplatte** [comment]
In case you're waiting for a reply, yes that sounds like a good plan :)

The first snippet would buffer the entire request body in memory, which can be a big problem for large requests.

**Comment by PaulDotSH** [comment]
> In case you're waiting for a reply, yes that sounds like a good plan :)
> 
> The first snippet would buffer the entire request body in memory, which can be a big problem for large requests.

I would be open to create a PR if the issue owner doesn't have the time to
