### ISSUE TITLE
Implement Clone for `AppendHeaders`

### ISSUE THREAD

**Issue by jbirnick** [tokio-rs/axum#2774]
- [x] I have looked for existing issues (including closed) about this

## Feature Request

Please implement `Clone` for `AppendHeaders`.

### Motivation

I need it in my project. I once and forever create an `AppendHeaders` object which contains some headers that I add to every response. However, when I create a response, the `AppendHeaders` object is consumed by `into_response_parts(...)` of `IntoResponseParts`. So I need to be able to clone it for every response.

### Proposal

Add a `#[derive(Clone)]` to the `AppendHeaders` struct.

```rust
...
#[derive(Clone)]
pub struct AppendHeaders<I>(pub I);
```

### Alternatives

I guess could only store the _contents_ of my `AppendHeaders` object, which I can clone, and then construct a new `AppendHeaders` object from cloned contents for every reponse. However, I really want to store the wrapping `AppendHeaders` object, because that it the correct semantics.

I think it's very natural that `AppendHeaders` should be clonable (if the contents are clonable), and I'm surprised that it's not already implemented.

**Comment by jplatte** [comment]
Seems reasonable, and we already derive this for many extractors, as well as the `Html` response wrappers.
Do you want to send a PR? Deriving `Copy` would be good as well for consistency.
