### ISSUE TITLE
Conversion from BodyDataStream to AsyncRead is not working

### ISSUE THREAD

**Issue by AsimmHirani** [tokio-rs/axum#2842]
- [x ] I have looked for existing issues (including closed) about this

### Version

├── axum v0.7.5
│   ├── axum-core v0.4.3
│   ├── axum-macros v0.4.1 (proc-macro)

### Platform

Linux pop-os 6.9.3-76060903-generic #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux

### Description

Hello, I am trying to stream a file from a client request into an s3 bucket. The code in question to repeat the problem is here:

```rust
#[axum::debug_handler]
async fn upload(State(s3) : State<Arc<Bucket>>, req : Request) -> Result<Response, StatusCode> {
    let file_id = rand::random::<u128>();
    let stream = req.body().into_data_stream().into_async_read();
    let file_id = format!("{}", file_id);
    s3.put_object_stream(&mut stream, file_id);
    todo!();
}
```

The conversion into async_read fails with the following error: 
```bash
error[E0271]: type mismatch resolving `<BodyDataStream as Stream>::Item == Result<Bytes, Error>`
    --> src/main.rs:115:48
     |
115  |     let stream = req.body().into_data_stream().into_async_read();
     |                                                ^^^^^^^^^^^^^^^ expected `std::io::Error`, found `axum::Error`
     |
     = note: `axum::Error` and `std::io::Error` have similar names, but are actually distinct types
```

I expected the ability to convert a BodyDataStream into an AsyncRead to interface with other asynchronous APIs. But something does not quite work, not sure what I am not understanding.

**Comment by mladedav** [comment]
We're using an `axum`-specific error so you need to map that to `std::io::Error`.

```
TryStreamExt::map_err(req.body().into_data_stream(), io::Error::other).into_async_read()
```

Alternatively you could use just `req.body().into_data_stream().map_err(io::Error::other).into_async_read()`, you just need to make sure you're using the `map_err` defined on `StreamExt`, not `BodyExt`.

**Comment by AsimmHirani** [comment]
Done
