### ISSUE TITLE
`RequestBodyLimit` docs link out of date

### ISSUE THREAD

**Issue by fs-99** [tokio-rs/axum#2844]
- [x] I have looked for existing issues (including closed) about this

## Stale Link in Docs

https://docs.rs/axum/latest/axum/extract/struct.DefaultBodyLimit.html
links to RequestBodyLimit but it's not the right link, it should be:
https://docs.rs/tower-http/latest/tower_http/limit/struct.RequestBodyLimit.html

**Comment by jplatte** [comment]
Ah yes, this is a broken intra-doc link. I'll try to figure out what's wrong soon.
