### ISSUE TITLE
feat: expose inner `WebSocketStream`

### ISSUE THREAD

**Issue by 0xJepsen** [tokio-rs/axum#2848]
- [x] I have looked for existing issues (including closed) about this

## Feature Request
I would like to be able to get the inner `WebSocketStream` from the `WebSocket` object. 

I prepose a small simple `inner()` function to be implemented on the `WebSocket` that Consumes `self` and get the inner [`tokio_tungstenite::WebSocketStream`].

### Motivation

I would like to use `ws_stream_tungstenite::ws_stream::new()` with this object to use https://github.com/tlsnotary/tlsn/blob/3554db83e17b2e5fc98293b397a2907b7f023496/notary/server/src/service/axum_websocket.rs#L363 to create proofs of tls sessions.

### Proposal
The feature could be a three line PR with the following logic in the following location. If need be it can be behind a feature flag.

```rust
  pub fn inner(self) -> WebSocketStream<TokioIo<hyper::upgrade::Upgraded>> {
    self.inner
  }
```
The implementation can go here:

https://github.com/tokio-rs/axum/blob/50274725cb2b865f2aaaa799ff81f44e6a587fd5/axum/src/extract/ws.rs#L463-L488

### Alternatives

I have looked into implementing this downstream in `ws_stream_tungstenite` but they need access to the `ATungSocket<S>` to check the buffer size and then call `TungWebSocket::new()` If another route forward is viable that i missed Im open to hearing about it and applying it to my needs. 

This change would also enable the tlsn to not need to fork the ws.rs file with the changes here 

https://github.com/tlsnotary/tlsn/blob/3554db83e17b2e5fc98293b397a2907b7f023496/notary/server/src/service/axum_websocket.rs#L363, which would enable closing: https://github.com/tlsnotary/tlsn/issues/541

**Comment by jplatte** [comment]
The tungstenite types are intentionally not exposed by `axum::extract::ws`. See [`axum-tungstenite`](https://docs.rs/axum-tungstenite/latest/axum_tungstenite/) for a crate that supports this use case.
