### ISSUE TITLE
Example for low-level-native-tls

### ISSUE THREAD

**Issue by msdrigg** [tokio-rs/axum#2853]
- [x] I have looked for existing issues (including closed) about this

### Motivation

There are currently good examples for low-level-rustls and low-level-openssl that are sufficient to get a beginner started on their project, but their is no such example for native-tls. The ecosystem around acceptors, listeners and streams is confusing enough that there is a lot of potential value to a simple example providing certificate configuration and then serving via axum.

### Proposal

There should be a new example added providing the same functionality as low-level-rustls or low-level-openssl but with the native-tls backend.

**Comment by SarthakPaandey** [comment]
Can you describe more about the issue?

**Comment by jplatte** [comment]
@SarthakPaandey What exactly is unclear to you here?

**Comment by SarthakPaandey** [comment]
Could you provide more specifics on what functionalities or configurations are unclear when using native-tls compared to rustls or openssl and in which are you addressing the issue?
