### ISSUE TITLE
0.7.5. server not reachable

### ISSUE THREAD

**Issue by DAMEK86** [tokio-rs/axum#2866]
- [x] I have looked for existing issues (including closed) about this

### 0.7.5

```
cargo tree | grep axum
├── axum v0.7.5
│   ├── axum-core v0.4.3
└── axum-test-helper v0.4.0
    ├── axum v0.7.5 (*)
```

### Platform

```
uname -a
Linux framework13-linux 6.10.3-061003-generic #202408030740 SMP PREEMPT_DYNAMIC Sat Aug  3 07:53:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
### Crates

```
axum = { version = "=0.7.5", default-features = false, features = [
    "tokio",
    "json",
    "http2"
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.39.2", features =[
    "macros",
    "rt-multi-thread",
    "signal",
] }
```

### Description

I tried this code:
```
pub async fn start_server(cfg: AppConfig) {
  let app = Router::new().nest("/",
    Router::new().route("/health", routing::get(get_config)).with_state(cfg));

  let listener: TcpListener = match TcpListener::bind(&addr).await {
    Ok(l) => l,
    Err(e) => {
        log::error!(target: "api", "Unable to create TCP listener: {}", e);
        std::process::exit(1);
    }
  };

  log::info!(target: "api", "Listening on http://{}", addr);

  axum::serve(listener, app).await.unwrap_or_else(|e| {
    log::error!(target: "api", "Unable to start server: {}", e);
    std::process::exit(1);
  });
}

#[derive(Serialize, Deserialize)]
struct HealthResponse {
    version: String,
    config: AppConfig,
}

async fn get_config(State(cfg): State<AppConfig>) -> impl IntoResponse {
    (
        StatusCode::OK,
        Json(&HealthResponse {
            version: env!("CARGO_PKG_VERSION").to_string(),
            config: cfg,
        }),
    )
        .into_response()
}

#[tokio::main]
async fn main() {
  let config = ...
  api::start_server(config).await;
}
```
cargo build works as expected and doesn't complain.
Server starts up but if i try to curl them, the server doesn't respond.
Also the port bind is working. I checked this with `netstat -tulpen`.

Workaround as described in other 0.7.5 tickets falling back to `version = "=0.7.4"`.

**Comment by Wardenfar** [comment]
I have the same issue, seems to happen when using a specific sets of features for the axum crate.

This is not working (connection reset by peer) :
```
axum = { version = "=0.7.5", default-features = false, features = [
    "tokio",
    "http2",
    "json",
    "matched-path",
    "macros",
    "query",
] }
```

But this is working as expected :
```
axum = { version = "=0.7.5" }
```

**Comment by jplatte** [comment]
Seems like a pretty uncommon thing to enable `http2` but not `http1`.

AFAIU, most HTTP 2 connections start out as HTTP 1.x connections that get upgraded. Does the problem go away when enabling `http1`?

**Comment by DAMEK86** [comment]
jub, adding "http1" feature fix make it working again.

**Comment by mladedav** [comment]
Can you provide the curl command you tried? It also creates HTTP 1.1 request with upgrade by default when asked to use HTTP 2.0 so if you didn't explicitly set prior knowledge h2, it's expected that it wouldn't work.

**Comment by jplatte** [comment]
In any case, we don't have any code for either `http1` or `http2`, these are just feature passthroughs for `hyper` (and I think `hyper-util`). If there is a bug here at all, it's not ours but hyper's.
