### ISSUE TITLE
Drop IntoResponse trait requirement from FromRequestParts and FromRequest Rejections

### ISSUE THREAD

**Issue by MOZGIII** [tokio-rs/axum#2869]
- [x] I have looked for existing issues (including closed) about this

### Motivation

Optional extractors don't need the rejection to implement `IntoResponse`. Providing an extraction with a `Rejection` that doesn't implement `IntoResponse` will indicate this extractor *must* be used as optional.

> This is a required feature for enforcing certain response shapes via the type system.

### Proposal

Make the following changes (simplified):

```diff
pub trait FromRequestParts<S>: Sized {
-    type Rejection: IntoResponse;
+    type Rejection;
```

```diff
pub trait FromRequest<S, M = private::ViaRequest>: Sized { {
-    type Rejection: IntoResponse;
+    type Rejection;
```

**Comment by mladedav** [comment]
There may be another trait for optional extractors, see #2475. It would allow pretty much what you're proposing by using `Infallible` as the rejection.

**Comment by Turbo87** [comment]
now that https://github.com/tokio-rs/axum/pull/2475 was merged I guess we can close this issue :)
