### ISSUE TITLE
Duplicate dependency `sync_wrapper` with latest version of `axum` and `axum-core`

### ISSUE THREAD

**Issue by peddermaster2** [tokio-rs/axum#2871]
- [x] I have looked for existing issues (including closed) about this

## Bug Report

With the currently latest versions of `axum` and `axum-core` the dependency on `sync_wrapper` gets added for `1.0.1` and `0.1.2`.  
This comes from `axum-core` not having a more recent release. The last was in january and the dependency got updated with c6fd8528446e8738d14a0e6e916acea51f951330 in march.

### Version
```
axum v0.7.5
axum-core v0.4.3
```
### Platform

Windows 11 64bit (not important)

**Comment by yhx-12243** [comment]
In fact fixed in c6fd852 except it is not released yet.

**Comment by Turbo87** [comment]
> Once `axum-core` releases a next version than `v0.4.3` it will be automatically solved

we're at axum-core@0.4.5 now, so I assume that this has been fixed
