### ISSUE TITLE
Missing scheme and host information from Uri.

### ISSUE THREAD

**Issue by druide** [tokio-rs/axum#2876]
Request URL (`request.uri()`) is missing the scheme and host parts, it has only a stripped path. If it is a relative URL, then there should be the full original_uri method.

```
pub async fn handler(
    req: Request, 
) -> Result<Response, StatusCode> {
    let uri = req.uri(); // <-- missing the scheme and host
```

**Comment by jplatte** [comment]
This is how the HTTP protocol works, the scheme and host are not sent to the server.

**Comment by jplatte** [comment]
If you're expecting the URI to be built from the host header and similar bits (I think http 2.0 has a `:path` pseudo-header), this would be a job for hyper. `axum` only sees the `http::Request` as it was parsed by hyper, including URI, headers and such.
