### ISSUE TITLE
FromRef derive macro prevents axum re-export

### ISSUE THREAD

**Issue by gpoblon** [tokio-rs/axum#2883]
- [x] I have looked for existing issues (including closed) about this

## Bug Report
As a user I'd expect to be able to re-export axum.
It works with basic methods and extractors.
But once trying to call `axum::extract::FromRef` derive macro, it does not compile.
This is a known issue on other rust libraries, some maintainers tends to remove it some don't (or can't).
Here is the issue: *failed to resolve: could not find `axum` in the list of imported crates*.

It is caused by the following expanded call:
```rust
impl ::axum::extract::FromRef<AppState> for Arc<Config> {
    fn from_ref(state: &AppState) -> Self {
        state.config.clone()
    }
}
```
As it is trying to access `::axum` path, it cannot work in a re-export situation.

### Version
axum 0.7.5
No other deps

### Platform
windows 64bits

### Description

I tried this code:

```rust
#[derive(Clone, mylib::axum::export::FromRef)]
pub struct AppState {
    pub config: Arc<Config>,
}
```
`mylib` lib.rs has a `pub use axum;`

I expected to see this happen:  
simply work.

Instead, this happened:  
*failed to resolve: could not find `axum` in the list of imported crates*, with an error 
When not using FromRef but other methods/extractors, my axum re-export works. Did not test with other derive macros.

**Comment by jplatte** [comment]
> This is a known issue on other rust libraries, some maintainers tends to remove it some don't (or can't).

At are you talking about removing here?

As far as I know, this issue is unfortunately unfixable until the Rust language gains new features that would allow the proc-macro to name its "parent" crate even without that being a dependency at the macro invocation site.

**Comment by gpoblon** [comment]
I've looked at a few forum pages and github issues related to this. Multiple crates are or where "affected", but I'm pretty sure I've seen one or two of these issues solved (or a workaround had been found by the issuer).
Sorry I'm not helping here.

Next person looking for it will know!
This can be labelled as rejected or closed, thank you for the explanation.
You're probably right, right since crates like serde have proposed workarounds such as `#[serde(crate = "self::serde")]` (https://github.com/serde-rs/serde/issues/1465#issuecomment-800686252)

**Comment by jplatte** [comment]
Yeah, we could add a workaround like serde has, but would people really want to use that? I haven't seen that serde feature used anywhere.

I'll close, because this seems unactionable to me.
