### ISSUE TITLE
Expose hyper::body::to_bytes in axum::body

### ISSUE THREAD

**Issue by barlog-m** [tokio-rs/axum#290]
Expose hyper::body::to_bytes in axum::body, it useful at least for tests.

For example:
```
let future = task::spawn(service.call("foo".to_string()));
let body = future.into_inner().await.unwrap().into_body();
let body_data = hyper::body::to_bytes(body).await.unwrap();
assert_eq!(body_data, Bytes::from("ok"));
```

**Comment by davidpdrsn** [comment]
I think adding hyper as a test dependency is fine. For testing axum itself, we use reqwest because of its higher level API.
