### ISSUE TITLE
Incompatibiliy between `axum::TestSever` and `tower_http::NormalizePathLayer`

### ISSUE THREAD

**Issue by agersant** [tokio-rs/axum#2901]
- [x] I have looked for existing issues (including closed) about this

### Version

- axum 0.7.5
- axum-extra 0.9.3
- tower-http 0.5.2

### Platform

x64 Linux

### Description

It is not possible to instantiate a Axum [TestServer](https://docs.rs/axum-test/latest/axum_test/struct.TestServer.html) that also applies path normalization (trailing slash trimming).

Prior discussion: https://github.com/tokio-rs/axum/discussions/2833#discussioncomment-10182358

I tried this code:

```
let router = Router::new();
let app = NormalizePathLayer::trim_trailing_slash().layer(router);
let app = ServiceExt::<axum::extract::Request>::into_make_service(app);

let server = TestServer::new(app).unwrap();
```

I expected to see this happen: The code compiles and the test server normalizes paths before routing requests.

Instead, this happened: 

```
error[E0277]: the trait bound `axum::routing::IntoMakeService<tower_http::normalize_path::NormalizePath<axum::Router>>: axum_test::transport_layer::IntoTransportLayer` is not satisfied
 --> src\server\axum\test.rs:40:32
  |
40 |         let server = TestServer::new(app).unwrap();
  |                      --------------- ^^^ the trait `axum_test::transport_layer::IntoTransportLayer` is not implemented for `axum::routing::IntoMakeService<tower_http::normalize_path::NormalizePath<axum::Router>>`
  |                      |
  |                      required by a bound introduced by this call
  |
  = help: the trait `axum_test::transport_layer::IntoTransportLayer` is implemented for `axum::routing::IntoMakeService<axum::Router>
```

**Comment by jplatte** [comment]
`axum-test` is an independent project, please report this on their repo: https://github.com/JosephLenton/axum-test
