### ISSUE TITLE
Consider adding `axum::json!`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/axum#2937]
## Feature Request

Consider adding an `axum::json!` macro that matches the `serde_json` macro syntax and avoids the stutter:

```rust
async fn hello_world() -> impl IntoResponse {
    axum::json!({ "hello": "world" })
}
```

### Motivation

Returning JSON is common. This would avoid adding an extra dependency in the end user's Cargo.toml and avoid some stutter (`Json(json!(...))`) without exposing the `serde_json` dependency.

**Comment by SabrinaJewson** [comment]
Given that this function returns `impl IntoResponse` anyway, might it be worth using an approach like [`typed-json`](https://docs.rs/typed-json) to avoid the heap allocation?

**Comment by jplatte** [comment]
That's exactly the sort of thing I was planning to write myself! Really nice that it already exists. I think that crate can be used directly by wrapping the generated type in `axum::Json` (and documenting that people are free to write either `-> Json<impl Serialize>` or `-> impl IntoResponse`). Would you be interested in making a PR for it?
