### ISSUE TITLE
Add prelude support

### ISSUE THREAD

**Issue by mrgzi** [tokio-rs/axum#2982]
Adding a prelude module to Axum could make importing easier. Preludes would save time on imports.

**Comment by mladedav** [comment]
Personally, I don't think it would really save any time if you're using rust analyzer and auto-imports.

In general, I also agree with #185 in that glob imports make code harder to understand by obscuring where things are coming from.

Generally it seems to me the community as a whole is also moving from prelude imports from what I've seen. Of course this whole thing is mostly personal preference.
