### ISSUE TITLE
Hit unreachable code when deserializing a [char; 2] inside Path

### ISSUE THREAD

**Issue by 2ndDerivative** [tokio-rs/axum#3038]
### Description

Hi, I used this struct inside a `Path`
```
#[derive(Debug, Deserialize)]
struct MoreChars {
    first_two: [char; 2],
    second_two: [char; 2],
    crate_name: String,
}
```

with the route `.route("/:first_two/:second_two/:crate_name", get(handler::<MoreChars>))`
and upon extraction of the path it hit unreachable code inside `deserialize_tuple` for `Path`

I was hoping to only hit that when the first path element is 2 characters long
Can't say much more about that, I guess that's my report.

Axum version: 0.7.9

**Comment by jplatte** [comment]
Can reproduce on `main`.

**Comment by jplatte** [comment]
I don't think serde supports `[char, 2]` as a string type. You can use `#[deserialize_with]` to write a custom deserialize function for those two fields though, that only succeeds for two-character strings. I'm also raising a PR to turn this panic into a regular path deserialization error.
