### ISSUE TITLE
Splitting WebSockets in send/receive streams?

### ISSUE THREAD

**Issue by pixelspark** [tokio-rs/axum#304]
## Feature Request

First of all, great work on Axum! Coming from Warp and Actix this feels like yet another great step forward 🥇 

### Motivation

Suppose I'd want to write a chat server using WebSockets and Axum. My server would have to listen for chat messages and then send them to all other connected clients' websockets. However, these websockets are all busy listening. As [`recv` takes a mutable reference to WebSocket](https://docs.rs/axum/0.2.3/axum/extract/ws/struct.WebSocket.html), I cannot concurrently call `send` on them while also `recv`ing.

### Proposal

Add a way to 'split' a WebSocket like you can [split Tokio's TcpStream to a TcpStreamReadHalfMut / TcpStreamWriteHalfMut](https://docs.rs/tokio/0.2.0-alpha.4/tokio/net/tcp/split/index.html).

### Alternatives

Polling or adding a time-out to recv (this would however add significant delay to messages queued for delivery to a client)

**Comment by davidpdrsn** [comment]
You can use `futures::stream::StreamExt::split` as shown [here](https://github.com/tokio-rs/axum/blob/main/examples/chat/src/main.rs#L56). It'll be [documented more ](https://github.com/tokio-rs/axum/pull/291)clearly in the next release.

**Comment by pixelspark** [comment]
Oops missed that example! Thanks :)
