### ISSUE TITLE
[Example request]: simple jwt example

### ISSUE THREAD

**Issue by silvioprog** [tokio-rs/axum#306]
It would be nice to provide a simple JWT example, something like [this](https://github.com/zupzup/rust-jwt-example).

What do you think?

**Comment by Z4RX** [comment]
Agree, it would be nice to enrich axum examples with jwt one. But it should be listed as community showcase because it will use lot of third-party crates.

Btw I can do it in 1-2 days.

**Comment by davidpdrsn** [comment]
Sounds like a good idea! Something using `jsonwebtoken` would be nice.

**Comment by silvioprog** [comment]
I'm going try to implement an example and send as PR. (btw I just started studying Axum, so it will be a naive example 😅)

**Comment by silvioprog** [comment]
Done: https://github.com/tokio-rs/axum/pull/308. 😅

**Comment by Z4RX** [comment]
Also made [example](https://github.com/Z4RX/axum_jwt_exampl), but a bit more opinioned and complex :D

**Comment by silvioprog** [comment]
@Z4RX Woooow, amazing example! 🤩

What do you think about adding the two examples? The first one shows the basic concepts of JWT, and this second shows a full integration of JWT + Axum + PG.

**Comment by Z4RX** [comment]
@silvioprog as I mentioned above, I think that it should be added to something like `community examples` section because it covers db connection, error handling, project layout and those themes  are very opinioned and shouldn't be shown as official example.

**Comment by silvioprog** [comment]
> @silvioprog as I mentioned above, I think that it should be added to something like `community examples` ...

The first, second, or both? (the first one dependes only of `jsonwebtoken`)

**Comment by Z4RX** [comment]
Your example should be added into repository examples

**Comment by Z4RX** [comment]
I think this issue should be closed now @silvioprog

**Comment by silvioprog** [comment]
Oops, I forgot to close it. Thanks a lot guys!
