### ISSUE TITLE
Bad protocol version error : example-websockets-http2

### ISSUE THREAD

**Issue by Alphapage** [tokio-rs/axum#3068]
Hello,

When updating axum-server from 0.6 to 0.7.1 in example-websockets-http2, I get a `bad protocol version: native-tls error`.
With the previous version, all is working as expected.

And just for info, when do you plan to release http2 websocket feature ?

Thank you in advance for your answers.

**Comment by mladedav** [comment]
`axum-server` is 3rd party crate, you maybe wanted to create an issue there?

We'll release http2 websockets as part of 0.8, hopefully soon.

**Comment by Alphapage** [comment]
Ok sorry !
Will fill an issue to axum-server ... +1
