### ISSUE TITLE
Add some magic around Path extractor to allow multiple instances in one handler function to match different parameters?

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#334]
In #328, a user was confused that the following handler signature doesn't work:

```rust
async fn handler(Path(ty): Path<String>, Path(id): Path<u8>) -> _;
```

as the first `Path` extractor produces the error `Invalid URL param. wrong number of parameters: 2 expected 1`.

The current solution to this is using a single `Path<(String, u8)>` handler. However, the signature above could potentially also be supported.

I think the simplest way to support it is tracking how many parameters were already extracted in the corresponding request extension, however that would break code that currently accesses the same path parameters multiple times (e.g. once in a middleware, once in the actual handler). Additional magic like resetting the "scan position" for the path parameters inside `RequestParts::new` could be employed to less likely affect existing code, but properly explaining that in the docs would probably be challenging.

Wdyt @davidpdrsn?

**Comment by davidpdrsn** [comment]
I've been thinking about this and not sure the necessary machinery is worth it. So I don't think we should work to add support for this. Using `Path<(T, K)>` to get multiple captures is already documented [here](https://docs.rs/axum/0.2.6/axum/extract/struct.Path.html#example).
