### ISSUE TITLE
Does the routes get matched in order of chain order?

### ISSUE THREAD

**Issue by kingluo** [tokio-rs/axum#367]
It seems that the routes matching is done one by one in the chain order.
If there are hundreds of thousands of routes, it would be slow.
Why not use RegexSet (https://docs.rs/regex/1.5.4/regex/struct.RegexSet.html) so that routes get matched in parallel?

Moreover, not all paths need regex, for those routes, is it meaningful to construct a balanced tree to match? The tree is also good for prefix/inclusive matching.

**Comment by davidpdrsn** [comment]
This'll be fixed in 0.3 as part of https://github.com/tokio-rs/axum/pull/363.

**Comment by kingluo** [comment]
How about a full regex match? I mean, for "/user/id.jpg", could I use regex `\.(jpg|gif)$` to match it?

Moreover, could we get regex named capture group into param map? e.g. `(?<title>\w+)`

**Comment by davidpdrsn** [comment]
Sorry but we have no plans to support any sort of regex routes. It often leads to complex routes that are hard to maintain and routing implementations that are hard to optimize.

`/foo`, `/:key`, and `/*key` is all that we'll support for now. I have personally found that to cover all my needs.

**Comment by kingluo** [comment]
Why not use a binary search tree just like what Nginx does? In the Nginx way, the paths at the same level are sorted in a balanced binary tree, while the subtree (also balanced binary tree) stores sub nodes with the same common prefix.
In the radix tree, it seems that at the same level, it compares the node value one by one?

**Comment by davidpdrsn** [comment]
Please file an issue for matchit if you want to discuss the actual routing implementation.
