### ISSUE TITLE
Web Platform URLPattern

### ISSUE THREAD

**Issue by gmosx** [tokio-rs/axum#368]
### Motivation

It would be beneficial to use a standard format for defining routes.

### Proposal

I was pleased to see that Axum supports a format very similar to `URLPattern` (https://web.dev/urlpattern/) for defining routes. It would be nice to explicitly mention this in the documentation even if a subset of the functionality is currently supported. Moreover, it would be a reasonable future goal to strive for complete compatibility with the `URLPattern` standard.

### Alternatives

Affinity to the `URLPattern` standard is not explicitly mentioned in the documentation.

**Comment by davidpdrsn** [comment]
We are making some changes to routing in https://github.com/tokio-rs/axum/pull/363. The main syntactic change is adding support for wildcard routes such as `/*key`. We are currently not planning on making any other routing related changes.

What you're linking appears to be a JavaScript thing and isn't something I've heard of before. Not sure how it's relevant for Axum.

**Comment by gmosx** [comment]
This is more like a 'Web Platform' API than a 'JavaScript thing. All I am suggesting is to _consider_ aligning with this upcoming 'standard'.

**Comment by davidpdrsn** [comment]
Alright. Im not familiar with it so have some questions:

- What is axum missing to match this standard?
- Does it have any library support in the rust ecosystem?
- Any other frameworks that use it, rust or not
- Who is behind the standard?
- Is it used in a significant way in other ecosystems similar for example to openapi?

**Comment by gmosx** [comment]
> * What is axum missing to match this standard?

No need to support everything, just keep it in mind while designing new features (e.g. the wildcard)

> * Does it have any library support in the rust ecosystem?

https://github.com/denoland/rust-urlpattern

> * Any other frameworks that use it, rust or not

e.g. Deno

> * Who is behind the standard?

WEB PLATFORM INCUBATOR COMMUNITY GROUP

https://github.com/WICG/urlpattern
https://www.w3.org/community/wicg/

> * Is it used in a significant way in other ecosystems similar for example to openapi?

Not sure, this is an 'upcoming' thing.

**Comment by gmosx** [comment]
Anw, #363 looks nice also :)

**Comment by davidpdrsn** [comment]
Interesting that they're using it in deno. Guess it's worth keeping and eye on but don't think we'll be making more routing changes outside of what's in https://github.com/tokio-rs/axum/pull/363

Thanks for bringing it up but think I'll close this for now. We can always reconsider if it gains good traction in the future.
