### ISSUE TITLE
support feature bundle static files to binary

### ISSUE THREAD

**Issue by bigdogs** [tokio-rs/axum#379]
## Feature Request

Support feature like [actix_web_static_files](https://docs.rs/actix-web-static-files/3.0.5/actix_web_static_files/index.html)

### Motivation

All resource file can be bundle to a single binary,   it make distribution convenient , for some simple web project

**Comment by davidpdrsn** [comment]
As far as I understand this doesn't have to be built into axum and could be done entirely in a third party crate.

**Comment by Z4RX** [comment]
@bigdogs you can use [rust-embed crate](https://crates.io/crates/rust-embed)

**Comment by bigdogs** [comment]
@Z4RX Thanks for your suggestion,  I'll check it later

**Comment by davidpdrsn** [comment]
I'll close this since it doesn't require anything new from axum.

**Comment by bigdogs** [comment]
Take a quick look at rust-embed crate, it doesn't seems to meet my needs fully.

actix_web_static_files compiles all static resource(css, js, png…) to specific rust structure,  I just need to tell actix_web to use that rust struct to serve it like normal directory, and then everything works fine .

 For rust-embed, seems it just compile resource to rust "file",  Currently I have no idea about how to tell axum to use thoses "files" to make website works… I think I need to investigate further for both rust-embed and axum creates :)

**Comment by lazywalker** [comment]
> Take a quick look at rust-embed crate, it doesn't seems to meet my needs fully.
> 
> actix_web_static_files compiles all static resource(css, js, png…) to specific rust structure, I just need to tell actix_web to use that rust struct to serve it like normal directory, and then everything works fine .
> 
> For rust-embed, seems it just compile resource to rust "file", Currently I have no idea about how to tell axum to use thoses "files" to make website works… I think I need to investigate further for both rust-embed and axum creates :)

https://github.com/pyros2097/rust-embed/blob/master/examples/axum.rs
have you check this demo?

**Comment by bigdogs** [comment]
@lazywalker That's exactly what I want , Thank you :) !
