### ISSUE TITLE
Allow access to matched route pattern(s) from middlewares

### ISSUE THREAD

**Issue by gsson** [tokio-rs/axum#386]
## Feature Request

As far as I can tell it's not possible to access information about if a route matched and if so, which route pattern (or patterns in case of nested routes) was matched. This is something a lot of services in environments I've worked needs.

I could implement my own router (cue Bender quote), but I think this would be a common enough use case for production services that it would be valuable to have in the standard router.

### Motivation

I'm trying to create a minimal web server that does nothing of importance, but does it while serving up request logs and metrics in a particular format.

My sample server exposes two endpoints, `/api/hello/:name` and `/prometheus`. The first just returns `format!("Hello, {}!", name)`, and the second returns application metrics.

In this service, I would use the pattern for my logs (currently emitting `tracing::info!` events, probably with the path parameters at separate keys) and in the request metrics (currently using `opentelemetry` and Prometheus)

Currently I log and split the metrics on the full path, but doing that with any sort of cardinality on the path parameters won't scale.

I'm looking to create collapsed metrics like eg.
```
http_server_requests_seconds_count{method="GET",status="200",uri="/api/hello/:name"} 4
...
```
instead of my current
```
http_server_requests_seconds_count{method="GET",status="200",uri="/api/hello/world"} 1
http_server_requests_seconds_count{method="GET",status="200",uri="/api/hello/foo"} 1
http_server_requests_seconds_count{method="GET",status="200",uri="/api/hello/bar"} 1
http_server_requests_seconds_count{method="GET",status="200",uri="/api/hello/fnord"} 1
...
```

In addition I would like the ability to separate a "404" that was due to no route matching and a "404" due to a particular resource identified by parameters, so I can have metrics (and corresponding logs) like so:
```
http_server_requests_seconds_count{method="GET",status="404",uri=""} 1
http_server_requests_seconds_count{method="GET",status="404",uri="/api/hello/:name"} 1
...
```

Sample server source code here: https://github.com/gsson/mini-web-rs/tree/axum-issue-386 (see `meter_layer.rs`)

### Proposal

I think it would be useful to use the matched route pattern as attributes in logs, request metrics and such. The absence of a matched pattern in the case of 404s is similarly useful to distinguish a missed route from a missing resource.

I guess attaching a public extension to the request/response would do the trick, but I'm still an Axum noob.

**Comment by davidpdrsn** [comment]
I believe I've found a workaround. I first want apologies for the crazy types, if/when this becomes built in to axum we'll make sure to have a simpler API. But yeah this seems to work:

```rust
use axum::{
    body::{box_body, BoxBody},
    extract::Path,
    handler::get,
    http::Request,
    routing::Route,
    AddExtension, AddExtensionLayer, Router,
};
use std::sync::Arc;
use tower::ServiceBuilder;
use tower_http::{
    classify::{ServerErrorsAsFailures, SharedClassifier},
    map_response_body::{MapResponseBody, MapResponseBodyLayer},
    trace::{MakeSpan, Trace, TraceLayer},
};

#[tokio::main]
async fn main() {
    // Set the RUST_LOG, if it hasn't been explicitly defined
    if std::env::var_os("RUST_LOG").is_none() {
        std::env::set_var("RUST_LOG", "example_testing=debug,tower_http=debug")
    }
    tracing_subscriber::fmt::init();

    let app = Router::new().route_with_path_tracing(
        "/users/:id",
        get(|Path(id): Path<String>| async move {
            tracing::debug!(%id);
        }),
    );

    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], 3000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

trait RouterExt<S> {
    fn route_with_path_tracing<T>(self, path: &str, svc: T) -> Router<RouteWithPathTracing<T, S>>;
}

impl<S> RouterExt<S> for Router<S> {
    fn route_with_path_tracing<T>(self, path: &str, svc: T) -> Router<RouteWithPathTracing<T, S>> {
        let path: Arc<str> = path.into();
        let svc = ServiceBuilder::new()
            .layer(MapResponseBodyLayer::new(box_body as _))
            .layer(AddExtensionLayer::new(RoutePath(path.clone())))
            .layer(TraceLayer::new_for_http().make_span_with(MakeSpanFromPath))
            .service(svc);
        self.route(&path, svc)
    }
}

type RouteWithPathTracing<T, S> = Route<
    MapResponseBody<
        AddExtension<
            Trace<T, SharedClassifier<ServerErrorsAsFailures>, MakeSpanFromPath>,
            RoutePath,
        >,
        fn(TraceBody) -> BoxBody,
    >,
    S,
>;

type TraceBody = tower_http::trace::ResponseBody<
    BoxBody,
    tower_http::classify::NeverClassifyEos<tower_http::classify::ServerErrorsFailureClass>,
    tower_http::trace::DefaultOnBodyChunk,
    tower_http::trace::DefaultOnEos,
    tower_http::trace::DefaultOnFailure,
>;

#[derive(Clone)]
struct RoutePath(Arc<str>);

#[derive(Clone, Copy)]
struct MakeSpanFromPath;

impl<B> MakeSpan<B> for MakeSpanFromPath {
    fn make_span(&mut self, request: &Request<B>) -> tracing::Span {
        let RoutePath(path) = request.extensions().get::<RoutePath>().unwrap();
        tracing::debug_span!(
            "request",
            method = %request.method(),
            path = %path,
        )
    }
}
```

That results in logs like this:

```
Oct 14 23:42:57.684 DEBUG request{method=GET path=/users/:id}: tower_http::trace::on_request: started processing request
Oct 14 23:42:57.685 DEBUG request{method=GET path=/users/:id}: example_testing: id=123
Oct 14 23:42:57.685 DEBUG request{method=GET path=/users/:id}: tower_http::trace::on_response: finished processing request latency=1 ms status=200
```
