### ISSUE TITLE
Extractor similar to `actic_web::web::Path`

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#42]
Axum already has [`UrlParams`](https://docs.rs/axum/0.1.1/axum/extract/struct.UrlParams.html) and [`UrlParamsMap`](https://docs.rs/axum/0.1.1/axum/extract/struct.UrlParamsMap.html) for extracting data from request URIs. However I was recently made aware of [`actic_web::web::Path`](https://docs.rs/actix-web/3.3.2/actix_web/web/struct.Path.html) which seems more powerful since it relies on `serde::Deserialize`. I think that is something we should look into.

**Comment by sunli829** [comment]
Maybe we can copy this file directly?

https://github.com/actix/actix-net/blob/master/actix-router/src/de.rs

**Comment by davidpdrsn** [comment]
Yes I had the same thought 👍 

Would have to read through the code though and make sure it fits with the rest of axum. There are also some commented tests towards the bottom which we should look into.

And include their license at the top of file.

**Comment by davidpdrsn** [comment]
I'm also curious if we even need [`UrlParams`](https://docs.rs/axum/0.1.1/axum/extract/struct.UrlParams.html) and [`UrlParamsMap`](https://docs.rs/axum/0.1.1/axum/extract/struct.UrlParamsMap.html) when this is merged. Would be nice if `Path` could do everything.

**Comment by sunli829** [comment]
Yes, `Path` looks like it can replace `UrlParams` and `UrlParamsMap`, I will look into it tomorrow.
