### ISSUE TITLE
Support for Vec in Query?

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#434]
### Discussed in https://github.com/tokio-rs/axum/discussions/433

<div type='discussions-op-text'>

<sup>Originally posted by **Vesafary** October 29, 2021</sup>
Hi! 
I've been struggling with this for a while, and didn't get it to work. 
Looking through the docs and examples also didn't give me the answer.

What I'm looking for is support for one of the following:
```
<url>?id=1&id=2&id=3
<url>?id=[1, 2, 3]
```

I've tried several options like
```
struct IdQuery {
    ids: Vec<uuid::Uuid>,
}
async fn get_ids(filter: Query<IdQuery>)
```
```
struct IdQuery {
    id: uuid::Uuid,
}
async fn get_ids(filter: Query<Vec<IdQuery>>)
```
Of course I can implement it myself using the RawQuery extractor, but it seems like fairly basic usage so I was wondering whether I did something wrong.

Cheers!</div>

**Comment by ezracelli** [comment]
For the curious, the patch of `serde_urlencoded` mentioned above is now maintained as a separate crate: https://crates.io/crates/serde_html_form

Other relevant issues in `serde_urlencoded` with its maintainer's reasoning as to why this isn't natively supported:

- https://github.com/nox/serde_urlencoded/issues/6
- https://github.com/nox/serde_urlencoded/issues/75

**Comment by jplatte** [comment]
Yes, and we have `Query` and `Form` extractors in axum-extra that use it.

**Comment by flo-at** [comment]
> `id=[1,2,3]` already works with `serde_urlencoded` if you add a small helper function along the lines of
> 
> ```rust
> fn deserialize_array<'de, D, T>(deserializer: D) -> Result<Vec<T>, D::Error>
> where
>     D: Deserializer<'de>,
>     T: Deserialize<'de>,
> {
>     let s = String::deserialize(deserializer)?;
>     let v = todo!("parse the bracketed comma-separated items")
>     Ok(v)
> }
> ```
> 
> and use it with `#[serde(deserialize_with = "deserialize_arrray")]`.

This does not work for strings though. At least I haven't found a way to make it work. The problem is that at that point, the string `s` is already url-decoded, so any `[`, `]`, or `,` in the array element string makes it impossible to decide which comma is a delimiter and which is part of the string element.

The workaround with the custom Extractor that uses serde_qs is not perfect either because it's not possible to apply this to only one field but only the whole struct afaik.

What's left is:
- escaping the delimiters inside the element strings
- base64(url) encode the element strings

If you guys see a better way to make this work please help me out!
Cheers.

**Comment by flo-at** [comment]
@jplatte After some fiddling I found a working solution that is alright. It's a combination of the `axum_extra::extract::Query` extractor and a `#[serde(default, deserialize_with(..))]` attribute, like this:
```rust
#[derive(serde::Deserialize)]
struct SearchArgs {
    #[serde(default, deserialize_with = "filter_vec_deserialize")]
    filters : Option<Vec<Filter>>,
}
```
`filter_vec_deserlialize` then uses `let opt = Option::<Vec<String>>::deserialize(deserializer)?;` to get the individual strings that I handle myself. This internally uses the `Query` extractor from `axum_extra`.

This way I can use my custom deserializer on the inner type `Filter` and let `serde_html_form` handle the `Vec<String>` part.
Thanks for the hint!

**Comment by arcstur** [comment]
Using Form in the axum-extra crate solved it for me really quickly.

**Comment by joebnb** [comment]
> Using Form in the axum-extra crate solved it for me really quickly.

https://docs.rs/axum-extra/0.9.3/axum_extra/extract/struct.Query.html
