### ISSUE TITLE
Enhance documentation - hello world example. cant find hyper::server::Server

### ISSUE THREAD

**Issue by jcbritobr** [tokio-rs/axum#44]
Hello, 

I'm trying to build your examples but I can't cofigure a custom project, because I don't know where hyper::Server are.

![image](https://user-images.githubusercontent.com/6579862/127708321-48d33749-c9af-4a27-a42f-335c57dc0c90.png)

Below are my Cargo.toml file

![image](https://user-images.githubusercontent.com/6579862/127708401-589530db-d03b-45d5-9f72-56f19ffc6f5b.png)

**Comment by davidpdrsn** [comment]
You have to enable hyper's `http1` or `http2` feature.

**Comment by jcbritobr** [comment]
> 
> 
> You have to enable hyper's `http1` or `http2` feature, depending on what your needs are.

Thank you very much
