### ISSUE TITLE
Panic merging routes with same path but different method

### ISSUE THREAD

**Issue by ufoscout** [tokio-rs/axum#457]
### Version
axum v0.3.0

### Platform
$ uname -a
Linux ufo-lap-1 5.11.0-38-generic #42-Ubuntu SMP Fri Sep 24 14:03:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Description
When two routes with the same path are merged, even if they handle different HTTP methods, an "Invalid Route" error is thrown.
Here a small reproduced:

``` rust
use axum::{routing::{get, post}, Router};

fn route_get() -> Router {
    Router::new().route("/", get(|| async { "Hello, World!" }))
}

fn route_post() -> Router {
    Router::new().route("/", post(|| async { "Hello, World!" }))
}

// This panics with this message:
// thread 'test_merge' panicked at 'Invalid route: insertion failed due to conflict with previously registered route: /'
#[test]
fn test_merge() {
    Router::new()
    .merge(route_get())
    .merge(route_post());
}
```

Please note that this works as expected in axum 0.2:
``` rust
// AXUM 0.2
#[test]
fn test_merge() {
    Router::new()
    .or(route_get())
    .or(route_post());
}
```

This problem was found migrating an application from axum 0.2 to 0.3 and it is currently a blocker for our migration :(

**Comment by davidpdrsn** [comment]
Yep this was changed in 0.3 so you have to add all methods for routes up front. There are no current plans to change this. See also https://github.com/tokio-rs/axum/issues/451.

**Comment by davidpdrsn** [comment]
I've added a mention of this in the changelog https://github.com/tokio-rs/axum/commit/420918a53ab37061761e62144f483a4da8f37824
