### ISSUE TITLE
Document how Axum works

### ISSUE THREAD

**Issue by hamza1311** [tokio-rs/axum#482]
As a newcomer to Axum, it's hard to understand what type is returned by a function, which trait is implemented for a certain type or where a method comes from. The root docs on docs.rs explain the higher level workings of Axum and how to use it but they don't explain the type system magic Axum pulls (unlike, say, Rocket) to work.

`Handler` trait is an example of such magic. Anyone who doesn't know about it's existence would be confused as to how and why the code works. Also some re-exports cause error messages which don't align with the signature on docs.rs. One such example is of `MethodRouter`. The error message mentions `axum::routing::MethodRouter` re-export whereas when searched on docs.rs, that is no where to be found:
![docs.rs screenshot](https://media.discordapp.net/attachments/907281052991647804/907281879584079902/unknown.png)

**More Context:**  
Discord discussion: [the thread](https://discord.com/channels/500028886025895936/870760546109116496/907281052991647804)

**Comment by davidpdrsn** [comment]
The specific issue with `MethodRouter` will be addressed in 0.4 where I plan on writing a new method router that supports both handlers and services so we don't need two types. Hinted at [here](https://github.com/tokio-rs/axum/pull/459#issuecomment-959582019). With that new design you'll be able to do something like `get(handler).post(other_handler).put_service(some_service)` which should be a lot simpler.

**Comment by davidpdrsn** [comment]
This started due some confusion over two types both called `MethodRouter`. That has been resolved by https://github.com/tokio-rs/axum/pull/521 and 0.4.0 will only have one `MethodRouter`.

As far as `Handler` being hard to discover I'm not sure I agree. Its featured quite prominently in the docs with lots of examples. I also don't think a new user needs to be concerned with exactly how the `Handler` trait works and I'm worried it might confused people. For those who want to know I would also hope looking at its [implementors](https://docs.rs/axum/0.3.3/axum/handler/trait.Handler.html#implementors) makes it somewhat clear. There is no magic, just a trait implemented for functions that take 0 to 16 arguments (the trick being to use `(T,)` for the one argument case).

As far which methods return which types and what which traits are implemented for what, that is all [in the generated docs](https://docs.rs/axum).

If there are specific questions the docs don't answer then I think those should be filed as separate issues and looked at individually. "Document how it all works" isn't feasible in my opinion 😕

Therefore I'll close this for now.
