### ISSUE TITLE
Make the `B` type parameter in `Handler` default to `axum::body::Body`

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#502]
There are some use cases for building handlers dynamically which can be done like this:

```rust
fn make_handler<B>(env: &'static str) -> impl Handler<B, (Path<String>,)>
where
    B: Send + 'static,
{
    move |Path(id)| async move {
        ...
    }
}
```

However if the request body type is `axum::body::Body` (which it is by default unless you add a middleware that changes it) then having to specify the `B` type param is a little annoying.

We should change the `Handler` trait so `B` defaults to `Body`:

```diff
-pub trait Handler<B, T>: Clone + Send + Sized + 'static {
+pub trait Handler<T, B = Body>: Clone + Send + Sized + 'static {
```

Note this requires changing the order of the type params since types with defaults must be at the end of the list. So its a breaking change we can make for 0.4

**Comment by jplatte** [comment]
To make the improvement clearer for the cases mentioned:

```diff
- fn make_handler<B>(env: &'static str) -> impl Handler<B, (Path<String>,)>
+ fn make_handler(env: &'static str) -> impl Handler<(Path<String>,)>
- where
-     B: Send + 'static,
  {
      move |Path(id)| async move {
          ...
      }
  }
