### ISSUE TITLE
Consider using serde_qs instead of serde_urlencoded for deserializing Query

### ISSUE THREAD

**Issue by theowenyoung** [tokio-rs/axum#504]
### Motivation

Hi, for query string like  `key[]=value1&key[]=value2`,  `serde_urlencoded` will not respect it as an array, could we consider using [serde_qs](https://github.com/samscott89/serde_qs) instead of serde_urlencoded for deserializing Query?

https://github.com/tokio-rs/axum/blob/c7b8813c4715afd0a6fdf0872545a516bd8e1924/axum/src/extract/query.rs#L60

### Proposal

Just using `serde_qs::from_str<T>(raw_query_string)` instead of `serde_urlencoded`

### Alternatives

Yes, now I can get the raw query string to parse it.

**Comment by davidpdrsn** [comment]
There is no standard way to serialize arrays in query strings, therefore `serde_urlencoded` doesn't support it. Therefore I think its also the right choice for axum. Note that warp and actix-web also uses `serde_urlencoded`.

See https://github.com/tokio-rs/axum/issues/434 for more details and [a workaround](https://github.com/tokio-rs/axum/issues/434#issuecomment-954898159).
