### ISSUE TITLE
Remove unnecessary header validation

### ISSUE THREAD

**Issue by tbillington** [tokio-rs/axum#531]
### Motivation

When returning responses in user supplied functions the `IntoResponse` [implementations validate the header values on every response](https://github.com/tokio-rs/axum/blob/main/axum/src/response/mod.rs#L476). This repeated checking is unnecessary.

### Proposal

Two options

1. Skip the validation performed by `HeaderValue::from_static` when inserting into the response headers. The header values used by the implementations are known to be good so this shouldn't be an issue to 'assert' this fact in code.
2. Perform the check once (lazy static?) then copy/clone the header value to avoid the need for validation per-request.

**Comment by davidpdrsn** [comment]
I suppose putting the header values into constants (or statics?) is the easier solution. `HeaderValue::from_static` is `const` as of a recent release of `http`.

I want axum to remain `unsafe` free so something like `HeaderValue::from_maybe_shared_unchecked` is not an option.

**Comment by davidpdrsn** [comment]
I did a quick benchmark comparing 0.3.4 from crates with a version that stored the content-type for `Json` in a static.

Diff:

```diff
diff --git a/axum/Cargo.toml b/axum/Cargo.toml
index 011ef0b..890c0ed 100644
--- a/axum/Cargo.toml
+++ b/axum/Cargo.toml
@@ -25,7 +25,7 @@ async-trait = "0.1.43"
 bitflags = "1.0"
 bytes = "1.0"
 futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
-http = "0.2"
+http = "0.2.5"
 http-body = "0.4.4"
 hyper = { version = "0.14.14", features = ["server", "tcp", "stream"] }
 matchit = "0.4.4"
diff --git a/axum/src/json.rs b/axum/src/json.rs
index 75b9a58..f3106fc 100644
--- a/axum/src/json.rs
+++ b/axum/src/json.rs
@@ -176,6 +176,8 @@ where
     type BodyError = Infallible;

     fn into_response(self) -> Response<Self::Body> {
+        static APPLICATION_JSON: HeaderValue = HeaderValue::from_static("application/json");
+
         let bytes = match serde_json::to_vec(&self.0) {
             Ok(res) => res,
             Err(err) => {
@@ -188,10 +190,8 @@ where
         };

         let mut res = Response::new(Full::from(bytes));
-        res.headers_mut().insert(
-            header::CONTENT_TYPE,
-            HeaderValue::from_static("application/json"),
-        );
+        res.headers_mut()
+            .insert(header::CONTENT_TYPE, APPLICATION_JSON.clone());
         res
     }
 }
```

Benchmark code:

```rust
use std::time::Instant;
use axum::{response::IntoResponse, Json};

fn main() {
    let n = 10_000_000;

    let start = Instant::now();
    for _ in 0..n {
        Json(()).into_response();
    }
    dbg!(start.elapsed() / n);
}
```

Results:
- Baseline: 248ns
- With `static` patch: 237ns

So a delta of 11ns which arguably isn't much. So I'm not convinced we need to change anything here. Thoughts?

**Comment by jplatte** [comment]
It's a measureable improvement and doesn't really complicate the code, so why not?

**Comment by davidpdrsn** [comment]
Mostly just because of needless churn 🤷 but sure if someone wants to change this go ahead!

**Comment by jplatte** [comment]
I've tried it myself with that benchmark and can't actually see a difference between inline / static and also a named const variation where the `.clone()` is not needed when running them all a few times.

**Comment by davidpdrsn** [comment]
It just have been jitter or general nondeterminism. I only ran the benchmark a couple of times. I'm on an m1 macbook air.

In theory one could assume that since the `HeaderValue::from_static` is `const` the compiler is able to optimize it automatically.

**Comment by jplatte** [comment]
No, if the compiler would implicitly evaluate `const fn` calls with constant / literal arguments at compile time, that could turn runtime panics into compile-time panics, which could lead to a working program (where a never-taken branch would error) not compiling anymore.

In the future it will be easier to opt into part of a function being evaluated at compile time with [inline `const {}` expressiosn](https://github.com/rust-lang/rust/issues/76001).

**Comment by davidpdrsn** [comment]
Ah right that makes sense!

**Comment by jplatte** [comment]
Oh, since it wasn't a `#[bench]` benchmark I just added it as an example and used `cargo run`. Should have used `cargo run --release`! 🤦🏼

PR to use named constants incoming.

**Comment by tbillington** [comment]
Oh wow, wrote this at night, woke up to it done :joy:
