### ISSUE TITLE
Add metrics endpoint support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [tokio-rs/axum#547]
## Feature Request
Add /metrics route and print collected metrics

**Comment by davidpdrsn** [comment]
This can be done by writing your own [`tower::Service`](https://docs.rs/tower/0.4.11/tower/trait.Service.html) middleware that collects the metrics you need. We have middleware starter template [here](https://docs.rs/axum/0.3.4/axum/#writing-your-own-middleware).

I have good experience with [metrics](https://crates.io/crates/metrics) and [metrics-exporter-prometheus](https://crates.io/crates/metrics-exporter-prometheus). I happened to post an example [here](https://github.com/kube-rs/version-rs/issues/8#issuecomment-957753050) a while ago.

Over time I would like for tower-http to provide more metrics. I[t currently only has in-flight requests](https://docs.rs/tower-http/0.1.2/tower_http/metrics/index.html). I haven't been able to find the right design for it yet though. But until then you have to roll your own.

We don't plan on building anything specific into axum as middleware is the right place for stuff like this to live so I'll close this issue for now. Feel free to ask follow up questions.
