### ISSUE TITLE
Allow defining routes multiple times again

### ISSUE THREAD

**Issue by winterqt** [tokio-rs/axum#549]
## Feature Request

Allow defining (non-conflicting) routes multiple times again:

```rust
Router::new()
.route("/foo", get(get_foo))
.route("/foo", post(post_foo))
```

### Motivation

I have a custom framework of sorts built around axum, and one of the features is automating the definition of routes, which took advantage of this functionality (which is now infeasible in its current state due to the new matchit router).

### Proposal

Maybe by doing the route validation at the end of the router definition chain, i.e. a `build` method. This specific implementation has the advantage of not panicking upon invalid routes (a `Result` could be returned from the `build` method). The disadvantage is that this breaks existing code.

### Alternatives

Not really sure if there are any, honestly.

**Comment by jplatte** [comment]
This is supported on the latest git version and will be part of the 0.4.0 release.
