### ISSUE TITLE
Remove the associated `Body` type on `IntoResponse`

### ISSUE THREAD

**Issue by KaiJewson** [tokio-rs/axum#570]
### Motivation

Dealing with multiple distinct body types is difficult. For example, the following code does not compile:

```rs
async fn index() -> impl IntoResponse {
    if condition() {
        "hello world".into_response()
    } else {
        ().into_response()
    }
}
```

If users want it to compile they would have to add `.map(body::boxed)` after every call to `.into_response()`. That's a bit boilerplatey however and not an immediately obvious solution.

When writing generic code, `IntoResponse` having a body associated type means that these specific bounds:

```rs
B: Body<Data = Bytes> + Send + 'static,
B::Error: Into<BoxError>,
```

tend to profilerate all over the codebase. While not being enormously long, it does become very tedious to have them everywhere in my experience. Especially since it often will require introducing a where clause where there was none before, it's not ideal.

### Proposal

Change the definition of `IntoResponse` to be this:

```rs
pub trait IntoResponse: Sized {
    fn into_response(self) -> Response<BoxBody>;
}
```

I doubt there is much benefit to providing typed access to the underlying body type of `IntoRequest` implementors - the majority of body types (`Empty`, `Full`, `hyper::Body`, `sse::Body` and `StreamBody`) are totally opaque after creation anyway, so they might as well be boxed. In future it might be desirable to provide downcasting methods on `BoxBody` to support this. Additionally, the trait bounds on the body type of `IntoResponse` are identical to those required to make a `BoxBody`, so we don't lose any generic abilities that we haven't already lost (e.g. having a `!Send` body is already impossible).

There is no performance gain in not boxing the bodies in most code - since #569 bodies will only ever be boxed to one layer, so double-boxing is not a concern, and all handlers (the primary user of the `IntoResponse` trait) will end up boxing the body anyway. The only case where it would affect performance is if a user is using `IntoResponse`, but for some reason not handlers or any other parts of Axum - but no-one does that.

Anecdotally, in my personal project I gave up on generic bodies entirely and just switched to using `BoxBody` everywhere, and it's a much nicer experience. I added an extension trait to `IntoResponse` that gives `.into_response_boxed()` - more typing than otherwise, but worth it because it's significantly less hassle to deal with.

### Alternatives

- Provide `.into_response_boxed()`. This would unfortunately lead to two distinct ways of writing handlers, and more tiny things for the user to decide. It could also lure users into thinking `.into_response()` is somehow more performant than the boxed version, when that's most likely not the case. To return a response users would have to write `impl IntoResponse<Body = BoxBody>`, which is more of a mouthful than just `impl IntoResponse`.

**Comment by davidpdrsn** [comment]
All the reasons sound good. I think we should do it! PR welcome 😊

**Comment by KaiJewson** [comment]
An extension of this is to provide a type alias `pub type Response<B = BoxBody> = http::Response<B>;`, so `Response` would default to the most common body type. I think it would make sense to have it in the `response` module.
