### ISSUE TITLE
Add helper fn to test a JSON response

### ISSUE THREAD

**Issue by ufoscout** [tokio-rs/axum#59]
### Motivation
As of now, to test a REST endpoint that returns a JSON object, two steps are needed; the first one, to get the body of the response using hyper, and the second one to convert it to JSON with serde:
```rust
    #[tokio::test]
    async fn json() {
        let app = app();

        let response = app.oneshot(Request::builder()...).await.unwrap();

        let body = hyper::body::to_bytes(response.into_body()).await.unwrap(); 
        let body: Value = serde_json::from_slice(&body).unwrap();

        assert_eq!(body, json!({ "data": [1, 2, 3, 4] }));
    }
```

### Proposal
It would be great to have a single fn that does all the job, so one can write, for example:
```rust
    #[tokio::test]
    async fn json() {
        let app = app();

        let response = app.oneshot(Request::builder()...).await.unwrap();

        let body: Value = test::read_response_json(response).unwrap();

        assert_eq!(body, json!({ "data": [1, 2, 3, 4] }));
    }
```

though this would require, probably, the creation of a `test` module

**Comment by davidpdrsn** [comment]
Decided not provide something like this, at least for now. See https://github.com/tokio-rs/axum/pull/60#issuecomment-890493168 for my reasoning.
