### ISSUE TITLE
adaptate the old api

### ISSUE THREAD

**Issue by NateLing** [tokio-rs/axum#593]
I am moving my http api to axum, there are so many api like :

```rust
pub type GenericError = Box<dyn std::error::Error + Send + Sync + 'static>;
pub type Result<T> = std::result::Result<T, GenericError>;

pub fn record(
  Json(mut payload): Json<NewAnnouncement>,
) -> Result<usize> {
  payload.publish = false;
  payload
    .write()
}

/// by this way, It make Ok<T> to response 200 and other error to different http status code.
```

but , they are not working with axum post:

```rust
pub fn register_routes() -> axum::Router {
  axum::Router::new().route("/", post(record))
}
```

How to fix it?

**Comment by davidpdrsn** [comment]
See the docs for how to generate responses https://docs.rs/axum/latest/axum/response/index.html.

If you return `Result<T, E>` from a handler both `T` and `E` must implement `IntoResponse`, which `usize` and `Box<dyn std::error::Error + Send + Sync + 'static>` don't. So you need to return something else, that implements `IntoResponse`.

For the error you'll have to make something like

```rust
struct AppError(Box<dyn std::error::Error + Send + Sync + 'static>);
```

and implement `IntoResponse` for that.

Same for `usize`.
