### ISSUE TITLE
Require `Output = ()` on `WebSocketStream::on_upgrade`

### ISSUE THREAD

**Issue by SabrinaJewson** [tokio-rs/axum#636]
### Motivation

By accepting a future with any return type, users can easily make a mistake if they for example give a future that outputs a `Result`, not realizing that the `Result` will simply be ignored.

### Proposal

Change the bound on [`WebSocketUpgrade::on_upgrade`](https://docs.rs/axum/latest/axum/extract/ws/struct.WebSocketUpgrade.html#method.on_upgrade) to `Fut: Future<Output = ()>` in 0.5.

**Comment by davidpdrsn** [comment]
Makes sense 👍

**Comment by davidpdrsn** [comment]
Fixed in https://github.com/tokio-rs/axum/pull/646
