### ISSUE TITLE
InternalServerError when Request and Json extractors are used together

### ISSUE THREAD

**Issue by ufoscout** [tokio-rs/axum#64]
The following test returns HTTP status 500:

```rust
#[tokio::test]
async fn test_extractors() {

    let app = route("/api", 
    post(|req: Request<Body>, payload: extract::Json<String>| async move {
        println!("CALL RECEIVED");
    }));

    // Act
    let response = app
        .oneshot(Request::builder()
            .method(http::Method::POST)
            .header(http::header::CONTENT_TYPE, "application/json")
            .uri("/api")
            .body(Body::from(
                serde_json::to_vec(&"payload").unwrap(),
            )).unwrap())
        .await
        .unwrap();

    // Assert
    assert_eq!(response.status(), StatusCode::OK);

}
```
The issue is caused by the fact that the Request and the Json extractors are used at the same time.

I tried to replace the `Request` with `extract::RequestParts`, but, by doing that, the compiler complains that 
```
the trait bound `[closure@....]: axum::handler::Handler<_, _>` is not satisfied.
```

**Comment by programatik29** [comment]
Check out [this](https://docs.rs/axum/0.1.1/axum/extract/index.html#multiple-extractors) docs page.

`Note that only one extractor can consume the request body. If multiple body extractors are applied a 500 Internal Server Error response will be returned.`

**Comment by ufoscout** [comment]
@programatik29 
I am trying to migrate a small demo `actix-web` application to `axum`, in the `actix-web` application I have both the `Request` and the `Json` extractors on a handle. I need both of them because I need to use the Json body and I need to print some info about the request (e.g. the path, the headers, the HTTP method and so on).
How can I do the same with `axum`? As the `Json` extractor consumes only the body of the request, is there another extractor that allows accessing all the other parts except the body?

**Comment by programatik29** [comment]
It is possible to use `axum` just like `hyper`. You can do something like this:

```rust
let app = route("/api", post(|req: Request<Body>| async {
    let (_parts, body) = req.into_parts();

    let body = hyper::body::to_bytes(body).await.unwrap();
    let json: Value = serde_json::from_slice(&body).unwrap();

    serde_json::to_string_pretty(&json).unwrap()
}));
```

**Comment by davidpdrsn** [comment]
Yeah @programatik29 is right. Extracting `Request<_>` cannot be combined with other extractors because it consumes the entire request.

However `Uri`, `Method`, `HeaderMap` all implement `FromRequest` so they can be used as extractors directly:

```rust
async fn handler(
    method: http::Method,
    uri: http::Uri,
    headers: http::HeaderMap,
    body: String,
) {
    // ...
}
```

You can see everything that implements `FromRequest` [here](https://docs.rs/axum/0.1.1/axum/extract/trait.FromRequest.html). If you find something thats missing please file an issue.

**Comment by davidpdrsn** [comment]
@ufoscout note that the order of extractors matters and since `extract::Json<_>` requires the headers it must be specified _before_ `HeaderMap`:

```rust
async fn handler(
    method: http::Method,
    uri: http::Uri,
    body: extract::Json<Vec<i32>>,
    headers: http::HeaderMap,
) {
    // ...
}
```

I've spent a bunch of time trying to make stuff like this type errors but haven't found a way 😞

**Comment by ufoscout** [comment]
@davidpdrsn 
ok, thanks for the answer, I'll search for a solution using those extractors.

About this code, instead, why it does not compile?
```rust
    let app = route("/api", 
    post(|req: RequestParts<Body>| async move {
        println!("CALL RECEIVED");
    }));
```

**Comment by davidpdrsn** [comment]
Are you able to post all your code? With `use` statements and everything? And also what exact error are you getting?

**Comment by davidpdrsn** [comment]
I'll close this for now. Feel free to open another issue if you have more questions.

**Comment by davidpdrsn** [comment]
You cannot use `RequestParts` as an extractor. Use `Request` instead:

```diff
fn main() {
    let app = route("/api", 
+   post(|req: Request<Body>| async move {
-   post(|req: RequestParts<Body>| async move {
        println!("CALL RECEIVED");
    }));
}
```

**Comment by ufoscout** [comment]
ok, thanks. The fact it appears in the `extract` module confused me. I thought it was an extractor with optional parts.

**Comment by davidpdrsn** [comment]
Its used when implementing [`FromRequest`](https://docs.rs/axum/0.1.2/axum/extract/trait.FromRequest.html) but its not an extractor itself.

**Comment by davidpdrsn** [comment]
Since it doesn't implement `FromRequest` :)
