### ISSUE TITLE
Accept `ToSocketAddrs` in `axum::Server::bind`

### ISSUE THREAD

**Issue by misalcedo** [tokio-rs/axum#651]
### Motivation

TCP Listeners in std and tokio accept `ToSocketAddrs` to resolve host names.

### Proposal

Switch the input type to match TCPListener in std and tokio:
* https://docs.rs/tokio/1.15.0/tokio/net/struct.TcpListener.html#method.bind
* https://doc.rust-lang.org/std/net/struct.TcpListener.html#method.bind

**Comment by davidpdrsn** [comment]
`axum::Server` is a re-export of `hyper::Server` so this isn't something axum can fix. You have to open an issue for hyper 😊
