### ISSUE TITLE
Support returning pretty json in response

### ISSUE THREAD

**Issue by guylapid** [tokio-rs/axum#657]
### Motivation

It often happens that I want to implement a route that returns a pretty JSON (using e.g `serde_json::to_string_pretty`),
so that the JSON returned to the client can be easily read by a human.
For example, imagine some "admin" API that a service exposes, with routes such as `/config` (showing the current config of the service as JSON).
Today, I just manually run the JSON serialization in my routes, returning a string body, and manually set the `content-type` header to `application/json`, instead of enjoying axum's already existing implementation.

### Proposal

- Add a tuple-struct `JsonPretty<T>` in the `json` module, with a similar implementation of `IntoResponse` as `Json<T>`, but call `to_vec_pretty` instead of `to_vec`.
- The implementation of `FromRequest` is actually exactly identical, so I'm imagining something like using `From<Json> for JsonPretty` and vice-versa.
- Since these 2 structs are implemented very much the same, they should share most of their code somehow (maybe using an inner struct that has some `Formatter` field which is an enum, or something similar).

Of course, I would very much be happy to implement it if you agree it should be included in axum.

### Alternatives

- Don't implement anything, leave this implementation to the user, like today.
- Consider a breaking change that would change `Json<T>(pub T)` into `Json<T>(pub T, Formatter)`, where `Formatter` may be an enum. This would make redundant the inner struct described in the proposal, but it's a breaking change.
- A similar breaking change, but the `Formatter` can be a trait instead of an enum. This would also allow a user to implement other formatters except for the default and the pretty ones. However, it's a bit less simple, and doesn't seem very necessary.

**Comment by jplatte** [comment]
There's not much to the `Json` type, and `JsonPretty` could share its rejection type and `FromRequest` implementation (the latter by calling it in its own impl).

I think this is something that we could experiment with in axum-extra, but there's also another possibility: If nothing changes, Rust 1.59 will stabilize defaults for const generics, so we could change `Json<T>` to `Json<T, const Pretty: bool = false>` without breaking existing users.

Overall, I'm a little surprised there's people returning pretty-fied JSON from APIs. I see GitHub also does this on api.github.com, but I had to switch to Chromium to find out because Firefox automatically display the JSON in a structured way no matter how it is formatted.

**Comment by davidpdrsn** [comment]
> I think this is something that we could experiment with in axum-extra, but there's also another possibility: If nothing changes, Rust 1.59 will stabilize defaults for const generics, so we could change the Json type to
> 
> ```rust
> struct Json<T, #[rustversion::since(1.59)] const Pretty: bool = false>(pub T);
> ```
> 
> without breaking existing users.

Thats pretty neat! Definitely worth trying!

Adding something like `JsonPretty` to axum-extra is also fine by me.

> Overall, I'm a little surprised there's people returning pretty-fied JSON from APIs.

Same. I would expect users of APIs to format stuff, if necessary. I often pipe stuff to [`jq`](https://github.com/stedolan/jq) if I need pretty printing.

**Comment by guylapid** [comment]
Great, so I'll soon open a PR to axum-extra adding `JsonPretty`

**Comment by guylapid** [comment]
Actually, now I see @jplatte already implemented a similar `ErasedJson` struct in axum-extra, which performs the serialization in the `new` method instead of inside `into_response`.
So I'm thinking maybe just adding a function like
```rust
pub fn pretty<T: Serialize>(val: T) -> Self {
    Self(serde_json::to_vec_pretty(&val))
}
```
to `ErasedJson` would simply do the job, and won't require a different struct for the pretty JSON.
WDYT?

**Comment by jplatte** [comment]
I would personally find `PrettyJson(value)` nicer than `ErasedJson::new_pretty(value)` or `ErasedJson::pretty(value)`, but I agree there's not really a reason *not* to add that.
