### ISSUE TITLE
Support side-by-side precompressed static files

### ISSUE THREAD

**Issue by shepmaster** [tokio-rs/axum#66]
### Motivation

The [Rust Playground](https://github.com/integer32llc/rust-playground/) has a number of assets (mainly JavaScript) that rarely get updated. To save bandwidth, these are served in a compressed form. To save CPU time, they are *precompressed* on disk.

When a request is made for `foo.js` and the client indicates that they accept GZip-compressed data, we look instead for `foo.js.gz`. If that's found, we return it. Otherwise, `foo.js` is attempted.

The [current implementation of this](https://github.com/integer32llc/playground-middleware/blob/146df5e79210fc21ded487cf41fcb4e1ae1a347a/src/staticfile.rs#L57-L102) (for the old Iron framework) has a fair amount of hand-written code to achieve this. Most web frameworks I've investigated make it very difficult (impossible?) to reuse relevant code such as path traversal protection or file -> HTTP caching information.

### Proposal

I don't think that this is something that Axum itself needs to provide, as it's a relatively uncommon requirement. However, I do think that it should be possible to *reuse* large chunks of Axum code such as serving a static file.

If it seems generally interesting, then I don't see why it _couldn't_ be added to Axum proper, of course.

### Alternatives

I believe many people punt this off to a different web server. For example, NGINX plus [`ngx_http_gzip_static_module`](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html). I don't _like_ this path, but I see why many people choose it.

**Comment by davidpdrsn** [comment]
@shepmaster We're doing work on this in tower-http. Do you think https://github.com/tower-rs/tower-http/pull/156 would work for your use case? There are some examples [in the tests](https://github.com/tower-rs/tower-http/pull/156/files#diff-a8e0e4e7c18b53c3521750c41d90c034418079e7a718c2ae2d111b208f909d63R380-R399).

**Comment by shepmaster** [comment]
It certainly seems relevant! I note that you mention that a breaking change will be required — I assume that means that it will still be a while before I'd be able to test it out in Axum?

**Comment by davidpdrsn** [comment]
My goal is to publish the final 0.1.x release of tower-http next week and then starting merging breaking PRs and working towards 0.2. Then at least then you can test it out with a git dependency. It should work just fine with axum I think.

When tower-http 0.2 will be released I'm not sure off.
