### ISSUE TITLE
Use constant time comparison in middleware example

### ISSUE THREAD

**Issue by jzelinskie** [tokio-rs/axum#664]
### Crates

axum-extra

### Description

The example for middleware in axum-extra checks the authorization http header value with a secret without using a constant time comparison.

This is obviously just an example, but could mistakenly be copy-pasted and used by someone.

Another option would be to use an entirely different example that is not security sensitive.

**Comment by davidpdrsn** [comment]
How do you make such comparisons constant time?

**Comment by jplatte** [comment]
The [constant_time_eq crate](https://docs.rs/constant_time_eq) provides an implementation (and is pretty easy to review, little over 100 lines long).

**Comment by davidpdrsn** [comment]
Hm maybe using a different example altogether is better. Bringing in a dependency for an example feels overkill.
