### ISSUE TITLE
Improve documentation for router

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#67]
The router has a few slightly surprising behaviors due to its design that should we clearly document:

- That `route("/foo", get(handler)).route("/foo", post(handler))` only matches POST and not GET. This is https://github.com/tokio-rs/axum/issues/62
- That routes are matched bottom to top. Not top to bottom, or longest path wins.

**Comment by jcbritobr** [comment]
And for all examples. There are a lot of dependencies. Its hard to know what is needed to compile, and  makes hard to setup a new project.

**Comment by davidpdrsn** [comment]
@jcbritobr sure but please file a new issue for that rather than piggy bagging on this one.

**Comment by jcbritobr** [comment]
> 
> 
> @jcbritobr sure but please file a new issue for that rather than piggy bagging on this one.

For sure. As this one is about documentation, for good I think to post here also. :)
