### ISSUE TITLE
Add client TLS cert auth

### ISSUE THREAD

**Issue by andrewbanchich** [tokio-rs/axum#677]
## Feature Request

It would be great to have an equivalent of warp's [`client_auth_required`](https://docs.rs/warp/latest/warp/struct.TlsServer.html#method.client_auth_required).

### Motivation

I'd like to use mTLS for request authentication. I found a low level example that looks relevant, but it would be nice to have something high level like what warp offers.

**Comment by davidpdrsn** [comment]
@programatik29 is this something axum-server can do?

**Comment by programatik29** [comment]
Everything possible with [`rustls::ServerConfig`](https://docs.rs/rustls/latest/rustls/struct.ServerConfig.html) is possible with `axum-server`.

**Comment by programatik29** [comment]
Features that `rustls` doesn't support requires `openssl` which is not implemented yet in `axum-server`. Though it is possible for users to implement it with `Accept` trait.

**Comment by andrewbanchich** [comment]
Would it make sense to add the `axum-server` functionality to `axum`? I feel like configuring TLS would be a much needed high level piece of functionality.

**Comment by jplatte** [comment]
A lot of people exclusively run their http services behind a reverse proxy, e.g. nginx, haproxy or traefik. Terminating TLS in the same application that also contains the business logic isn't necessary and maybe even a bad idea security-wise – the projects mentioned are much larger than Rust web frameworks and more likely to receive quick security fixes.

**Comment by davidpdrsn** [comment]
> Would it make sense to add the `axum-server` functionality to `axum`? I feel like configuring TLS would be a much needed high level piece of functionality.

An HTTP server is currently out of scope for axum. Axum is flexible enough that these things can be built by the community and doesn't have to be built and maintained specifically for axum.

I also agree with what @jplatte said.

**Comment by ttys3** [comment]
agree with @jplatte 
Usually, serve HTTP services behind a reverse proxy is more efficiently and flexible.
And most CDN providers even provide flexible SSL feature.

**Comment by davidpdrsn** [comment]
Think I'll close this for now since its not actionable in axum. @andrewbanchich just let us know if you have more questions :)

**Comment by andrewbanchich** [comment]
@jplatte @ttys3 There are other discussions about this:

https://github.com/http-rs/tide/issues/25#issuecomment-437031683

https://github.com/seanmonstar/warp/pull/743

A reverse proxy isn't a one size fits all solution for people. I agree with @seanmonstar that it's a great feature to have and with the other commenters in that thread that requiring someone to deploy an entire reverse proxy just for that feature seems like overkill for many people.

IMO if there is a security issue with Rustls / the rest of the Rust implementation then that's just a bug that should be fixed.

**Comment by andrewbanchich** [comment]
> And most CDN providers even provide flexible SSL feature.

I'm running Axum in an airgapped environment so that won't work.

**Comment by davidpdrsn** [comment]
Just to elaborate on why a server is out of scope for axum: I think every framework having its own custom server implementation is counter productive. I would rather collaborate on abstractions that allows frameworks and servers to be built independently and mixed and matched however users see fit. This is a general goal with axum. I don't want us to keep reinventing things. This is one of the reasons axum is based on `tower::Service`. That makes axum compatible with any server that supports tower. Realistically your only option is hyper (or building something on top of hyper, which is what axum-server is) or building something from scratch.

**Comment by andrewbanchich** [comment]
@davidpdrsn That sounds ideal, and I agree with that. I may be misunderstanding something though, but `axum-server` sounds like it *is* specific to axum.

I don't know much about Tower, but is this something which could be written as middleware?

**Comment by davidpdrsn** [comment]
> I may be misunderstanding something though, but axum-server sounds like it is specific to axum.

I agree the name can be confusing but axum-server can be used with any tower service and no just axum. Its created and maintained by @programatik29.

> I don't know much about Tower, but is this something which could be written as middleware?

Yes, tower is a general "async function from request to response" abstraction that can be used to build clients, servers, and middleware. For a general introduction to tower I recommend reading the [guides](https://github.com/tower-rs/tower/tree/master/guides). [tower-http](https://docs.rs/tower-http/latest/tower_http) has many HTTP compatible middleware which work with axum but also hyper clients/servers, and even [tonic](https://crates.io/crates/tonic) client/servers. For example [`tower_http::trace::Trace`](https://docs.rs/tower-http/latest/tower_http/trace/index.html) is how you add tracing to axum apps, without having to write something specific for axum.

**Comment by andrewbanchich** [comment]
Yeah, that is confusing. Also, the first line is:

> axum-server is a hyper server implementation designed to be used with axum framework.

Maybe it's worth renaming / explaining in the README @programatik29 ?

I don't want to get too off track here since this seems to be about axum-server / tower now. I'll open an issue there.

Thanks @davidpdrsn

**Comment by davidpdrsn** [comment]
np :)

**Comment by andrewbanchich** [comment]
Found an existing issue [here](https://github.com/programatik29/axum-server/issues/1#issuecomment-1003376578) in case you're interested in weighing in.

**Comment by davidpdrsn** [comment]
programatik29 is active in Discord and we've talked about it a few times already so they know what I think. Ultimately is their decision.

**Comment by ttys3** [comment]
@andrewbanchich  

Axum is not battery included framework. currently it does not has built in mTLS feature.

But you can use Axum with a TLS server with mTLS enabled.

I just tried with a slightly modified version `axum-server`  (with TLS client cert auth enabled). this works.

**Comment by programatik29** [comment]
I think `axum-server` name is all right with current state of ecosystem. `hyper` already has a high level server which is re-exported in `axum`. But this high level server design works badly with TLS so `axum-server` solves it with a different design.

Name and documentation is written for users who want to do TLS with `axum`.

I don't think changing the name makes sense until new version of `hyper` drops high level server and become a more low level library. Then a renamed `axum-server` can be one of the high level `hyper` servers.

**Comment by ttys3** [comment]
@andrewbanchich  here's a mTLS example base on exists axum example:

https://github.com/ttys3/rust-mtls-axum-example/blob/45d07d3545a1affeeaf854dc6c4d1d7b3417c5fd/src/main.rs#L111

the main diff is a custom  rustls `ServerConfig` with client auth enable.

**Comment by andrewbanchich** [comment]
Thanks @ttys3
