### ISSUE TITLE
GraphQL example

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#68]
Would be nice to provide an example of setting up a basic GraphQL server. Don't think it matters if the example uses [async-graphql](https://github.com/async-graphql/async-graphql) or [juniper](https://github.com/graphql-rust/juniper). I expect both implementations to be fairly similar.

**Comment by sunli829** [comment]
`Axum` looks pretty good, I've basically finished the `Async-GraphQL` integration, Will send a PR later.

**Comment by sunli829** [comment]
`Actix-web` can use `app_data` function to pass parameters to `Extractor`, I want to know whether `Axum` has corresponding features. 🙂

https://docs.rs/actix-web/4.0.0-beta.8/actix_web/web/struct.JsonConfig.html

**Comment by davidpdrsn** [comment]
I'm not very familiar with actix but I believe https://docs.rs/axum/0.1.1/axum/extract/struct.Extension.html is similar.

**Comment by sunli829** [comment]
I have another question, how to split a `WebSocket` into half-read and half-write?

**Comment by davidpdrsn** [comment]
On `main` `WebSocket` implements `Stream` and `Sink` (https://github.com/tokio-rs/axum/pull/52) so you can use `StreamExt::split`. That isn't released yet though. Will probably do another release today or early next week.

**Comment by sunli829** [comment]
Thank you! 🙂

**Comment by davidpdrsn** [comment]
@sunli829 0.1.2 is now on crates.io. It includes the fix mentioned above.

**Comment by sunli829** [comment]
I have tried a lot, but this example still fails to compile. I suspect that this error is related to lifetime or FnOnce. I checked the relevant implementation code of websocket in Axum, but couldn't find the cause of the error. Can you help me see it? 😁 😁 😁

https://github.com/async-graphql/examples/tree/74765cc20413344a8cb7a050f0b18e4a1fe81813/axum/subscription

```
error[E0308]: mismatched types
  --> axum/subscription/src/main.rs:47:21
   |
47 |         .route("/", ws(graphql_subscription_handler))
   |                     ^^ lifetime mismatch
   |
   = note: expected type `FnOnce<(&Result<Message, Box<(dyn std::error::Error + Sync + std::marker::Send + 'static)>>,)>`
              found type `for<'r> FnOnce<(&'r Result<Message, Box<dyn std::error::Error + Sync + std::marker::Send>>,)>`
   = note: the required lifetime does not necessarily outlive the static lifetime
note: the lifetime requirement is introduced here
  --> /Users/sunli/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/axum-0.1.2/src/ws/mod.rs:94:8
   |
94 |     F: WebSocketHandler<B, T>,
   |        ^^^^^^^^^^^^^^^^^^^^^^

error: implementation of `FnOnce` is not general enough
  --> axum/subscription/src/main.rs:47:21
   |
47 |         .route("/", ws(graphql_subscription_handler))
   |                     ^^ implementation of `FnOnce` is not general enough
   |
   = note: `fn(Result<Message, Box<(dyn std::error::Error + Sync + std::marker::Send + '0)>>) -> Message {Result::<Message, Box<(dyn std::error::Error + Sync + std::marker::Send + '0)>>::unwrap}` must implement `FnOnce<(Result<Message, Box<(dyn std::error::Error + Sync + std::marker::Send + 'static)>>,)>`, for any lifetime `'0`...
   = note: ...but it actually implements `FnOnce<(Result<Message, Box<dyn std::error::Error + Sync + std::marker::Send>>,)>`

```

**Comment by davidpdrsn** [comment]
Hm yeah that looks very weird. I'm gonna spend some time today and look into it.

**Comment by sunli829** [comment]
Maybe it is the problem caused by `tower::BoxError`. When I changed it to `tungstenite::Error`, the compilation passed.


use tower::{~BoxError~, Service};

type BoxError = tokio_tungstenite::tungstenite::Error;

**Comment by davidpdrsn** [comment]
Hm I'm not sure.

I found that changing `graphql_subscription_with_data` to this also works. Basically using `filter_map` instead of `filter` (perhaps the fact that `filter` receives `&Message` messes something up) and doing a manual implementation of `StreamExt::forward`.

```rust
/// GraphQL subscription handler
///
/// Specifies that a function converts the init payload to data.
pub async fn graphql_subscription_with_data<Query, Mutation, Subscription, F, R>(
    websocket: WebSocket,
    schema: Schema<Query, Mutation, Subscription>,
    protocol: SecWebsocketProtocol,
    initializer: F,
) where
    Query: ObjectType + 'static,
    Mutation: ObjectType + 'static,
    Subscription: SubscriptionType + 'static,
    F: FnOnce(serde_json::Value) -> R + Send + 'static,
    R: Future<Output = Result<Data>> + Send + 'static,
{
    let (mut sink, stream) = websocket.split();

    let input = stream
        .take_while(|res| future::ready(res.is_ok()))
        .map(Result::unwrap)
        // `filter` doesn't work. We get "lifetime mismatch"
        // errors
        .filter_map(|msg| {
            if msg.is_text() || msg.is_binary() {
                future::ready(Some(msg))
            } else {
                future::ready(None)
            }
        })
        .map(Message::into_bytes);

    let mut stream =
        async_graphql::http::WebSocket::with_data(schema, input, initializer, protocol.0).map(
            |msg| match msg {
                WsMessage::Text(text) => Message::text(text),
                WsMessage::Close(code, status) => Message::close_with(code, status),
            },
        );

    // manual implementation of `StreamExt::forward` because using that
    // leads to odd "lifetime mismatch" errors.
    use futures_util::sink::SinkExt;
    while let Some(item) = stream.next().await {
        // not sure if using `.send` is more appropriate, to flush
        // after sending each message
        sink.feed(item)
            .await
            .expect("not sure if you wanna ignore this error");
    }
    sink.close()
        .await
        .expect("not sure if you wanna ignore this error");
}
```

**Comment by sunli829** [comment]
Thank you, it can be compiled! 👏🏻
