### ISSUE TITLE
Provide extractors for Bearer / Basic auth

### ISSUE THREAD

**Issue by sebpuetz** [tokio-rs/axum#697]
## Feature Request

Follow-up to the discussion on Discord: It would be nice to have extractors for Bearer / Basic Authorization that can then be used in custom authorization middleware.

### Motivation

Offers easy to (re-)use extractors to implement custom authorization middleware

### Proposal

@davidpdrsn suggested on Discord that these types should live in `axum-extra`, the types could be fairly simple but should handle e.g. decoding the B64 encoded credentials for Basic and splitting the token from the `Bearer` prefix.

### Alternatives

Don't implement the extractors and keep the status quo where users write their own extraction logic.

**Comment by davidpdrsn** [comment]
Yep I think this is something that makes sense to have and nice for building more higher level auth extractors.

**Comment by sebpuetz** [comment]
Looks like this is actually covered through `headers` and `TypedHeader` https://github.com/tokio-rs/axum/blob/d181867355a46566e2e9bf2860471c642d905ed1/examples/jwt/src/main.rs#L128-L140 :thinking:

**Comment by davidpdrsn** [comment]
TIL!

[headers even has basic and bearer](https://docs.rs/headers/latest/headers/authorization/trait.Credentials.html#implementors). I think thats fine an we probably don't need anything in axum.
