### ISSUE TITLE
Add .json() method to Response

### ISSUE THREAD

**Issue by longfellowone** [tokio-rs/axum#709]
## Feature Request

Add .json() to Response similar to reqwest::Response

https://docs.rs/reqwest/latest/reqwest/struct.Response.html#method.json

### Motivation

Simplify testing 

```
        let body = hyper::body::to_bytes(response.into_body()).await.unwrap();
        let body: Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(body, json!({ "data": [1, 2, 3, 4] }));
```

**Comment by davidpdrsn** [comment]
The `Response` type in axum is actually a re-export of [`http::Response`](https://docs.rs/http/latest/http/response/struct.Response.html) so we cannot add methods to it from axum. We could in theory provide a function or extension trait but I think a small helper for this in your own crate is fine.
