### ISSUE TITLE
Query parameter arrays don't parse correctly

### ISSUE THREAD

**Issue by tasn** [tokio-rs/axum#721]
### Version

├── axum v0.4.4
│   ├── axum-core v0.1.1

### Platform

Linux p15s 5.16.2-arch1-1 #1 SMP PREEMPT Thu, 20 Jan 2022 16:18:29 +0000 x86_64 GNU/Linux

### Description

If you look at https://swagger.io/docs/specification/serialization/#query you'll see that the standard OpenAPI setting for query parameters is explode=true. What does that mean? It means that parameters are passed like this:
```
http://example.com?arr=item1&arr=item2
```
Axum however treats queries as a map and doesn't correctly parse these into an array. Instead it just uses the last one.

Expected:
```
arr: ["item1", "item2"]
```
Actual:
```
arr: "item2"
```

**Comment by davidpdrsn** [comment]
See https://github.com/tokio-rs/axum/issues/504

**Comment by tasn** [comment]
Sorry, and thanks!

**Comment by huntc** [comment]
As this turned up first on Google for me, https://github.com/tokio-rs/axum/tree/main/axum-extra's `Query` declaration supports multi-valued query params.
