### ISSUE TITLE
Incorrect content-length header in reply to HEAD request

### ISSUE THREAD

**Issue by mdickopp** [tokio-rs/axum#730]
### Version

axum v0.4.4
axum-core v0.1.1

### Platform

Debian Linux 12 (“bookworm”)
Linux feynman 5.15.0-3-amd64 <span>#</span>1 SMP Debian 5.15.15-1 (2022-01-18) x86_64 GNU/Linux
rustc 1.58.1 (db9d1b20b 2022-01-20)

### Description

The `content-length` header in the reply to a simple `HEAD` request is set to `0` instead of the length of the reply body to the corresponding `GET` request.

#### Steps to reproduce

Run the axum examle program:

```rust
use axum::{routing::get, Router};

#[tokio::main]
async fn main() {
    let app = Router::new().route("/", get(|| async { "Hello, World!" }));
    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}
```

Send a HTTP/1.1 `HEAD` request for `/`. I used the the following command on the Linux command line:

```sh
printf 'HEAD / HTTP/1.1\r\n\r\n' | nc 127.0.0.1 3000
```

#### Observed behavior

The output contains the line:

```
content-length: 0
```

#### Expected behavior

The output contains the line:

```
content-length: 13
```

When a web server sends a `content-length` header in reply to a `HEAD` request, its value should be the same as would have been used in the reply to the same request using the `GET` method.

**Comment by davidpdrsn** [comment]
Not quite sure whats going on here, but axum doesn't remove `content-length`s from responses to `HEAD` requests:

```rust
use axum::{
    http::Request,
    middleware::{self, Next},
    response::{IntoResponse, Response, Headers},
    routing::get,
    Router,
};
use std::net::SocketAddr;

#[tokio::main]
async fn main() {
    let app = Router::new()
        .route("/", get(handler))
        .layer(middleware::from_fn(debug));

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn handler() -> impl IntoResponse {
    let body = "Hello, World!";
    let headers = Headers([("content-length", body.len())]);
    (headers, body)
}

async fn debug<B>(request: Request<B>, next: Next<B>) -> Response {
    dbg!(&request.method());
    let res = next.run(request).await.into_response();
    dbg!(&res.headers());
    res
}
```

And then

```
❯ curl -v -I localhost:3000
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> HEAD / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< content-type: text/plain; charset=utf-8
content-type: text/plain; charset=utf-8
< content-length: 13
content-length: 13
< date: Sun, 30 Jan 2022 12:15:36 GMT
date: Sun, 30 Jan 2022 12:15:36 GMT

<
* Connection #0 to host localhost left intact
* Closing connection 0
```

If you make a response that just returns `&'static str` (without any additional headers from your handler) its actually hyper that inserts the `content-length`. axum doesn't as seen [here](https://github.com/tokio-rs/axum/blob/main/axum-core/src/response/mod.rs#L273-L282). Maybe we should though, but thats a separate question.

So it appears that hyper's automatic `content-length` stuff doesn't happen on HEAD requests which might be a bug.

It would be worth it to experiment with using straight hyper so without involving axum.

**Comment by davidpdrsn** [comment]
@seanmonstar maybe you know whats going on here.

**Comment by mdickopp** [comment]
I could not reproduce this issue with plain hyper, but while experimenting, I noticed that axum removes the response body for `HEAD` requests, and hyper does as well. Maybe it is related to this double stripping, i.e., when hyper adds the `content-length` header, the body has already been stripped?

When I replace [this code](https://github.com/tokio-rs/axum/blob/911c4a788e35e74a6c210b82e15880b68fbb1efa/axum/src/routing/route.rs#L101-L105) with `Poll::Ready(Ok(res))`, everything seems to work fine. The header is `content-length: 13`, and the body is empty (presumably because it is stripped by hyper).

**Comment by davidpdrsn** [comment]
If we change axum to set a `content-length` in the `IntoResponse` impls then it works correctly:

```diff
--- a/axum-core/src/response/mod.rs
+++ b/axum-core/src/response/mod.rs
@@ -272,11 +272,16 @@ impl IntoResponse for String {

 impl IntoResponse for Cow<'static, str> {
     fn into_response(self) -> Response {
+        let len = self.len();
         let mut res = Response::new(boxed(Full::from(self)));
         res.headers_mut().insert(
             header::CONTENT_TYPE,
             HeaderValue::from_static(mime::TEXT_PLAIN_UTF_8.as_ref()),
         );
+        res.headers_mut().insert(
+            header::CONTENT_LENGTH,
+            HeaderValue::from_str(&len.to_string()).unwrap(),
+        );
         res
     }
 }
```

That feels like the most correct solution to me. Then things work both with and without hyper.

**Comment by mdickopp** [comment]
Thanks!
