### ISSUE TITLE
docs.rs does not show feature gate on `Multipart` or `WebSocketUpgrade`

### ISSUE THREAD

**Issue by SaadiSave** [tokio-rs/axum#763]
For some reason, the docs page does not show the feature gates, but compilation works fine. I suspect this is a docs.rs bug, but I thought it would be better to report it here first:

![image](https://user-images.githubusercontent.com/53120037/154297819-189378bb-d3fb-49cf-93dd-a566315de2a8.png)

The feature gate for `TypedHeader` is correctly shown

**Comment by jplatte** [comment]
Trying to reproduce locally...

**Comment by SaadiSave** [comment]
> Trying to reproduce locally...
> 
> edit: Can reproduce. This is actually a bug in axum. Working on a fix.

How does one reproduce docs.rs builds locally? A simple `cargo doc` does not do the job.

**Comment by jplatte** [comment]
In the case of the axum crate, `RUSTDOCFLAGS='--cfg docsrs' cargo +nightly doc --all-features` (see `package.metadata.docs.rs`) in `Cargo.toml`.
