### ISSUE TITLE
(Default-)Feature-gate form and query extractors?

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#764]
For very simple apps (like https://turbo.fish) I don't think the dependency on `serde_urlencoded` is needed. @davidpdrsn are you okay with feature-gating `Form` and `Query` behind one or two default-on features, like json before? 🙂

**Comment by davidpdrsn** [comment]
Sure!

**Comment by jplatte** [comment]
It had the intended effect! :)

https://github.com/jplatte/turbo.fish/compare/axum-0.5
