### ISSUE TITLE
Why you name Router "Application"

### ISSUE THREAD

**Issue by liigo** [tokio-rs/axum#766]
### Version

master

### Platform

all

### Crates

nop

### Description

In README:

```rs
    // build our application with a route
    let app = Router::new()
        // `GET /` goes to `root`
        .route("/", get(root))
        // `POST /users` goes to `create_user`
        .route("/users", post(create_user));
```

The `Router` is just a router (`Router::route()` also returns `Router`), why you name it "app"? confusing.

**Comment by davidpdrsn** [comment]
Because typically the router effectively is your app. Its just a convention. I think its fine.

**Comment by liigo** [comment]
`struct Router` is defined in axum lib, it does not store app (or user) states.
