### ISSUE TITLE
implementing IntoResponse for Box<dyn IntoResponse> or explaining why it is not possible.

### ISSUE THREAD

**Issue by nicoxxl** [tokio-rs/axum#786]
## Feature Request

Note : It is half a feature request, half a question.

### Motivation

I am doing some funky stuff around WebDAV and it does use some non standard/usual HTTP verbs.

The way I implemented it is that I have standard HTTP verbs using classic routed handlers and for the extras I have a function with few `if`s to route correctly.

But, I would love that each custom handler be able to return whatever is needed and simply boxing it.

### Proposal

Implementing `IntoResponse` for `Box<dyn IntoResponse>`.

### Alternatives

If it is not possible, it would be nice for it to be mentioned in the documentation, with maybe an example of the correct way to do it

**Comment by jplatte** [comment]
`IntoResponse` is implemented for `Response`, the easy way to return different responses from branches is calling `.into_response()` on them in those branches.

**Comment by davidpdrsn** [comment]
Will close this for now since there isn't much we can do but feel free to ask follow up questions!
