### ISSUE TITLE
Implement into Uri for TypedPath

### ISSUE THREAD

**Issue by norman784** [tokio-rs/axum#789]
## Feature Request

Add ergonomic improvements to `TypedPath`

### Motivation

It feels so off to write `Redirect::temporary(MyPath.to_string().parse().unwrap())` instead of `Redirect::temporary(MyPath.into_uri())`.

### Proposal

Add and implement a new trait `IntoUri` to `TypedPath`.

### Alternatives

Maybe `Into<Uri>` works  also just fine, the only open question is if/how can fail to generate the `Uri`.

**Comment by davidpdrsn** [comment]
Good call! I think we should implement `TryFrom<MyPath> for Uri` where the error type is [`InvalidUri`](https://docs.rs/http/0.2.6/http/uri/struct.InvalidUri.html).
