### ISSUE TITLE
How to get request header and body in one handler

### ISSUE THREAD

**Issue by jiashiwen** [tokio-rs/axum#798]
hi,I need get request header and body together and my code is 
```
pub async fn get_headers(headers: HeaderMap, Json(id): Json<ID>) -> HandlerResult<()> {
    println!("{:?}", headers);
    println!("{:?}", id);

    Ok(Json(Response::ok(())))
}
```

and i got a '501' error

I got some words from https://docs.rs/axum/0.2.3/axum/extract/index.html#multiple-extractors
```
Note that only one extractor can consume the request body. If multiple body extractors are applied a 500 Internal Server Error response will be returned.
```

may be is rule of axum and not bug.
my question is ,how to get header and body together in one handler or get origin request

**Comment by davidpdrsn** [comment]
Run the `Json` extractor first:

```rust
pub async fn get_headers(Json(id): Json<ID>, headers: HeaderMap)
```

More details [here](https://docs.rs/axum/latest/axum/extract/index.html#applying-multiple-extractors).

**Comment by jiashiwen** [comment]
thx
