### ISSUE TITLE
axum 0.4.7 issues warning on using axum::AddExtensionLayer but suggested Extension is not available

### ISSUE THREAD

**Issue by HK416-is-all-you-need** [tokio-rs/axum#814]
Version 0.4.7 issues warning on usage of AddExtensionLayer but `Extension` alternative is not available:

```
failed to resolve: could not find `Extension` in `axum`
```

Please publish up to date version of crate

**Comment by davidpdrsn** [comment]
The fix is to use https://docs.rs/axum/latest/axum/extract/struct.Extension.html. It's also shown in all the docs.

**Comment by davidpdrsn** [comment]
I just published axum 0.4.8 which contains the fix for the deprecation note.
