### ISSUE TITLE
`TypedPath` with `Double slash`

### ISSUE THREAD

**Issue by zys864** [tokio-rs/axum#818]
### Motivation
Both `/foo/bar/:id` and `/foo//bar/:id` work on modern browser.

`TypedPath` with path like `/foo//bar/:id` will pass test. 
We could add a `if` in `fn pase_path()`, which can only allow people use the first one, because the 
last one hasn't any practical implications.

### Proposal
Adding a `if` determine in `fn pase_path()` on `axum-macro`, then thowing compile error if `double slash` be used.

### Alternatives
Generate warning nor error.

**Comment by davidpdrsn** [comment]
I don't know what `pase_path` function you're talking about but if double slashes work just fine then why should we limit that? I agree they're rare, and probably often a typo, but not sure disallowing them is right.

`router.route("/foo//bar", _)` also works just fine so if we change `TypedPath` we should also change `Router`.

**Comment by jplatte** [comment]
A warning would be interesting, but at least if compile-time warnings are meant, those are still nightly-only and I'm not sure there's a way to silence them yet. But if there is, we could have a nightly-only warning 🤔

**Comment by davidpdrsn** [comment]
Yeah I agree re a warning. I've wanted them [before as well](https://github.com/davidpdrsn/todo-or-die/issues/1). I think we should wait until its doable on stable though.

**Comment by zys864** [comment]
[parse_path()](https://github.com/tokio-rs/axum/blob/1c8f09268bb610e1e6a375578458110cab84b3a2/axum-macros/src/typed_path.rs#L286), this could deny `/foo//bar` at compiler time in `#[typed_path("/:id")]`, which may don't influence on `router.route("/foo//bar", _)` working , just like `TypedPath` rejecting "*".

My meaning is that `TypedPath` should deny `/foo//bar`, but people can use `.route("/foo//bar",get(handler))` instead of `TypedPath`,if they do need "double slash" uri.

**Comment by zys864** [comment]
A warning may be better.

**Comment by davidpdrsn** [comment]
I still don't agree that double slashes should even be disallowed at all. If they work, why not allow them?

**Comment by davidpdrsn** [comment]
Actix is fine with it:

```rust
use actix_web::{get, web, App, HttpServer, Responder};

#[get("/foo//bar")]
async fn index() -> impl Responder {
    "hi"
}

#[actix_web::main] // or #[tokio::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().service(index))
        .bind(("127.0.0.1", 8080))?
        .run()
        .await
}
```

**Comment by zys864** [comment]
it's legal uri.but we use macro to make sure safety at compiler time.why not do more

**Comment by davidpdrsn** [comment]
I still don't see the safety angle. It works and `/foo//bar` is a valid URI. I'm gonna make a call and say that we don't do this. We can revisit when the proc-macro diagnostics is eventually stable.
