### ISSUE TITLE
Tests for truly nested routing?

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#830]
After the discussion in #714, I'm wondering whether all those variants (the updated behavior as of #824) work the same way when the inner router is wrapped in another service, and we hit the `Err` branch of [`try_downcast::<Router<B>, _>(svc)`](https://github.com/tokio-rs/axum/blob/f045f2356c16cd31c257ca3f41a9600d8ae64b01/axum/src/routing/mod.rs#L193). Do the tests cover this scenario already?

**Comment by davidpdrsn** [comment]
In general it seems we need better test coverage for nested opaque routes. This one fails:

```rust
#[tokio::test]
async fn nest_at_capture() {
    let api_routes = Router::new().route("/:b", get(|| async {})).boxed_clone();

    let app = Router::new().nest("/:a", api_routes);

    let client = TestClient::new(app);

    let res = client.get("/foo/bar").send().await;
    assert_eq!(res.status(), StatusCode::OK);
}
```

It gets 404.
