### ISSUE TITLE
handles `HEAD` requests automatically when there exists a `GET` route that would otherwise match.  `405 Method Not Allowed` returns for now.

### ISSUE THREAD

**Issue by songww** [tokio-rs/axum#84]
### Proposal

handles HEAD requests automatically when there exists a GET route that would otherwise match. It does this by stripping the body from the response, if there is one. You can also specialize the handling of a HEAD request by declaring a route for it;  won't interfere with HEAD requests your application explicitly handles.

### Alternatives

Just like rocket did.

[head-requests](https://rocket.rs/v0.5-rc/guide/requests/#head-requests)

**Comment by davidpdrsn** [comment]
I've looked into this and I don't think a clean solution is possible given the current design of the router.

When you compose two routes with `head(handler).get(other_handler)` neither `head` nor `get` knows if they're the "last" route. That is to say a `get` route has no way to know if there is another route that accepts `head` that is also defined and so it cannot change its behavior based on that.

One possible solution is to make `get` accept both `GET` and `HEAD` request but always remove the response body on `HEAD`. This is a breaking change however since `head(handler).get(other_handler)` would now call `other_handler` instead of `handler` on `HEAD` requests (routes are matched bottom to top).

Not sure if entirely removing explicit matching on `HEAD` requests would make things less confusing. That way `get` could always accept `GET` and `HEAD` without a `head` method getting in the way. I think that is quite drastic though, and removing the ability to match on `HEAD` feels odd. You can also get around it using `any` I suppose.

I checked with warp (the framework axum is most alike from a design perspective) and it handles `HEAD` requests the same way as axum does today. So `warp::get().map(|| "Hi there!");` does _not_ accept `HEAD` requests. It seems [an issue](https://github.com/seanmonstar/warp/issues/882) was opened about that recently so lets see what happens there.

Honestly I would be fine with leaving things as is. User's who want to support `HEAD` requests can explicitly add handlers for them. In my experience their usage is fairly niche. Don't think I've ever personally sent a `HEAD` request 🤔 At least not knowingly.

What do you think @songww @jplatte?

**Comment by jplatte** [comment]
> Don't think I've ever personally sent a `HEAD` request thinking

REST services used from browsers commonly need `HEAD` implemented for all endpoints AFAIK (though there's also many that don't, and I really should look into how that works). But it's really wasteful to hit the DB to generate a response body when the response is then stripped and only the headers returned, so the right thing would probably be to implement head manually, or have a macro that generates both head and get impl from one function, i.e. sth. like

```rust
use axum::{
    extract::{Query, UrlParams},
    response,
};

#[get_head]
async fn list_foos(
    UrlParams(user_id): UrlParams<Uuid>,
    params: Query<PaginationParams>,
    db: extension<sqlx::PgPool>,
) -> crate::Result<response::Json<Vec<Foo>>> {
    Ok(Foo::list_by_user(user_id, &pagination, db.deref()).await?)
}

// generates
async fn list_foos(
    UrlParams(user_id): UrlParams<Uuid>,
    params: Query<PaginationParams>,
    db: Extension<sqlx::PgPool>,
) -> crate::Result<response::Json<Vec<Foo>>> {
    Ok(Foo::list_by_user(user_id, &pagination, db.deref()).await?)
}

async fn head_list_foos(
    _: UrlParams<Uuid>,
    _: Query<PaginationParams>,
    _: Extension<sqlx::PgPool>,
) -> StatusCode {
    StatusCode::OK
}
```

Two notes:

* This works, but is still not *entirely* optimal (request extensions are pointlessly cloned)
* This assumes that the CORS headers without which HEAD requests are pointless are added by a middleware
  * That seems pretty much like the one right way to do things to me, but it still irks me that any headers set within the `async fn` body would not apply to the HEAD handler

**Comment by davidpdrsn** [comment]
> This assumes that the CORS headers without which HEAD requests are pointless are added by a middleware

That's a fair assumption to make I think but I see your point.

[Mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) mentions that headers should be identical across GET and HEAD so the actual handler (and possibly database) would probably have to be called in case you're setting `content-length`. Which would then have the same amount of load in the server.

Kinda feels like something that is hard for a framework to get right, in the general case 🤔 Is requiring users to explicitly handle HEAD in the way that makes sense for their app perhaps the best approach or is there a "goo enough" middle ground?

**Comment by jplatte** [comment]
Scrap everything I wrote. It doesn't belong on this issue; I mixed up HEAD and OPTIONS 😅

I have some additional thoughts for supporting HEAD *and* OPTIONS easier for some response types, but it's super late here, will write that up tomorrow.

**Comment by songww** [comment]
We usually use `curl -I` to test whether it is working properly. It is very effective for scenes where the body is large or does not care about the body.

If a handler returns static files by `tower_http::services::ServeFile`, it is difficult to implement the corresponding HEAD handler manually.

**Comment by davidpdrsn** [comment]
> If a handler is returning static files by tower_http::services::ServeFile, then manually implementing HEAD will be much more difficult than GET.

It can be done by making a `tower::Service` middleware that drops the response body like so:

```rust
use axum::{prelude::*, service};
use bytes::Bytes;
use http::Response;
use http_body::Empty;
use std::{
    net::SocketAddr,
    task::{Context, Poll},
};
use tower::Service;
use tower_http::services::ServeFile;

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();

    let serve_file_svc = ServeFile::new("Cargo.toml");
    let app = route(
        "/Cargo.toml",
        service::get(serve_file_svc.clone()).head(DropResponseBody(serve_file_svc)),
    );

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    tracing::debug!("listening on {}", addr);
    hyper::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

#[derive(Clone)]
struct DropResponseBody<S>(S);

impl<R, S, ResBody> Service<R> for DropResponseBody<S>
where
    S: Service<R, Response = Response<ResBody>> + Clone,
    S::Future: Send + 'static,
{
    type Response = Response<Empty<Bytes>>;
    type Error = S::Error;
    type Future = futures::future::BoxFuture<'static, Result<Self::Response, Self::Error>>;

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        self.0.poll_ready(cx)
    }

    fn call(&mut self, req: R) -> Self::Future {
        let future = self.0.call(req);

        Box::pin(async move {
            let response = future.await?;
            // discard the response body
            let response = response.map(|_body| Empty::new());
            Ok(response)
        })
    }
}
```

**Comment by songww** [comment]
It would be better to be able to automatically discard the response body on HEAD handler.

**Comment by davidpdrsn** [comment]
> It would be better to be able to automatically discard the response body on HEAD handler.

Does any other frameworks do this? Doesn't seem like [Rocket does](https://rocket.rs/v0.5-rc/guide/requests/#head-requests)

> Rocket won't interfere with HEAD requests your application explicitly handles.

Mdn makes it pretty clear that dropping response bodies on HEAD automatically is the way to go though. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

**Comment by jplatte** [comment]
I thing especially for files the right solution would be to provide some way to support both methods at once, but with a response-type specific implementation. For example a file serving route would ideally use sendfile internally for GET and stat for HEAD. Do the `ServeDir` and `ServeFile` services from tower-http already do this (seems like you don't register those with a specific method but I can't see any method-specific code in `ServeFile`s code)?

**Comment by davidpdrsn** [comment]
> For example a plain file serving route would ideally use sendfile internally for GET and stat for HEAD

Are those linux syscalls or something? I'm not familiar with them. `ServeDir` and `ServeFile` both returns a `tokio::fs::File` (mapped to an `http_body::Body`). And they don't change their behavior based on the http method. Arguably that was an oversight on my part 🤷

**Comment by davidpdrsn** [comment]
Being able to add routes for HEAD requests still feels like a good idea to me. Then you can avoid generating the body since it'll be stripped anyway.

**Comment by davidpdrsn** [comment]
Adding an example for it sounds good!
