### ISSUE TITLE
cors fail

### ISSUE THREAD

**Issue by rqyuan** [tokio-rs/axum#849]
### Version
0.4.8

### Platform
Windows x64 msvc

### Description
clone this code，then edit examples/cors/src/main.rs 
get(json) -> post(json) as shown follows，will prompt CORS error, but options request succeed

![image](https://user-images.githubusercontent.com/25656055/157621608-58ece481-d09f-43f5-8164-bd77b44d61e3.png)
![image](https://user-images.githubusercontent.com/25656055/157626273-b5531974-a454-4e06-921c-9e54ed1903e6.png)
![image](https://user-images.githubusercontent.com/25656055/157621726-8986ff87-56e3-4300-861e-e44b5d6e78a2.png)
![image](https://user-images.githubusercontent.com/25656055/157622341-eced84c1-63d8-47fc-a655-9d95abbddc96.png)

if delete fetch() headers 'Content-Type': 'application/json'  this request  will succeed

**Comment by jplatte** [comment]
The only content-type values allowed if you don't explicitly set it as an allowed header are [`application/x-www-form-urlencoded`, `multipart/form-data`, `text/plain`]. You need to set `.allow_headers(vec![http::header::CONTENT_TYPE])`.

https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_request_header

**Comment by rqyuan** [comment]
thanks, it's my problem
