### ISSUE TITLE
Add extra connect infos to `IntoMakeServiceWithConnectInfo`

### ISSUE THREAD

**Issue by lilyball** [tokio-rs/axum#851]
### Motivation

I want to be able to expose additional information through `ConnectInfo` without losing the `ConnectInfo<SocketAddr>` info. This way any middleware I have that uses `ConnectInfo<SocketAddr>` will continue to work even if I add other info too (such as local address).

### Proposal

`IntoMakeServiceWithConnectInfo` could have a builder-style method that lets me provide additional connect info types. I expect this would need some new wrapper type whose `Service` impl is just like `IntoMakeServiceWithConnectInfo` except it returns `svc.call(target)` instead of wrapping it in a future. It would specify a constraint like `S: Service<Target>, C2: Connected<Target>`[^service].

[^service]: This constraint should enforce that the entire stack (when adding 3 or more connect infos) supports the same `Target` type, which saying something like `C: Connected<Target>, C2: Connected<Target>` would not. It's probably also necessary to preserve the `MakeService` behavior though I haven't thought about that enough to prove it yet.

### Alternatives

We could possibly add extra stuff to `Connected` using optional methods or optional generic parameters or whatnot, though most approaches here would basically turn the `Connected` type into ad-hoc middleware (e.g. if the optional method actually sets up the extension layer and thus can be overridden to set up multiple layers, it could also just do other stuff too). This also means that installing your `Connected` type "magically" exposes other types too, without having to write the types in the `.into_make_service_with_connect_info()` line. There is a possible approach where the optional generic parameter is in fact a tuple up to some N-ary and `IntoMakeServiceWithConnectInfo` has separate service impls for each arity, which could be handled with a macro, but that may be confusing.

#### `Connectable<Target>`

Or maybe some new `trait Connectable<Target>: sealed::Sealed {}` could be added that is implemented for all `T: Connected<Target>` and also implemented for tuples up to some N-ary where each tuple element impls `Connectable<Target>`. This new trait's implementation would install the extension layer (and it's sealed so nobody else can have an impl that does anything else). And if someone really needs more types than the tuple is implemented for they can just nest tuples.

I'm actually somewhat fond of this approach, because usage would just look like `app.into_make_service_with_connect_info::<(SocketAddr, MyLocalAddr, MyProtocolInfo), _>()` which is pretty neat. It does complicate the implementation though, as compared with the "Proposal" above that keeps the API surface cleaner.

**Comment by davidpdrsn** [comment]
Feels to me like writing your own custom [`Connected`](https://docs.rs/axum/latest/axum/extract/connect_info/trait.Connected.html) impl is the simplest way to handle this.

All that you can get from `&AddrStream` anyway is `remote_addr` since `into_inner` takes self by value so feels unnecessary to add lots of new machinery for it.
