### ISSUE TITLE
`ServeDir` doesn't set the `Content-Type` header

### ISSUE THREAD

**Issue by dpc** [tokio-rs/axum#862]
## Bug Report

I've used 
https://github.com/tokio-rs/axum/blob/422a883cb2a81fa6fbd2f2a1affa089304b7e47b/examples/websockets/src/main.rs#L40
as a template to build a small project, and discovered that after adding `style.css`, it will not work because it doesn't have the correct mime type.

Kind of a paper-cut, but what's worse, I don't know how to fix it (even manually), without just not using `ServeDir` altogether.

### Version

0.4.8

### Platform

Linux

**Comment by davidpdrsn** [comment]
This isn't about axum. Please open an issue on tower-http.
