### ISSUE TITLE
HTTP Status on Invalid JSON Request

### ISSUE THREAD

**Issue by kamulos** [tokio-rs/axum#865]
When I send a request where the `content-type` is not `application/json` I get the answer `415 Unsupported Media Type` and if the JSON parsing fails I get `422 Unprocessable Entity`

Two issues:

1. This is not documented correctly: https://docs.rs/axum/latest/axum/struct.Json.html In this documentation both of them would result in `400 Bad Request`

2. `422 Unprocessable Entity` seems to be part of an HTTP extension intended for WebDAV. Is it appropriate to use this in a non-WebDAV server?

3. The description of `422 Unprocessable Entity` https://datatracker.ietf.org/doc/html/rfc4918#section-11.2 says that this should be used for syntactically correct, but semantically wrong requests. I also get that with a syntactically wrong JSON like `}`

**Comment by jplatte** [comment]
👍🏼 for distinguishing syntactic errors and content errors. `serde_json::Error` has a `classify()` method that allows to check what failed exactly.

**Comment by davidpdrsn** [comment]
> This is not documented correctly: https://docs.rs/axum/latest/axum/struct.Json.html In this documentation both of them would result in 400 Bad Request

Good catch. Thats easy to fix!

> 422 Unprocessable Entity seems to be part of an HTTP extension intended for WebDAV. Is it appropriate to use this in a non-WebDAV server?

Yeah its common. I know that Ruby on Rails uses it for a bunch of default things. MDN also doesn't mention thats its special https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422.

> The description of 422 Unprocessable Entity https://datatracker.ietf.org/doc/html/rfc4918#section-11.2 says that this should be used for syntactically correct, but semantically wrong requests. I also get that with a syntactically wrong JSON like }

Yeah we should fix that. Shouldn't be hard using what jplatte is hinting at.

@kamulos Are you up for making a PR for this?

**Comment by jplatte** [comment]
@davidpdrsn the docs are still wrong though, we still have

> If the request body cannot be parsed, or it does not contain the `Content-Type: application/json` header, it will reject the request and return a `400 Bad Request` response.
