### ISSUE TITLE
How could record req.body() in tracing?

### ISSUE THREAD

**Issue by goldwind-ting** [tokio-rs/axum#880]
```rust
#[derive(Clone)]
pub struct AxumMakeSpan();

impl<B:std::fmt::Debug> MakeSpan<B> for AxumMakeSpan {
    fn make_span(&mut self, req: &Request<B>) -> Span {
        let target;
        let span;

        
        target = req.uri().path_and_query().map(|p| p.as_str()).unwrap_or("");
        span = tracing::error_span!(
            "request",
            http.method = %req.method(),
            http.uri = %req.uri(),
            http.version = ?req.version(),
            http.headers = ?req.headers(),
            http.target = %target,
            http.body = format_args!("{:?}", req.body()),
            request_id = %Uuid::new_v4(),
        );
        span
    }
}
```
I want to record request body like above method, but it show the body is "Streaming".

**Comment by davidpdrsn** [comment]
Request bodies are async streams and `MakeSpan` doesn't support doing async stuff, so you cannot use that and need to write your own middleware.

This example shows how to buffer the body in a middleware https://github.com/tokio-rs/axum/blob/main/examples/consume-body-in-extractor-or-middleware/src/main.rs.

I'm gonna close the issue but feel free to ask follow up questions.

**Comment by goldwind-ting** [comment]
> Request bodies are async streams and `MakeSpan` doesn't support doing async stuff, so you cannot use that and need to write your own middleware.
> 
> This example shows how to buffer the body in a middleware https://github.com/tokio-rs/axum/blob/main/examples/consume-body-in-extractor-or-middleware/src/main.rs.
> 
> I'm gonna close the issue but feel free to ask follow up questions.

Thanks, but look at a bit queer.
