### ISSUE TITLE
Allow route parameters closer to OpenAPI style

### ISSUE THREAD

**Issue by nullren** [tokio-rs/axum#884]
### Motivation

Route parameters can only be defined up to a path component (ie, `/:something`). There is no way to define more granular routes (eg, `/{something}.json`) or multiple parameters in a single component (eg, `/{a}-{b}`).

**Comment by davidpdrsn** [comment]
It would require support in [matchit](https://crates.io/crates/matchit) which is the router axum uses internally. 

So you'll have to handle it manually in your handlers today.
