### ISSUE TITLE
Redirects should support URL fragments

### ISSUE THREAD

**Issue by emschwartz** [tokio-rs/axum#888]
### Version

```
├── axum v0.4.8
│   ├── axum-core v0.1.2
```

### Platform

`Darwin ... 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64`

### Description

I tried this code:

```
pub async fn handler() -> Result<Redirect> {
  let location = "/path/after/login#access_token=blah";
  let location = Uri::from_str(location).unwrap();
  Ok(Redirect::temporary(location))
}
```

I expected to have the browser redirected to the proper URL, including the URL fragment.

Instead, the `Uri` parsing strips the fragment so the browser is redirected to `/path/after/login` without the access token.

I understand this is the intended behavior from the `http::Uri` but, if so, axum's `Redirect` should probably accept a `url::Url` or just a string instead of a `Uri`.

For the time being, I'll just create an `axum::Response` myself and set the `Location` header manually.

**Comment by jplatte** [comment]
I think I was vaguely uneasy about the use of `http::Uri` there before. Not sure whether using `url` makes sense, esp. for simple things like just a hardcoded paths it's kind of overkill and if we use `String` in the interface you can still use `Url` for building it, then do `.to_string()`.

**Comment by davidpdrsn** [comment]
Yeah I agree. I've been thinking that having to call `.parse().unwrap()` all the time is quite annoying. Changing it to accept `&str`s is fine by me.

**Comment by emschwartz** [comment]
Thanks @jplatte and @davidpdrsn for the quick responses! I'm not sure I understand axum's macros well enough to get all of the tests passing, but this is the start of a PR for this change: https://github.com/tokio-rs/axum/pull/889.
