### ISSUE TITLE
Cannot mix infallible handlers and fallible services

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#89]
An app like this wont compile:

```rust
let app =
    // this route fails with Infallible
    route("/foo", get(|| async {}))
    // this route fails with hyper::Error
    .route(
        "/",
        axum::service::get(tower::service_fn(|_: Request<Body>| async {
            Ok::<_, hyper::Error>(Response::new(Body::empty()))
        })),
    );
```

Because the two error types don't match:

```
error[E0271]: type mismatch resolving `<Route<axum::handler::OnMethod<axum::handler::IntoService<[closure@examples/foo:10:33: 10:44], hyper::Body, ()>, EmptyRouter>, EmptyRouter> as Service<http::Request<hyper::Body>>>::Error == hyper::Error`
  --> examples/foo:20:10
   |
20 |         .serve(app.into_make_service())
   |          ^^^^^ expected enum `Infallible`, found struct `hyper::Error`
```

The solution currently is to use `.handle_error` and convert the `tower::service_fn`s error type to `Infallible`. However that might not be what you want. Or at the very least we should investigate if things could be changed to "just" work.

I believe the error happens because of [this trait bound](https://github.com/tokio-rs/axum/blob/main/src/routing.rs#L423-L424) which requires the two services to have the same error types. [`Nested`](https://github.com/tokio-rs/axum/blob/main/src/routing.rs#L933-L934) suffers from the same issue.

**Comment by jplatte** [comment]
> convert the `tower::service_fn`s error type to `Infallible`

I'm guessing you meant the other direction? Can't convert things (other than additional uninhabited types) *to* `Infallible` / `!`.

**Comment by davidpdrsn** [comment]
@jplatte I meant like this

```rust
let app = route("/foo", get(|| async {})).route(
    "/",
    // error type is now Infallible
    axum::service::get(tower::service_fn(|_: Request<Body>| async {
        Ok::<_, hyper::Error>(Response::new(Body::empty()))
    })).handle_error(|_| {
        Ok::<_, Infallible>(StatusCode::INTERNAL_SERVER_ERROR)
    }),
);
```

**Comment by jplatte** [comment]
I see.

**Comment by davidpdrsn** [comment]
I haven't bee able to find a fix for this so decided to document it instead so we can move on with shipping 0.2. I don't consider this a critical issue.

Removing the 0.2 milestone.

**Comment by davidpdrsn** [comment]
I'm not sure this is possible to fix so will close this for now. `handle_error` is the recommended way to solve this issue.

If someone knows of a way to make this "just work" please let me know.
