### ISSUE TITLE
add an example with tonic  and axum

### ISSUE THREAD

**Issue by NateLing** [tokio-rs/axum#905]
add an example with tonic  and axum

**Comment by davidpdrsn** [comment]
Can you please elaborate. What specifically are you looking for?

**Comment by NateLing** [comment]
> Can you please elaborate. What specifically are you looking for?

I am using router merge, the grpc router report it required to impl From<X> for Router.

**Comment by davidpdrsn** [comment]
You can convert a tonic service into a `Router` like [this](https://github.com/EmbarkStudios/server-framework/blob/main/src/server.rs#L669). Might not be updated to the latest version of tonic but will be similar if not simpler.
