### ISSUE TITLE
axum_extra::routing::Resource create not returning 201

### ISSUE THREAD

**Issue by sedrik** [tokio-rs/axum#908]
### Version

```
❯ cargo tree | grep axum
├── axum v0.5.1
│   ├── axum-core v0.2.1
├── axum-extra v0.2.1
│   ├── axum v0.5.1 (*)
├── axum-sqlx-tx v0.3.0
│   ├── axum-core v0.2.1 (*)
```

### Platform

`Linux desktop 5.13.0-37-generic #42-Ubuntu SMP Tue Mar 15 14:34:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Description

When using axum_extra::routing::Resource to manage a HTTP REST interface the create function does not automatically return a 201 but instead just a 200. It would be nice to return 201 for created resources.

The workaround is of course to return (StatusCode::CREATED, Output) but it would be nice if it was done automatically.

**Comment by davidpdrsn** [comment]
I'm not sure its appropriate to set this by default. I'd rather users be in control of things like this.

If we were to do it I suppose we'd have to check if you return `200 Ok` and if so change that to `201 Created` but that means you can never actually return `200 Ok` 😕

**Comment by sedrik** [comment]
My thinking is that if you buy in to using the `Resource` setup the most natural thing for creating a resource is to return `201`. A use is not forced to use the `Resource` so they can always define routes that return `200` for a `POST`. Do note that I am not saying that they should not be able to return `200` if they want but that the default makes more sense as `201`

**Comment by davidpdrsn** [comment]
> Do note that I am not saying that they should not be able to return 200 if they want but that the default makes more sense as 201.

Since 200 is the default I don't think we can tell the difference between the user explicitly setting the status to 200 or just going with the default. We we'd have to overwrite it no matter what. At least I cannot currently think of a way around that.

**Comment by sedrik** [comment]
Ok, I don't know the Axum codebase well enough to give any solutions currently. Might have some time to look into it in the coming evenings.

**Comment by davidpdrsn** [comment]
I'll close this for now. Not sure there is much we can do 😕
