### ISSUE TITLE
axum_extra::routing::Resource create set Location header

### ISSUE THREAD

**Issue by sedrik** [tokio-rs/axum#909]
### Motivation

It would be nice if the [Location Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location) was set when a new resource is created.

### Proposal

When a new resource has been created the Location Header would be set to the full URL of the `.show(|Path(user_id): Path<String>| async {})` resource. I have not looked at the actual implementation of this feature.

**Comment by davidpdrsn** [comment]
I don't follow. Afaik `Location` is only used for `3xx` redirect responses. Why do you need it on requests?

If you want the request URI then you can use [`axum::http::Uri`](https://docs.rs/axum/latest/axum/extract/trait.FromRequest.html#impl-FromRequest%3CB%3E-for-Uri) or [`axum::extract::OriginalUri`](https://docs.rs/axum/latest/axum/extract/struct.OriginalUri.html).

**Comment by davidpdrsn** [comment]
Ah I see. Yeah thats new to me as well.

But I don't see how to the `id` of the newly created resource. `Resource` knows what the "show" path is (like `/users/:id`) but it doesn't know what `id` is 🤔

**Comment by sedrik** [comment]
Yes, Location is a valid header for 201 responses and points to where the data can be read.

I guess we would need some way of telling `Resource` how to find the id of what we returned.

**Comment by davidpdrsn** [comment]
> I guess we would need some way of telling Resource how to find the id of what we returned.

That could be done by creating a `ResourceId` response part that inserts a response extension, which is picked up in a middleware:

```rust
let _: Resource<Body> = Resource::named("users")
    .create(|| async {
        let user_id = 1;
        let user = User { id: user_id };
        (StatusCode::CREATED, ResourceId(user_id), Json(user))
    })
    .show(|Path(id): Path<u64>| async { /* ... */ });
```

However is that really better than just setting the `Location` header manually?

```rust
let _: Resource<Body> = Resource::named("users")
    .create(|| async {
        let user_id = 1;
        let user = User { id: user_id };
        (
            StatusCode::CREATED,
            [("Location", format!("/users/{user_id}"))],
            Json(user),
        )
    })
    .show(|Path(id): Path<u64>| async { /* ... */ });
```

Its the same number of lines of code 🤷

**Comment by sedrik** [comment]
I guess the `ResourceId` route is nice to avoid as much manual work as possible (not having to remember to change the url if the resource is renamed/copied and so on).

I don't need this feature currently but know that other frameworks has it and for the consumers of the api it can be nice to have it.

**Comment by davidpdrsn** [comment]
> I don't need this feature currently but know that other frameworks has it and for the consumers of the api it can be nice to have it.

Which frameworks specifically? Can you give an example of how it works somewhere else?

**Comment by sedrik** [comment]
Hmm, I must have misremembered. I thought that for example the Phoenix framework in Elixir did it but it seems that it is done manually through some of their templates. Was many years since I did anything with that framework now.

They do a lot of cool stuff with their resource routing though. https://hexdocs.pm/phoenix/routing.html#resources

If you don't feel that it is worth doing always feel free to close the issue :)

**Comment by davidpdrsn** [comment]
Yeah sorry but I think we'll pass on this for now.

It can be done in user code like this:

```rust
#[derive(Debug)]
pub struct ResourceLocation<T>(T);

impl<T> IntoResponseParts for ResourceLocation<T>
where
    T: fmt::Display,
{
    type Error = (StatusCode, String);

    fn into_response_parts(self, mut res: ResponseParts) -> Result<ResponseParts, Self::Error> {
        let value = self
            .0
            .to_string()
            .parse::<axum::http::HeaderValue>()
            .map_err(|err| (StatusCode::INTERNAL_SERVER_ERROR, err.to_string()))?;
        res.headers_mut().insert(LOCATION, value);
        Ok(res)
    }
}

let resource = Resource::named("users")
    .create(|| async { (ResourceLocation("/users/1"), "users#create") });
```

I don't think thats too bad. The only real downside is that it requires hardcoding the show path.

If more people want this we can of course reconsider 😊
