### ISSUE TITLE
Allow wildcard matching one or more characters

### ISSUE THREAD

**Issue by NotAFile** [tokio-rs/axum#917]
### Motivation

Many APIs allow trailing slashes in their URLs, e.g:
```
/objects -> OK
/objects/ -> /objects
/objects/my/object/path -> OK
```

 This works fine in axum, until you add a wildcard handler:

```rust
    let app = Router::new()
        .route("/objects", get(my_handler))
        .route("/objects/*key", get(my_path_handler))
```

In this case, a request to `/objects/` will go to `my_path_handler` instead of `my_handler`.

### Proposal

In `actix-web`, this can be solved with a regex, like `{key:.+}`. This will only match the route if the key is not empty. A similar solution might be possible here, by using `/objects/+key`. However, this might break some existing code.

### Alternatives

This might be rare enough that it is preferable to make people manually route requests to the other handler if the wildcard is empty. I don't know how much of an inconvenience that is, as I have not figured out how to do it yet.

**Comment by davidpdrsn** [comment]
> This might be rare enough that it is preferable to make people manually route requests to the other handler if the wildcard is empty. I don't know how much of an inconvenience that is, as I have not figured out how to do it yet.

Personally I prefer this. Users manually handling this in their handler functions. axum's is intentionally kept pretty simple to avoid confusion, and keeping things fast.

**Comment by NotAFile** [comment]
I have spent some more trying to implement that and it seems like this is not possible without some more help from axum. For reference this is the closest I got:

```rust
        .route("/:object", get(my_handler))
        .route("/:object/*key", any(|Path((_, key)): Path<(String, String)>, req| async move {
            if key == "/" {
                // fails with "Invalid URL: Wrong number of parameters. Expected 1 but got 2"
                my_handler.call(req).await
            } else {
                my_path_handler.call(req).await
            }
        }))

```

It doesn't seem like there is enough access to the internals to be able to properly fix up the matched paths after doing your own routing.

**Comment by davidpdrsn** [comment]
Seems to be working for me:

- `/a` matches `/:object` where `object = a`
- `/a/` matches `/:object/*key` where `object = a` and `key = /`
- `/a/b` matches `/:object/*key` where `object = a` and `key = /b`
- `/a/b/c` matches `/:object/*key` where `object = a` and `key = /b/c`

**Comment by NotAFile** [comment]
@davidpdrsn Yeah, that part works fine. The problem with the workaround is just that when you call a handler from another handler like that appears to break a bunch of things. Extractors will have wrong request extensions, middleware will run too early, logs will show the wrong path, etc. As far as I can tell, that effectively means it's not possible to extend axum with any custom routing behaviors at all without reimplementing substantial portions of axum yourself by making your own routing or handler layer, which seems unfortunate.

Perhaps some kind of "pre-routing" step that allows you to return the route information to be used for a request could be a solution there? That might also allow people to implement other features people have requested that were also considered out of scope, like more general regex routing.

**Comment by davidpdrsn** [comment]
Ah I see. Honestly I wouldn't bother with going through `Service::call`. I'd just make the things you call good old rust functions that take arguments that you pass. No reason to make things more complicated than they have to be I guess.

**Comment by NotAFile** [comment]
I considered that, it is kind of what I meant with "reimplementing axum". It really doesn't play well with other parts of axum. For example, the issue I hit immediately is: How would I go about adding a middleware layer to one of the virtual routes but not the other?

But also just in general, taking a step back, it just feels like all of this is a lot of headache and complications just to strip a single trailing slash from a URL. Should it really necessary for me to rearchitect my application for that? Especially considering the fact that I was able to express the same thing in Actix-web in one character without any drawbacks. I just feel like this shouldn't be so hard.

**Comment by davidpdrsn** [comment]
> I had considered that, it is kind of what I meant with "reimplementing axum"

I don't think "calling a function" requires reimplementing axum.

What middleware do you need? You can always create another `Router` and add middleware to it and pass the request along. If there bugs in doing that then we should fix them of course. Something like this

```rust
let mut router_a = Router::new().layer(...);
let mut router_b = Router::new().layer(...);

let app = Router::new().route(
    "/:object/*key",
    any(
        move |Path((_, key)): Path<(String, String)>, req: Request<Body>| {
            if key == "/" {
                router_a.call(req)
            } else {
                router_b.call(req)
            }
        },
    ),
);
```

I don't think thats too bad.

> But also just in general, taking a step back, it just feels like all of this is a lot of headache and complications just to strip a single trailing slash from a URL

Adding more features the routing is a slippery slope. One day we'll be adding what you're asking for, then someone asks for routes that only match certain types like ints (I mean its just one line in some python framework they're using), then someone asks for full regex support, and then suddenly we have a very complex router. I understand you frustration but as maintainers we're trying to strike a balance between having the capabilities that users need and an API that isn't too complex both externally but also internally. You're of course welcome to argue that we haven't gotten that balance right 😊

axum uses [matchit](https://github.com/ibraheemdev/matchit) internally for routing so there actually isn't anything we can do directly from axum to support this.

**Comment by NotAFile** [comment]
Ohh, I didn't see you could `.call()` a router, like that! I'll have to try that and report back.

**Comment by davidpdrsn** [comment]
That method comes from `tower::Service::call` by the way. So you have import that trait.

**Comment by davidpdrsn** [comment]
I'll close this for now as I don't think we should add direct support for this, at least not yet. As mentioned it would also require new stuff in matchit.

Feel free to ask follow up questions or join us in [discord](https://github.com/tokio-rs/tokio).
