### ISSUE TITLE
graceful shutdown does not shutdown only you reload the webpage

### ISSUE THREAD

**Issue by ikey4u** [tokio-rs/axum#923]
### Version

Using the source at commit [HEAD](https://github.com/tokio-rs/axum/commit/f13eab893a3dfe056f5aad85aa604666448405c4) when report this bug.

### Platform

macOS Monterey 12.2

### Crates

Nothing

### Description

After clone axum source code, run the following command
```
cargo run -p example-graceful-shutdown
```
When the server is up, do the follows:

1. open the serving page http://127.0.0.1:3000 in browser (this is a must step to reproduce the problem)
2. go back to your terminal and press `ctrl+c` to stop the server
3.  and you see that the server is hanging up but not stop even after a long time
4. however if you go to the page at step 1 and refresh, the server stops immediately.

**Comment by davidpdrsn** [comment]
I think this is an issue for [hyper](https://github.com/hyperium/hyper) actually. `axum::Server` is just a re-export of `hyper::Server`.

**Comment by Oodachi** [comment]
maybe you need this https://github.com/jacob-pro/hyper-graceful

**Comment by davidpdrsn** [comment]
I'd recommend filing an issue with hyper and hearing what they have to say. I don't believe there is anything we do about this in axum so I'll close this issue for now.

**Comment by jussiniinikoski** [comment]
Try it like this?

```rust
let server = axum::Server::bind(&addr).serve(app.into_make_service());

tokio::select! {
     _ = server => {}
     _ = shutdown_signal() => {}
 };

println!("Server was shut down.");
```

**Comment by felipetesc** [comment]
> 

The function:  
```rust 
shutdown_signal()
``` 
can replaced by :
```rust
signal::ctrl_c()
```

Thanks [jussiniinikoski](https://github.com/jussiniinikoski)
