### ISSUE TITLE
Allow response multiple headers with the same name 

### ISSUE THREAD

**Issue by sinyo-matu** [tokio-rs/axum#925]
### Motivation
People may need to response multiple headers with the same name.
In my case it's Set-Cookie.
on `axum` version 0.4.x it worked. but not on version 0.5.x

### Proposal
```diff
impl<K, V, const N: usize> IntoResponse for [(K, V); N]
where
    K: TryInto<HeaderName>,
    K::Error: fmt::Display,
    V: TryInto<HeaderValue>,
    V::Error: fmt::Display,
{
    fn into_response(self) -> Response {
        let mut res = ().into_response();

        for (key, value) in self {
            let key = match key.try_into() {
                Ok(key) => key,
                Err(err) => {
                    return (StatusCode::INTERNAL_SERVER_ERROR, err.to_string()).into_response()
                }
            };

            let value = match value.try_into() {
                Ok(value) => value,
                Err(err) => {
                    return (StatusCode::INTERNAL_SERVER_ERROR, err.to_string()).into_response()
                }
            };
-            res.headers_mut().insert(key, value);
+            res.headers_mut().append(key, value);
        }

        res
    }
}
```
this worked. but I'm not sure is there any drawback on this change.

### Alternatives
using `axum_extra`'s `CookieJar` can solve this

**Comment by davidpdrsn** [comment]
I think overriding headers is the correct default. Internally in axum we use `[("content-type", foo)]` in a bunch of places, which we couldn't do if headers were append since you can only have one `content-type`. However we could provide an `AppendHeaders` newtype that does what you want.

**Comment by sinyo-matu** [comment]
> However we could provide an AppendHeaders newtype that does what you want.

Yeah, that is enough for me.
