### ISSUE TITLE
Internalize validators

### ISSUE THREAD

**Issue by ricardoalcantara** [tokio-rs/axum#939]
## Feature Request

Make Validators core feature

### Motivation

I needed to implement validator and I followed the example but I made for Json, I needed to implement a lot of boilerplate code, it would be nice to have it already implemented.

### Proposal

Like we have Json<T> and Form<T> we could make use of ValidatedJson and ValidatedForm or make it already inside Json and Form.

### Alternatives

The alternative is to follow the examples and implement all those validator in the application.

**Comment by davidpdrsn** [comment]
By "validations" do you mean whats shown in [this example](https://github.com/tokio-rs/axum/blob/main/examples/validator/src/main.rs)?

The example currently contains `ValidatedForm`, I'd expect `ValidateJson` to be pretty much identical. We can add that to the example. Are you up for making a PR?

I think just having this in the examples is fine. I don't think we need to put these in axum itself. You could build your own crate and then add that to [ECOSYSTEM.md](https://github.com/tokio-rs/axum/blob/main/ECOSYSTEM.md).

**Comment by ricardoalcantara** [comment]
I am not saying to add ValidateJson to the example, it's literally the same think I just replace Form to Json and it works just fine. I meant that validate could be internalized in the core of axum. I would only annotate the DTO struct and the framework would take care to validate it before the methods to receive that parameter.

I understand that I (or someone) could build a crate for that purpose, I was just suggestion that because I consider this feature part of a high level web framework, since everybody needs it.

But it's not big of a deal, let's see how Axum will grow, maybe it wants to be just like Express from NodeJS and have others building the pieces (like passport, logs, even upload file), or it may end up like NesjJS that tries to solve the problems the Express is not so good.

**Comment by davidpdrsn** [comment]
axum is intended to be a small modular framework. That way users can build whatever integrations they need. So having validations built in feels out of scope and doesn't provide any benefit by being built it, outside of discoverability of course.

**Comment by ricardoalcantara** [comment]
Sounds good 🙂!
