### ISSUE TITLE
Query Parameters With Arrays And Suggested Work Around Dooes Not Work

### ISSUE THREAD

**Issue by bonedaddy** [tokio-rs/axum#940]
# Overview

Using the latest version of axum, the [workaround](https://github.com/tokio-rs/axum/issues/434#issuecomment-954889152) for using arrays in query parameters no longer works. Using it gives the following error:

```
missing generics for trait `FromRequest` expected 1 generic argument
```

Changing to the following allowed the code to be compiled:

```rust
pub struct Qs<T>(pub T);

#[axum::async_trait]
impl<B, T> FromRequest<B> for Qs<T>
where
    T: serde::de::DeserializeOwned,
    B: std::marker::Send
{
    type Rejection = Infallible;

    async fn from_request(req: &mut RequestParts<B>) -> Result<Self, Self::Rejection> {
        // TODO: error handling
        match req.uri().query() {
            Some(params) => {
                Ok(Self(serde_qs::from_str(params).unwrap()))
            }
            None => {
                Ok(Self(serde_qs::from_str("").unwrap()))
            }
        }
    }
}
```

Unfortunately this still results in the same error "invalid type expected a sequence".

# Suggestions

This kind of functionality is absolutely required for any modern day web framework. Not having this kind of functionality out of the box makes reasoning to use a particular web framework hard. Granted axum is fantastic, and is pre v1 so all hope is not loss yet.

So my suggestions:

* Add an example, and test for query parameters with arrays
* Add this feature in before v1 is released
* Before v1 indicate in the readme that arrays in query parameters does not work

# Code Example

```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct FetchV1ObligationsLtvs {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub authorities: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_farms: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_addresses: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}

pub struct Qs<T>(pub T);

#[axum::async_trait]
impl<B, T> FromRequest<B> for Qs<T>
where
    T: serde::de::DeserializeOwned,
    B: std::marker::Send
{
    type Rejection = Infallible;

    async fn from_request(req: &mut RequestParts<B>) -> Result<Self, Self::Rejection> {
        // TODO: error handling
        match req.uri().query() {
            Some(params) => {
                Ok(Self(serde_qs::from_str(params).unwrap()))
            }
            None => {
                Ok(Self(serde_qs::from_str("").unwrap()))
            }
        }
    }
}
pub async fn obligation_ltv_handler_v1(
    Qs(mut input): Qs<FetchV1ObligationsLtvs>,
    Extension(state): Extension<Arc<State>>,
) -> ApiResult<(StatusCode, Json<V1ObligationLtvResponse>)> {
.....
}
```

Then the following code is being used from a unit test to invoke the handler:

```rust
            let response = app.clone().oneshot(
                Request::builder()
                .method(http::Method::GET)
                .header(http::header::CONTENT_TYPE, mime::APPLICATION_JSON.as_ref())
                .uri("/v1/obligations?authorities=foo,bar")
                .body(Body::default()).unwrap()
            ).await.unwrap();
            println!("status {}", response.status());
            let body = hyper::body::to_bytes(response.into_body()).await.unwrap();
            println!("{:?}", body);
            ```

**Comment by davidpdrsn** [comment]
What I wrote [here](https://github.com/tokio-rs/axum/issues/434#issuecomment-954898159) still stands. Since there is no standard for nested url params I think sticking with `serde_urlencoded` is the right way to go. That is also what warp and actix-web does.

If you want something outside of that you can switch to serde_qs. You're welcome to contribute an example that uses serde_qs.

I don't think any of this is related to axum not being 1.0. That wont happen in a long time as it requires all our public dependencies (futures, hyper, tower, etc) also being 1.0.

I'll close this issue for now but feel free to ask follow up questions.

**Comment by jplatte** [comment]
Arrays as comma-separated values are not a common thing, or standardized in any way. You can use `serde(deserialize_with)` to first deserialize to a string and then parse that into the type you need.

I agree that array handling (in the standard format as found in html forms) should be easier, but axum is a small modular library, not a big framework so this will never be implemented in axum directly. If a separate library pops up (I basically have one ready for publishing), it might get integrated but it won't help you if you submit your values as a single comma-separated value.

**Comment by davidpdrsn** [comment]
Oh yeah I think

```rust
.uri("/v1/obligations?authorities=foo,bar")
```

should be

```rust
.uri("/v1/obligations?authorities[]=foo&authorities[]=bar")
```

to work with serde_qs.

**Comment by jplatte** [comment]
Nope, the `field[]` syntax doesn't work with serde_qs either. It implements a way of passing arrays (and objects) in a way I have never seen in practice:

```bash
# array
foo[0]=bar&foo[1]=baz
# object
foo[a]=bar&foo[b]=baz
```

**Comment by davidpdrsn** [comment]
Oh wow okay. Weird 😕
