### ISSUE TITLE
Move `axum::extract::extractor_middleware` to `axum::middleware::from_extractor`

### ISSUE THREAD

**Issue by arniu** [tokio-rs/axum#954]

**Comment by davidpdrsn** [comment]
Sounds good to me! We didn't use to have the middleware module but that is probably a better home for it.

You up for making a PR? We just have to make its not a breaking change by re-exporting it from the old location.

**Comment by jplatte** [comment]
If we want to deprecate the old one, we need to do so by having two actual functions (one calling the other) since deprecating re-exports does nothing (https://github.com/rust-lang/rust/issues/84584).

**Comment by davidpdrsn** [comment]
Yeah thats probably better, to have the deprecation.
