### ISSUE TITLE
Consider renaming UrlParams to Path

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/axum#96]
### Motivation

This would be more in line with `Body` and `Query`, and be shorter (I think for some apps this type name will be written down a lot).

### Proposal

Rename `UrlParams` to `Path`. Not sure about `UrlParamsMap`, I guess `PathMap` isn't too bad.

**Comment by davidpdrsn** [comment]
I think `Path` would be nice to use for this https://github.com/tokio-rs/axum/issues/42. Could even consider removing `UrlParams` after that is implemented.

**Comment by jplatte** [comment]
Oh, I was kind of under the impression that `UrlParams` already works like `actix_web::web::Path`. I'll close this in favor of #42 then.
