### ISSUE TITLE
Replace `std::sync::RwLock` by `tokio`'s version in `key-value-store` example

### ISSUE THREAD

**Issue by jorgecarleitao** [tokio-rs/axum#983]
### Motivation

In example https://github.com/tokio-rs/axum/blob/main/examples/key-value-store/src/main.rs, we currently use `std::sync::RwLock`, which blocks.

### Proposal

Consider using tokio's version and `.await` accordingly to offer best practices on this?

**Comment by davidpdrsn** [comment]
The lock isn't held across `await`s and only held for a very short time. In that case using a regular sync lock is preferred actually.

See https://docs.rs/tokio/1.18.0/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use

**Comment by jorgecarleitao** [comment]
Thanks for the response and explanation. Indeed!
